<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="hy">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Ծրագրի մասին</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Բառապաշարի մարզիչ՝ բառակազմերը հիշելու համար.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Բառապաշարի և քերականության մարզիչ.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Բաց կոդով լիցենզիաներ</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Այս հավելվածն օգտագործում է Qt-ն GNU Lesser General Public License-ի 3-րդ տարբերակի ներքո։</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Qt ծանուցում</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Qt ծանուցում</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Qt-ի սկզբնական կոդ</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Qt նախագծի կայք</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Ստեղծված է AI-ի կողմից — կարող է սխալներ պարունակել</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Բողոքել</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Շնորհակալություն — ձեր բողոքն ուղարկվեց և կուսումնասիրվի։</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Բողոքել AI բովանդակության մասին</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Ի՞նչն է սխալ այս ստեղծված բովանդակության մեջ</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Սեռական կամ ակնարկային բովանդակություն</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Հայհոյանք կամ վիրավորական լեզու</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Ատելություն կամ ոտնձգություն պարունակող բովանդակություն</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Բռնի կամ վտանգավոր բովանդակություն</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Սխալ կամ մոլորեցնող տեղեկություն</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Այլ բան</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Մանրամասներ (ըստ ցանկության)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Ուղարկվում է…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Փակել</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Չեղարկել</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Ուղարկել բողոքը</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Լուսանկարել</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Չեղարկել</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>շուտով</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1օր %2ժ հետո</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1ժ %2ր հետո</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1ր հետո</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Ընտրել պատկեր</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Ընտրել աուդիո</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Ներմուծել բառակազմ</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Բառի լեզուն</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Հուշման լեզուն</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+326"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Չեղարկել</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ AI բառակազմերի գեներատոր</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Աշխատում է Gemini-ով</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Թեմա</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Նկարագրեք ցանկալի հավաքածուն — օր. «խոհանոցային իրեր, որոնք կարելի է գտնել ֆրանսիական տնային տնտեսությունում» կամ «գործնական ուղևորության արտահայտություններ կոնֆերանսի համար»…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Այս ամիս մնացել է %1 %2-ից գեներացիա — կվերականգնվի %3-ին</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI-ը կարող է սխալվել։ Ստեղծվում է միայն բոլոր տարիքների համար համապատասխան բովանդակություն — անհամապատասխան որևէ բան նշելու համար օգտագործեք 🚩 Բողոքել։</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Բառի լեզուն</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Հուշման լեզուն</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Բառերի քանակը</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Հարցում Gemini-ին…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Չեղարկել հարցումը</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Ստեղծել</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Նոր բառակազմ</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Խմբագրել բառակազմը</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Ներմուծել</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Հավաքածուի վերնագիրը…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Ինքնաշխատ բերել պատկերները</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Բառ</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>ընտրված</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Բառ / Տերմին</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Ընտրված չէ</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Մուտքագրեք բառը...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Հուշում / նշանակություն</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Հուշում, սահմանում...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Օգտագործման օրինակ</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Օրինակ նախադասություն՝ բառն օգտագործելով...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Փոխել պատկերը</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Ավելացնել պատկեր</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Բերել</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Տեսախցիկ</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Ավելացնել աուդիո</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Կանգնեցնել</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Նվագարկել</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ Ձայնային</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Կանգնեցնել</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Ձայնագրել</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Ավելացնել բառ</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Հեռացնել</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Պահպանել</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Վերնագիրը պարտադիր է</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>շուտով</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1օր %2ժ հետո</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1ժ %2ր հետո</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1ր հետո</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Ընտրել նկար</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Ընտրել աուդիո</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ ԱԲ</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Նոր կանոնների հավաքածու</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Խմբագրել կանոնների հավաքածուն</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Ներմուծել</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Ներմուծել կանոնների հավաքածու</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ ԱԲ կանոնների հավաքածուի գեներատոր</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Աշխատում է Gemini-ով</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Այս ամիս մնացել է %1 %2-ից գեներացում — վերականգնվում է %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Բացատրվող կանոն/թեմա</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Նկարագրեք ցանկալի կանոնը — օր. &quot;present simple ընդդեմ present continuous&quot; կամ &quot;երրորդ տիպի պայմանական նախադասություններ&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Հարցեր՝ ըստ տեսակի</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Լրացնել բացը</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Բազմակի ընտրություն</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Բացվող ցանկ</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Քաշել և գցել</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Հարցում Gemini-ին…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Չեղարկել հարցումը</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Չեղարկել</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI-ը կարող է սխալվել։ Ստեղծվում է միայն բոլոր տարիքների համար համապատասխան բովանդակություն — անհամապատասխան որևէ բան նշելու համար օգտագործեք 🚩 Բողոքել։</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Գեներացնել</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Մուտքագրեք վերնագիրը…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Տեսության բացատրություն</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Թաքնված է թեստավորման ընթացքում, մինչև սովորողը սխալվի — միշտ ընթեռնելի է նախադիտման մեջ։</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Օգտագործեք ▲▼՝ բլոկը վերադասավորելու համար։ Քաշեք նկարի // անկյունը՝ չափը փոխելու համար։</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Բացատրեք կանոնը, որը այս հավաքածուն մարզում է…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Աուդիո հատված</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Տեքստ</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Նկար</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Աուդիո</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Հարց</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>ընտրված</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Լրացնել բացը</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Բազմակի ընտրություն</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Բացվող ցանկ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Քաշել և գցել</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Օգտագործեք ___ (երեք ընդգծում) սովորողի լրացվող յուրաքանչյուր բացի համար։</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>օր. Ի՞նչ է նա անում ամեն օր։</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>օր. Նա ամեն օր ___ դպրոց։</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Պատասխաններ</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Մեկ պատասխան յուրաքանչյուր բացի համար, ստորակետերով բաժանված, հերթականությամբ։ Օգտագործեք \,՝ բառացի ստորակետի համար։</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>օր. գնում է</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Տարբերակներ</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Բաժանեք մեկ բացի տարբերակները ստորակետներով; բաժանեք բացերը կրկնակի երկկետով (::)։ Մեկ : անվտանգ է ինչպես կա; օգտագործեք \,՝ բառացի ստորակետի, \::՝ բառացի ::-ի, և ___՝ միտումնավոր դատարկ տարբերակի համար։ Օր. երկու բացի համար՝ գնում է, գնալ, գնալով::յուրաքանչյուր, մի քանիսը, մեծամասնությունը։</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Ստորակետերով բաժանված քարշվող սալիկներ — ներառեք ճիշտ պատասխանները, ինչպես նաև ընտրովի խաբուսիկ տարբերակներ, որոնցով սովորողը կարող է շփոթվել։ Օգտագործեք \,՝ բառացի ստորակետի, և ___՝ դատարկ սալիկի համար (այն բացի համար, որը ճիշտ է դատարկ մնալ)։ Լրացրեք ստորև բացերը, երբ դրանք սահմանված են։</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>օր. գնում է, գնալ, գնալով::յուրաքանչյուր, մի քանիսը, մեծամասնությունը</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>օր. գնում է, գնալ, գնալով, գնացել է</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Ճիշտ պատասխան յուրաքանչյուր բացի համար</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Հպեք ճիշտ տարբերակին ստորև յուրաքանչյուր վանդակում։</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Ընտրեք ճիշտ պատասխան յուրաքանչյուր բացի համար։</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Բաց %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Լրացրեք բացերը</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Քաշեք սալիկը ստորև գտնվող բացին, կամ հպեք սալիկին, ապա բացին՝ այն տեղադրելու համար։</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Լրացրեք յուրաքանչյուր բաց սալիկով։</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Ստորակետերով բաժանված տարբերակներ — հպեք ստորև ճիշտ պատասխանին։ Օգտագործեք \,՝ բառացի ստորակետի համար։</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Ստորակետերով բաժանված տարբերակներ — հպեք ստորև բոլոր ճիշտ պատասխաններին։ Օգտագործեք \,՝ բառացի ստորակետի համար։</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>օր. գնում է, գնալ, գնալով, գնացել է</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Միայն մեկ ճիշտ պատասխան</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Ճիշտ պատասխան</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Ճիշտ պատասխան(ներ)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Ընտրեք ճիշտ պատասխանը։</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Ընտրեք առնվազն մեկ ճիշտ պատասխան։</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Ավելացնել հարց</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Հեռացնել</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Պահպանել</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Վերնագիրը պարտադիր է</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Բացատրել քերականությունը</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Չհաջողվեց բեռնել %1 հարցը՝ %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Ստեղծվել է ընդամենը %1 հարց %2 պահանջվածից — փորձեք ավելի լայն թեմա կամ նվազեցրեք վերևի թվերը։</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Բացատրության լեզուն</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Բացատրության լեզուն</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Թեմայի լեզուն</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Թեմայի լեզուն</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Այս թեմայով հնարավոր չէ բովանդակություն ստեղծել։ AI-ը ստեղծում է միայն բոլոր տարիքների համար համապատասխան բովանդակություն — սեռական, գռեհիկ կամ վիրավորական թեմաները չեն աջակցվում։ Խնդրում ենք փորձել այլ թեմա։</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Դուք օգտագործել եք այս ամսվա բոլոր AI ստեղծումները։ Կրկին փորձեք հաջորդ ամիս։</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Այսօր չափազանց շատ բողոքներ են ուղարկվել — խնդրում ենք վաղը կրկին փորձել։</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>AI ծառայությունը հիմա զբաղված է — խնդրում ենք մի փոքր հետո կրկին փորձել։</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Նախ մուտքագրեք թեմա։</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Թեման չափազանց երկար է (առավելագույնը %1 նիշ)։</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Առնվազն մեկ հարցի տեսակ սահմանեք զրոյից մեծ։</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Ձեր նստաշրջանի ժամկետը լրացել է — խնդրում ենք կրկին մուտք գործել։</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Չհաջողվեց կապ հաստատել սերվերի հետ։ Ստուգեք ինտերնետ կապը և կրկին փորձեք։</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Ինչ-որ բան սխալ ընթացավ։ Խնդրում ենք կրկին փորձել։</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Մուտք գործված չէ։</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Հպեք՝ շրջելու համար</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Հպեք՝ հետ շրջելու համար</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>ԳԻՏԵՄ</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>ԱՆՑՆԵԼ</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Չգիտեմ</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Գիտեմ</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Ընտրված չէ</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Չհաջողվեց բեռնել լիցենզիայի տեքստը.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Մուտք գործեք՝ շարունակելու համար</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Բացվում է դիտարկիչը…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Մուտք գործել Google-ով</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Այս անունով գրադարան կամ հավաքածու արդեն գոյություն ունի այստեղ.</translation>
    </message>
    <message>
        <location line="+309"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Այս անունով բառակազմ արդեն գոյություն ունի այստեղ.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Այս անունով կանոնների հավաքածու արդեն գոյություն ունի այստեղ.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+37"/>
        <source>Results</source>
        <translation>Արդյունքներ</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Well</source>
        <translation>Հիանալի</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>done</source>
        <translation>կատարված</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>%1-ից</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Հիանալի աշխատանք է! Այսպես շարունակիր!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Լավ փորձ էր! Շարունակիր մարզվել.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Մի հանձնվիր – պրակտիկան կատարելության է հասցնում!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Այս սեսիա</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Չգիտեմ</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Գիտեմ</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Practice Again</source>
        <translation>Կրկին մարզվել</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Զրոյացնե՞լ թեստի առաջընթացը։</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Սա կմաքրի ձեր առաջընթացը այս կանոնների հավաքածուում և կսկսի նոր աշխատաշրջան։</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 հարց</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Ավարտված է՝ %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Ընթացքի մեջ է՝ %1 / %2</translation>
    </message>
    <message>
        <location line="+67"/>
        <source>← Reset</source>
        <translation>← Զրոյացնել</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Կանոնի բացատրություն</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Այս հավաքածուի համար բացատրություն չի ավելացվել։</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Աուդիո հատված</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Ուղղագրության խստություն</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Խիստ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Նորմալ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Մեղմ</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Սկսել թեստը</translation>
    </message>
    <message>
        <location line="-198"/>
        <source>Test is completed</source>
        <translation>Թեստն ավարտված է</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Հաջորդ հարցը՝ #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Ճիշտ է՝ %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Կանոն</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Կանոնի բացատրություն</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Աուդիո հատված</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Չեղարկել</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Դիտել կանոնը</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Պտտեք անիվը՝ յուրաքանչյուր բացի բառն ընտրելու համար։</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Բաց %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Քաշեք սալիկը բացին, կամ հպեք սալիկին, ապա բացին՝ այն տեղադրելու համար։</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Ընտրեք ճիշտ պատասխանը։</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Ընտրեք բոլոր համապատասխանները։</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Ճիշտ է՝ </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Ուղարկել</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Ճիշտ է՝ %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Տեսնել արդյունքները</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Հաջորդը →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Հարց համար %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Վերագրե՞լ բառակազմը.</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Միավորե՞լ գրադարանները.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>«%1» անունով բառակազմ արդեն գոյություն ունի այստեղ. Վերագրե՞լ այն տեղափոխված հավաքածուով.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>«%1» անունով գրադարան արդեն գոյություն ունի այստեղ. Միավորե՞լ դրա պարունակությունը սրա հետ.</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>«%1» անունով բառակազմ արդեն գոյություն ունի %2-ում. Վերագրե՞լ այն միավորված տարբերակով.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>նպատակակետ գրադարանը</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>.ppset արտահանել</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Նոր գրադարան</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Library name:</source>
        <translation>Գրադարանի անունը.</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>օր. Ճամփորդություն, Աշխատանք, Դպրոց…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Այս անունով գրադարան կամ հավաքածու արդեն գոյություն ունի այստեղ.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+74"/>
        <source>A library with this name already exists here.</source>
        <translation>Այս անունով գրադարան արդեն գոյություն ունի այստեղ.</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Create</source>
        <translation>Ստեղծել</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Rename Library</source>
        <translation>Վերանվանել գրադարանը</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Նոր անուն.</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Վերանվանել</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Ձեր բառակազմերը</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Գրադարան</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Տեղափոխել դուրս</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Թողեք ներսում տեղափոխելու համար</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>բառ</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>հարց</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Ջնջել գրադարանը</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Խմբագրել</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Ջնջել</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>.ppset ֆայլը կիսվել</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>.ppset արտահանել (պահել սկավառակին)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Այստեղ դեռ ոչինչ չկա.
Հպեք + Ստեղծել՝ բառակազմ կամ գրադարան ավելացնելու համար.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Բառակազմ</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Կանոնների հավաքածու</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Ստեղծել</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Ինտերֆեյսի լեզուն</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Cancel</source>
        <translation>Չեղարկել</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Ընտրեք թեստի տեսակը</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Ուսումնական քարտեր</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Շրջեք՝ բացահայտելու համար — սահեցրեք աջ, եթե գիտեք</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Գրեք բառը</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Տեսեք հուշումը — մուտքագրեք արտահայտությունը</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Գրեք հուշումը</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Տեսեք բառը — մուտքագրեք դրա թարգմանությունը</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Ընտրեք բառը</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Տեսեք հուշումը — ընտրեք 4 տարբերակից</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Ընտրեք հուշումը</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Տեսեք բառը — ընտրեք 4 տարբերակից</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Աստիճանական ուսուցում</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Բազմակի ընտրություն սովորելու համար, ապա գրելը՝ բոլոր բառերին տիրապետելու համար</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Հակադարձ աստիճանական ուսուցում</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Բազմակի ընտրություն սովորելու համար, ապա գրելը՝ բոլոր հուշումներին տիրապետելու համար</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>✓ Done</source>
        <translation>✓ Կատարված</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>← Reset</source>
        <translation>← Զրոյացնել</translation>
    </message>
    <message>
        <location line="+96"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Ուղղագրության խստություն</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Խիստ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Նորմալ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Մեղմ</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Չեղարկել</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Կրկնել արտահայտությունները</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Կանգնեցնել</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Լսել</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Սկսել թեստը</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Բառեր դեռ չկան</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Մուտքագրեք հուշումը / թարգմանությունը…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Մուտքագրեք արտահայտությունը…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Ճիշտ. </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Նշել որպես ճիշտ (սխալ եմ մուտքագրել)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Ուղարկել</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Նշել որպես ճիշտ (սխալ եմ սեղմել)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Ճիշտ. %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Տեսնել արդյունքները</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Հաջորդը →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Հարց համար %1</translation>
    </message>
</context>
</TS>
