<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="lv">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Par lietotni</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Vārdu krājuma treneris vārdu kopu iegaumēšanai.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Vārdu krājuma un gramatikas treneris.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Atvērtā koda licences</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Šī lietotne izmanto Qt saskaņā ar GNU Lesser General Public License 3. versijas licenci.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Qt paziņojums</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Qt paziņojums</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Qt pirmkods</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Qt projekta vietne</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Izveidojis AI — var saturēt kļūdas</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Ziņot</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Paldies — jūsu ziņojums ir nosūtīts un tiks izskatīts.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Ziņot par AI saturu</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Kas nav kārtībā ar šo izveidoto saturu?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Seksuāls vai divdomīgs saturs</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Rupjības vai aizvainojoša valoda</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Naidu kurinošs vai aizskarošs saturs</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Vardarbīgs vai bīstams saturs</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Nepareiza vai maldinoša informācija</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Kaut kas cits</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Sīkāka informācija (nav obligāti)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Sūta…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Aizvērt</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Atcelt</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Nosūtīt ziņojumu</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Uzņemt fotoattēlu</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Atcelt</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>drīzumā</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>pēc %1d %2h</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>pēc %1h %2min</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>pēc %1min</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Izvēlēties attēlu</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Izvēlēties audio</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Importēt vārdu kopu</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Vārda valoda</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Norādes valoda</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+339"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Atcelt</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ AI vārdu kopu ģenerators</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Darbojas ar Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Tēma</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Aprakstiet vēlamo kopu — piem., „virtuves piederumi, ko atrastu franču mājsaimniecībā” vai „darījumu brauciena frāzes uz konferenci”…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Šomēnes atlikuši %1 no %2 ģenerēšanas reizēm — atiestatīs %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI var kļūdīties. Tiek veidots tikai visām vecuma grupām piemērots saturs — izmantojiet 🚩 Ziņot, lai atzīmētu jebko nepiemērotu.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Vārda valoda</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Norādes valoda</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Vārdu skaits</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Jautā Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Atcelt pieprasījumu</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Ģenerēt</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Jauna vārdu kopa</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Rediģēt vārdu kopu</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importēt</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Kopas nosaukums…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Automātiski iegūt attēlus</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Vārds</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>atlasīts</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Vārds / Termins</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Nav atlasīts</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Ievadiet vārdu...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Norāde / nozīme</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Norāde, definīcija...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Lietojuma piemērs</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Piemēra teikums ar šo vārdu...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Mainīt attēlu</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Pievienot attēlu</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Iegūt</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Kamera</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Pievienot audio</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Apturēt</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Atskaņot</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ Balss</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Apturēt</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Ierakstīt</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Pievienot vārdu</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Noņemt</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Saglabāt</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Nosaukums ir obligāts</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>drīz</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>pēc %1d %2st</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>pēc %1st %2min</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>pēc %1min</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Izvēlēties attēlu</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Izvēlēties audio</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ MI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Jauns noteikumu kopums</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Rediģēt noteikumu kopumu</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importēt</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Importēt noteikumu kopumu</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ MI noteikumu kopuma ģenerators</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Darbina Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Šomēnes atlikuši %1 no %2 ģenerēšanas reizēm — atiestatīsies %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Skaidrojamais noteikums/tēma</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Aprakstiet vēlamo noteikumu — piem., &quot;present simple pret present continuous&quot; vai &quot;trešā tipa nosacījuma teikumi&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Jautājumi pēc veida</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Aizpildīt robu</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Vairākizvēle</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Nolaižamā izvēle</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Vilkt un nomest</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Vaicā Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Atcelt pieprasījumu</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Atcelt</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI var kļūdīties. Tiek veidots tikai visām vecuma grupām piemērots saturs — izmantojiet 🚩 Ziņot, lai atzīmētu jebko nepiemērotu.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Ģenerēt</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Ievadiet nosaukumu…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Teorijas skaidrojums</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Paslēpts testēšanas laikā, līdz apguvējs pieļauj kļūdu — priekšskatījumā vienmēr lasāms.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Izmantojiet ▲▼, lai pārkārtotu bloku. Velciet fotoattēla // stūri, lai mainītu izmēru.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Paskaidrojiet noteikumu, ko šis kopums trenē…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Audio fragments</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Teksts</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Fotoattēls</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Audio</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Jautājums</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>atlasīts</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Aizpildīt robu</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Vairākizvēle</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Nolaižamā izvēle</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Vilkt un nomest</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Izmantojiet ___ (trīs pasvītrojumus) katrai robai, ko apguvējs aizpilda.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>piem., Ko viņa dara katru dienu?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>piem., Viņa katru dienu iet ___ uz skolu.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Atbildes</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Viena atbilde uz robu, atdalītas ar komatiem, secībā. Izmantojiet \, burtiskam komatam.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>piem., iet</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Opcijas</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Atdaliet vienas robas opcijas ar komatiem; atdaliet robas ar dubultkolu (::). Viens : ir drošs tāds, kāds ir; izmantojiet \, burtiskam komatam, \:: burtiskam ::, un ___ apzināti tukšai opcijai. Piem., divām robām: iet, iet, ejot::katrs, daži, vairums.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Ar komatiem atdalītas velkamas flīzes — iekļaujiet pareizās atbildes, kā arī neobligātus maldinātājus, ar kuriem apguvēju var maldināt. Izmantojiet \, burtiskam komatam, un ___ tukšai flīzei (robai, kurai pareizi jāpaliek tukšai). Aizpildiet zemāk esošās robas, tiklīdz tās ir iestatītas.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>piem., iet, iet, ejot::katrs, daži, vairums</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>piem., iet, iet, ejot, gājis</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Pareizā atbilde katrai robai</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Pieskarieties pareizajai opcijai katrā zemāk redzamajā lodziņā.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Atlasiet pareizu atbildi katrai robai.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Roba %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Aizpildiet robas</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Velciet flīzi uz zemāk esošo robu vai pieskarieties flīzei un tad robai, lai to novietotu.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Aizpildiet katru robu ar flīzi.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Ar komatiem atdalītas opcijas — pieskarieties pareizajai atbildei zemāk. Izmantojiet \, burtiskam komatam.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Ar komatiem atdalītas opcijas — pieskarieties visām pareizajām atbildēm zemāk. Izmantojiet \, burtiskam komatam.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>piem., iet, iet, ejot, gājis</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Tikai viena pareiza atbilde</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Pareizā atbilde</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Pareizā(-s) atbilde(-s)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Atlasiet pareizo atbildi.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Atlasiet vismaz vienu pareizu atbildi.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Pievienot jautājumu</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Noņemt</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Saglabāt</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Nosaukums ir obligāts</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Paskaidrot gramatiku</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Neizdevās ielādēt %1 jautājumu: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Izveidoti tikai %1 no %2 pieprasītajiem jautājumiem — izmēģiniet plašāku tēmu vai samaziniet iepriekš norādītos skaitļus.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Skaidrojuma valoda</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Skaidrojuma valoda</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Tēmas valoda</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Tēmas valoda</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Par šo tēmu nevar izveidot saturu. AI veido tikai visām vecuma grupām piemērotu saturu — seksuālas, rupjas vai aizvainojošas tēmas netiek atbalstītas. Lūdzu, izmēģiniet citu tēmu.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Visas šī mēneša AI ģenerēšanas reizes ir izmantotas. Mēģiniet vēlreiz nākamajā mēnesī.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Šodien pārāk daudz ziņojumu — lūdzu, mēģiniet vēlreiz rīt.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>AI pakalpojums pašlaik ir aizņemts — lūdzu, mēģiniet vēlreiz pēc brīža.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Vispirms ievadiet tēmu.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Tēma ir pārāk gara (maks. %1 rakstzīmes).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Iestatiet vismaz viena jautājumu veida skaitu lielāku par nulli.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Jūsu sesija ir beigusies — lūdzu, pierakstieties vēlreiz.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Neizdevās sazināties ar serveri. Pārbaudiet interneta savienojumu un mēģiniet vēlreiz.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Radās kļūda. Lūdzu, mēģiniet vēlreiz.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Nav pierakstīts.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Pieskarieties, lai apgrieztu</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Pieskarieties, lai apgrieztu atpakaļ</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>ZINU</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>IZLAIST</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Nezinu</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Zinu</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Nav atlasīts</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Neizdevās ielādēt licences tekstu.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Pierakstieties, lai turpinātu</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Tiek atvērts pārlūks…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Pierakstīties ar Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Bibliotēka vai kopa ar šādu nosaukumu šeit jau pastāv.</translation>
    </message>
    <message>
        <location line="+317"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Vārdu kopa ar šādu nosaukumu šeit jau pastāv.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Noteikumu kopa ar šādu nosaukumu šeit jau pastāv.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+38"/>
        <source>Results</source>
        <translation>Rezultāti</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>Well</source>
        <translation>Lieliski</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>done</source>
        <translation>padarīts</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>no %1</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Lielisks darbs! Turpini tā!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Labs mēģinājums! Turpini praktizēties.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Nepadodies – prakse dara pilnību!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Šī sesija</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Nezinu</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Zinu</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Practice again</source>
        <translation>Vingrināties vēlreiz</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Find another set</source>
        <translation>Atrast citu kopu</translation>
    </message>
    <message>
        <source>Practice Again</source>
        <translation type="vanished">Praktizēties vēlreiz</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Atiestatīt testa progresu?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Tas notīrīs jūsu progresu šajā noteikumu kopumā un sāks jaunu sesiju.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 jautājumi</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Pabeigts: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Notiek: %1 / %2</translation>
    </message>
    <message>
        <source>← Reset</source>
        <translation type="vanished">← Atiestatīt</translation>
    </message>
    <message>
        <location line="+185"/>
        <source>Reset to practise again</source>
        <translation>Atiestatīt, lai vingrinātos vēlreiz</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Reset</source>
        <translation>Atiestatīt</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Noteikuma skaidrojums</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Šim kopumam nav pievienots skaidrojums.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Audio fragments</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Pareizrakstības stingrība</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Stingra</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Parasta</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Iecietīga</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Sākt testu</translation>
    </message>
    <message>
        <location line="-316"/>
        <source>Test is completed</source>
        <translation>Tests ir pabeigts</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Nākamais jautājums: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Pareizi: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Noteikums</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Noteikuma skaidrojums</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Audio fragments</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Atcelt</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Skatīt noteikumu</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Grieziet riteni, lai izvēlētos katras robas vārdu.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Roba %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Velciet flīzi uz robu vai pieskarieties flīzei un tad robai, lai to novietotu.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Atlasiet pareizo atbildi.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Atlasiet visu atbilstošo.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Pareizi: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Iesniegt</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Pareizi: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Skatīt rezultātus</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Tālāk →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Jautājuma numurs %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Pārrakstīt vārdu kopu?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Apvienot bibliotēkas?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Vārdu kopa ar nosaukumu „%1” šeit jau pastāv. Pārrakstīt to ar pārvietoto kopu?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Bibliotēka ar nosaukumu „%1” šeit jau pastāv. Apvienot tās saturu ar šo?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Vārdu kopa ar nosaukumu „%1” jau pastāv vietā %2. Pārrakstīt to ar apvienoto versiju?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>mērķa bibliotēka</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Eksportēt kā .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Jauna bibliotēka</translation>
    </message>
    <message>
        <location line="+31"/>
        <source>Library name:</source>
        <translation>Bibliotēkas nosaukums:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>piem., Ceļojumi, Darbs, Skola…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Bibliotēka vai kopa ar šādu nosaukumu šeit jau pastāv.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+99"/>
        <source>A library with this name already exists here.</source>
        <translation>Bibliotēka ar šādu nosaukumu šeit jau pastāv.</translation>
    </message>
    <message>
        <location line="-62"/>
        <source>Create</source>
        <translation>Izveidot</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Rename Library</source>
        <translation>Pārdēvēt bibliotēku</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Jauns nosaukums:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Pārdēvēt</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Jūsu vārdu kopas</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Bibliotēka</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Pārvietot ārā no</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Nometiet, lai pārvietotu iekšā</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>vārdi</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>jautājumi</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Dzēst bibliotēku</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Rediģēt</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Dzēst</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Kopīgot .ppset failu</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Eksportēt .ppset (saglabāt diskā)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Šeit vēl nekā nav.
Pieskarieties + Izveidot, lai pievienotu vārdu kopu vai bibliotēku.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Vārdu kopa</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Noteikumu kopums</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Izveidot</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Saskarnes valoda</translation>
    </message>
    <message>
        <location line="-710"/>
        <location line="+796"/>
        <source>Cancel</source>
        <translation>Atcelt</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Izvēlieties testa veidu</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Atmiņas kartītes</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Apgrieziet, lai atklātu — velciet pa labi, ja zināt</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Uzrakstiet vārdu</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Apskatiet norādi — ierakstiet izteicienu</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Uzrakstiet norādi</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Apskatiet vārdu — ierakstiet tā tulkojumu</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Izvēlieties vārdu</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Apskatiet norādi — izvēlieties no 4 variantiem</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Izvēlieties norādi</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Apskatiet vārdu — izvēlieties no 4 variantiem</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Pakāpeniska mācīšanās</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Vispirms izvēle no variantiem, tad rakstīšana, lai apgūtu visus vārdus</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Apgriezta pakāpeniska mācīšanās</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Vispirms izvēle no variantiem, tad rakstīšana, lai apgūtu visas norādes</translation>
    </message>
    <message>
        <location line="+36"/>
        <location line="+82"/>
        <source>✓ Done</source>
        <translation>✓ Gatavs</translation>
    </message>
    <message>
        <location line="-82"/>
        <source>← Reset</source>
        <translation>← Atiestatīt</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Completed — swipe left to reset</source>
        <translation>Pabeigts — pavelciet pa kreisi, lai atiestatītu</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>%1 left</source>
        <translation>Atlikuši: %1</translation>
    </message>
    <message>
        <location line="+51"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Pareizrakstības stingrība</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Stingra</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Parasta</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Iecietīga</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Atcelt</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Atkārtot izteicienus</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Apturēt</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Klausīties</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Sākt testu</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Vēl nav vārdu</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Ierakstiet norādi / tulkojumu…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Ierakstiet izteicienu…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Pareizi: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Atzīmēt kā pareizu (pārrakstījos)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Iesniegt</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Atzīmēt kā pareizu (nejauši uzklikšķināju)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Pareizi: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Skatīt rezultātus</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Tālāk →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Jautājuma numurs %1</translation>
    </message>
</context>
</TS>
