<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ro">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Despre</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Antrenor de vocabular pentru memorarea seturilor de cuvinte.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Antrenor de vocabular și gramatică.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Licențe open source</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Această aplicație folosește Qt sub licența GNU Lesser General Public License versiunea 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Notă Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Notă Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Cod sursă Qt</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Site-ul proiectului Qt</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Generat de IA — poate conține greșeli</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Raportează</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Mulțumim — raportul tău a fost trimis și va fi analizat.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Raportează conținut IA</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Ce este în neregulă cu acest conținut generat?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Conținut sexual sau sugestiv</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Vulgarități sau limbaj ofensator</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Conținut care incită la ură sau hărțuire</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Conținut violent sau periculos</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Informații greșite sau înșelătoare</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Altceva</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Detalii (opțional)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Se trimite…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Închide</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Anulează</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Trimite raportul</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Fă o fotografie</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Anulează</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>în curând</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>în %1z %2h</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>în %1h %2m</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>în %1m</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Selectează imagine</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Selectează audio</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Importă set de cuvinte</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Limba cuvântului</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Limba indiciului</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+326"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Anulează</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ Generator de seturi de cuvinte cu IA</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Susținut de Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Temă</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Descrie setul dorit — de ex. „obiecte de bucătărie pe care le-ai găsi într-o gospodărie franceză” sau „expresii de călătorie de afaceri pentru o conferință”…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Mai sunt %1 din %2 generări luna aceasta — se resetează %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>IA poate greși. Se generează doar conținut potrivit pentru toate vârstele — folosește 🚩 Raportează pentru a semnala orice este nepotrivit.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Limba cuvântului</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Limba indiciului</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Numărul de cuvinte</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Se întreabă Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Anulează cererea</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Generează</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ IA</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Set nou de cuvinte</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Editează setul de cuvinte</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importă</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Titlul setului…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Preia imagini automat</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Cuvânt</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>selectat</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Cuvânt / Termen</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Neselectat</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Introdu cuvântul...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Indiciu / sens</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Indiciu, definiție...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Exemplu de utilizare</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Propoziție exemplu cu cuvântul...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Schimbă imaginea</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Adaugă imagine</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Preia</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Cameră</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Adaugă audio</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Oprește</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Redă</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ TTS</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Oprește</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Înreg.</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Adaugă cuvânt</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Elimină</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Salvează</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Titlul este obligatoriu</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>în curând</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>peste %1z %2o</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>peste %1o %2m</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>peste %1m</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Selectează imagine</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Selectează audio</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ IA</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Set de reguli nou</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Editează setul de reguli</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importă</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Importă set de reguli</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ Generator de seturi de reguli cu IA</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Susținut de Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Au mai rămas %1 din %2 generări luna aceasta — se resetează %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Regula/subiectul de explicat</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Descrie regula dorită — de ex. &quot;prezent simplu vs. prezent continuu&quot; sau &quot;propoziții condiționale de tipul trei&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Întrebări pe tip</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Completează spațiul liber</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Alegere multiplă</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Selecție derulantă</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Trage și plasează</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Se interoghează Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Anulează cererea</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Anulează</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>IA poate greși. Se generează doar conținut potrivit pentru toate vârstele — folosește 🚩 Raportează pentru a semnala orice este nepotrivit.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Generează</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Introdu titlul…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Explicația teoriei</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Ascuns în timpul testului până când elevul face o greșeală — mereu vizibil în previzualizare.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Folosește ▲▼ pentru a reordona un bloc. Trage colțul // al unei fotografii pentru a-i modifica dimensiunea.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Explică regula pe care o exersează acest set…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Clip audio</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Text</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Fotografie</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Audio</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Întrebare</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>selectat</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Completează spațiul liber</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Alegere multiplă</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Selecție derulantă</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Trage și plasează</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Folosește ___ (trei liniuțe de subliniere) pentru fiecare spațiu liber completat de elev.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>de ex. Ce face ea în fiecare zi?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>de ex. Ea merge ___ la școală în fiecare zi.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Răspunsuri</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Un răspuns pentru fiecare spațiu liber, separate prin virgule, în ordine. Folosește \, pentru o virgulă literală.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>de ex. merge</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Opțiuni</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Separă opțiunile pentru un spațiu liber cu virgule; separă spațiile libere cu două puncte duble (::). Un singur : este sigur așa cum este; folosește \, pentru o virgulă literală, \:: pentru un :: literal, și ___ pentru o opțiune goală în mod deliberat. De ex. pentru două spații libere: merge, a merge, mergând::fiecare, unii, majoritatea.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Piese trăgabile separate prin virgule — include răspunsurile corecte, plus momeli opționale cu care elevul poate fi păcălit. Folosește \, pentru o virgulă literală și ___ pentru o piesă goală (pentru un spațiu liber care trebuie să rămână gol). Completează spațiile libere de mai jos odată ce acestea sunt stabilite.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>de ex. merge, a merge, mergând::fiecare, unii, majoritatea</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>de ex. merge, a merge, mergând, mers</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Răspuns corect pentru fiecare spațiu liber</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Atinge opțiunea corectă din fiecare casetă de mai jos.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Selectează un răspuns corect pentru fiecare spațiu liber.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Spațiu liber %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Completează spațiile libere</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Trage o piesă pe un spațiu liber de mai jos, sau atinge o piesă și apoi un spațiu liber pentru a o plasa.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Completează fiecare spațiu liber cu o piesă.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Opțiuni separate prin virgule — atinge răspunsul corect de mai jos. Folosește \, pentru o virgulă literală.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Opțiuni separate prin virgule — atinge toate răspunsurile corecte de mai jos. Folosește \, pentru o virgulă literală.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>de ex. merge, a merge, mergând, mers</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Doar un răspuns corect</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Răspuns corect</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Răspuns(uri) corect(e)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Selectează răspunsul corect.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Selectează cel puțin un răspuns corect.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Adaugă întrebare</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Elimină</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Salvează</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Titlul este obligatoriu</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Explică gramatica</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Întrebarea %1 nu a putut fi încărcată: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Au fost generate doar %1 din %2 întrebări solicitate — încearcă un subiect mai larg sau redu numerele de mai sus.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Limba explicației</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Limba explicației</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Limba subiectului</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Limba subiectului</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Pentru această temă nu se poate genera conținut. IA creează doar conținut potrivit pentru toate vârstele — temele sexuale, vulgare sau ofensatoare nu sunt acceptate. Încearcă o altă temă.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Ai folosit toate generările cu IA din această lună. Încearcă din nou luna viitoare.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Prea multe rapoarte astăzi — încearcă din nou mâine.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Serviciul IA este ocupat acum — încearcă din nou peste câteva momente.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Introdu mai întâi o temă.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Tema este prea lungă (max. %1 caractere).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Setează cel puțin un tip de întrebare peste zero.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Sesiunea ta a expirat — conectează-te din nou.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Serverul nu a putut fi contactat. Verifică-ți conexiunea la internet și încearcă din nou.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Ceva nu a mers bine. Încearcă din nou.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Nu ești conectat.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Atinge pentru a întoarce</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Atinge pentru a întoarce înapoi</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>ȘTIU</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>SARI</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Nu știu</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Știu</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Neselectat</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Textul licenței nu a putut fi încărcat.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Conectează-te pentru a continua</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Se deschide browserul…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Conectează-te cu Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Există deja aici o bibliotecă sau un set cu acest nume.</translation>
    </message>
    <message>
        <location line="+309"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Există deja aici un set de cuvinte cu acest nume.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Există deja aici un set de reguli cu acest nume.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+37"/>
        <source>Results</source>
        <translation>Rezultate</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Well</source>
        <translation>Foarte</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>done</source>
        <translation>bine</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>din %1</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Muncă excelentă! Continuă tot așa!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Efort bun! Continuă să exersezi.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Nu renunța – exercițiul face maestrul!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Această sesiune</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Nu știu</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Știu</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Practice Again</source>
        <translation>Exersează din nou</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Resetezi progresul testului?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Aceasta va șterge progresul tău în acest set de reguli și va începe o sesiune nouă.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 întrebări</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Finalizat: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">În curs: %1 / %2</translation>
    </message>
    <message>
        <location line="+67"/>
        <source>← Reset</source>
        <translation>← Resetează</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Explicația regulii</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Nu a fost adăugată nicio explicație pentru acest set.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Clip audio</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Strictețea ortografică</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Strictă</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normală</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Permisivă</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Începe testul</translation>
    </message>
    <message>
        <location line="-198"/>
        <source>Test is completed</source>
        <translation>Testul este finalizat</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Următoarea întrebare: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Corect: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Regulă</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Explicația regulii</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Clip audio</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Anulează</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Vezi regula</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Rotește roata pentru a alege cuvântul fiecărui spațiu liber.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Spațiu liber %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Trage o piesă pe un spațiu liber, sau atinge o piesă și apoi un spațiu liber pentru a o plasa.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Selectează răspunsul corect.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Selectează tot ce se aplică.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Corect: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Trimite</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Corect: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Vezi rezultatele</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Următorul →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Întrebarea numărul %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Suprascrii setul de cuvinte?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Combini bibliotecile?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Există deja aici un set de cuvinte numit „%1”. Îl suprascrii cu setul mutat?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Există deja aici o bibliotecă numită „%1”. Îi combini conținutul cu aceasta?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Există deja un set de cuvinte numit „%1” în %2. Îl suprascrii cu versiunea combinată?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>biblioteca de destinație</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Exportă ca .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Bibliotecă nouă</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Library name:</source>
        <translation>Numele bibliotecii:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>de ex. Călătorii, Muncă, Școală…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Există deja aici o bibliotecă sau un set cu acest nume.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+74"/>
        <source>A library with this name already exists here.</source>
        <translation>Există deja aici o bibliotecă cu acest nume.</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Create</source>
        <translation>Creează</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Rename Library</source>
        <translation>Redenumește biblioteca</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Nume nou:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Redenumește</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Seturile tale de cuvinte</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Bibliotecă</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Mută în afara</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Lasă pentru a muta înăuntru</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>cuvinte</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>întrebări</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Șterge biblioteca</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Editează</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Șterge</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Distribuie fișierul .ppset</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Exportă .ppset (salvează pe disc)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Încă nimic aici.
Atinge + Creează pentru a adăuga un set de cuvinte sau o bibliotecă.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Set de cuvinte</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Set de reguli</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Creează</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Limba interfeței</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Cancel</source>
        <translation>Anulează</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Alege tipul de test</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Flashcard-uri</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Întoarce pentru a dezvălui — glisează la dreapta dacă știi</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Scrie cuvântul</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Vezi indiciul — tastează expresia</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Scrie indiciul</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Vezi cuvântul — tastează traducerea</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Alege cuvântul</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Vezi indiciul — alege dintre 4 opțiuni</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Alege indiciul</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Vezi cuvântul — alege dintre 4 opțiuni</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Învățare progresivă</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Grilă pentru a învăța, apoi scriere pentru a stăpâni toate cuvintele</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Învățare progresivă inversă</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Grilă pentru a învăța, apoi scriere pentru a stăpâni toate indiciile</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>✓ Done</source>
        <translation>✓ Terminat</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>← Reset</source>
        <translation>← Resetează</translation>
    </message>
    <message>
        <location line="+96"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Strictețea ortografică</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Strictă</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normală</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Permisivă</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Anulează</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Revizuiește expresiile</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Oprește</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Ascultă</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Începe testul</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Încă niciun cuvânt</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Tastează indiciul / traducerea…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Tastează expresia…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Corect: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Marchează ca fiind corect (am greșit la tastare)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Trimite</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Marchează ca fiind corect (am dat clic greșit)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Corect: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Vezi rezultatele</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Următorul →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Întrebarea numărul %1</translation>
    </message>
</context>
</TS>
