<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="is">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Um</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Orðaforðaþjálfari til að leggja á minnið orðasett.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Þjálfari í orðaforða og málfræði.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Opinn hugbúnaðarleyfi</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Þetta forrit notar Qt undir GNU Lesser General Public License útgáfu 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Qt-tilkynning</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Qt-tilkynning</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Qt frumkóði</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Vefsíða Qt verkefnisins</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Búið til af gervigreind — getur innihaldið villur</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Tilkynna</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Takk — tilkynningin þín var send og verður yfirfarin.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Tilkynna efni frá gervigreind</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Hvað er að þessu tilbúna efni?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Kynferðislegt eða tvírætt efni</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Blótsyrði eða móðgandi orðalag</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Hatursfullt eða áreitandi efni</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Ofbeldisfullt eða hættulegt efni</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Rangar eða villandi upplýsingar</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Eitthvað annað</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Nánar (valfrjálst)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Sendi…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Loka</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Hætta við</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Senda tilkynningu</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Taka mynd</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Hætta við</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>fljótlega</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>eftir %1d %2klst</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>eftir %1klst %2mín</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>eftir %1mín</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Velja mynd</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Velja hljóð</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Flytja inn orðasett</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Tungumál orðs</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Tungumál vísbendingar</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+339"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Hætta við</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ AI orðasettsgjafi</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Knúið af Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Þema</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Lýstu settinu sem þú vilt — t.d. „eldhúshlutir sem þú myndir finna á frönsku heimili“ eða „viðskiptaferðasetningar fyrir ráðstefnu“…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>%1 af %2 kynslóðum eftir í mánuðinum — endurstillist %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>Gervigreind getur gert mistök. Aðeins er búið til efni sem hentar öllum aldurshópum — notaðu 🚩 Tilkynna til að merkja allt óviðeigandi.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Tungumál orðs</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Tungumál vísbendingar</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Fjöldi orða</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Spyr Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Hætta við beiðni</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Búa til</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Nýtt orðasett</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Breyta orðasetti</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Flytja inn</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Titill setts…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Sækja myndir sjálfkrafa</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Orð</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>valið</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Orð / Hugtak</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Ekki valið</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Sláðu inn orð...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Vísbending / merking</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Vísbending, skilgreining...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Dæmi um notkun</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Dæmasetning með orðinu...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Breyta mynd</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Bæta við mynd</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Sækja</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Myndavél</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Bæta við hljóði</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Stöðva</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Spila</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ TTS</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Stöðva</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Taka upp</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Bæta við orði</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Fjarlægja</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Vista</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Titill er nauðsynlegur</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>bráðum</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>eftir %1d %2klst</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>eftir %1klst %2mín</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>eftir %1mín</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Velja mynd</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Velja hljóð</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ Gervigreind</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Nýtt reglusafn</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Breyta reglusafni</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Flytja inn</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Flytja inn reglusafn</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ Gervigreindar reglusafnsgjafi</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Knúið af Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>%1 af %2 útgáfum eftir í þessum mánuði — endurstillist %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Regla/efni til að útskýra</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Lýstu reglunni sem þú vilt — t.d. &quot;nútíð einföld vs nútíð yfirstandandi&quot; eða &quot;skilyrðissetningar af þriðju gerð&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Spurningar á tegund</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Fylla í eyðu</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Fjölvalsspurning</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Fellivalmynd</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Draga og sleppa</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Spyr Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Hætta við beiðni</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Hætta við</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>Gervigreind getur gert mistök. Aðeins er búið til efni sem hentar öllum aldurshópum — notaðu 🚩 Tilkynna til að merkja allt óviðeigandi.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Búa til</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Sláðu inn titil…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Kenningarskýring</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Falið meðan á prófi stendur þar til nemandi gerir mistök — alltaf læsilegt í forskoðun.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Notaðu ▲▼ til að endurraða bloki. Dragðu // horn myndar til að breyta stærð hennar.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Útskýrðu regluna sem þetta safn æfir…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Hljóðbrot</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Texti</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Mynd</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Hljóð</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Spurning</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>valið</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Fylla í eyðu</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Fjölvalsspurning</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Fellivalmynd</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Draga og sleppa</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Notaðu ___ (þrjú undirstrik) fyrir hverja eyðu sem nemandinn fyllir út í.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>t.d. Hvað gerir hún á hverjum degi?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>t.d. Hún fer ___ í skólann á hverjum degi.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Svör</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Eitt svar á eyðu, aðskilin með kommum, í röð. Notaðu \, fyrir bókstaflega kommu.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>t.d. fer</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Valkostir</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Aðskildu valkosti fyrir eina eyðu með kommum; aðskildu eyður með tvöföldu tvípunkti (::). Stakt : er öruggt eins og það er; notaðu \, fyrir bókstaflega kommu, \:: fyrir bókstaflegt ::, og ___ fyrir viljandi tóman valkost. T.d. fyrir tvær eyður: fer, fara, farandi::hver, sumir, flestir.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Dráttarflísar aðskildar með kommum — bættu við réttum svörum, auk valfrjálsra gildra sem hægt er að plata nemandann með. Notaðu \, fyrir bókstaflega kommu, og ___ fyrir tóma flís (fyrir eyðu sem á réttilega að vera tóm). Fylltu út í eyðurnar hér að neðan þegar þessar eru stilltar.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>t.d. fer, fara, farandi::hver, sumir, flestir</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>t.d. fer, fara, farandi, farið</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Rétt svar fyrir hverja eyðu</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Ýttu á réttan valkost í hverjum reit hér að neðan.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Veldu rétt svar fyrir hverja eyðu.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Eyða %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Fylltu út í eyðurnar</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Dragðu flís á eyðu hér að neðan, eða ýttu á flís og síðan eyðu til að setja hana.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Fylltu hverja eyðu með flís.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Valkostir aðskildir með kommum — ýttu á rétt svar hér að neðan. Notaðu \, fyrir bókstaflega kommu.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Valkostir aðskildir með kommum — ýttu á öll rétt svör hér að neðan. Notaðu \, fyrir bókstaflega kommu.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>t.d. fer, fara, farandi, farið</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Aðeins eitt rétt svar</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Rétt svar</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Rétt svar/svör</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Veldu rétta svarið.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Veldu að minnsta kosti eitt rétt svar.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Bæta við spurningu</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Fjarlægja</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Vista</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Titill er nauðsynlegur</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Útskýra málfræði</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Ekki tókst að hlaða %1 spurningu: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Aðeins %1 af %2 umbeðnum spurningum voru búnar til — prófaðu víðara efni eða minnkaðu tölurnar hér að ofan.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Skýringarmál</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Skýringarmál</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Efnismál</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Efnismál</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Ekki er hægt að búa til efni um þetta efni. Gervigreindin býr aðeins til efni sem hentar öllum aldurshópum — kynferðisleg, dónaleg eða móðgandi viðfangsefni eru ekki studd. Prófaðu annað viðfangsefni.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Þú hefur notað allar gervigreindarkeyrslur þessa mánaðar. Reyndu aftur í næsta mánuði.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Of margar tilkynningar í dag — reyndu aftur á morgun.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Gervigreindarþjónustan er upptekin núna — reyndu aftur eftir smástund.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Sláðu fyrst inn þema.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Þemað er of langt (hámark %1 stafir).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Stilltu að minnsta kosti eina spurningategund yfir núll.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Lotan þín er útrunnin — skráðu þig inn aftur.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Ekki náðist samband við þjóninn. Athugaðu nettenginguna og reyndu aftur.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Eitthvað fór úrskeiðis. Reyndu aftur.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Ekki innskráð(ur).</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Ýttu til að snúa við</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Ýttu til að snúa til baka</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>KANN</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>SLEPPA</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Kann ekki</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Kann</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Ekki valið</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Ekki tókst að hlaða leyfistexta.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Skráðu þig inn til að halda áfram</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Opna vafra…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Skrá inn með Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Safn eða sett með þessu nafni er þegar til hér.</translation>
    </message>
    <message>
        <location line="+317"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Orðasett með þessu nafni er þegar til hér.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Reglusafn með þessu nafni er þegar til hér.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+38"/>
        <source>Results</source>
        <translation>Niðurstöður</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>Well</source>
        <translation>Vel</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>done</source>
        <translation>gert</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>af %1</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Frábært starf! Haltu áfram!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Góð tilraun! Haltu áfram að æfa.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Ekki gefast upp – æfingin skapar meistarann!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Þessi lota</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Kann ekki</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Kann</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Practice again</source>
        <translation>Æfa aftur</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Find another set</source>
        <translation>Finna annað sett</translation>
    </message>
    <message>
        <source>Practice Again</source>
        <translation type="vanished">Æfa aftur</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Endurstilla framvindu prófs?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Þetta hreinsar framvindu þína í þessu reglusafni og hefur nýja lotu.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 spurningar</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Lokið: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Í vinnslu: %1 / %2</translation>
    </message>
    <message>
        <source>← Reset</source>
        <translation type="vanished">← Endurstilla</translation>
    </message>
    <message>
        <location line="+185"/>
        <source>Reset to practise again</source>
        <translation>Endurstilla til að æfa aftur</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Reset</source>
        <translation>Endurstilla</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Reglaútskýring</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Engin útskýring hefur verið bætt við fyrir þetta safn.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Hljóðbrot</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Stafsetningarstrangleiki</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Strangt</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Venjulegt</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Vægt</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Hefja próf</translation>
    </message>
    <message>
        <location line="-316"/>
        <source>Test is completed</source>
        <translation>Prófinu er lokið</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Næsta spurning: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Rétt: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Regla</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Reglaútskýring</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Hljóðbrot</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Hætta við</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Skoða reglu</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Snúðu hjólinu til að velja orð hverrar eyðu.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Eyða %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Dragðu flís á eyðu, eða ýttu á flís og síðan eyðu til að setja hana.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Veldu rétta svarið.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Veldu allt sem á við.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Rétt: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Senda inn</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Rétt: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Skoða niðurstöður</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Næsta →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Spurning númer %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Skrifa yfir orðasett?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Sameina söfn?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Orðasett með nafninu „%1“ er þegar til hér. Skrifa yfir það með flutta settinu?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Safn með nafninu „%1“ er þegar til hér. Sameina innihald þess við það?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Orðasett með nafninu „%1“ er þegar til í %2. Skrifa yfir það með sameinaðri útgáfu?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>marksafnið</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Flytja út sem .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Nýtt safn</translation>
    </message>
    <message>
        <location line="+31"/>
        <source>Library name:</source>
        <translation>Nafn safns:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>t.d. Ferðalög, Vinna, Skóli…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Safn eða sett með þessu nafni er þegar til hér.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+99"/>
        <source>A library with this name already exists here.</source>
        <translation>Safn með þessu nafni er þegar til hér.</translation>
    </message>
    <message>
        <location line="-62"/>
        <source>Create</source>
        <translation>Búa til</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Rename Library</source>
        <translation>Endurnefna safn</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Nýtt nafn:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Endurnefna</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Orðasettin þín</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Safn</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Flytja út úr</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Slepptu til að flytja inn í</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>orð</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>spurningar</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Eyða safni</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Breyta</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Eyða</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Deila .ppset skrá</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Flytja út .ppset (vista á disk)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Ekkert hér enn.
Ýttu á + Búa til til að bæta við orðasetti eða safni.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Orðasett</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Reglusafn</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Búa til</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Tungumál viðmóts</translation>
    </message>
    <message>
        <location line="-710"/>
        <location line="+796"/>
        <source>Cancel</source>
        <translation>Hætta við</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Veldu prófgerð</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Minniskort</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Snúðu til að afhjúpa — strjúktu til hægri ef þú kannt það</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Skrifaðu orðið</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Sjáðu vísbendinguna — sláðu inn orðasambandið</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Skrifaðu vísbendinguna</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Sjáðu orðið — sláðu inn þýðingu þess</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Veldu orðið</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Sjáðu vísbendinguna — veldu úr 4 möguleikum</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Veldu vísbendinguna</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Sjáðu orðið — veldu úr 4 möguleikum</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Stighækkandi nám</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Fjölval til að læra, síðan skrifun til að ná tökum á öllum orðum</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Öfugt stighækkandi nám</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Fjölval til að læra, síðan skrifun til að ná tökum á öllum vísbendingum</translation>
    </message>
    <message>
        <location line="+36"/>
        <location line="+82"/>
        <source>✓ Done</source>
        <translation>✓ Lokið</translation>
    </message>
    <message>
        <location line="-82"/>
        <source>← Reset</source>
        <translation>← Endurstilla</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Completed — swipe left to reset</source>
        <translation>Lokið — strjúktu til vinstri til að endurstilla</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>%1 left</source>
        <translation>%1 eftir</translation>
    </message>
    <message>
        <location line="+51"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Stafsetningarstrangleiki</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Strangt</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Venjulegt</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Vægt</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Hætta við</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Fara yfir orðasambönd</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Stöðva</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Hlusta</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Hefja próf</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Engin orð enn</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Sláðu inn vísbendingu / þýðingu…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Sláðu inn orðasambandið…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Rétt: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Merkja sem rétt (ég skrifaði vitlaust)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Senda inn</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Merkja sem rétt (ég smellti vitlaust)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Rétt: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Sjá niðurstöður</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Áfram →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Spurning númer %1</translation>
    </message>
</context>
</TS>
