<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="th">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>เกี่ยวกับ</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">โปรแกรมฝึกคำศัพท์สำหรับจดจำชุดคำศัพท์</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>โปรแกรมฝึกคำศัพท์และไวยากรณ์</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>สัญญาอนุญาตโอเพนซอร์ส</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>แอปพลิเคชันนี้ใช้ Qt ภายใต้สัญญาอนุญาต GNU Lesser General Public License เวอร์ชัน 3</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>ประกาศเกี่ยวกับ Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>ประกาศเกี่ยวกับ Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>ซอร์สโค้ดของ Qt</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>เว็บไซต์โครงการ Qt</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ สร้างโดย AI — อาจมีข้อผิดพลาด</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 รายงาน</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>ขอบคุณ — ส่งรายงานของคุณแล้ว และจะได้รับการตรวจสอบ</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 รายงานเนื้อหา AI</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>เนื้อหาที่สร้างขึ้นนี้มีปัญหาอะไร</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>เนื้อหาทางเพศหรือส่อไปในทางเพศ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>คำหยาบหรือภาษาที่ไม่เหมาะสม</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>เนื้อหาที่แสดงความเกลียดชังหรือการคุกคาม</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>เนื้อหาที่รุนแรงหรือเป็นอันตราย</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>ข้อมูลที่ไม่ถูกต้องหรือทำให้เข้าใจผิด</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>อื่น ๆ</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>รายละเอียด (ไม่บังคับ)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>กำลังส่ง…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>ปิด</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>ยกเลิก</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>ส่งรายงาน</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>ถ่ายภาพ</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>ยกเลิก</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>เร็ว ๆ นี้</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>ใน %1 วัน %2 ชม.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>ใน %1 ชม. %2 นาที</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>ใน %1 นาที</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>เลือกรูปภาพ</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>เลือกเสียง</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>นำเข้าชุดคำศัพท์</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>ภาษาของคำศัพท์</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>ภาษาของคำใบ้</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+326"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>ยกเลิก</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ ตัวสร้างชุดคำศัพท์ด้วย AI</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>ขับเคลื่อนด้วย Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 หัวข้อ</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>อธิบายชุดคำศัพท์ที่คุณต้องการ — เช่น “ของใช้ในครัวที่พบได้ในบ้านฝรั่งเศส” หรือ “วลีสำหรับการเดินทางธุรกิจไปประชุม”…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>เหลือ %1 จาก %2 ครั้งในเดือนนี้ — รีเซ็ตวันที่ %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI อาจผิดพลาดได้ ระบบสร้างเฉพาะเนื้อหาที่เหมาะสมกับทุกวัย — ใช้ 🚩 รายงาน เพื่อแจ้งสิ่งที่ไม่เหมาะสม</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>ภาษาของคำศัพท์</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>ภาษาของคำใบ้</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 จำนวนคำ</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>กำลังสอบถาม Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>ยกเลิกคำขอ</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ สร้าง</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>ชุดคำศัพท์ใหม่</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>แก้ไขชุดคำศัพท์</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>นำเข้า</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>ชื่อชุดคำศัพท์…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>ดึงรูปภาพอัตโนมัติ</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>คำศัพท์</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>เลือกแล้ว</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>คำศัพท์ / คำ</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>ยังไม่ได้เลือก</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>ป้อนคำศัพท์...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>คำใบ้ / ความหมาย</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>คำใบ้ คำจำกัดความ...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>ตัวอย่างการใช้งาน</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>ตัวอย่างประโยคที่ใช้คำนี้...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>เปลี่ยนรูปภาพ</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>เพิ่มรูปภาพ</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>ดึงข้อมูล</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>กล้อง</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>เพิ่มเสียง</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ หยุด</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ เล่น</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ อ่านออกเสียง</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ หยุด</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● อัดเสียง</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ เพิ่มคำศัพท์</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>ลบออก</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>บันทึก</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>ต้องระบุชื่อ</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>เร็วๆ นี้</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>ใน %1วัน %2ชม.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>ใน %1ชม. %2น.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>ใน %1น.</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>เลือกรูปภาพ</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>เลือกเสียง</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>ชุดกฎใหม่</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>แก้ไขชุดกฎ</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>นำเข้า</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>นำเข้าชุดกฎ</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ ตัวสร้างชุดกฎด้วย AI</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>ขับเคลื่อนโดย Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>เหลือ %1 จาก %2 การสร้างในเดือนนี้ — รีเซ็ต %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 กฎ/หัวข้อที่จะอธิบาย</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>อธิบายกฎที่คุณต้องการ — เช่น &quot;present simple กับ present continuous&quot; หรือ &quot;ประโยคเงื่อนไขแบบที่สาม&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 จำนวนคำถามต่อประเภท</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 เติมคำในช่องว่าง</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 ปรนัย</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 เลือกแบบดรอปดาวน์</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 ลากแล้ววาง</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>กำลังถาม Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>ยกเลิกคำขอ</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>ยกเลิก</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI อาจผิดพลาดได้ ระบบสร้างเฉพาะเนื้อหาที่เหมาะสมกับทุกวัย — ใช้ 🚩 รายงาน เพื่อแจ้งสิ่งที่ไม่เหมาะสม</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ สร้าง</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>ใส่ชื่อเรื่อง…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>คำอธิบายทฤษฎี</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>ซ่อนอยู่ระหว่างการทดสอบจนกว่าผู้เรียนจะทำผิด — สามารถอ่านได้เสมอในหน้าตัวอย่าง</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>ใช้ ▲▼ เพื่อจัดลำดับบล็อกใหม่ ลากมุม // ของรูปภาพเพื่อปรับขนาด</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>อธิบายกฎที่ชุดนี้ฝึกฝน…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>คลิปเสียง</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ ข้อความ</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ รูปภาพ</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ เสียง</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>คำถาม</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>เลือกแล้ว</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>เติมคำในช่องว่าง</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>ปรนัย</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>เลือกแบบดรอปดาวน์</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>ลากแล้ววาง</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>ใช้ ___ (ขีดล่างสามตัว) สำหรับแต่ละช่องว่างที่ผู้เรียนเติม</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>เช่น เธอทำอะไรทุกวัน?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>เช่น เธอไป ___ โรงเรียนทุกวัน</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>คำตอบ</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>คำตอบหนึ่งข้อต่อช่องว่างหนึ่งช่อง คั่นด้วยจุลภาค ตามลำดับ ใช้ \, สำหรับจุลภาคตามตัวอักษร</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>เช่น ไป</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>ตัวเลือก</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>แยกตัวเลือกสำหรับช่องว่างหนึ่งช่องด้วยจุลภาค แยกช่องว่างด้วยเครื่องหมายทวิภาคคู่ (::) เครื่องหมาย : เดี่ยวปลอดภัยตามที่เป็นอยู่ ใช้ \, สำหรับจุลภาคตามตัวอักษร \:: สำหรับ :: ตามตัวอักษร และ ___ สำหรับตัวเลือกว่างเปล่าโดยตั้งใจ เช่น สำหรับสองช่องว่าง: ไป, ไป, กำลังไป::ทุก, บาง, ส่วนใหญ่</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>กระเบื้องที่ลากได้ คั่นด้วยจุลภาค — รวมคำตอบที่ถูกต้อง บวกกับตัวลวงที่เป็นตัวเลือกซึ่งอาจทำให้ผู้เรียนสับสน ใช้ \, สำหรับจุลภาคตามตัวอักษร และ ___ สำหรับกระเบื้องว่างเปล่า (สำหรับช่องว่างที่ควรเว้นว่างไว้อย่างถูกต้อง) เติมช่องว่างด้านล่างเมื่อกำหนดค่าเหล่านี้แล้ว</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>เช่น ไป, ไป, กำลังไป::ทุก, บาง, ส่วนใหญ่</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>เช่น ไป, ไป, กำลังไป, ไปแล้ว</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>คำตอบที่ถูกต้องสำหรับแต่ละช่องว่าง</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>แตะตัวเลือกที่ถูกต้องในแต่ละกล่องด้านล่าง</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>เลือกคำตอบที่ถูกต้องสำหรับแต่ละช่องว่าง</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>ช่องว่าง %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>เติมช่องว่าง</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>ลากกระเบื้องไปยังช่องว่างด้านล่าง หรือแตะกระเบื้องแล้วแตะช่องว่างเพื่อวาง</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>เติมแต่ละช่องว่างด้วยกระเบื้อง</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>ตัวเลือกคั่นด้วยจุลภาค — แตะคำตอบที่ถูกต้องด้านล่าง ใช้ \, สำหรับจุลภาคตามตัวอักษร</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>ตัวเลือกคั่นด้วยจุลภาค — แตะคำตอบที่ถูกต้องทั้งหมดด้านล่าง ใช้ \, สำหรับจุลภาคตามตัวอักษร</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>เช่น ไป, ไป, กำลังไป, ไปแล้ว</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>คำตอบที่ถูกต้องเพียงข้อเดียว</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>คำตอบที่ถูกต้อง</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>คำตอบที่ถูกต้อง</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>เลือกคำตอบที่ถูกต้อง</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>เลือกคำตอบที่ถูกต้องอย่างน้อยหนึ่งข้อ</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ เพิ่มคำถาม</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>ลบ</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>บันทึก</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>ต้องระบุชื่อเรื่อง</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 อธิบายไวยากรณ์</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>ไม่สามารถโหลดคำถาม %1 ได้: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>สร้างได้เพียง %1 จาก %2 คำถามที่ขอ — ลองใช้หัวข้อที่กว้างขึ้น หรือลดจำนวนด้านบน</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>ภาษาของคำอธิบาย</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>ภาษาของคำอธิบาย</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>ภาษาของหัวข้อ</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>ภาษาของหัวข้อ</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>ไม่สามารถสร้างเนื้อหาในหัวข้อนี้ได้ AI สร้างเฉพาะเนื้อหาที่เหมาะสมกับทุกวัย — ไม่รองรับหัวข้อทางเพศ หยาบคาย หรือไม่เหมาะสม โปรดลองหัวข้ออื่น</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>คุณใช้การสร้างด้วย AI ของเดือนนี้ครบแล้ว โปรดลองอีกครั้งในเดือนหน้า</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>วันนี้มีการรายงานมากเกินไป — โปรดลองอีกครั้งพรุ่งนี้</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>บริการ AI ไม่ว่างในขณะนี้ — โปรดลองอีกครั้งในอีกสักครู่</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>โปรดป้อนหัวข้อก่อน</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>หัวข้อยาวเกินไป (สูงสุด %1 ตัวอักษร)</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>ตั้งค่าคำถามอย่างน้อยหนึ่งประเภทให้มากกว่าศูนย์</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>เซสชันของคุณหมดอายุแล้ว — โปรดลงชื่อเข้าใช้อีกครั้ง</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ได้ โปรดตรวจสอบการเชื่อมต่ออินเทอร์เน็ตแล้วลองอีกครั้ง</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>เกิดข้อผิดพลาด โปรดลองอีกครั้ง</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>ยังไม่ได้ลงชื่อเข้าใช้</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>แตะเพื่อพลิก</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>แตะเพื่อพลิกกลับ</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>รู้จัก</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>ข้าม</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  ไม่รู้จัก</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  รู้จัก</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>ยังไม่ได้เลือก</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>ไม่สามารถโหลดข้อความสัญญาอนุญาตได้</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>ลงชื่อเข้าใช้เพื่อดำเนินการต่อ</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>กำลังเปิดเบราว์เซอร์…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>ลงชื่อเข้าใช้ด้วย Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">มีไลบรารีหรือชุดคำศัพท์ชื่อนี้อยู่แล้วที่นี่</translation>
    </message>
    <message>
        <location line="+309"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>มีชุดคำศัพท์ชื่อนี้อยู่แล้วที่นี่</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>มีชุดกฎชื่อนี้อยู่แล้วที่นี่</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+37"/>
        <source>Results</source>
        <translation>ผลลัพธ์</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Well</source>
        <translation>เยี่ยม</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>done</source>
        <translation>มาก</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>จาก %1</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>ทำได้ดีมาก! ทำต่อไปนะ!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>พยายามได้ดี! ฝึกฝนต่อไป</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>อย่ายอมแพ้ – การฝึกฝนทำให้สมบูรณ์แบบ!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>เซสชันนี้</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>ไม่รู้จัก</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>รู้จัก</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Practice Again</source>
        <translation>ฝึกอีกครั้ง</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>รีเซ็ตความคืบหน้าการทดสอบ?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>การดำเนินการนี้จะล้างความคืบหน้าของคุณในชุดกฎนี้และเริ่มเซสชันใหม่</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 คำถาม</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">เสร็จสิ้น: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">กำลังดำเนินการ: %1 / %2</translation>
    </message>
    <message>
        <location line="+67"/>
        <source>← Reset</source>
        <translation>← รีเซ็ต</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>คำอธิบายกฎ</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>ไม่มีคำอธิบายที่เพิ่มสำหรับชุดนี้</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>คลิปเสียง</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ ความเข้มงวดด้านการสะกดคำ</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>เข้มงวด</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>ปกติ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>ผ่อนปรน</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>เริ่มการทดสอบ</translation>
    </message>
    <message>
        <location line="-198"/>
        <source>Test is completed</source>
        <translation>แบบทดสอบเสร็จสมบูรณ์แล้ว</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>คำถามถัดไป: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>ถูกต้อง: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>กฎ</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 คำอธิบายกฎ</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>คลิปเสียง</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>ยกเลิก</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 ดูกฎ</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>หมุนวงล้อเพื่อเลือกคำของแต่ละช่องว่าง</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>ช่องว่าง %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>ลากกระเบื้องไปยังช่องว่าง หรือแตะกระเบื้องแล้วแตะช่องว่างเพื่อวาง</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>เลือกคำตอบที่ถูกต้อง</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>เลือกทั้งหมดที่เกี่ยวข้อง</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>ถูกต้อง: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>ส่ง</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>ถูกต้อง: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>ดูผลลัพธ์</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>ถัดไป →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>คำถามหมายเลข %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>เขียนทับชุดคำศัพท์หรือไม่</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>รวมไลบรารีหรือไม่</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>มีชุดคำศัพท์ชื่อ “%1” อยู่แล้วที่นี่ ต้องการเขียนทับด้วยชุดที่ย้ายมาหรือไม่</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>มีไลบรารีชื่อ “%1” อยู่แล้วที่นี่ ต้องการรวมเนื้อหาเข้ากับไลบรารีนี้หรือไม่</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>มีชุดคำศัพท์ชื่อ “%1” อยู่แล้วใน %2 ต้องการเขียนทับด้วยเวอร์ชันที่รวมเข้าด้วยกันหรือไม่</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>ไลบรารีปลายทาง</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>ส่งออกเป็น .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>ไลบรารีใหม่</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Library name:</source>
        <translation>ชื่อไลบรารี:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>เช่น ท่องเที่ยว งาน โรงเรียน…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">มีไลบรารีหรือชุดคำศัพท์ชื่อนี้อยู่แล้วที่นี่</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+74"/>
        <source>A library with this name already exists here.</source>
        <translation>มีไลบรารีชื่อนี้อยู่แล้วที่นี่</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Create</source>
        <translation>สร้าง</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Rename Library</source>
        <translation>เปลี่ยนชื่อไลบรารี</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>ชื่อใหม่:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>เปลี่ยนชื่อ</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>ชุดคำศัพท์ของคุณ</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>ไลบรารี</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>ย้ายออกจาก</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>วางเพื่อย้ายเข้าไป</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>คำ</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>คำถาม</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>ลบไลบรารี</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>แก้ไข</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>ลบ</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>แชร์ไฟล์ .ppset</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>ส่งออก .ppset (บันทึกลงดิสก์)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>ยังไม่มีอะไรที่นี่
แตะ + สร้าง เพื่อเพิ่มชุดคำศัพท์หรือไลบรารี</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>ชุดคำศัพท์</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>ชุดกฎ</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ สร้าง</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>ภาษาส่วนติดต่อผู้ใช้</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Cancel</source>
        <translation>ยกเลิก</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>เลือกประเภทแบบทดสอบ</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>บัตรคำ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>พลิกเพื่อดูคำตอบ — ปัดขวาถ้าคุณรู้จัก</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>เขียนคำศัพท์</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>ดูคำใบ้ — พิมพ์สำนวน</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>เขียนคำใบ้</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>ดูคำศัพท์ — พิมพ์คำแปล</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>เลือกคำศัพท์</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>ดูคำใบ้ — เลือกจาก 4 ตัวเลือก</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>เลือกคำใบ้</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>ดูคำศัพท์ — เลือกจาก 4 ตัวเลือก</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>การเรียนรู้แบบต่อเนื่อง</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>เลือกตอบแบบปรนัยเพื่อเรียนรู้ก่อน จากนั้นเขียนเพื่อฝึกฝนคำศัพท์ทั้งหมด</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>การเรียนรู้แบบต่อเนื่องย้อนกลับ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>เลือกตอบแบบปรนัยเพื่อเรียนรู้ก่อน จากนั้นเขียนเพื่อฝึกฝนคำใบ้ทั้งหมด</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>✓ Done</source>
        <translation>✓ เสร็จสิ้น</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>← Reset</source>
        <translation>← รีเซ็ต</translation>
    </message>
    <message>
        <location line="+96"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ ความเข้มงวดด้านการสะกดคำ</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>เข้มงวด</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>ปกติ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>ผ่อนปรน</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>ยกเลิก</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>ทบทวนสำนวน</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  หยุด</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  ฟัง</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>เริ่มแบบทดสอบ</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>ยังไม่มีคำศัพท์</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>พิมพ์คำใบ้ / คำแปล…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>พิมพ์สำนวน…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>ถูกต้อง: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ ทำเครื่องหมายว่าถูกต้อง (ฉันพิมพ์ผิด)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>ส่ง</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ ทำเครื่องหมายว่าถูกต้อง (ฉันคลิกผิด)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>ถูกต้อง: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>ดูผลลัพธ์</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>ถัดไป →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>คำถามหมายเลข %1</translation>
    </message>
</context>
</TS>
