<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>关于</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">用于记忆单词集的词汇训练器。</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>词汇和语法训练器。</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>开源许可</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>本应用程序在 GNU 宽通用公共许可证第 3 版下使用 Qt。</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Qt 声明</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Qt 声明</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Qt 源代码</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Qt 项目网站</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ 由 AI 生成——可能包含错误</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 举报</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>谢谢——你的举报已提交，我们会进行审核。</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 举报 AI 内容</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>这段生成的内容有什么问题？</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>色情或性暗示内容</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>脏话或冒犯性语言</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>仇恨或骚扰内容</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>暴力或危险内容</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>错误或误导性信息</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>其他问题</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>详细说明（可选）</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>正在发送…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>关闭</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>提交举报</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>拍照</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>即将推出</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1天%2小时后</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1小时%2分钟后</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1分钟后</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>选择图片</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>选择音频</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>导入单词集</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>单词语言</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>提示语言</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+326"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ AI 单词集生成器</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>由 Gemini 提供支持</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 主题</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>描述你想要的单词集——例如“法国家庭中常见的厨房用品”或“出差参加会议的常用短语”……</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>本月还剩 %1/%2 次生成 — 将于 %3 重置</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI 可能会出错。只会生成适合所有年龄段的内容——如发现任何不当内容，请使用 🚩 举报 进行标记。</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>单词语言</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>提示语言</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 单词数量</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>正在询问 Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>取消请求</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ 生成</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>新建单词集</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>编辑单词集</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>导入</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>单词集标题…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>自动获取图片</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>单词</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>已选择</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>单词 / 词条</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>未选择</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>输入单词...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>提示 / 含义</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>提示、定义...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>用法示例</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>使用该单词的例句...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>更换图片</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>添加图片</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>获取</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>相机</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>添加音频</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ 停止</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ 播放</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ 朗读</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ 停止</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● 录音</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ 添加单词</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>移除</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>标题为必填项</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>即将开始</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1天%2小时后</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1小时%2分钟后</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1分钟后</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>选择图片</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>选择音频</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>新建规则集</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>编辑规则集</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>导入</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>导入规则集</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ AI 规则集生成器</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>由 Gemini 提供支持</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>本月还剩 %1/%2 次生成 — 将于 %3 重置</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 需要解释的规则/主题</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>描述您想要的规则——例如“一般现在时与现在进行时”或“第三类条件句”…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 每种类型的题目数</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 填空</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 多项选择</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 下拉选择</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 拖放</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>正在询问 Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>取消请求</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI 可能会出错。只会生成适合所有年龄段的内容——如发现任何不当内容，请使用 🚩 举报 进行标记。</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ 生成</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>输入标题…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>理论讲解</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>测试期间隐藏，直到学习者出错为止 — 在预览中始终可读。</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>使用 ▲▼ 重新排序区块。拖动照片的 // 角以调整其大小。</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>解释此题集练习的规则…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>音频片段</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ 文本</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ 照片</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ 音频</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>问题</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>已选择</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>填空</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>多项选择</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>下拉选择</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>拖放</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>为学习者填写的每个空格使用 ___（三个下划线）。</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>例如：她每天做什么？</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>例如：她每天 ___ 上学。</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>答案</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>每个空格一个答案，用逗号分隔，按顺序排列。使用 \, 表示字面逗号。</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>例如：去</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>选项</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>用逗号分隔一个空格的选项；用双冒号（::）分隔各个空格。单个 : 可以安全地照常使用；使用 \, 表示字面逗号，\:: 表示字面 ::，使用 ___ 表示故意留空的选项。例如两个空格：去, 去, 正在去::每个, 一些, 大多数。</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>用逗号分隔的可拖动方块 — 包括正确答案，以及可能使学习者混淆的可选干扰项。使用 \, 表示字面逗号，使用 ___ 表示空白方块（用于应正确保持空白的空格）。设置好这些后，请在下方填写空格。</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>例如：去, 去, 正在去::每个, 一些, 大多数</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>例如：去, 去, 正在去, 已经去了</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>每个空格的正确答案</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>点按下方每个框中的正确选项。</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>为每个空格选择一个正确答案。</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>空格 %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>填写空格</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>将方块拖到下方的空格上，或点按方块然后点按空格以放置它。</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>用方块填充每个空格。</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>用逗号分隔的选项 — 点按下方的正确答案。使用 \, 表示字面逗号。</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>用逗号分隔的选项 — 点按下方所有正确答案。使用 \, 表示字面逗号。</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>例如：去, 去, 正在去, 已经去了</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>只有一个正确答案</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>正确答案</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>正确答案</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>选择正确答案。</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>至少选择一个正确答案。</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ 添加问题</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>移除</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>标题为必填项</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 解释语法</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>无法加载%1问题：%2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>仅生成了%2个请求问题中的%1个 — 请尝试更广泛的主题，或减少上面的数量。</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>解释语言</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>解释语言</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>主题语言</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>主题语言</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>无法生成此主题。AI 只会创建适合所有年龄段的内容——不支持色情、粗俗或冒犯性的主题。请尝试其他主题。</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>你本月的 AI 生成次数已用完。请下个月再试。</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>今天的举报次数过多——请明天再试。</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>AI 服务当前繁忙——请稍后重试。</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>请先输入主题。</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>主题过长（最多 %1 个字符）。</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>请至少将一种题型的数量设为大于零。</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>你的登录已过期——请重新登录。</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>无法连接到服务器。请检查你的网络连接后重试。</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>出了点问题，请重试。</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>未登录。</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>点击翻转</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>点击翻回</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>认识</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>跳过</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  不认识</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  认识</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>未选择</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>无法加载许可证文本。</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>登录以继续</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>正在打开浏览器…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>使用 Google 登录</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">此处已存在同名的库或单词集。</translation>
    </message>
    <message>
        <location line="+309"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>此处已存在同名的单词集。</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>此处已存在同名的规则集。</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+37"/>
        <source>Results</source>
        <translation>结果</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Well</source>
        <translation>做得</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>done</source>
        <translation>不错</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>共 %1 个</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>做得很棒！继续保持！</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>不错的尝试！继续练习吧。</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>不要放弃——熟能生巧！</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>本次学习</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>不认识</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>认识</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Practice Again</source>
        <translation>再次练习</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>要重置测试进度吗？</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>这将清除您在此规则集上的进度并开始新的会话。</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 个问题</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">已完成：%1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">进行中：%1 / %2</translation>
    </message>
    <message>
        <location line="+67"/>
        <source>← Reset</source>
        <translation>← 重置</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>规则讲解</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>此题集未添加讲解。</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>音频片段</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ 拼写严格程度</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>严格</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>正常</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>宽松</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>开始测试</translation>
    </message>
    <message>
        <location line="-198"/>
        <source>Test is completed</source>
        <translation>测试已完成</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>下一题：#%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>正确：%1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>规则</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 规则讲解</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>音频片段</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 查看规则</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>转动转盘以选择每个空格的单词。</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>空格 %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>将方块拖到空格上，或点按方块然后点按空格以放置它。</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>选择正确答案。</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>选择所有适用项。</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>正确：</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>提交</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>正确：%1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>查看结果</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>下一步 →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>问题编号 %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>覆盖单词集？</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>合并库？</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>此处已存在名为“%1”的单词集。是否用移动过来的单词集覆盖它？</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>此处已存在名为“%1”的库。是否将其内容合并到该库中？</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>%2 中已存在名为“%1”的单词集。是否用合并后的版本覆盖它？</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>目标库</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>导出为 .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>新建库</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Library name:</source>
        <translation>库名称：</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>例如：旅行、工作、学校……</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">此处已存在同名的库或单词集。</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+74"/>
        <source>A library with this name already exists here.</source>
        <translation>此处已存在同名的库。</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Create</source>
        <translation>创建</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Rename Library</source>
        <translation>重命名库</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>新名称：</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>重命名</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>您的单词集</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>库</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>移出</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>拖放以移入</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>个单词</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>题</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>删除库</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>编辑</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>删除</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>分享 .ppset 文件</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>导出 .ppset（保存到磁盘）</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>这里还没有任何内容。
点击“+ 创建”以添加单词集或库。</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>单词集</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>规则集</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ 创建</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>界面语言</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>选择测试类型</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>单词卡</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>翻转以查看——如果认识就向右滑动</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>写出单词</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>查看提示——输入表达</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>写出提示</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>查看单词——输入其翻译</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>选出单词</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>查看提示——从4个选项中选择</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>选出提示</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>查看单词——从4个选项中选择</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>渐进式学习</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>先选择题学习，再通过书写掌握所有单词</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>反向渐进式学习</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>先选择题学习，再通过书写掌握所有提示</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>✓ Done</source>
        <translation>✓ 完成</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>← Reset</source>
        <translation>← 重置</translation>
    </message>
    <message>
        <location line="+96"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ 拼写严格程度</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>严格</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>正常</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>宽松</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>复习表达</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  停止</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  收听</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>开始测试</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>暂无单词</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>输入提示 / 翻译…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>输入表达…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>正确：</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ 标记为正确（我打错了）</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>提交</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ 标记为正确（我点错了）</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>正确：%1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>查看结果</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>下一个 →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>问题编号 %1</translation>
    </message>
</context>
</TS>
