<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ar">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>حول</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">مدرّب مفردات لحفظ مجموعات الكلمات.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>مدرّب للمفردات والقواعد.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>تراخيص المصادر المفتوحة</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>يستخدم هذا التطبيق Qt بموجب رخصة جنو العمومية الصغرى الإصدار 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>إشعار Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>إشعار Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>الشيفرة المصدرية لـ Qt</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>الموقع الإلكتروني لمشروع Qt</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ تم إنشاؤه بالذكاء الاصطناعي — قد يحتوي على أخطاء</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 إبلاغ</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>شكرًا لك — تم إرسال بلاغك وستتم مراجعته.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 الإبلاغ عن محتوى الذكاء الاصطناعي</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>ما المشكلة في هذا المحتوى المُنشأ؟</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>محتوى جنسي أو إيحائي</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>ألفاظ نابية أو لغة مسيئة</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>محتوى يحض على الكراهية أو التحرش</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>محتوى عنيف أو خطير</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>معلومات خاطئة أو مضللة</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>شيء آخر</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>التفاصيل (اختياري)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>جارٍ الإرسال…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>إغلاق</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>إلغاء</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>إرسال البلاغ</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>التقاط صورة</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>إلغاء</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>قريبًا</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>خلال %1 يوم و%2 ساعة</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>خلال %1 ساعة و%2 دقيقة</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>خلال %1 دقيقة</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>اختيار صورة</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>اختيار صوت</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>استيراد مجموعة كلمات</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>لغة الكلمة</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>لغة التلميح</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+326"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>إلغاء</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ مولّد مجموعات الكلمات بالذكاء الاصطناعي</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>مدعوم بواسطة Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 الموضوع</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>صف المجموعة التي تريدها — مثلًا «أدوات مطبخ توجد في منزل فرنسي» أو «عبارات لرحلة عمل لحضور مؤتمر»…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>تبقّى %1 من %2 عملية توليد هذا الشهر — تُعاد الإعادة في %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>قد يخطئ الذكاء الاصطناعي. يتم إنشاء محتوى مناسب لجميع الأعمار فقط — استخدم 🚩 إبلاغ للإشارة إلى أي محتوى غير لائق.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>لغة الكلمة</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>لغة التلميح</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 عدد الكلمات</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>جارٍ سؤال Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>إلغاء الطلب</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ توليد</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ ذكاء اصطناعي</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>مجموعة كلمات جديدة</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>تعديل مجموعة الكلمات</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>استيراد</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>عنوان المجموعة…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>جلب الصور تلقائيًا</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>كلمة</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>محدَّد</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>كلمة / مصطلح</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>غير محدَّد</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>أدخل الكلمة...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>تلميح / معنى</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>تلميح، تعريف...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>مثال على الاستخدام</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>جملة مثال تستخدم الكلمة...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>تغيير الصورة</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>إضافة صورة</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>جلب</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>الكاميرا</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>إضافة صوت</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ إيقاف</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ تشغيل</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ نطق</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ إيقاف</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● تسجيل</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ إضافة كلمة</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>إزالة</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>حفظ</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>العنوان مطلوب</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>قريبًا</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>خلال %1 يوم و%2 ساعة</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>خلال %1 ساعة و%2 دقيقة</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>خلال %1 دقيقة</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>اختر صورة</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>اختر صوتًا</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ ذكاء اصطناعي</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>مجموعة قواعد جديدة</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>تعديل مجموعة القواعد</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>استيراد</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>استيراد مجموعة قواعد</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ مولّد مجموعات القواعد بالذكاء الاصطناعي</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>مدعوم بواسطة Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>%1 من %2 عملية توليد متبقية هذا الشهر — تُعاد %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 القاعدة أو الموضوع المطلوب شرحه</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>صف القاعدة التي تريدها — مثال: &quot;المضارع البسيط مقابل المضارع المستمر&quot; أو &quot;جمل الشرط الثالث&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 عدد الأسئلة لكل نوع</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 املأ الفراغ</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 اختيار من متعدد</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 قائمة منسدلة</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 اسحب وأفلت</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>جارٍ سؤال Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>إلغاء الطلب</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>إلغاء</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>قد يخطئ الذكاء الاصطناعي. يتم إنشاء محتوى مناسب لجميع الأعمار فقط — استخدم 🚩 إبلاغ للإشارة إلى أي محتوى غير لائق.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ توليد</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>أدخل العنوان…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>شرح القاعدة</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>مخفي أثناء الاختبار حتى يخطئ المتعلم — يمكن قراءته دائمًا في المعاينة.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>استخدم ▲▼ لإعادة ترتيب الكتلة. اسحب زاوية // الخاصة بالصورة لتغيير حجمها.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>اشرح القاعدة التي تتدرب عليها هذه المجموعة…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>مقطع صوتي</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ نص</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ صورة</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ صوت</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>السؤال</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>محدَّد</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>املأ الفراغ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>اختيار من متعدد</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>قائمة منسدلة</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>اسحب وأفلت</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>استخدم ___ (ثلاث شرطات سفلية) لكل فراغ يملؤه المتعلم.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>مثال: ماذا تفعل كل يوم؟</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>مثال: هي ___ إلى المدرسة كل يوم.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>الإجابات</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>إجابة واحدة لكل فراغ، مفصولة بفواصل، بالترتيب. استخدم \, للفاصلة الحرفية.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>مثال: تذهب</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>الخيارات</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>افصل الخيارات لفراغ واحد بفواصل؛ افصل الفراغات بنقطتين مزدوجتين (::). النقطتان المفردتان : آمنتان كما هما؛ استخدم \, لفاصلة حرفية، \:: لعلامة :: حرفية، و___ لخيار فارغ عمدًا. مثال لفراغين: تذهب، يذهب، ذاهب::كل، بعض، معظم.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>قطع قابلة للسحب مفصولة بفواصل — أدرج الإجابات الصحيحة، بالإضافة إلى بدائل خادعة اختيارية يمكن أن يُخدع بها المتعلم. استخدم \, لفاصلة حرفية، و___ لقطعة فارغة (لفراغ يجب أن يبقى فارغًا بشكل صحيح). املأ الفراغات أدناه بمجرد تحديد هذه.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>مثال: تذهب، يذهب، ذاهب::كل، بعض، معظم</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>مثال: تذهب، يذهب، ذاهب، ذهب</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>الإجابة الصحيحة لكل فراغ</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>اضغط على الخيار الصحيح في كل مربع أدناه.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>اختر إجابة صحيحة لكل فراغ.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>الفراغ %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>املأ الفراغات</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>اسحب قطعة إلى فراغ أدناه، أو اضغط على قطعة ثم اضغط على فراغ لوضعها.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>املأ كل فراغ بقطعة.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>خيارات مفصولة بفواصل — اضغط على الإجابة الصحيحة أدناه. استخدم \, لفاصلة حرفية.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>خيارات مفصولة بفواصل — اضغط على جميع الإجابات الصحيحة أدناه. استخدم \, لفاصلة حرفية.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>مثال: تذهب، يذهب، ذاهب، ذهب</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>إجابة صحيحة واحدة فقط</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>الإجابة الصحيحة</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>الإجابة (الإجابات) الصحيحة</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>اختر الإجابة الصحيحة.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>اختر إجابة صحيحة واحدة على الأقل.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ أضف سؤالًا</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>إزالة</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>حفظ</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>العنوان مطلوب</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 اشرح القواعد</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>تعذّر تحميل سؤال %1: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>تم إنشاء %1 فقط من أصل %2 سؤالاً مطلوبًا — جرّب موضوعًا أوسع، أو قلّل الأعداد أعلاه.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>لغة الشرح</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>لغة الشرح</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>لغة الموضوع</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>لغة الموضوع</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>لا يمكن إنشاء هذا الموضوع. ينشئ الذكاء الاصطناعي محتوى مناسبًا لجميع الأعمار فقط — المواضيع الجنسية أو البذيئة أو المسيئة غير مدعومة. يُرجى تجربة موضوع آخر.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>لقد استخدمت جميع عمليات الإنشاء بالذكاء الاصطناعي لهذا الشهر. حاول مرة أخرى الشهر القادم.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>عدد كبير جدًا من البلاغات اليوم — يُرجى المحاولة غدًا.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>خدمة الذكاء الاصطناعي مشغولة حاليًا — يُرجى المحاولة بعد قليل.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>أدخل موضوعًا أولًا.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>الموضوع طويل جدًا (الحد الأقصى %1 حرفًا).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>اجعل نوع سؤال واحد على الأقل أكبر من صفر.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>انتهت صلاحية جلستك — يُرجى تسجيل الدخول مرة أخرى.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>تعذّر الوصول إلى الخادم. تحقّق من اتصالك بالإنترنت وحاول مرة أخرى.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>حدث خطأ ما. يُرجى المحاولة مرة أخرى.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>لم يتم تسجيل الدخول.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>اضغط للقلب</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>اضغط للقلب مرة أخرى</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>أعرف</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>تخطٍّ</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  لا أعرف</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  أعرف</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>غير محدَّد</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>تعذّر تحميل نص الترخيص.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>سجّل الدخول للمتابعة</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>جارٍ فتح المتصفح…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>تسجيل الدخول عبر Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">توجد مكتبة أو مجموعة بهذا الاسم هنا بالفعل.</translation>
    </message>
    <message>
        <location line="+309"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>توجد مجموعة كلمات بهذا الاسم هنا بالفعل.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>توجد مجموعة قواعد بهذا الاسم هنا بالفعل.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+37"/>
        <source>Results</source>
        <translation>النتائج</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Well</source>
        <translation>أحسنت</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>done</source>
        <translation>صنعًا</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>من أصل %1</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>عمل رائع! واصل!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>محاولة جيدة! واصل التدرّب.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>لا تستسلم – التدريب يؤدي إلى الإتقان!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>هذه الجلسة</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>لا أعرف</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>أعرف</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Practice Again</source>
        <translation>تدرّب مجددًا</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>إعادة تعيين تقدم الاختبار؟</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>سيؤدي هذا إلى مسح تقدمك في مجموعة القواعد هذه وبدء جلسة جديدة.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 أسئلة</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">اكتمل: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">قيد التقدم: %1 / %2</translation>
    </message>
    <message>
        <location line="+67"/>
        <source>← Reset</source>
        <translation>← إعادة تعيين</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>شرح القاعدة</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>لم تتم إضافة شرح لهذه المجموعة.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>مقطع صوتي</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ صرامة التدقيق الإملائي</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>صارم</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>عادي</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>متساهل</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>ابدأ الاختبار</translation>
    </message>
    <message>
        <location line="-198"/>
        <source>Test is completed</source>
        <translation>اكتمل الاختبار</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>السؤال التالي: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>صحيح: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>القاعدة</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 شرح القاعدة</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>مقطع صوتي</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>إلغاء</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 عرض القاعدة</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>أدر العجلة لاختيار كلمة كل فراغ.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>الفراغ %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>فارغ</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>اسحب قطعة إلى فراغ، أو اضغط على قطعة ثم اضغط على فراغ لوضعها.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>اختر الإجابة الصحيحة.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>اختر كل ما ينطبق.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>صحيح: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>إرسال</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>صحيح: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>عرض النتائج</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>التالي →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>رقم السؤال %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>استبدال مجموعة الكلمات؟</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>دمج المكتبات؟</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>توجد بالفعل مجموعة كلمات باسم “%1” هنا. هل تريد استبدالها بالمجموعة المنقولة؟</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>توجد بالفعل مكتبة باسم “%1” هنا. هل تريد دمج محتوياتها فيها؟</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>توجد بالفعل مجموعة كلمات باسم “%1” في %2. هل تريد استبدالها بالنسخة المدمجة؟</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>المكتبة الوجهة</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>تصدير كملف ‎.ppset‎</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>مكتبة جديدة</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Library name:</source>
        <translation>اسم المكتبة:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>مثلًا: السفر، العمل، المدرسة…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">توجد مكتبة أو مجموعة بهذا الاسم هنا بالفعل.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+74"/>
        <source>A library with this name already exists here.</source>
        <translation>توجد مكتبة بهذا الاسم هنا بالفعل.</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Create</source>
        <translation>إنشاء</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Rename Library</source>
        <translation>إعادة تسمية المكتبة</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>الاسم الجديد:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>إعادة تسمية</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>مجموعات كلماتك</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>المكتبة</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>نقل خارجًا من</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>أفلت للنقل إلى الداخل</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>كلمة</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>أسئلة</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>حذف المكتبة</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>تعديل</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>حذف</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>مشاركة ملف ‎.ppset‎</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>تصدير ‎.ppset‎ (الحفظ على القرص)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>لا يوجد شيء هنا بعد.
اضغط + إنشاء لإضافة مجموعة كلمات أو مكتبة.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>مجموعة كلمات</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>مجموعة القواعد</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ إنشاء</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>لغة الواجهة</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Cancel</source>
        <translation>إلغاء</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>اختر نوع الاختبار</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>بطاقات تعليمية</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>اقلب للكشف — اسحب لليمين إذا كنت تعرفها</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>اكتب الكلمة</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>انظر التلميح — اكتب العبارة</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>اكتب التلميح</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>انظر الكلمة — اكتب ترجمتها</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>اختر الكلمة</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>انظر التلميح — اختر من بين 4 خيارات</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>اختر التلميح</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>انظر الكلمة — اختر من بين 4 خيارات</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>التعلّم التدريجي</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>اختيار من متعدد للتعلّم، ثم الكتابة لإتقان جميع الكلمات</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>التعلّم التدريجي المعكوس</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>اختيار من متعدد للتعلّم، ثم الكتابة لإتقان جميع التلميحات</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>✓ Done</source>
        <translation>✓ تم</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>← Reset</source>
        <translation>← إعادة تعيين</translation>
    </message>
    <message>
        <location line="+96"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ صرامة التدقيق الإملائي</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>صارم</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>عادي</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>متساهل</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>إلغاء</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>مراجعة العبارات</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  إيقاف</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  استماع</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>بدء الاختبار</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>لا توجد كلمات بعد</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>اكتب التلميح / الترجمة…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>اكتب العبارة…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>صحيح: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ وضع علامة صحيح (أخطأت في الكتابة)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>إرسال</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ وضع علامة صحيح (نقرت بالخطأ)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>صحيح: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>عرض النتائج</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>التالي ←</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>رقم السؤال %1</translation>
    </message>
</context>
</TS>
