<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="hr">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>O aplikaciji</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Trener vokabulara za pamćenje skupova riječi.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Trener za vokabular i gramatiku.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Licencije otvorenog koda</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Ova aplikacija koristi Qt pod licencom GNU Lesser General Public License verzije 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Qt obavijest</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Qt obavijest</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Izvorni kod Qt-a</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Web-stranica Qt projekta</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Generirao UI — može sadržavati pogreške</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Prijavi</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Hvala — vaša je prijava poslana i bit će pregledana.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Prijavi sadržaj UI-ja</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Što nije u redu s ovim generiranim sadržajem?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Seksualni ili sugestivni sadržaj</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Psovke ili uvredljiv jezik</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Sadržaj koji širi mržnju ili uznemirava</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Nasilni ili opasni sadržaj</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Netočne ili obmanjujuće informacije</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Nešto drugo</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Pojedinosti (neobavezno)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Slanje…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Zatvori</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Odustani</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Pošalji prijavu</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Fotografiraj</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Odustani</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>uskoro</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>za %1d %2h</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>za %1h %2min</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>za %1min</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Odaberi sliku</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Odaberi zvuk</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Uvezi skup riječi</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Jezik riječi</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Jezik natuknice</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+326"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Odustani</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ Generator skupova riječi s UI</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Pokreće Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Tema</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Opišite skup koji želite — npr. „kuhinjski predmeti koje biste našli u francuskom domaćinstvu” ili „fraze za poslovno putovanje na konferenciju”…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Preostalo %1 od %2 generiranja ovaj mjesec — resetiranje %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>UI može pogriješiti. Stvara se samo sadržaj prikladan za sve dobi — upotrijebite 🚩 Prijavi da biste označili bilo što neprikladno.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Jezik riječi</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Jezik natuknice</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Broj riječi</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Postavljanje upita Gemini-ju…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Odustani od zahtjeva</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Generiraj</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ UI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Novi skup riječi</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Uredi skup riječi</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Uvezi</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Naslov skupa…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Automatsko preuzimanje slika</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Riječ</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>odabrano</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Riječ / Pojam</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Nije odabrano</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Unesite riječ...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Natuknica / značenje</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Natuknica, definicija...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Primjer upotrebe</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Primjer rečenice s riječju...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Promijeni sliku</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Dodaj sliku</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Preuzmi</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Kamera</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Dodaj zvuk</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Zaustavi</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Reproduciraj</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ TTS</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Zaustavi</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Snim.</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Dodaj riječ</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Ukloni</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Spremi</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Naslov je obavezan</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>uskoro</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>za %1d %2h</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>za %1h %2m</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>za %1m</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Odaberi sliku</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Odaberi zvuk</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ UI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Novi skup pravila</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Uredi skup pravila</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Uvezi</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Uvezi skup pravila</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ UI generator skupova pravila</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Pokreće Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Preostalo je %1 od %2 generiranja ovaj mjesec — resetira se %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Pravilo/tema za objašnjenje</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Opišite pravilo koje želite — npr. &quot;present simple naspram present continuous&quot; ili &quot;pogodbene rečenice trećeg tipa&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Pitanja po vrsti</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Popuni prazninu</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Višestruki izbor</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Padajući izbornik</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Povuci i ispusti</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Postavljanje upita Gemini-ju…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Otkaži zahtjev</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Otkaži</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>UI može pogriješiti. Stvara se samo sadržaj prikladan za sve dobi — upotrijebite 🚩 Prijavi da biste označili bilo što neprikladno.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Generiraj</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Unesite naslov…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Objašnjenje teorije</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Skriveno tijekom testa dok učenik ne pogriješi — uvijek čitljivo u pregledu.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Koristite ▲▼ za promjenu redoslijeda bloka. Povucite // kut fotografije za promjenu veličine.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Objasnite pravilo koje ovaj skup vježba…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Audio isječak</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Tekst</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Fotografija</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Audio</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Pitanje</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>odabrano</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Popuni prazninu</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Višestruki izbor</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Padajući izbornik</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Povuci i ispusti</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Koristite ___ (tri donje crte) za svaku prazninu koju učenik popunjava.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>npr. Što ona radi svaki dan?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>npr. Ona ide ___ u školu svaki dan.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Odgovori</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Jedan odgovor po praznini, odvojeni zarezima, redoslijedom. Koristite \, za doslovni zarez.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>npr. ide</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Opcije</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Odvojite opcije za jednu prazninu zarezima; odvojite praznine dvostrukom dvotočkom (::). Jedan : siguran je takav kakav jest; koristite \, za doslovni zarez, \:: za doslovni ::, i ___ za namjerno praznu opciju. Npr. za dvije praznine: ide, ići, idući::svaki, neki, većina.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Pločice za povlačenje odvojene zarezima — uključite točne odgovore, plus neobavezne mamce kojima se učenik može zavarati. Koristite \, za doslovni zarez, i ___ za praznu pločicu (za prazninu koja bi ispravno trebala ostati prazna). Popunite praznine ispod nakon što su ove postavljene.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>npr. ide, ići, idući::svaki, neki, većina</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>npr. ide, ići, idući, otišao</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Točan odgovor za svaku prazninu</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Dodirnite točan izbor u svakom okviru ispod.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Odaberite točan odgovor za svaku prazninu.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Praznina %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Popunite praznine</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Povucite pločicu na prazninu ispod, ili dodirnite pločicu, a zatim prazninu da je postavite.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Popunite svaku prazninu pločicom.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Opcije odvojene zarezima — dodirnite točan odgovor ispod. Koristite \, za doslovni zarez.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Opcije odvojene zarezima — dodirnite sve točne odgovore ispod. Koristite \, za doslovni zarez.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>npr. ide, ići, idući, otišao</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Samo jedan točan odgovor</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Točan odgovor</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Točan(i) odgovor(i)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Odaberite točan odgovor.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Odaberite barem jedan točan odgovor.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Dodaj pitanje</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Ukloni</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Spremi</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Naslov je obavezan</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Objasni gramatiku</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Nije moguće učitati pitanje %1: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Generirano je samo %1 od %2 traženih pitanja — pokušajte širu temu ili smanjite brojeve iznad.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Jezik objašnjenja</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Jezik objašnjenja</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Jezik teme</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Jezik teme</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Ovu temu nije moguće generirati. UI stvara samo sadržaj prikladan za sve dobi — seksualne, vulgarne ili uvredljive teme nisu podržane. Pokušajte s drugom temom.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Iskoristili ste sva generiranja s UI-jem za ovaj mjesec. Pokušajte ponovno sljedeći mjesec.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Previše prijava danas — pokušajte ponovno sutra.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Usluga UI-ja trenutno je zauzeta — pokušajte ponovno za trenutak.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Najprije unesite temu.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Tema je predugačka (najviše %1 znakova).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Postavite barem jednu vrstu pitanja iznad nule.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Vaša je sesija istekla — prijavite se ponovno.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Nije moguće povezati se s poslužiteljem. Provjerite internetsku vezu i pokušajte ponovno.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Nešto nije u redu. Pokušajte ponovno.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Niste prijavljeni.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Dodirnite za okretanje</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Dodirnite za okretanje natrag</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>ZNAM</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>PRESKOČI</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Ne znam</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Znam</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Nije odabrano</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Tekst licencije nije moguće učitati.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Prijavite se za nastavak</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Otvaranje preglednika…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Prijavi se putem Googlea</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Knjižnica ili skup s ovim nazivom već postoji ovdje.</translation>
    </message>
    <message>
        <location line="+309"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Skup riječi s ovim nazivom već postoji ovdje.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Skup pravila s ovim nazivom već postoji ovdje.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+37"/>
        <source>Results</source>
        <translation>Rezultati</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Well</source>
        <translation>Odlično</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>done</source>
        <translation>obavljeno</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>od %1</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Izvrstan rad! Nastavi tako!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Dobar trud! Nastavi vježbati.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Ne odustaj – vježba čini majstora!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Ova sesija</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Ne znam</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Znam</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Practice Again</source>
        <translation>Vježbaj ponovno</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Resetirati napredak testa?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Ovo će izbrisati vaš napredak na ovom skupu pravila i pokrenuti novu sesiju.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 pitanja</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Dovršeno: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">U tijeku: %1 / %2</translation>
    </message>
    <message>
        <location line="+67"/>
        <source>← Reset</source>
        <translation>← Resetiraj</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Objašnjenje pravila</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Za ovaj skup nije dodano objašnjenje.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Audio isječak</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Strogost pravopisa</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Strogo</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normalno</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Blago</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Pokreni test</translation>
    </message>
    <message>
        <location line="-198"/>
        <source>Test is completed</source>
        <translation>Test je dovršen</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Sljedeće pitanje: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Točno: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Pravilo</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Objašnjenje pravila</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Audio isječak</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Otkaži</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Prikaži pravilo</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Okrenite kotač da odaberete riječ za svaku prazninu.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Praznina %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Povucite pločicu na prazninu, ili dodirnite pločicu, a zatim prazninu da je postavite.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Odaberite točan odgovor.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Odaberite sve što se primjenjuje.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Točno: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Pošalji</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Točno: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Prikaži rezultate</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Sljedeće →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Pitanje broj %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Prepisati skup riječi?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Spojiti knjižnice?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Skup riječi pod nazivom „%1” već postoji ovdje. Prepisati ga premještenim skupom?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Knjižnica pod nazivom „%1” već postoji ovdje. Spojiti njezin sadržaj s njom?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Skup riječi pod nazivom „%1” već postoji u %2. Prepisati ga spojenom verzijom?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>ciljna knjižnica</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Izvezi kao .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Nova knjižnica</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Library name:</source>
        <translation>Naziv knjižnice:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>npr. Putovanja, Posao, Škola…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Knjižnica ili skup s ovim nazivom već postoji ovdje.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+74"/>
        <source>A library with this name already exists here.</source>
        <translation>Knjižnica s ovim nazivom već postoji ovdje.</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Create</source>
        <translation>Izradi</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Rename Library</source>
        <translation>Preimenuj knjižnicu</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Novi naziv:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Preimenuj</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Vaši skupovi riječi</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Knjižnica</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Premjesti izvan</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Ispusti za premještanje unutra</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>riječi</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>pitanja</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Izbriši knjižnicu</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Uredi</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Izbriši</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Podijeli .ppset datoteku</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Izvezi .ppset (spremi na disk)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Ovdje još ničega nema.
Dodirnite + Izradi za dodavanje skupa riječi ili knjižnice.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Skup riječi</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Skup pravila</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Izradi</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Jezik sučelja</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Cancel</source>
        <translation>Odustani</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Odaberi vrstu testa</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Kartice za učenje</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Okreni za otkrivanje — prijeđi udesno ako znaš</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Napiši riječ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Pogledaj natuknicu — upiši izraz</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Napiši natuknicu</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Pogledaj riječ — upiši njezin prijevod</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Odaberi riječ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Pogledaj natuknicu — odaberi između 4 opcije</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Odaberi natuknicu</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Pogledaj riječ — odaberi između 4 opcije</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Progresivno učenje</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Višestruki izbor za učenje, zatim pisanje za svladavanje svih riječi</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Obrnuto progresivno učenje</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Višestruki izbor za učenje, zatim pisanje za svladavanje svih natuknica</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>✓ Done</source>
        <translation>✓ Gotovo</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>← Reset</source>
        <translation>← Resetiraj</translation>
    </message>
    <message>
        <location line="+96"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Strogost pravopisa</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Strogo</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normalno</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Blago</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Odustani</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Ponovi izraze</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Zaustavi</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Slušaj</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Pokreni test</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Još nema riječi</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Upiši natuknicu / prijevod…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Upiši izraz…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Točno: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Označi kao točno (pogrešno sam utipkao)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Pošalji</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Označi kao točno (pogrešno sam kliknuo)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Točno: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Pogledaj rezultate</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Sljedeće →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Pitanje broj %1</translation>
    </message>
</context>
</TS>
