<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="pl">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>O aplikacji</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Trener słownictwa do zapamiętywania zestawów słów.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Trener słownictwa i gramatyki.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Licencje open source</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Ta aplikacja korzysta z Qt na licencji GNU Lesser General Public License w wersji 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Informacja o Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Informacja o Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Kod źródłowy Qt</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Strona projektu Qt</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Wygenerowane przez AI — może zawierać błędy</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Zgłoś</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Dziękujemy — Twoje zgłoszenie zostało wysłane i zostanie sprawdzone.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Zgłoś treść AI</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Co jest nie tak z tą wygenerowaną treścią?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Treści seksualne lub dwuznaczne</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Wulgaryzmy lub obraźliwy język</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Treści szerzące nienawiść lub nękanie</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Treści brutalne lub niebezpieczne</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Błędne lub wprowadzające w błąd informacje</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Coś innego</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Szczegóły (opcjonalnie)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Wysyłanie…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Zamknij</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Anuluj</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Wyślij zgłoszenie</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Zrób zdjęcie</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Anuluj</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>wkrótce</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>za %1d %2h</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>za %1h %2min</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>za %1min</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Wybierz obraz</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Wybierz audio</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Importuj zestaw słów</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Język słowa</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Język podpowiedzi</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+339"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Anuluj</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ Generator zestawów słów AI</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Wykorzystuje Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Temat</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Opisz zestaw, który chcesz — np. „przedmioty kuchenne, które można znaleźć we francuskim domu” lub „zwroty na podróż służbową na konferencję”…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Pozostało %1 z %2 generacji w tym miesiącu — reset %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI może się mylić. Generowane są tylko treści odpowiednie dla każdego wieku — użyj 🚩 Zgłoś, aby oznaczyć coś nieodpowiedniego.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Język słowa</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Język podpowiedzi</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Liczba słów</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Pytanie Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Anuluj żądanie</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Generuj</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Nowy zestaw słów</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Edytuj zestaw słów</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importuj</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Tytuł zestawu…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Automatycznie pobieraj obrazy</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Słowo</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>wybrano</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Słowo / Termin</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Nie wybrano</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Wpisz słowo...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Podpowiedź / znaczenie</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Podpowiedź, definicja...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Przykład użycia</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Przykładowe zdanie ze słowem...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Zmień obraz</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Dodaj obraz</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Pobierz</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Aparat</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Dodaj audio</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Zatrzymaj</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Odtwórz</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ TTS</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Zatrzymaj</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Nagr.</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Dodaj słowo</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Usuń</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Zapisz</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Tytuł jest wymagany</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>wkrótce</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>za %1d %2godz.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>za %1godz. %2min</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>za %1min</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Wybierz obraz</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Wybierz dźwięk</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ SI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Nowy zestaw reguł</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Edytuj zestaw reguł</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importuj</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Importuj zestaw reguł</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ Generator zestawów reguł SI</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Wspierane przez Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Pozostało %1 z %2 generowań w tym miesiącu — reset %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Reguła/temat do wyjaśnienia</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Opisz regułę, którą chcesz — np. &quot;czas present simple a present continuous&quot; lub &quot;zdania warunkowe trzeciego typu&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Pytania na typ</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Uzupełnij lukę</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Wielokrotny wybór</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Wybór rozwijany</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Przeciągnij i upuść</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Zapytanie do Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Anuluj żądanie</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Anuluj</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI może się mylić. Generowane są tylko treści odpowiednie dla każdego wieku — użyj 🚩 Zgłoś, aby oznaczyć coś nieodpowiedniego.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Generuj</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Wprowadź tytuł…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Wyjaśnienie teorii</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Ukryte podczas testu, dopóki uczeń nie popełni błędu — zawsze widoczne w podglądzie.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Użyj ▲▼, aby zmienić kolejność bloku. Przeciągnij róg // zdjęcia, aby zmienić jego rozmiar.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Wyjaśnij regułę, którą ćwiczy ten zestaw…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Klip audio</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Tekst</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Zdjęcie</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Dźwięk</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Pytanie</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>wybrano</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Uzupełnij lukę</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Wielokrotny wybór</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Wybór rozwijany</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Przeciągnij i upuść</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Użyj ___ (trzy podkreślenia) dla każdej luki, którą wypełnia uczeń.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>np. Co ona robi codziennie?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>np. Ona ___ codziennie do szkoły.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Odpowiedzi</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Jedna odpowiedź na lukę, oddzielona przecinkami, w kolejności. Użyj \, dla dosłownego przecinka.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>np. idzie</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Opcje</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Oddziel opcje dla jednej luki przecinkami; oddziel luki podwójnym dwukropkiem (::). Pojedynczy : jest bezpieczny w takiej postaci; użyj \, dla dosłownego przecinka, \:: dla dosłownego ::, i ___ dla celowo pustej opcji. Np. dla dwóch luk: idzie, iść, idąc::każdy, niektórzy, większość.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Przeciągane kafelki oddzielone przecinkami — dodaj poprawne odpowiedzi oraz opcjonalne fałszywe tropy, którymi uczeń może zostać zmylony. Użyj \, dla dosłownego przecinka, i ___ dla pustego kafelka (dla luki, która powinna prawidłowo pozostać pusta). Uzupełnij poniższe luki, gdy te zostaną ustawione.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>np. idzie, iść, idąc::każdy, niektórzy, większość</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>np. idzie, iść, idąc, poszedł</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Poprawna odpowiedź dla każdej luki</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Dotknij poprawnej opcji w każdym polu poniżej.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Wybierz poprawną odpowiedź dla każdej luki.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Luka %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Uzupełnij luki</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Przeciągnij kafelek na lukę poniżej lub dotknij kafelka, a następnie luki, aby go umieścić.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Uzupełnij każdą lukę kafelkiem.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Opcje oddzielone przecinkami — dotknij poprawnej odpowiedzi poniżej. Użyj \, dla dosłownego przecinka.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Opcje oddzielone przecinkami — dotknij wszystkich poprawnych odpowiedzi poniżej. Użyj \, dla dosłownego przecinka.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>np. idzie, iść, idąc, poszedł</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Tylko jedna poprawna odpowiedź</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Poprawna odpowiedź</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Poprawna odpowiedź (odpowiedzi)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Wybierz poprawną odpowiedź.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Wybierz co najmniej jedną poprawną odpowiedź.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Dodaj pytanie</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Usuń</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Zapisz</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Tytuł jest wymagany</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Wyjaśnij gramatykę</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Nie udało się wczytać pytania %1: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Wygenerowano tylko %1 z %2 żądanych pytań — spróbuj szerszego tematu lub zmniejsz liczby powyżej.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Język wyjaśnienia</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Język wyjaśnienia</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Język tematu</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Język tematu</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Na ten temat nie można wygenerować treści. AI tworzy tylko treści odpowiednie dla każdego wieku — tematy seksualne, wulgarne lub obraźliwe nie są obsługiwane. Spróbuj innego tematu.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Wykorzystano wszystkie generowania AI w tym miesiącu. Spróbuj ponownie w przyszłym miesiącu.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Zbyt wiele zgłoszeń dzisiaj — spróbuj ponownie jutro.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Usługa AI jest teraz zajęta — spróbuj ponownie za chwilę.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Najpierw wpisz temat.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Temat jest za długi (maks. %1 znaków).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Ustaw co najmniej jeden typ pytań powyżej zera.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Twoja sesja wygasła — zaloguj się ponownie.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Nie można połączyć się z serwerem. Sprawdź połączenie z internetem i spróbuj ponownie.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Coś poszło nie tak. Spróbuj ponownie.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Nie zalogowano.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Dotknij, aby obrócić</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Dotknij, aby obrócić z powrotem</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>ZNAM</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>POMIŃ</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Nie znam</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Znam</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Nie wybrano</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Nie udało się wczytać tekstu licencji.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Zaloguj się, aby kontynuować</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Otwieranie przeglądarki…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Zaloguj się przez Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Biblioteka lub zestaw o tej nazwie już tu istnieje.</translation>
    </message>
    <message>
        <location line="+317"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Zestaw słów o tej nazwie już tu istnieje.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Zestaw reguł o tej nazwie już tu istnieje.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+38"/>
        <source>Results</source>
        <translation>Wyniki</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>Well</source>
        <translation>Dobra</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>done</source>
        <translation>robota</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>z %1</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Świetna robota! Tak trzymaj!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Dobry wysiłek! Ćwicz dalej.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Nie poddawaj się – praktyka czyni mistrza!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Ta sesja</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Nie znam</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Znam</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Practice again</source>
        <translation>Ćwicz ponownie</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Find another set</source>
        <translation>Znajdź inny zestaw</translation>
    </message>
    <message>
        <source>Practice Again</source>
        <translation type="vanished">Ćwicz ponownie</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Zresetować postęp testu?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>To wyczyści twój postęp w tym zestawie reguł i rozpocznie nową sesję.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 pytań</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Ukończono: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">W trakcie: %1 / %2</translation>
    </message>
    <message>
        <source>← Reset</source>
        <translation type="vanished">← Resetuj</translation>
    </message>
    <message>
        <location line="+185"/>
        <source>Reset to practise again</source>
        <translation>Zresetuj, aby ćwiczyć ponownie</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Reset</source>
        <translation>Resetuj</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Wyjaśnienie reguły</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Do tego zestawu nie dodano żadnego wyjaśnienia.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Klip audio</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Rygor ortograficzny</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Rygorystyczny</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normalny</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Łagodny</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Rozpocznij test</translation>
    </message>
    <message>
        <location line="-316"/>
        <source>Test is completed</source>
        <translation>Test został ukończony</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Następne pytanie: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Poprawnie: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Reguła</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Wyjaśnienie reguły</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Klip audio</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Anuluj</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Zobacz regułę</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Obróć koło, aby wybrać słowo dla każdej luki.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Luka %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Przeciągnij kafelek na lukę lub dotknij kafelka, a następnie luki, aby go umieścić.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Wybierz poprawną odpowiedź.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Wybierz wszystkie pasujące.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Poprawnie: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Wyślij</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Poprawnie: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Zobacz wyniki</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Dalej →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Numer pytania %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Nadpisać zestaw słów?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Scalić biblioteki?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Zestaw słów o nazwie „%1” już tu istnieje. Nadpisać go przeniesionym zestawem?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Biblioteka o nazwie „%1” już tu istnieje. Scalić jej zawartość z tą biblioteką?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Zestaw słów o nazwie „%1” już istnieje w %2. Nadpisać go scaloną wersją?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>biblioteka docelowa</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Eksportuj jako .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Nowa biblioteka</translation>
    </message>
    <message>
        <location line="+31"/>
        <source>Library name:</source>
        <translation>Nazwa biblioteki:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>np. Podróże, Praca, Szkoła…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Biblioteka lub zestaw o tej nazwie już tu istnieje.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+99"/>
        <source>A library with this name already exists here.</source>
        <translation>Biblioteka o tej nazwie już tu istnieje.</translation>
    </message>
    <message>
        <location line="-62"/>
        <source>Create</source>
        <translation>Utwórz</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Rename Library</source>
        <translation>Zmień nazwę biblioteki</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Nowa nazwa:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Zmień nazwę</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Twoje zestawy słów</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Biblioteka</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Przenieś poza</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Upuść, aby przenieść do środka</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>słów</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>pytania</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Usuń bibliotekę</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Edytuj</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Usuń</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Udostępnij plik .ppset</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Eksportuj .ppset (zapisz na dysku)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Jeszcze nic tu nie ma.
Dotknij + Utwórz, aby dodać zestaw słów lub bibliotekę.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Zestaw słów</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Zestaw reguł</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Utwórz</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Język interfejsu</translation>
    </message>
    <message>
        <location line="-710"/>
        <location line="+796"/>
        <source>Cancel</source>
        <translation>Anuluj</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Wybierz typ testu</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Fiszki</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Odwróć, aby ujawnić — przesuń w prawo, jeśli znasz</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Napisz słowo</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Zobacz podpowiedź — wpisz wyrażenie</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Napisz podpowiedź</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Zobacz słowo — wpisz jego tłumaczenie</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Wybierz słowo</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Zobacz podpowiedź — wybierz spośród 4 opcji</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Wybierz podpowiedź</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Zobacz słowo — wybierz spośród 4 opcji</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Nauka progresywna</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Wybór wielokrotny do nauki, potem pisanie, aby opanować wszystkie słowa</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Odwrócona nauka progresywna</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Wybór wielokrotny do nauki, potem pisanie, aby opanować wszystkie podpowiedzi</translation>
    </message>
    <message>
        <location line="+36"/>
        <location line="+82"/>
        <source>✓ Done</source>
        <translation>✓ Gotowe</translation>
    </message>
    <message>
        <location line="-82"/>
        <source>← Reset</source>
        <translation>← Resetuj</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Completed — swipe left to reset</source>
        <translation>Ukończono — przesuń w lewo, aby zresetować</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>%1 left</source>
        <translation>Pozostało: %1</translation>
    </message>
    <message>
        <location line="+51"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Rygor ortograficzny</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Rygorystyczny</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normalny</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Łagodny</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Anuluj</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Powtórz wyrażenia</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Zatrzymaj</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Słuchaj</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Rozpocznij test</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Brak słów</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Wpisz podpowiedź / tłumaczenie…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Wpisz wyrażenie…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Poprawnie: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Oznacz jako poprawne (literówka)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Wyślij</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Oznacz jako poprawne (pomyłka kliknięcia)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Poprawnie: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Zobacz wyniki</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Dalej →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Numer pytania %1</translation>
    </message>
</context>
</TS>
