<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="id">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Tentang</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Pelatih kosakata untuk menghafal set kata.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Pelatih kosakata dan tata bahasa.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Lisensi Sumber Terbuka</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Aplikasi ini menggunakan Qt di bawah lisensi GNU Lesser General Public License versi 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Pemberitahuan Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Pemberitahuan Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Kode sumber Qt</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Situs web proyek Qt</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Dibuat oleh AI — mungkin mengandung kesalahan</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Laporkan</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Terima kasih — laporan Anda telah dikirim dan akan ditinjau.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Laporkan konten AI</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Apa yang salah dengan konten yang dibuat ini?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Konten seksual atau sugestif</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Kata-kata kasar atau bahasa yang menyinggung</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Konten kebencian atau pelecehan</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Konten kekerasan atau berbahaya</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Informasi yang salah atau menyesatkan</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Lainnya</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Detail (opsional)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Mengirim…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Tutup</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Batal</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Kirim laporan</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Ambil Foto</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Batal</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>segera hadir</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>dalam %1h %2j</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>dalam %1j %2m</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>dalam %1m</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Pilih Gambar</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Pilih Audio</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Impor Set Kata</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Bahasa Kata</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Bahasa Petunjuk</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+339"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Batal</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ Generator Set Kata AI</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Didukung oleh Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Tema</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Jelaskan set yang Anda inginkan — mis. “peralatan dapur yang bisa ditemukan di rumah tangga Prancis” atau “frasa perjalanan bisnis untuk menghadiri konferensi”…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Tersisa %1 dari %2 pembuatan bulan ini — reset pada %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI bisa membuat kesalahan. Hanya konten yang sesuai untuk semua usia yang dibuat — gunakan 🚩 Laporkan untuk menandai apa pun yang tidak pantas.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Bahasa kata</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Bahasa petunjuk</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Jumlah kata</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Menanyakan Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Batalkan Permintaan</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Buat</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Set Kata Baru</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Edit Set Kata</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Impor</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Judul set…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Ambil gambar otomatis</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Kata</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>dipilih</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Kata / Istilah</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Belum dipilih</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Masukkan kata...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Petunjuk / arti</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Petunjuk, definisi...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Contoh penggunaan</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Contoh kalimat menggunakan kata tersebut...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Ubah gambar</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Tambah gambar</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Ambil</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Kamera</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Tambah audio</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Berhenti</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Putar</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ TTS</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Berhenti</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Rekam</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Tambah kata</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Hapus</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Simpan</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Judul wajib diisi</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>segera</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>dalam %1h %2j</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>dalam %1j %2m</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>dalam %1m</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Pilih Gambar</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Pilih Audio</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Set Aturan Baru</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Edit Set Aturan</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Impor</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Impor Set Aturan</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ Generator Set Aturan AI</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Didukung oleh Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Tersisa %1 dari %2 pembuatan bulan ini — direset %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Aturan/topik yang akan dijelaskan</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Jelaskan aturan yang Anda inginkan — mis. &quot;present simple vs present continuous&quot; atau &quot;kalimat kondisional tipe ketiga&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Pertanyaan per jenis</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Isi Bagian Kosong</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Pilihan Ganda</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Pilihan Dropdown</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Seret &amp; Lepas</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Menanyakan Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Batalkan permintaan</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Batal</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI bisa membuat kesalahan. Hanya konten yang sesuai untuk semua usia yang dibuat — gunakan 🚩 Laporkan untuk menandai apa pun yang tidak pantas.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Buat</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Masukkan judul…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Penjelasan Teori</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Tersembunyi selama pengujian hingga pelajar membuat kesalahan — selalu dapat dibaca di pratinjau.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Gunakan ▲▼ untuk mengatur ulang blok. Seret sudut // foto untuk mengubah ukurannya.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Jelaskan aturan yang dilatih oleh set ini…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Klip audio</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Teks</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Foto</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Audio</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Pertanyaan</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>dipilih</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Isi Bagian Kosong</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Pilihan Ganda</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Pilihan Dropdown</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Seret &amp; Lepas</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Gunakan ___ (tiga garis bawah) untuk setiap bagian kosong yang diisi pelajar.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>mis. Apa yang dia lakukan setiap hari?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>mis. Dia pergi ___ ke sekolah setiap hari.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Jawaban</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Satu jawaban per bagian kosong, dipisahkan koma, secara berurutan. Gunakan \, untuk koma literal.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>mis. pergi</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Opsi</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Pisahkan opsi untuk satu bagian kosong dengan koma; pisahkan bagian kosong dengan titik dua ganda (::). Satu : aman apa adanya; gunakan \, untuk koma literal, \:: untuk :: literal, dan ___ untuk opsi yang sengaja kosong. Mis. untuk dua bagian kosong: pergi, pergi, pergi::setiap, beberapa, kebanyakan.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Ubin yang dapat diseret dipisahkan koma — sertakan jawaban yang benar, ditambah pengecoh opsional yang dapat mengelabui pelajar. Gunakan \, untuk koma literal, dan ___ untuk ubin kosong (untuk bagian kosong yang seharusnya tetap kosong). Isi bagian kosong di bawah setelah ini ditetapkan.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>mis. pergi, pergi, pergi::setiap, beberapa, kebanyakan</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>mis. pergi, pergi, pergi, pergi</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Jawaban benar untuk setiap bagian kosong</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Ketuk pilihan yang benar di setiap kotak di bawah.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Pilih jawaban yang benar untuk setiap bagian kosong.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Bagian Kosong %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Isi bagian kosong</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Seret ubin ke bagian kosong di bawah, atau ketuk ubin lalu bagian kosong untuk menempatkannya.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Isi setiap bagian kosong dengan ubin.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Opsi dipisahkan koma — ketuk jawaban yang benar di bawah. Gunakan \, untuk koma literal.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Opsi dipisahkan koma — ketuk semua jawaban yang benar di bawah. Gunakan \, untuk koma literal.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>mis. pergi, pergi, pergi, pergi</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Hanya satu jawaban benar</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Jawaban benar</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Jawaban benar</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Pilih jawaban yang benar.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Pilih setidaknya satu jawaban yang benar.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Tambah pertanyaan</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Hapus</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Simpan</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Judul wajib diisi</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Jelaskan tata bahasa</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Tidak dapat memuat pertanyaan %1: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Hanya %1 dari %2 pertanyaan yang diminta yang dibuat — coba topik yang lebih luas, atau kurangi jumlah di atas.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Bahasa penjelasan</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Bahasa penjelasan</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Bahasa topik</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Bahasa topik</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Topik ini tidak dapat dibuat. AI hanya membuat konten yang sesuai untuk semua usia — topik seksual, kasar, atau menyinggung tidak didukung. Silakan coba topik lain.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Anda telah menggunakan semua pembuatan AI untuk bulan ini. Coba lagi bulan depan.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Terlalu banyak laporan hari ini — silakan coba lagi besok.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Layanan AI sedang sibuk — silakan coba lagi sebentar lagi.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Masukkan tema terlebih dahulu.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Tema terlalu panjang (maks. %1 karakter).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Atur setidaknya satu jenis pertanyaan di atas nol.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Sesi Anda telah berakhir — silakan masuk lagi.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Tidak dapat menghubungi server. Periksa koneksi internet Anda dan coba lagi.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Terjadi kesalahan. Silakan coba lagi.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Belum masuk.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Ketuk untuk membalik</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Ketuk untuk membalik kembali</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>TAHU</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>LEWATI</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Tidak tahu</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Tahu</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Belum dipilih</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Tidak dapat memuat teks lisensi.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Masuk untuk melanjutkan</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Membuka peramban…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Masuk dengan Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Pustaka atau set dengan nama ini sudah ada di sini.</translation>
    </message>
    <message>
        <location line="+317"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Set kata dengan nama ini sudah ada di sini.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Set aturan dengan nama ini sudah ada di sini.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+38"/>
        <source>Results</source>
        <translation>Hasil</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>Well</source>
        <translation>Kerja</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>done</source>
        <translation>bagus</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>dari %1</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Kerja luar biasa! Pertahankan!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Usaha yang baik! Terus berlatih.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Jangan menyerah – latihan membuat sempurna!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Sesi ini</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Tidak tahu</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Tahu</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Practice again</source>
        <translation>Latihan lagi</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Find another set</source>
        <translation>Cari set lain</translation>
    </message>
    <message>
        <source>Practice Again</source>
        <translation type="vanished">Berlatih Lagi</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Reset kemajuan tes?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Ini akan menghapus kemajuan Anda pada set aturan ini dan memulai sesi baru.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 pertanyaan</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Selesai: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Sedang berlangsung: %1 / %2</translation>
    </message>
    <message>
        <source>← Reset</source>
        <translation type="vanished">← Reset</translation>
    </message>
    <message>
        <location line="+185"/>
        <source>Reset to practise again</source>
        <translation>Atur ulang untuk berlatih lagi</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Reset</source>
        <translation>Atur Ulang</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Penjelasan Aturan</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Tidak ada penjelasan yang ditambahkan untuk set ini.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Klip audio</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Ketegasan ejaan</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Ketat</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Longgar</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Mulai Tes</translation>
    </message>
    <message>
        <location line="-316"/>
        <source>Test is completed</source>
        <translation>Tes telah selesai</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Pertanyaan berikutnya: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Benar: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Aturan</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Penjelasan Aturan</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Klip audio</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Batal</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Lihat aturan</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Putar roda untuk memilih kata setiap bagian kosong.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Bagian Kosong %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Seret ubin ke bagian kosong, atau ketuk ubin lalu bagian kosong untuk menempatkannya.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Pilih jawaban yang benar.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Pilih semua yang berlaku.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Benar: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Kirim</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Benar: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Lihat Hasil</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Berikutnya →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Nomor pertanyaan %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Timpa set kata?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Gabungkan pustaka?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Set kata bernama “%1” sudah ada di sini. Timpa dengan set yang dipindahkan?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Pustaka bernama “%1” sudah ada di sini. Gabungkan isinya ke dalamnya?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Set kata bernama “%1” sudah ada di %2. Timpa dengan versi yang digabungkan?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>pustaka tujuan</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Ekspor sebagai .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Pustaka Baru</translation>
    </message>
    <message>
        <location line="+31"/>
        <source>Library name:</source>
        <translation>Nama pustaka:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>mis. Perjalanan, Kerja, Sekolah…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Pustaka atau set dengan nama ini sudah ada di sini.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+99"/>
        <source>A library with this name already exists here.</source>
        <translation>Pustaka dengan nama ini sudah ada di sini.</translation>
    </message>
    <message>
        <location line="-62"/>
        <source>Create</source>
        <translation>Buat</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Rename Library</source>
        <translation>Ganti Nama Pustaka</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Nama baru:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Ganti Nama</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Set kata Anda</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Pustaka</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Pindahkan keluar dari</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Lepaskan untuk memindahkan ke dalam</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>kata</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>pertanyaan</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Hapus Pustaka</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Edit</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Hapus</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Bagikan file .ppset</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Ekspor .ppset (simpan ke disk)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Belum ada apa pun di sini.
Ketuk + Buat untuk menambahkan set kata atau pustaka.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Set Kata</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Set Aturan</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Buat</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Bahasa Antarmuka</translation>
    </message>
    <message>
        <location line="-710"/>
        <location line="+796"/>
        <source>Cancel</source>
        <translation>Batal</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Pilih Jenis Tes</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Kartu Flash</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Balikkan untuk mengungkap — geser kanan jika Anda tahu</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Tulis Kata</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Lihat petunjuk — ketik ungkapannya</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Tulis Petunjuk</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Lihat kata — ketik terjemahannya</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Pilih Kata</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Lihat petunjuk — pilih dari 4 opsi</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Pilih Petunjuk</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Lihat kata — pilih dari 4 opsi</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Pembelajaran Progresif</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Pilihan ganda untuk belajar, lalu menulis untuk menguasai semua kata</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Pembelajaran Progresif Terbalik</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Pilihan ganda untuk belajar, lalu menulis untuk menguasai semua petunjuk</translation>
    </message>
    <message>
        <location line="+36"/>
        <location line="+82"/>
        <source>✓ Done</source>
        <translation>✓ Selesai</translation>
    </message>
    <message>
        <location line="-82"/>
        <source>← Reset</source>
        <translation>← Atur Ulang</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Completed — swipe left to reset</source>
        <translation>Selesai — geser ke kiri untuk mengatur ulang</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>%1 left</source>
        <translation>%1 tersisa</translation>
    </message>
    <message>
        <location line="+51"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Ketegasan ejaan</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Ketat</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Longgar</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Batal</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Tinjau Ungkapan</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Berhenti</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Dengarkan</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Mulai Tes</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Belum ada kata</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Ketik petunjuk / terjemahan…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Ketik ungkapan…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Benar: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Tandai sebagai benar (saya salah ketik)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Kirim</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Tandai sebagai benar (saya salah klik)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Benar: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Lihat Hasil</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Berikutnya →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Nomor pertanyaan %1</translation>
    </message>
</context>
</TS>
