<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="cs">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>O aplikaci</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Trenér slovní zásoby pro zapamatování slovních sad.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Trenér slovní zásoby a gramatiky.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Licence open source</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Tato aplikace používá Qt pod licencí GNU Lesser General Public License verze 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Oznámení Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Oznámení Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Zdrojový kód Qt</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Web projektu Qt</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Vygenerováno AI — může obsahovat chyby</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Nahlásit</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Děkujeme — vaše hlášení bylo odesláno a bude posouzeno.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Nahlásit obsah AI</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Co je s tímto vygenerovaným obsahem špatně?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Sexuální nebo lascivní obsah</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Vulgarity nebo urážlivé výrazy</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Nenávistný nebo obtěžující obsah</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Násilný nebo nebezpečný obsah</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Nesprávné nebo zavádějící informace</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Něco jiného</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Podrobnosti (volitelné)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Odesílání…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Zavřít</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Zrušit</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Odeslat hlášení</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Vyfotit</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Zrušit</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>brzy</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>za %1d %2h</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>za %1h %2min</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>za %1min</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Vybrat obrázek</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Vybrat zvuk</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Importovat sadu slov</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Jazyk slova</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Jazyk nápovědy</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+326"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Zrušit</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ Generátor sad slov s AI</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Poháněno Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Téma</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Popište sadu, kterou chcete — např. „kuchyňské potřeby, které byste našli ve francouzské domácnosti“ nebo „fráze pro pracovní cestu na konferenci“…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Zbývá %1 z %2 generování tento měsíc — reset %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI se může mýlit. Generuje se pouze obsah vhodný pro všechny věkové kategorie — cokoli nevhodného nahlaste pomocí 🚩 Nahlásit.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Jazyk slova</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Jazyk nápovědy</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Počet slov</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Dotazování Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Zrušit požadavek</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Generovat</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Nová sada slov</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Upravit sadu slov</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importovat</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Název sady…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Automaticky stahovat obrázky</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Slovo</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>vybráno</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Slovo / Termín</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Nevybráno</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Zadejte slovo...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Nápověda / význam</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Nápověda, definice...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Příklad použití</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Příkladová věta se slovem...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Změnit obrázek</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Přidat obrázek</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Stáhnout</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Fotoaparát</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Přidat zvuk</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Zastavit</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Přehrát</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ TTS</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Zastavit</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Nahr.</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Přidat slovo</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Odebrat</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Uložit</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Název je povinný</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>brzy</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>za %1d %2h</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>za %1h %2m</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>za %1m</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Vybrat obrázek</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Vybrat zvuk</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Nová sada pravidel</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Upravit sadu pravidel</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importovat</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Importovat sadu pravidel</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ Generátor sad pravidel s AI</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Poháněno Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Zbývá %1 z %2 generování tento měsíc — reset %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Pravidlo/téma k vysvětlení</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Popište pravidlo, které chcete — např. &quot;přítomný prostý vs. přítomný průběhový&quot; nebo &quot;věty třetího kondicionálu&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Otázek na typ</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Doplňte mezeru</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Výběr z možností</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Rozbalovací nabídka</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Přetáhnout</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Dotazuji se Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Zrušit požadavek</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Zrušit</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI se může mýlit. Generuje se pouze obsah vhodný pro všechny věkové kategorie — cokoli nevhodného nahlaste pomocí 🚩 Nahlásit.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Generovat</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Zadejte název…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Vysvětlení teorie</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Skryto během testu, dokud student neudělá chybu — vždy čitelné v náhledu.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Pomocí ▲▼ změňte pořadí bloku. Přetažením rohu // fotky změníte její velikost.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Vysvětlete pravidlo, které tato sada procvičuje…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Zvuková ukázka</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Text</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Fotka</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Zvuk</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Otázka</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>vybráno</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Doplňte mezeru</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Výběr z možností</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Rozbalovací nabídka</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Přetáhnout</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Pro každou mezeru, kterou student doplňuje, použijte ___ (tři podtržítka).</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>např. Co dělá každý den?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>např. Chodí ___ každý den do školy.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Odpovědi</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Jedna odpověď na mezeru, oddělené čárkami, v pořadí. Pro doslovnou čárku použijte \,.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>např. jde</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Možnosti</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Možnosti pro jednu mezeru oddělte čárkami; mezery oddělte dvojitou dvojtečkou (::). Jednoduchá : je bezpečná tak, jak je; pro doslovnou čárku použijte \,, pro doslovné :: použijte \::, a pro záměrně prázdnou možnost použijte ___. Např. pro dvě mezery: jde, jít, jdoucí::každý, někteří, většina.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Přetahovatelné dlaždice oddělené čárkami — zahrňte správné odpovědi a volitelně i vějičky, kterými lze studenta zmást. Pro doslovnou čárku použijte \, a pro prázdnou dlaždici ___ (pro mezeru, která má správně zůstat prázdná). Jakmile jsou nastaveny, vyplňte níže mezery.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>např. jde, jít, jdoucí::každý, někteří, většina</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>např. jde, jít, jdoucí, šel</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Správná odpověď pro každou mezeru</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Klepněte na správnou možnost v každém poli níže.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Vyberte správnou odpověď pro každou mezeru.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Mezera %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Vyplňte mezery</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Přetáhněte dlaždici na mezeru níže, nebo klepněte na dlaždici a poté na mezeru pro její umístění.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Vyplňte každou mezeru dlaždicí.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Možnosti oddělené čárkami — klepněte níže na správnou odpověď. Pro doslovnou čárku použijte \,.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Možnosti oddělené čárkami — klepněte níže na všechny správné odpovědi. Pro doslovnou čárku použijte \,.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>např. jde, jít, jdoucí, šel</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Pouze jedna správná odpověď</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Správná odpověď</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Správná odpověď(i)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Vyberte správnou odpověď.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Vyberte alespoň jednu správnou odpověď.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Přidat otázku</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Odebrat</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Uložit</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Název je povinný</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Vysvětlit gramatiku</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Otázku %1 se nepodařilo načíst: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Vygenerováno pouze %1 z %2 požadovaných otázek — zkuste širší téma nebo snižte počty výše.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Jazyk vysvětlení</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Jazyk vysvětlení</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Jazyk tématu</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Jazyk tématu</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Toto téma nelze vygenerovat. AI vytváří pouze obsah vhodný pro všechny věkové kategorie — sexuální, vulgární nebo urážlivá témata nejsou podporována. Zkuste prosím jiné téma.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Vyčerpali jste všechna generování AI pro tento měsíc. Zkuste to znovu příští měsíc.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Dnes jste odeslali příliš mnoho hlášení — zkuste to prosím zítra.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Služba AI je právě vytížená — zkuste to prosím za chvíli znovu.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Nejprve zadejte téma.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Téma je příliš dlouhé (max. %1 znaků).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Nastavte alespoň jeden typ otázek na hodnotu větší než nula.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Vaše relace vypršela — přihlaste se prosím znovu.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Nepodařilo se spojit se serverem. Zkontrolujte připojení k internetu a zkuste to znovu.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Něco se pokazilo. Zkuste to prosím znovu.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Nejste přihlášeni.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Klepnutím otočíte</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Klepnutím otočíte zpět</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>ZNÁM</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>PŘESKOČIT</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Neznám</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Znám</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Nevybráno</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Text licence se nepodařilo načíst.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Přihlaste se pro pokračování</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Otevírání prohlížeče…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Přihlásit se přes Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Knihovna nebo sada s tímto názvem zde již existuje.</translation>
    </message>
    <message>
        <location line="+309"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Sada slov s tímto názvem zde již existuje.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Sada pravidel s tímto názvem zde již existuje.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+37"/>
        <source>Results</source>
        <translation>Výsledky</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Well</source>
        <translation>Dobrá</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>done</source>
        <translation>práce</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>z %1</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Skvělá práce! Tak dál!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Dobrá snaha! Pokračujte v procvičování.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Nevzdávejte to – opakování je matka moudrosti!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Toto sezení</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Neznám</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Znám</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Practice Again</source>
        <translation>Procvičit znovu</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Resetovat průběh testu?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Tím se vymaže váš postup v této sadě pravidel a spustí se nová relace.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 otázek</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Dokončeno: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Probíhá: %1 / %2</translation>
    </message>
    <message>
        <location line="+67"/>
        <source>← Reset</source>
        <translation>← Resetovat</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Vysvětlení pravidla</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>K této sadě nebylo přidáno žádné vysvětlení.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Zvuková ukázka</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Přísnost pravopisu</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Přísná</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normální</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Mírná</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Zahájit test</translation>
    </message>
    <message>
        <location line="-198"/>
        <source>Test is completed</source>
        <translation>Test je dokončen</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Další otázka: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Správně: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Pravidlo</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Vysvětlení pravidla</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Zvuková ukázka</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Zrušit</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Zobrazit pravidlo</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Otočením kola vyberte slovo pro každou mezeru.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Mezera %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Přetáhněte dlaždici na mezeru, nebo klepněte na dlaždici a poté na mezeru pro její umístění.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Vyberte správnou odpověď.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Vyberte vše, co platí.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Správně: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Odeslat</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Správně: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Zobrazit výsledky</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Další →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Otázka číslo %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Přepsat sadu slov?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Sloučit knihovny?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Sada slov s názvem „%1“ zde již existuje. Přepsat ji přesunutou sadou?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Knihovna s názvem „%1“ zde již existuje. Sloučit její obsah s ní?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Sada slov s názvem „%1“ již existuje v %2. Přepsat ji sloučenou verzí?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>cílová knihovna</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Exportovat jako .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Nová knihovna</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Library name:</source>
        <translation>Název knihovny:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>např. Cestování, Práce, Škola…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Knihovna nebo sada s tímto názvem zde již existuje.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+74"/>
        <source>A library with this name already exists here.</source>
        <translation>Knihovna s tímto názvem zde již existuje.</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Create</source>
        <translation>Vytvořit</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Rename Library</source>
        <translation>Přejmenovat knihovnu</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Nový název:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Přejmenovat</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Vaše sady slov</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Knihovna</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Přesunout ven z</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Upusťte pro přesun dovnitř</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>slov</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>otázky</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Odstranit knihovnu</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Upravit</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Odstranit</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Sdílet soubor .ppset</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Exportovat .ppset (uložit na disk)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Zatím tu nic není.
Klepněte na + Vytvořit pro přidání sady slov nebo knihovny.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Sada slov</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Sada pravidel</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Vytvořit</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Jazyk rozhraní</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Cancel</source>
        <translation>Zrušit</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Vybrat typ testu</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Kartičky</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Otočením odhalíte — přejeďte doprava, pokud to znáte</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Napište slovo</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Podívejte se na nápovědu — napište výraz</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Napište nápovědu</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Podívejte se na slovo — napište jeho překlad</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Vyberte slovo</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Podívejte se na nápovědu — vyberte ze 4 možností</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Vyberte nápovědu</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Podívejte se na slovo — vyberte ze 4 možností</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Progresivní učení</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Nejprve výběr z možností, poté psaní pro zvládnutí všech slov</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Obrácené progresivní učení</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Nejprve výběr z možností, poté psaní pro zvládnutí všech nápověd</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>✓ Done</source>
        <translation>✓ Hotovo</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>← Reset</source>
        <translation>← Resetovat</translation>
    </message>
    <message>
        <location line="+96"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Přísnost pravopisu</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Přísná</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normální</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Mírná</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Zrušit</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Opakovat výrazy</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Zastavit</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Poslechnout</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Zahájit test</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Zatím žádná slova</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Napište nápovědu / překlad…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Napište výraz…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Správně: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Označit jako správné (překlep)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Odeslat</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Označit jako správné (špatné kliknutí)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Správně: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Zobrazit výsledky</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Další →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Otázka číslo %1</translation>
    </message>
</context>
</TS>
