<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="et">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Teave</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Sõnavaratreener sõnakomplektide meeldejätmiseks.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Sõnavara ja grammatika treener.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Avatud lähtekoodiga litsentsid</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>See rakendus kasutab Qt-d GNU Lesser General Public License versiooni 3 alusel.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Qt teatis</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Qt teatis</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Qt lähtekood</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Qt projekti veebisait</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Loodud AI abil — võib sisaldada vigu</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Teata</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Aitäh — sinu teade saadeti ja see vaadatakse üle.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Teata AI sisust</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Mis selle loodud sisuga valesti on?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Seksuaalne või vihjeline sisu</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Roppused või solvav keelekasutus</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Vihkav või ahistav sisu</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Vägivaldne või ohtlik sisu</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Vale või eksitav teave</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Midagi muud</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Üksikasjad (valikuline)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Saatmine…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Sulge</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Tühista</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Saada teade</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Tee foto</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Tühista</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>varsti</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1p %2t pärast</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1t %2min pärast</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1min pärast</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Vali pilt</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Vali heli</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Impordi sõnakomplekt</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Sõna keel</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Vihje keel</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+339"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Tühista</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ AI sõnakomplektide generaator</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Käitab Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Teema</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Kirjelda soovitud komplekti — nt „köögitarbed, mida leiaks Prantsuse kodust” või „ärireisi fraasid konverentsile”…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Sel kuul jäänud %1 / %2 genereerimist — lähtestub %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI võib eksida. Luuakse ainult igale vanusele sobivat sisu — kasuta nuppu 🚩 Teata, et märkida midagi sobimatut.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Sõna keel</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Vihje keel</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Sõnade arv</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Küsin Geminilt…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Tühista päring</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Genereeri</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Uus sõnakomplekt</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Muuda sõnakomplekti</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Impordi</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Komplekti pealkiri…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Too pildid automaatselt</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Sõna</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>valitud</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Sõna / Termin</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Valimata</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Sisesta sõna...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Vihje / tähendus</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Vihje, definitsioon...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Kasutusnäide</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Näidislause, mis kasutab sõna...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Muuda pilti</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Lisa pilt</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Too</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Kaamera</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Lisa heli</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Peata</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Esita</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ Kõne</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Peata</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Salvesta</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Lisa sõna</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Eemalda</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Salvesta</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Pealkiri on kohustuslik</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>varsti</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1p %2t pärast</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1t %2min pärast</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1min pärast</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Vali pilt</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Vali heli</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ Tehisintellekt</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Uus reeglistik</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Muuda reeglistikku</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Impordi</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Impordi reeglistik</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ Tehisintellekti reeglistiku generaator</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Toiteallikas Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Sel kuul jäänud %1 genereerimist %2-st — lähtestatakse %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Selgitatav reegel/teema</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Kirjelda soovitud reeglit — nt &quot;present simple vs present continuous&quot; või &quot;kolmanda tüübi tingimuslaused&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Küsimusi tüübi kohta</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Täida lünk</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Valikvastus</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Rippmenüü valik</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Lohista ja aseta</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Küsitakse Geminilt…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Tühista päring</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Tühista</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI võib eksida. Luuakse ainult igale vanusele sobivat sisu — kasuta nuppu 🚩 Teata, et märkida midagi sobimatut.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Loo</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Sisesta pealkiri…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Teooria selgitus</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Peidetud testimise ajal, kuni õppija teeb vea — eelvaates alati loetav.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Ploki ümberjärjestamiseks kasuta ▲▼. Foto suuruse muutmiseks lohista selle // nurka.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Selgita reeglit, mida see komplekt harjutab…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Heliklipp</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Tekst</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Foto</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Heli</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Küsimus</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>valitud</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Täida lünk</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Valikvastus</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Rippmenüü valik</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Lohista ja aseta</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Kasuta ___ (kolm alakriipsu) iga lünga jaoks, mille õppija täidab.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>nt Mida ta iga päev teeb?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>nt Ta läheb iga päev ___ kooli.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Vastused</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Üks vastus lünga kohta, komadega eraldatud, järjekorras. Kasuta sõnasõnalise koma jaoks \,.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>nt läheb</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Valikud</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Eralda ühe lünga valikud komadega; eralda lüngad topeltkooloniga (::). Üksik : on turvaline nagu on; kasuta sõnasõnalise koma jaoks \,, sõnasõnalise :: jaoks \::, ja tahtlikult tühja valiku jaoks ___. Nt kahe lünga jaoks: läheb, minna, minnes::iga, mõned, enamik.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Komadega eraldatud lohistatavad plaadid — lisa õiged vastused, pluss valikulised petised, millega õppijat saab eksitada. Kasuta sõnasõnalise koma jaoks \, ja tühja plaadi jaoks ___ (lünga jaoks, mis peab õigesti tühjaks jääma). Täida allolevad lüngad, kui need on määratud.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>nt läheb, minna, minnes::iga, mõned, enamik</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>nt läheb, minna, minnes, läinud</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Iga lünga õige vastus</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Puuduta õiget valikut igas allolevas kastis.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Vali igale lüngale õige vastus.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Lünk %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Täida lüngad</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Lohista plaat allolevale lüngale või puuduta plaati ja seejärel lünka, et see paigutada.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Täida iga lünk plaadiga.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Komadega eraldatud valikud — puuduta allolevat õiget vastust. Kasuta sõnasõnalise koma jaoks \,.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Komadega eraldatud valikud — puuduta kõiki allolevaid õigeid vastuseid. Kasuta sõnasõnalise koma jaoks \,.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>nt läheb, minna, minnes, läinud</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Ainult üks õige vastus</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Õige vastus</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Õige(d) vastus(ed)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Vali õige vastus.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Vali vähemalt üks õige vastus.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Lisa küsimus</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Eemalda</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Salvesta</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Pealkiri on nõutav</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Selgita grammatikat</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Küsimust %1 ei õnnestunud laadida: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Loodi ainult %1 küsimust %2-st soovitust — proovi laiemat teemat või vähenda ülaltoodud arve.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Selgituse keel</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Selgituse keel</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Teema keel</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Teema keel</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Seda teemat ei saa luua. AI loob ainult igale vanusele sobivat sisu — seksuaalseid, roppe või solvavaid teemasid ei toetata. Proovi mõnda muud teemat.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Oled selle kuu kõik AI-genereerimised ära kasutanud. Proovi järgmisel kuul uuesti.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Täna on liiga palju teateid saadetud — proovi homme uuesti.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>AI-teenus on praegu hõivatud — proovi hetke pärast uuesti.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Sisesta kõigepealt teema.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Teema on liiga pikk (max %1 märki).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Määra vähemalt ühe küsimusetüübi arv suuremaks kui null.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Sinu seanss aegus — logi uuesti sisse.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Serveriga ei saanud ühendust. Kontrolli internetiühendust ja proovi uuesti.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Midagi läks valesti. Proovi uuesti.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Pole sisse logitud.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Puuduta, et ümber pöörata</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Puuduta, et tagasi pöörata</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>TEAN</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>JÄTA VAHELE</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Ei tea</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Tean</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Valimata</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Litsentsiteksti ei õnnestunud laadida.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Jätkamiseks logi sisse</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Brauseri avamine…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Logi sisse Google&apos;iga</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Sellenimeline teek või komplekt on siin juba olemas.</translation>
    </message>
    <message>
        <location line="+317"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Sellenimeline sõnakomplekt on siin juba olemas.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Sellenimeline reeglistik on siin juba olemas.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+38"/>
        <source>Results</source>
        <translation>Tulemused</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>Well</source>
        <translation>Väga</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>done</source>
        <translation>tubli</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>%1-st</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Suurepärane töö! Jätka samas vaimus!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Hea katse! Jätka harjutamist.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Ära anna alla – harjutamine teeb meistriks!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>See seanss</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Ei tea</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Tean</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Practice again</source>
        <translation>Harjuta uuesti</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Find another set</source>
        <translation>Leia teine komplekt</translation>
    </message>
    <message>
        <source>Practice Again</source>
        <translation type="vanished">Harjuta uuesti</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Lähtestada testi edenemine?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>See kustutab sinu edenemise selles reeglistikus ja alustab uue seansi.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 küsimust</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Lõpetatud: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Pooleli: %1 / %2</translation>
    </message>
    <message>
        <source>← Reset</source>
        <translation type="vanished">← Lähtesta</translation>
    </message>
    <message>
        <location line="+185"/>
        <source>Reset to practise again</source>
        <translation>Lähtesta, et uuesti harjutada</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Reset</source>
        <translation>Lähtesta</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Reegli selgitus</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Sellele komplektile pole selgitust lisatud.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Heliklipp</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Õigekirja rangus</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Range</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Tavaline</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Leebe</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Alusta testi</translation>
    </message>
    <message>
        <location line="-316"/>
        <source>Test is completed</source>
        <translation>Test on lõpetatud</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Järgmine küsimus: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Õige: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Reegel</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Reegli selgitus</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Heliklipp</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Tühista</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Vaata reeglit</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Keera ratast, et valida iga lünga sõna.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Lünk %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Lohista plaat lünka või puuduta plaati ja seejärel lünka, et see paigutada.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Vali õige vastus.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Vali kõik sobivad.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Õige: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Esita</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Õige: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Vaata tulemusi</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Järgmine →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Küsimuse number %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Kirjutada sõnakomplekt üle?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Ühendada teegid?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Sõnakomplekt nimega „%1” on siin juba olemas. Kas kirjutada see teisaldatud komplektiga üle?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Teek nimega „%1” on siin juba olemas. Kas ühendada selle sisu sellega?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Sõnakomplekt nimega „%1” on juba olemas kohas %2. Kas kirjutada see ühendatud versiooniga üle?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>sihtteek</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Ekspordi kui .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Uus teek</translation>
    </message>
    <message>
        <location line="+31"/>
        <source>Library name:</source>
        <translation>Teegi nimi:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>nt Reisimine, Töö, Kool…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Sellenimeline teek või komplekt on siin juba olemas.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+99"/>
        <source>A library with this name already exists here.</source>
        <translation>Sellenimeline teek on siin juba olemas.</translation>
    </message>
    <message>
        <location line="-62"/>
        <source>Create</source>
        <translation>Loo</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Rename Library</source>
        <translation>Nimeta teek ümber</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Uus nimi:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Nimeta ümber</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Sinu sõnakomplektid</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Teek</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Liiguta väljapoole</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Lohista siia, et liigutada sisse</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>sõna</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>küsimust</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Kustuta teek</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Muuda</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Kustuta</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Jaga .ppset faili</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Ekspordi .ppset (salvesta kettale)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Siin pole veel midagi.
Puuduta + Loo, et lisada sõnakomplekt või teek.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Sõnakomplekt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Reeglistik</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Loo</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Liidese keel</translation>
    </message>
    <message>
        <location line="-710"/>
        <location line="+796"/>
        <source>Cancel</source>
        <translation>Tühista</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Vali testi tüüp</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Õppekaardid</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Pööra, et paljastada — pühi paremale, kui tead</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Kirjuta sõna</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Vaata vihjet — trüki väljend</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Kirjuta vihje</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Vaata sõna — trüki selle tõlge</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Vali sõna</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Vaata vihjet — vali 4 valiku hulgast</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Vali vihje</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Vaata sõna — vali 4 valiku hulgast</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Progressiivne õppimine</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Kõigepealt valikvastused õppimiseks, seejärel kirjutamine kõigi sõnade omandamiseks</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Ümberpööratud progressiivne õppimine</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Kõigepealt valikvastused õppimiseks, seejärel kirjutamine kõigi vihjete omandamiseks</translation>
    </message>
    <message>
        <location line="+36"/>
        <location line="+82"/>
        <source>✓ Done</source>
        <translation>✓ Valmis</translation>
    </message>
    <message>
        <location line="-82"/>
        <source>← Reset</source>
        <translation>← Lähtesta</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Completed — swipe left to reset</source>
        <translation>Lõpetatud — lähtestamiseks pühkige vasakule</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>%1 left</source>
        <translation>%1 jäänud</translation>
    </message>
    <message>
        <location line="+51"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Õigekirja rangus</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Range</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Tavaline</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Leebe</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Tühista</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Vaata väljendid üle</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Peata</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Kuula</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Alusta testi</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Sõnu pole veel</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Trüki vihje / tõlge…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Trüki väljend…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Õige: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Märgi õigeks (tegin trükivea)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Esita</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Märgi õigeks (klõpsasin valesti)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Õige: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Vaata tulemusi</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Järgmine →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Küsimuse number %1</translation>
    </message>
</context>
</TS>
