<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="fa">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>درباره</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">مربی واژگان برای به‌خاطرسپاری مجموعه‌های واژه.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>مربی واژگان و دستور زبان.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>مجوزهای متن‌باز</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>این برنامه از Qt تحت مجوز GNU Lesser General Public License نسخه ۳ استفاده می‌کند.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>اعلان Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>اعلان Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>کد منبع Qt</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>وب‌سایت پروژه Qt</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ تولیدشده با هوش مصنوعی — ممکن است اشتباه داشته باشد</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 گزارش</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>سپاسگزاریم — گزارش شما ارسال شد و بررسی خواهد شد.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 گزارش محتوای هوش مصنوعی</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>این محتوای تولیدشده چه مشکلی دارد؟</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>محتوای جنسی یا تحریک‌آمیز</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>ناسزا یا زبان توهین‌آمیز</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>محتوای نفرت‌آمیز یا آزاردهنده</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>محتوای خشونت‌آمیز یا خطرناک</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>اطلاعات نادرست یا گمراه‌کننده</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>مورد دیگر</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>جزئیات (اختیاری)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>در حال ارسال…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>بستن</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>لغو</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>ارسال گزارش</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>عکس گرفتن</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>لغو</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>به‌زودی</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1 روز و %2 ساعت دیگر</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1 ساعت و %2 دقیقه دیگر</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1 دقیقه دیگر</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>انتخاب تصویر</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>انتخاب صدا</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>درون‌ریزی مجموعه واژه</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>زبان واژه</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>زبان راهنما</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+339"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>لغو</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ سازندهٔ مجموعه واژهٔ هوش مصنوعی</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>قدرت‌گرفته از Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 موضوع</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>مجموعه‌ای را که می‌خواهید توصیف کنید — مثلاً «وسایل آشپزخانه‌ای که در یک خانهٔ فرانسوی پیدا می‌شود» یا «عبارات سفر کاری برای شرکت در کنفرانس»…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>%1 از %2 تولید باقی‌مانده در این ماه — بازنشانی در %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>هوش مصنوعی ممکن است اشتباه کند. فقط محتوای مناسب برای همهٔ سنین تولید می‌شود — برای گزارش هر چیز نامناسب از 🚩 گزارش استفاده کنید.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>زبان واژه</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>زبان راهنما</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 تعداد واژه‌ها</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>در حال پرسش از Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>لغو درخواست</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ تولید</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ هوش مصنوعی</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>مجموعه واژهٔ جدید</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>ویرایش مجموعه واژه</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>درون‌ریزی</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>عنوان مجموعه…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>دریافت خودکار تصاویر</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>واژه</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>انتخاب‌شده</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>واژه / اصطلاح</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>انتخاب‌نشده</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>واژه را وارد کنید...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>راهنما / معنی</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>راهنما، تعریف...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>نمونهٔ کاربرد</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>جملهٔ نمونه با استفاده از این واژه...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>تغییر تصویر</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>افزودن تصویر</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>دریافت</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>دوربین</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>افزودن صدا</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ توقف</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ پخش</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ خوانش صوتی</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ توقف</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● ضبط</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ افزودن واژه</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>حذف</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>ذخیره</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>عنوان الزامی است</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>به‌زودی</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>تا %1روز و %2ساعت</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>تا %1ساعت و %2دقیقه</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>تا %1دقیقه</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>انتخاب تصویر</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>انتخاب صدا</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ هوش مصنوعی</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>مجموعه قوانین جدید</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>ویرایش مجموعه قوانین</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>درون‌ریزی</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>درون‌ریزی مجموعه قوانین</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ مولد مجموعه قوانین هوش مصنوعی</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>با پشتیبانی Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>%1 از %2 تولید در این ماه باقی مانده — بازنشانی %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 قانون/موضوع برای توضیح</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>قانونی که می‌خواهید را توصیف کنید — مثلاً «حال ساده در برابر حال استمراری» یا «جملات شرطی نوع سوم»…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 تعداد سؤال به ازای هر نوع</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 پر کردن جای خالی</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 چندگزینه‌ای</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 انتخاب کشویی</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 بکشید و رها کنید</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>در حال پرسش از Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>لغو درخواست</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>لغو</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>هوش مصنوعی ممکن است اشتباه کند. فقط محتوای مناسب برای همهٔ سنین تولید می‌شود — برای گزارش هر چیز نامناسب از 🚩 گزارش استفاده کنید.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ تولید</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>عنوان را وارد کنید…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>توضیح نظریه</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>در طول آزمون تا زمانی که یادگیرنده اشتباه کند پنهان است — همیشه در پیش‌نمایش قابل خواندن است.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>برای تغییر ترتیب یک بلوک از ▲▼ استفاده کنید. برای تغییر اندازه عکس، گوشه // آن را بکشید.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>قانونی را که این مجموعه تمرین می‌کند توضیح دهید…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>قطعه صوتی</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ متن</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ عکس</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ صدا</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>سؤال</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>انتخاب‌شده</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>پر کردن جای خالی</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>چندگزینه‌ای</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>انتخاب کشویی</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>بکشید و رها کنید</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>برای هر جای خالی که یادگیرنده پر می‌کند از ___ (سه خط زیر) استفاده کنید.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>مثلاً او هر روز چه‌کار می‌کند؟</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>مثلاً او هر روز ___ مدرسه می‌رود.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>پاسخ‌ها</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>یک پاسخ برای هر جای خالی، با کاما جدا شده، به ترتیب. برای کامای واقعی از \, استفاده کنید.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>مثلاً می‌رود</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>گزینه‌ها</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>گزینه‌های یک جای خالی را با کاما جدا کنید؛ جاهای خالی را با دو نقطه دوتایی (::) جدا کنید. یک : تنها همان‌طور که هست ایمن است؛ برای کامای واقعی از \,، برای :: واقعی از \::، و برای گزینه‌ی عمداً خالی از ___ استفاده کنید. مثلاً برای دو جای خالی: می‌رود، رفتن، درحال‌رفتن::هر، برخی، بیشتر.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>کاشی‌های قابل کشیدن با کاما جدا شده — پاسخ‌های درست، به‌علاوه فریب‌های اختیاری که یادگیرنده می‌تواند با آن‌ها گمراه شود را اضافه کنید. برای کامای واقعی از \، و برای کاشی خالی از ___ استفاده کنید (برای جای خالی‌ای که درست است خالی بماند). پس از تنظیم این‌ها، جاهای خالی زیر را پر کنید.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>مثلاً می‌رود، رفتن، درحال‌رفتن::هر، برخی، بیشتر</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>مثلاً می‌رود، رفتن، درحال‌رفتن، رفته</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>پاسخ درست برای هر جای خالی</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>در هر کادر زیر روی گزینه درست ضربه بزنید.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>برای هر جای خالی یک پاسخ درست انتخاب کنید.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>جای خالی %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>جاهای خالی را پر کنید</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>کاشی را به یک جای خالی زیر بکشید، یا روی کاشی و سپس روی جای خالی ضربه بزنید تا قرار گیرد.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>هر جای خالی را با یک کاشی پر کنید.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>گزینه‌های جدا شده با کاما — روی پاسخ درست زیر ضربه بزنید. برای کامای واقعی از \, استفاده کنید.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>گزینه‌های جدا شده با کاما — روی همه پاسخ‌های درست زیر ضربه بزنید. برای کامای واقعی از \, استفاده کنید.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>مثلاً می‌رود، رفتن، درحال‌رفتن، رفته</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>فقط یک پاسخ درست</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>پاسخ درست</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>پاسخ(های) درست</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>پاسخ درست را انتخاب کنید.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>حداقل یک پاسخ درست انتخاب کنید.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ افزودن سؤال</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>حذف</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>ذخیره</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>عنوان لازم است</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 توضیح گرامر</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>بارگذاری سؤال %1 ممکن نشد: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>فقط %1 از %2 سؤال درخواستی ساخته شد — موضوعی گسترده‌تر امتحان کنید یا اعداد بالا را کاهش دهید.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>زبان توضیح</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>زبان توضیح</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>زبان موضوع</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>زبان موضوع</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>این موضوع قابل تولید نیست. هوش مصنوعی فقط محتوای مناسب برای همهٔ سنین می‌سازد — موضوعات جنسی، رکیک یا توهین‌آمیز پشتیبانی نمی‌شوند. لطفاً موضوع دیگری را امتحان کنید.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>همهٔ تولیدهای هوش مصنوعی این ماه را استفاده کرده‌اید. ماه آینده دوباره تلاش کنید.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>امروز گزارش‌های زیادی ارسال شده است — لطفاً فردا دوباره تلاش کنید.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>سرویس هوش مصنوعی اکنون مشغول است — لطفاً کمی بعد دوباره تلاش کنید.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>ابتدا یک موضوع وارد کنید.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>موضوع بیش از حد طولانی است (حداکثر %1 نویسه).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>دست‌کم یک نوع پرسش را بیشتر از صفر تنظیم کنید.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>نشست شما منقضی شده است — لطفاً دوباره وارد شوید.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>اتصال به سرور ممکن نشد. اتصال اینترنت خود را بررسی کنید و دوباره تلاش کنید.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>مشکلی پیش آمد. لطفاً دوباره تلاش کنید.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>وارد نشده‌اید.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>برای برگرداندن ضربه بزنید</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>برای برگرداندن دوباره ضربه بزنید</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>بلدم</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>رد شدن</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  بلد نیستم</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  بلدم</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>انتخاب‌نشده</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>متن مجوز بارگذاری نشد.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>برای ادامه وارد شوید</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>در حال باز کردن مرورگر…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>ورود با Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">کتابخانه یا مجموعه‌ای با این نام از قبل اینجا وجود دارد.</translation>
    </message>
    <message>
        <location line="+317"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>مجموعه واژه‌ای با این نام از قبل اینجا وجود دارد.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>مجموعه قوانینی با این نام از قبل اینجا وجود دارد.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+38"/>
        <source>Results</source>
        <translation>نتایج</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>Well</source>
        <translation>کارت</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>done</source>
        <translation>خوب</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>از %1</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>کار عالی! همینطور ادامه بده!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>تلاش خوبی بود! به تمرین ادامه بده.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>تسلیم نشو – تمرین باعث کمال می‌شود!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>این جلسه</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>بلد نیستم</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>بلدم</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Practice again</source>
        <translation>دوباره تمرین کنید</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Find another set</source>
        <translation>مجموعه‌ای دیگر پیدا کنید</translation>
    </message>
    <message>
        <source>Practice Again</source>
        <translation type="vanished">دوباره تمرین کن</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>پیشرفت آزمون بازنشانی شود؟</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>این کار پیشرفت شما در این مجموعه قوانین را پاک می‌کند و نشستی تازه آغاز می‌کند.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 سؤال</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">تکمیل‌شده: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">در حال انجام: %1 / %2</translation>
    </message>
    <message>
        <source>← Reset</source>
        <translation type="vanished">← بازنشانی</translation>
    </message>
    <message>
        <location line="+185"/>
        <source>Reset to practise again</source>
        <translation>بازنشانی برای تمرین دوباره</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Reset</source>
        <translation>بازنشانی</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>توضیح قانون</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>توضیحی برای این مجموعه اضافه نشده است.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>قطعه صوتی</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ سخت‌گیری املا</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>سخت‌گیرانه</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>معمولی</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>آسان‌گیرانه</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>شروع آزمون</translation>
    </message>
    <message>
        <location line="-316"/>
        <source>Test is completed</source>
        <translation>آزمون تکمیل شد</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>سؤال بعدی: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>درست: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>قانون</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 توضیح قانون</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>قطعه صوتی</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>لغو</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 مشاهده قانون</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>برای انتخاب کلمه هر جای خالی، چرخ را بچرخانید.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>جای خالی %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>کاشی را به یک جای خالی بکشید، یا روی کاشی و سپس روی جای خالی ضربه بزنید تا قرار گیرد.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>پاسخ درست را انتخاب کنید.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>همه موارد صادق را انتخاب کنید.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>درست: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>ارسال</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>درست: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>مشاهده نتایج</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>بعدی →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>شماره سؤال %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>مجموعه واژه بازنویسی شود؟</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>کتابخانه‌ها ادغام شوند؟</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>مجموعه واژه‌ای با نام «%1» از قبل اینجا وجود دارد. آن را با مجموعهٔ منتقل‌شده بازنویسی کنم؟</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>کتابخانه‌ای با نام «%1» از قبل اینجا وجود دارد. محتوای آن را با این ادغام کنم؟</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>مجموعه واژه‌ای با نام «%1» از قبل در %2 وجود دارد. آن را با نسخهٔ ادغام‌شده بازنویسی کنم؟</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>کتابخانهٔ مقصد</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>برون‌بری به‌صورت ‎.ppset‎</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>کتابخانهٔ جدید</translation>
    </message>
    <message>
        <location line="+31"/>
        <source>Library name:</source>
        <translation>نام کتابخانه:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>مثلاً: سفر، کار، مدرسه…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">کتابخانه یا مجموعه‌ای با این نام از قبل اینجا وجود دارد.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+99"/>
        <source>A library with this name already exists here.</source>
        <translation>کتابخانه‌ای با این نام از قبل اینجا وجود دارد.</translation>
    </message>
    <message>
        <location line="-62"/>
        <source>Create</source>
        <translation>ایجاد</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Rename Library</source>
        <translation>تغییر نام کتابخانه</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>نام جدید:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>تغییر نام</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>مجموعه واژه‌های شما</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>کتابخانه</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>انتقال به بیرون از</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>برای انتقال به داخل رها کنید</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>واژه</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>سؤال</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>حذف کتابخانه</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>ویرایش</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>حذف</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>اشتراک‌گذاری فایل ‎.ppset‎</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>برون‌بری ‎.ppset‎ (ذخیره روی دیسک)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>هنوز چیزی اینجا نیست.
برای افزودن مجموعه واژه یا کتابخانه، + ایجاد را لمس کنید.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>مجموعه واژه</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>مجموعه قوانین</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ ایجاد</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>زبان رابط کاربری</translation>
    </message>
    <message>
        <location line="-710"/>
        <location line="+796"/>
        <source>Cancel</source>
        <translation>لغو</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>نوع آزمون را انتخاب کنید</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>فلش‌کارت</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>برای مشاهده برگردانید — اگر بلدید به راست بکشید</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>واژه را بنویسید</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>راهنما را ببینید — عبارت را تایپ کنید</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>راهنما را بنویسید</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>واژه را ببینید — ترجمهٔ آن را تایپ کنید</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>واژه را انتخاب کنید</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>راهنما را ببینید — از میان ۴ گزینه انتخاب کنید</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>راهنما را انتخاب کنید</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>واژه را ببینید — از میان ۴ گزینه انتخاب کنید</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>یادگیری پیش‌رونده</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>ابتدا چندگزینه‌ای برای یادگیری، سپس نوشتن برای تسلط بر همهٔ واژه‌ها</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>یادگیری پیش‌رونده معکوس</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>ابتدا چندگزینه‌ای برای یادگیری، سپس نوشتن برای تسلط بر همهٔ راهنماها</translation>
    </message>
    <message>
        <location line="+36"/>
        <location line="+82"/>
        <source>✓ Done</source>
        <translation>✓ انجام شد</translation>
    </message>
    <message>
        <location line="-82"/>
        <source>← Reset</source>
        <translation>← بازنشانی</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Completed — swipe left to reset</source>
        <translation>تکمیل شد — برای بازنشانی به چپ بکشید</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>%1 left</source>
        <translation>%1 مانده</translation>
    </message>
    <message>
        <location line="+51"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ سخت‌گیری املا</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>سخت‌گیرانه</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>معمولی</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>آسان‌گیرانه</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>لغو</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>مرور عبارت‌ها</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  توقف</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  گوش دادن</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>شروع آزمون</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>هنوز واژه‌ای نیست</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>راهنما / ترجمه را تایپ کنید…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>عبارت را تایپ کنید…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>درست: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ علامت‌گذاری به‌عنوان درست (اشتباه تایپی)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>ارسال</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ علامت‌گذاری به‌عنوان درست (اشتباه کلیک)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>درست: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>مشاهدهٔ نتایج</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>بعدی ←</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>شماره سؤال %1</translation>
    </message>
</context>
</TS>
