<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="vi">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Giới thiệu</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Trình luyện từ vựng để ghi nhớ các bộ từ.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Trình luyện từ vựng và ngữ pháp.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Giấy phép mã nguồn mở</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Ứng dụng này sử dụng Qt theo Giấy phép Công cộng Hạn chế GNU (GNU LGPL) phiên bản 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Thông báo Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Thông báo Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Mã nguồn Qt</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Trang web dự án Qt</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Do AI tạo — có thể có sai sót</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Báo cáo</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Cảm ơn bạn — báo cáo của bạn đã được gửi và sẽ được xem xét.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Báo cáo nội dung AI</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Nội dung được tạo này có vấn đề gì?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Nội dung tình dục hoặc khiêu gợi</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Lời lẽ tục tĩu hoặc xúc phạm</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Nội dung thù ghét hoặc quấy rối</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Nội dung bạo lực hoặc nguy hiểm</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Thông tin sai hoặc gây hiểu lầm</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Lý do khác</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Chi tiết (không bắt buộc)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Đang gửi…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Đóng</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Hủy</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Gửi báo cáo</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Chụp ảnh</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Hủy</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>sắp ra mắt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>sau %1 ngày %2 giờ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>sau %1 giờ %2 phút</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>sau %1 phút</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Chọn hình ảnh</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Chọn âm thanh</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Nhập bộ từ</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Ngôn ngữ của từ</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Ngôn ngữ gợi ý</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+339"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Hủy</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ Trình tạo bộ từ bằng AI</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Được hỗ trợ bởi Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Chủ đề</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Mô tả bộ từ bạn muốn — ví dụ: “các vật dụng nhà bếp thường thấy ở một gia đình Pháp” hoặc “các cụm từ đi công tác dự hội nghị”…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Còn lại %1/%2 lượt tạo trong tháng này — đặt lại vào %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI có thể mắc lỗi. Chỉ nội dung phù hợp với mọi lứa tuổi mới được tạo — hãy dùng 🚩 Báo cáo để đánh dấu bất cứ điều gì không phù hợp.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Ngôn ngữ của từ</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Ngôn ngữ gợi ý</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Số lượng từ</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Đang hỏi Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Hủy yêu cầu</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Tạo</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Bộ từ mới</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Chỉnh sửa bộ từ</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Nhập</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Tiêu đề bộ từ…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Tự động tải hình ảnh</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Từ</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>đã chọn</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Từ / Thuật ngữ</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Chưa chọn</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Nhập từ...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Gợi ý / Nghĩa</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Gợi ý, định nghĩa...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Ví dụ sử dụng</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Câu ví dụ sử dụng từ này...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Đổi hình ảnh</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Thêm hình ảnh</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Tải về</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Máy ảnh</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Thêm âm thanh</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Dừng</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Phát</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ Đọc</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Dừng</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Ghi âm</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Thêm từ</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Xóa</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Lưu</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Cần có tiêu đề</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>sắp tới</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>trong %1n %2g</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>trong %1g %2p</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>trong %1p</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Chọn hình ảnh</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Chọn âm thanh</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Bộ quy tắc mới</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Chỉnh sửa bộ quy tắc</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Nhập</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Nhập bộ quy tắc</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ Trình tạo bộ quy tắc AI</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Được hỗ trợ bởi Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Còn lại %1 trong %2 lượt tạo tháng này — đặt lại %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Quy tắc/chủ đề cần giải thích</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Mô tả quy tắc bạn muốn — vd. &quot;hiện tại đơn so với hiện tại tiếp diễn&quot; hoặc &quot;câu điều kiện loại ba&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Số câu hỏi mỗi loại</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Điền vào chỗ trống</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Trắc nghiệm</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Lựa chọn thả xuống</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Kéo và thả</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Đang hỏi Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Hủy yêu cầu</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Hủy</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI có thể mắc lỗi. Chỉ nội dung phù hợp với mọi lứa tuổi mới được tạo — hãy dùng 🚩 Báo cáo để đánh dấu bất cứ điều gì không phù hợp.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Tạo</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Nhập tiêu đề…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Giải thích lý thuyết</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Ẩn trong khi kiểm tra cho đến khi người học mắc lỗi — luôn có thể đọc được ở chế độ xem trước.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Sử dụng ▲▼ để sắp xếp lại một khối. Kéo góc // của ảnh để thay đổi kích thước.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Giải thích quy tắc mà bộ này luyện tập…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Đoạn âm thanh</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Văn bản</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Ảnh</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Âm thanh</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Câu hỏi</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>đã chọn</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Điền vào chỗ trống</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Trắc nghiệm</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Lựa chọn thả xuống</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Kéo và thả</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Sử dụng ___ (ba dấu gạch dưới) cho mỗi chỗ trống mà người học điền vào.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>vd. Cô ấy làm gì mỗi ngày?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>vd. Cô ấy ___ đến trường mỗi ngày.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Câu trả lời</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Một câu trả lời cho mỗi chỗ trống, phân tách bằng dấu phẩy, theo thứ tự. Sử dụng \, cho dấu phẩy theo nghĩa đen.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>vd. đi</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Tùy chọn</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Phân tách các tùy chọn cho một chỗ trống bằng dấu phẩy; phân tách các chỗ trống bằng dấu hai chấm kép (::). Một dấu : đơn lẻ an toàn như hiện tại; sử dụng \, cho dấu phẩy theo nghĩa đen, \:: cho :: theo nghĩa đen, và ___ cho một tùy chọn cố ý để trống. Vd. cho hai chỗ trống: đi, đi, đang đi::mỗi, một số, hầu hết.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Các ô có thể kéo được, phân tách bằng dấu phẩy — bao gồm các câu trả lời đúng, cộng với các mồi nhử tùy chọn mà người học có thể bị đánh lừa. Sử dụng \, cho dấu phẩy theo nghĩa đen, và ___ cho một ô trống (cho chỗ trống nên đúng là để trống). Điền vào các chỗ trống bên dưới sau khi những điều này được thiết lập.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>vd. đi, đi, đang đi::mỗi, một số, hầu hết</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>vd. đi, đi, đang đi, đã đi</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Câu trả lời đúng cho mỗi chỗ trống</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Chạm vào lựa chọn đúng trong mỗi ô bên dưới.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Chọn một câu trả lời đúng cho mỗi chỗ trống.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Chỗ trống %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Điền vào các chỗ trống</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Kéo một ô vào chỗ trống bên dưới, hoặc chạm vào một ô rồi chạm vào chỗ trống để đặt nó.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Điền vào mỗi chỗ trống bằng một ô.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Các tùy chọn phân tách bằng dấu phẩy — chạm vào câu trả lời đúng bên dưới. Sử dụng \, cho dấu phẩy theo nghĩa đen.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Các tùy chọn phân tách bằng dấu phẩy — chạm vào tất cả các câu trả lời đúng bên dưới. Sử dụng \, cho dấu phẩy theo nghĩa đen.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>vd. đi, đi, đang đi, đã đi</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Chỉ một câu trả lời đúng</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Câu trả lời đúng</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>(Các) câu trả lời đúng</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Chọn câu trả lời đúng.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Chọn ít nhất một câu trả lời đúng.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Thêm câu hỏi</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Xóa</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Lưu</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Cần có tiêu đề</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Giải thích ngữ pháp</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Không thể tải câu hỏi %1: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Chỉ tạo được %1 trong số %2 câu hỏi yêu cầu — hãy thử chủ đề rộng hơn, hoặc giảm số lượng ở trên.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Ngôn ngữ giải thích</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Ngôn ngữ giải thích</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Ngôn ngữ chủ đề</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Ngôn ngữ chủ đề</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Không thể tạo nội dung cho chủ đề này. AI chỉ tạo nội dung phù hợp với mọi lứa tuổi — không hỗ trợ các chủ đề tình dục, tục tĩu hoặc xúc phạm. Vui lòng thử chủ đề khác.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Bạn đã dùng hết lượt tạo bằng AI của tháng này. Hãy thử lại vào tháng sau.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Hôm nay có quá nhiều báo cáo — vui lòng thử lại vào ngày mai.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Dịch vụ AI hiện đang bận — vui lòng thử lại sau giây lát.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Hãy nhập chủ đề trước.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Chủ đề quá dài (tối đa %1 ký tự).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Hãy đặt ít nhất một loại câu hỏi lớn hơn 0.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Phiên của bạn đã hết hạn — vui lòng đăng nhập lại.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Không thể kết nối tới máy chủ. Hãy kiểm tra kết nối internet và thử lại.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Đã xảy ra lỗi. Vui lòng thử lại.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Chưa đăng nhập.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Chạm để lật</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Chạm để lật lại</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>BIẾT</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>BỎ QUA</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Không biết</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Biết</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Chưa chọn</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Không thể tải văn bản giấy phép.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Đăng nhập để tiếp tục</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Đang mở trình duyệt…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Đăng nhập bằng Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Đã tồn tại thư viện hoặc bộ từ với tên này.</translation>
    </message>
    <message>
        <location line="+317"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Đã tồn tại bộ từ với tên này.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Đã tồn tại bộ quy tắc với tên này.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+38"/>
        <source>Results</source>
        <translation>Kết quả</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>Well</source>
        <translation>Làm</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>done</source>
        <translation>tốt lắm</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>trên %1</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Làm rất tốt! Tiếp tục phát huy!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Cố gắng tốt! Hãy tiếp tục luyện tập.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Đừng bỏ cuộc – luyện tập tạo nên hoàn hảo!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Phiên này</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Không biết</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Biết</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Practice again</source>
        <translation>Luyện tập lại</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Find another set</source>
        <translation>Tìm bộ khác</translation>
    </message>
    <message>
        <source>Practice Again</source>
        <translation type="vanished">Luyện tập lại</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Đặt lại tiến trình kiểm tra?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Điều này sẽ xóa tiến trình của bạn trên bộ quy tắc này và bắt đầu một phiên mới.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 câu hỏi</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Đã hoàn thành: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Đang tiến hành: %1 / %2</translation>
    </message>
    <message>
        <source>← Reset</source>
        <translation type="vanished">← Đặt lại</translation>
    </message>
    <message>
        <location line="+185"/>
        <source>Reset to practise again</source>
        <translation>Đặt lại để luyện tập lại</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Reset</source>
        <translation>Đặt lại</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Giải thích quy tắc</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Không có giải thích nào được thêm vào cho bộ này.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Đoạn âm thanh</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Độ nghiêm ngặt chính tả</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Nghiêm ngặt</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Bình thường</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Khoan dung</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Bắt đầu kiểm tra</translation>
    </message>
    <message>
        <location line="-316"/>
        <source>Test is completed</source>
        <translation>Bài kiểm tra đã hoàn thành</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Câu hỏi tiếp theo: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Đúng: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Quy tắc</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Giải thích quy tắc</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Đoạn âm thanh</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Hủy</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Xem quy tắc</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Xoay bánh xe để chọn từ cho mỗi chỗ trống.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Chỗ trống %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Kéo một ô vào chỗ trống, hoặc chạm vào một ô rồi chạm vào chỗ trống để đặt nó.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Chọn câu trả lời đúng.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Chọn tất cả những gì áp dụng.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Đúng: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Gửi</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Đúng: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Xem kết quả</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Tiếp theo →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Câu hỏi số %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Ghi đè bộ từ?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Hợp nhất thư viện?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Bộ từ có tên “%1” đã tồn tại ở đây. Ghi đè bằng bộ từ vừa di chuyển?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Thư viện có tên “%1” đã tồn tại ở đây. Hợp nhất nội dung của nó vào đây?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Bộ từ có tên “%1” đã tồn tại trong %2. Ghi đè bằng phiên bản đang hợp nhất?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>thư viện đích</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Xuất dưới dạng .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Thư viện mới</translation>
    </message>
    <message>
        <location line="+31"/>
        <source>Library name:</source>
        <translation>Tên thư viện:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>ví dụ: Du lịch, Công việc, Trường học…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Đã tồn tại thư viện hoặc bộ từ với tên này.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+99"/>
        <source>A library with this name already exists here.</source>
        <translation>Đã tồn tại thư viện với tên này.</translation>
    </message>
    <message>
        <location line="-62"/>
        <source>Create</source>
        <translation>Tạo</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Rename Library</source>
        <translation>Đổi tên thư viện</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Tên mới:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Đổi tên</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Bộ từ của bạn</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Thư viện</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Di chuyển ra khỏi</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Thả để di chuyển vào trong</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>từ</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>câu hỏi</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Xóa thư viện</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Chỉnh sửa</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Xóa</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Chia sẻ tệp .ppset</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Xuất .ppset (lưu vào ổ đĩa)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Chưa có gì ở đây.
Chạm + Tạo để thêm bộ từ hoặc thư viện.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Bộ từ</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Bộ quy tắc</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Tạo</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Ngôn ngữ giao diện</translation>
    </message>
    <message>
        <location line="-710"/>
        <location line="+796"/>
        <source>Cancel</source>
        <translation>Hủy</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Chọn loại bài kiểm tra</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Thẻ ghi nhớ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Lật để xem — vuốt sang phải nếu bạn biết</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Viết từ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Xem gợi ý — nhập cụm từ</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Viết gợi ý</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Xem từ — nhập bản dịch của nó</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Chọn từ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Xem gợi ý — chọn trong 4 phương án</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Chọn gợi ý</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Xem từ — chọn trong 4 phương án</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Học tăng dần</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Trắc nghiệm để học, sau đó viết để thành thạo mọi từ</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Học tăng dần đảo ngược</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Trắc nghiệm để học, sau đó viết để thành thạo mọi gợi ý</translation>
    </message>
    <message>
        <location line="+36"/>
        <location line="+82"/>
        <source>✓ Done</source>
        <translation>✓ Xong</translation>
    </message>
    <message>
        <location line="-82"/>
        <source>← Reset</source>
        <translation>← Đặt lại</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Completed — swipe left to reset</source>
        <translation>Đã hoàn thành — vuốt sang trái để đặt lại</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>%1 left</source>
        <translation>Còn %1</translation>
    </message>
    <message>
        <location line="+51"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Độ nghiêm ngặt chính tả</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Nghiêm ngặt</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Bình thường</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Khoan dung</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Hủy</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Ôn tập cụm từ</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Dừng</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Nghe</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Bắt đầu bài kiểm tra</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Chưa có từ nào</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Nhập gợi ý / bản dịch…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Nhập cụm từ…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Đúng: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Đánh dấu là đúng (tôi gõ nhầm)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Gửi</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Đánh dấu là đúng (tôi bấm nhầm)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Đúng: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Xem kết quả</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Tiếp theo →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Câu hỏi số %1</translation>
    </message>
</context>
</TS>
