<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="he">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>אודות</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">מאמן אוצר מילים לשינון ערכות מילים.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>מאמן לאוצר מילים ודקדוק.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>רישיונות קוד פתוח</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>אפליקציה זו משתמשת ב-Qt תחת רישיון GNU Lesser General Public License גרסה 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>הודעת Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>הודעת Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>קוד המקור של Qt</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>אתר האינטרנט של פרויקט Qt</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ נוצר על ידי בינה מלאכותית — עשוי להכיל טעויות</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 דיווח</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>תודה — הדיווח שלכם נשלח וייבדק.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 דיווח על תוכן בינה מלאכותית</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>מה הבעיה בתוכן שנוצר?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>תוכן מיני או מרמז</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>ניבולי פה או שפה פוגענית</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>תוכן שנאה או הטרדה</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>תוכן אלים או מסוכן</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>מידע שגוי או מטעה</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>משהו אחר</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>פרטים (לא חובה)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>שולח…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>סגירה</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>ביטול</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>שליחת דיווח</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>צלם תמונה</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>ביטול</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>בקרוב</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>בעוד %1 ימים ו-%2 שעות</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>בעוד %1 שעות ו-%2 דקות</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>בעוד %1 דקות</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>בחר תמונה</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>בחר קובץ שמע</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>ייבוא ערכת מילים</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>שפת המילה</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>שפת הרמז</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+339"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>ביטול</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ מחולל ערכות מילים מבוסס בינה מלאכותית</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>מופעל על ידי Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 נושא</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>תארו את הערכה שתרצו — למשל “כלי מטבח שאפשר למצוא בבית צרפתי” או “ביטויים לנסיעת עסקים לכנס”…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>נותרו %1 מתוך %2 יצירות החודש — איפוס ב-%3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>בינה מלאכותית עלולה לטעות. נוצר רק תוכן המתאים לכל הגילים — השתמשו ב־🚩 דיווח כדי לסמן כל דבר לא הולם.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>שפת המילה</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>שפת הרמז</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 מספר מילים</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>פונה אל Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>ביטול הבקשה</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ צור</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ בינה מלאכותית</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>ערכת מילים חדשה</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>עריכת ערכת מילים</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>ייבוא</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>כותרת הערכה…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>הבאת תמונות אוטומטית</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>מילה</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>נבחר</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>מילה / מונח</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>לא נבחר</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>הזן מילה...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>רמז / משמעות</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>רמז, הגדרה...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>דוגמת שימוש</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>משפט לדוגמה המשתמש במילה...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>החלף תמונה</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>הוסף תמונה</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>הבא</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>מצלמה</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>הוסף קובץ שמע</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ עצור</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ נגן</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ הקראה</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ עצור</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● הקלטה</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ הוסף מילה</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>הסר</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>שמור</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>נדרשת כותרת</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>בקרוב</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>בעוד %1י %2ש</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>בעוד %1ש %2ד</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>בעוד %1ד</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>בחירת תמונה</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>בחירת אודיו</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ בינה מלאכותית</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>ערכת כללים חדשה</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>עריכת ערכת כללים</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>ייבוא</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>ייבוא ערכת כללים</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ מחולל ערכות כללים מבוסס בינה מלאכותית</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>מופעל באמצעות Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>נותרו %1 מתוך %2 יצירות החודש — איפוס %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 כלל/נושא להסבר</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>תארו את הכלל הרצוי — למשל &quot;הווה פשוט מול הווה מתמשך&quot; או &quot;משפטי תנאי שלישי&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 שאלות לכל סוג</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 השלמת החסר</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 רב־ברירה</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 בחירה נגללת</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 גררו ושחררו</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>שואלים את Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>ביטול הבקשה</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>ביטול</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>בינה מלאכותית עלולה לטעות. נוצר רק תוכן המתאים לכל הגילים — השתמשו ב־🚩 דיווח כדי לסמן כל דבר לא הולם.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ יצירה</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>הזינו כותרת…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>הסבר תאורטי</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>מוסתר במהלך המבחן עד שהלומד טועה — תמיד קריא בתצוגה מקדימה.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>השתמשו ב-▲▼ כדי לסדר מחדש בלוק. גררו את הפינה // של תמונה כדי לשנות את גודלה.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>הסבירו את הכלל שערכה זו מתרגלת…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>קטע שמע</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ טקסט</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ תמונה</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ שמע</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>שאלה</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>נבחר</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>השלמת החסר</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>רב־ברירה</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>בחירה נגללת</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>גררו ושחררו</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>השתמשו ב-___ (שלושה קווים תחתונים) עבור כל חסר שהלומד ממלא.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>למשל מה היא עושה בכל יום?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>למשל היא הולכת ___ לבית הספר בכל יום.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>תשובות</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>תשובה אחת לכל חסר, מופרדות בפסיקים, לפי הסדר. השתמשו ב-\, לפסיק מילולי.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>למשל הולכת</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>אפשרויות</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>הפרידו אפשרויות עבור חסר אחד בפסיקים; הפרידו בין חסרים בנקודתיים כפולות (::). נקודתיים בודדות : בטוחות כפי שהן; השתמשו ב-\, לפסיק מילולי, ב-\:: ל-:: מילולי, וב-___ לבחירה ריקה בכוונה. למשל עבור שני חסרים: הולכת, ללכת, הולכות::כל, כמה, רוב.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>אריחים לגרירה מופרדים בפסיקים — כללו את התשובות הנכונות, וכן מסיחים אופציונליים שבהם ניתן להטעות את הלומד. השתמשו ב-\, לפסיק מילולי, וב-___ לאריח ריק (עבור חסר שצריך להישאר ריק כראוי). מלאו את החסרים למטה לאחר שנקבעו אלה.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>למשל הולכת, ללכת, הולכות::כל, כמה, רוב</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>למשל הולכת, ללכת, הולכות, הלכה</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>תשובה נכונה לכל חסר</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>הקישו על הבחירה הנכונה בכל תיבה למטה.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>בחרו תשובה נכונה לכל חסר.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>חסר %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>מלאו את החסרים</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>גררו אריח לחסר למטה, או הקישו על אריח ולאחר מכן על חסר כדי למקם אותו.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>מלאו כל חסר באריח.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>אפשרויות מופרדות בפסיקים — הקישו על התשובה הנכונה למטה. השתמשו ב-\, לפסיק מילולי.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>אפשרויות מופרדות בפסיקים — הקישו על כל התשובות הנכונות למטה. השתמשו ב-\, לפסיק מילולי.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>למשל הולכת, ללכת, הולכות, הלכה</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>תשובה נכונה אחת בלבד</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>תשובה נכונה</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>תשובה(ות) נכונה(ות)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>בחרו את התשובה הנכונה.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>בחרו לפחות תשובה נכונה אחת.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ הוספת שאלה</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>הסרה</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>שמירה</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>נדרשת כותרת</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 הסבר דקדוק</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>לא ניתן היה לטעון שאלת %1: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>נוצרו רק %1 מתוך %2 שאלות מבוקשות — נסה נושא רחב יותר, או הקטן את המספרים למעלה.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>שפת ההסבר</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>שפת ההסבר</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>שפת הנושא</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>שפת הנושא</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>לא ניתן ליצור את הנושא הזה. הבינה המלאכותית יוצרת רק תוכן המתאים לכל הגילים — נושאים מיניים, גסים או פוגעניים אינם נתמכים. נסו נושא אחר.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>ניצלתם את כל יצירות הבינה המלאכותית לחודש זה. נסו שוב בחודש הבא.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>יותר מדי דיווחים היום — נסו שוב מחר.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>שירות הבינה המלאכותית עמוס כרגע — נסו שוב בעוד רגע.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>הזינו נושא תחילה.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>הנושא ארוך מדי (עד %1 תווים).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>הגדירו לפחות סוג שאלה אחד מעל אפס.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>תוקף ההפעלה פג — התחברו שוב.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>לא ניתן להתחבר לשרת. בדקו את החיבור לאינטרנט ונסו שוב.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>משהו השתבש. נסו שוב.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>לא מחוברים.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>הקש כדי להפוך</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>הקש כדי להפוך בחזרה</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>אני יודע/ת</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>דלג</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  אני לא יודע/ת</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  אני יודע/ת</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>לא נבחר</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>לא ניתן לטעון את טקסט הרישיון.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>היכנס כדי להמשיך</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>פותח דפדפן…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>היכנס עם Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">ספרייה או ערכה בשם זה כבר קיימת כאן.</translation>
    </message>
    <message>
        <location line="+317"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>ערכת מילים בשם זה כבר קיימת כאן.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>ערכת כללים בשם זה כבר קיימת כאן.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+38"/>
        <source>Results</source>
        <translation>תוצאות</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>Well</source>
        <translation>עבודה</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>done</source>
        <translation>נהדרת</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>מתוך %1</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>עבודה מצוינת! המשך כך!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>מאמץ יפה! המשך להתאמן.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>אל תוותר – התרגול עושה שלמות!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>הפעלה זו</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>לא יודע/ת</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>יודע/ת</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Practice again</source>
        <translation>לתרגל שוב</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Find another set</source>
        <translation>למצוא סט אחר</translation>
    </message>
    <message>
        <source>Practice Again</source>
        <translation type="vanished">תרגל שוב</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>לאפס את התקדמות המבחן?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>פעולה זו תמחק את ההתקדמות שלך בערכת כללים זו ותתחיל הפעלה חדשה.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 שאלות</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">הושלם: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">בתהליך: %1 / %2</translation>
    </message>
    <message>
        <source>← Reset</source>
        <translation type="vanished">← איפוס</translation>
    </message>
    <message>
        <location line="+185"/>
        <source>Reset to practise again</source>
        <translation>לאפס כדי לתרגל שוב</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Reset</source>
        <translation>איפוס</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>הסבר הכלל</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>לא נוסף הסבר עבור ערכה זו.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>קטע שמע</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ חומרת איות</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>מחמיר</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>רגיל</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>סלחני</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>התחלת המבחן</translation>
    </message>
    <message>
        <location line="-316"/>
        <source>Test is completed</source>
        <translation>המבחן הושלם</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>השאלה הבאה: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>נכון: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>כלל</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 הסבר הכלל</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>קטע שמע</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>ביטול</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 הצגת הכלל</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>סובבו את הגלגל כדי לבחור את המילה של כל חסר.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>חסר %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>גררו אריח לחסר, או הקישו על אריח ולאחר מכן על חסר כדי למקם אותו.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>בחרו את התשובה הנכונה.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>בחרו את כל התשובות הרלוונטיות.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>נכון: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>שליחה</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>נכון: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>הצגת תוצאות</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>הבא →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>שאלה מספר %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>האם לשכתב את ערכת המילים?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>למזג ספריות?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>ערכת מילים בשם “%1” כבר קיימת כאן. לשכתב אותה בערכה שהועברה?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>ספרייה בשם “%1” כבר קיימת כאן. למזג את תוכנה אליה?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>ערכת מילים בשם “%1” כבר קיימת ב-%2. לשכתב אותה בגרסה הממוזגת?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>ספריית היעד</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>ייצוא כ-‎.ppset‎</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>ספרייה חדשה</translation>
    </message>
    <message>
        <location line="+31"/>
        <source>Library name:</source>
        <translation>שם הספרייה:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>למשל: נסיעות, עבודה, בית ספר…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">ספרייה או ערכה בשם זה כבר קיימת כאן.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+99"/>
        <source>A library with this name already exists here.</source>
        <translation>ספרייה בשם זה כבר קיימת כאן.</translation>
    </message>
    <message>
        <location line="-62"/>
        <source>Create</source>
        <translation>צור</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Rename Library</source>
        <translation>שינוי שם הספרייה</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>שם חדש:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>שנה שם</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>ערכות המילים שלך</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>ספרייה</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>הוצא מתוך</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>שחרר כדי להעביר פנימה</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>מילים</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>שאלות</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>מחק ספרייה</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>ערוך</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>מחק</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>שתף קובץ ‎.ppset‎</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>ייצוא ‎.ppset‎ (שמור לדיסק)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>אין כאן כלום עדיין.
הקש על + צור כדי להוסיף ערכת מילים או ספרייה.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>ערכת מילים</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>ערכת כללים</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ צור</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>שפת הממשק</translation>
    </message>
    <message>
        <location line="-710"/>
        <location line="+796"/>
        <source>Cancel</source>
        <translation>ביטול</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>בחר סוג מבחן</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>כרטיסיות</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>הפוך כדי לחשוף — החלק ימינה אם אתה יודע</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>כתוב את המילה</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>ראה את הרמז — הקלד את הביטוי</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>כתוב את הרמז</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>ראה את המילה — הקלד את התרגום שלה</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>בחר את המילה</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>ראה את הרמז — בחר מתוך 4 אפשרויות</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>בחר את הרמז</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>ראה את המילה — בחר מתוך 4 אפשרויות</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>למידה מתקדמת</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>בחירה מרובה ללמידה, ואז כתיבה לשליטה בכל המילים</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>למידה מתקדמת הפוכה</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>בחירה מרובה ללמידה, ואז כתיבה לשליטה בכל הרמזים</translation>
    </message>
    <message>
        <location line="+36"/>
        <location line="+82"/>
        <source>✓ Done</source>
        <translation>✓ בוצע</translation>
    </message>
    <message>
        <location line="-82"/>
        <source>← Reset</source>
        <translation>← איפוס</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Completed — swipe left to reset</source>
        <translation>הושלם — החליקו שמאלה כדי לאפס</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>%1 left</source>
        <translation>נותרו %1</translation>
    </message>
    <message>
        <location line="+51"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ חומרת איות</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>מחמיר</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>רגיל</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>סלחני</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>ביטול</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>סקירת ביטויים</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  עצור</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  האזן</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>התחל מבחן</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>אין עדיין מילים</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>הקלד את הרמז / התרגום…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>הקלד את הביטוי…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>נכון: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ סמן כנכון (הקלדתי בטעות)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>שלח</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ סמן כנכון (לחצתי בטעות)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>נכון: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>הצג תוצאות</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>הבא ←</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>שאלה מספר %1</translation>
    </message>
</context>
</TS>
