<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="az">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Haqqında</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Söz dəstlərini yadda saxlamaq üçün lüğət məşqçisi.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Lüğət və qrammatika məşqçisi.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Açıq mənbə lisenziyaları</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Bu tətbiq Qt-ni GNU Lesser General Public License versiya 3 altında istifadə edir.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Qt bildirişi</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Qt bildirişi</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Qt mənbə kodu</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Qt layihəsinin veb saytı</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Süni intellekt tərəfindən yaradılıb — səhvlər ola bilər</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Şikayət et</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Təşəkkür edirik — şikayətiniz göndərildi və nəzərdən keçiriləcək.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Süni intellekt məzmunundan şikayət et</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Bu yaradılmış məzmunda nə problem var?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Cinsi və ya işarəli məzmun</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Söyüş və ya təhqiredici dil</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Nifrət və ya təqib xarakterli məzmun</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Zorakı və ya təhlükəli məzmun</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Yanlış və ya çaşdırıcı məlumat</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Başqa bir şey</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Təfərrüatlar (istəyə bağlı)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Göndərilir…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Bağla</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Ləğv et</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Şikayəti göndər</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Şəkil çək</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Ləğv et</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>tezliklə</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1g %2s sonra</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1s %2dəq sonra</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1dəq sonra</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Şəkil seç</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Audio seç</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Söz dəstini idxal et</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Sözün dili</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>İpucunun dili</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+326"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Ləğv et</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ Süni intellekt söz dəsti generatoru</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Gemini ilə işləyir</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Mövzu</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>İstədiyiniz dəsti təsvir edin — məs. «fransız evində tapıla biləcək mətbəx əşyaları» və ya «konfrans üçün iş səfəri ifadələri»…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Bu ay %2-dən %1 yaratma qalıb — %3 tarixində sıfırlanacaq</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>Süni intellekt səhv edə bilər. Yalnız bütün yaşlar üçün uyğun məzmun yaradılır — uyğunsuz hər şeyi bildirmək üçün 🚩 Şikayət et düyməsindən istifadə edin.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Sözün dili</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>İpucunun dili</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Sözlərin sayı</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Gemini-dən soruşulur…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Sorğunu ləğv et</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Yarat</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ Süni intellekt</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Yeni söz dəsti</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Söz dəstini redaktə et</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>İdxal et</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Dəstin başlığı…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Şəkilləri avtomatik gətir</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Söz</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>seçilib</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Söz / Termin</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Seçilməyib</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Sözü daxil edin...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>İpucu / məna</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>İpucu, tərif...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>İstifadə nümunəsi</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Sözü istifadə edən nümunə cümlə...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Şəkli dəyiş</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Şəkil əlavə et</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Gətir</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Kamera</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Audio əlavə et</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Dayandır</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Oxut</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ Səsləndir</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Dayandır</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Yaz</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Söz əlavə et</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Sil</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Yadda saxla</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Başlıq tələb olunur</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>tezliklə</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1g %2s ərzində</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1s %2d ərzində</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1d ərzində</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Şəkil seçin</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Audio seçin</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Yeni Qayda Dəsti</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Qayda Dəstini Redaktə Et</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>İdxal et</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Qayda Dəstini İdxal Et</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ AI Qayda Dəsti Generatoru</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Gemini tərəfindən dəstəklənir</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Bu ay %2 yaratmadan %1-i qalıb — %3 tarixində sıfırlanır</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 İzah ediləcək qayda/mövzu</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>İstədiyiniz qaydanı təsvir edin — məs. &quot;present simple ilə present continuous&quot; və ya &quot;üçüncü şərt cümlələri&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Növ üzrə sual sayı</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Boşluğu Doldur</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Çoxseçimli</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Açılan Siyahı</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Sürüklə və Burax</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Gemini soruşulur…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Sorğunu ləğv et</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Ləğv et</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>Süni intellekt səhv edə bilər. Yalnız bütün yaşlar üçün uyğun məzmun yaradılır — uyğunsuz hər şeyi bildirmək üçün 🚩 Şikayət et düyməsindən istifadə edin.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Yarat</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Başlıq daxil edin…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Qayda İzahı</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Test zamanı tələbə səhv edənə qədər gizlidir — önizləmədə həmişə oxuna bilər.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Bloku yenidən sıralamaq üçün ▲▼ istifadə edin. Şəklin ölçüsünü dəyişmək üçün // küncündən sürükləyin.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Bu dəstin öyrətdiyi qaydanı izah edin…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Audio klip</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Mətn</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Şəkil</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Audio</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Sual</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>seçilib</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Boşluğu Doldur</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Çoxseçimli</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Açılan Siyahı</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Sürüklə və Burax</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Tələbənin dolduracağı hər boşluq üçün ___ (üç alt xətt) istifadə edin.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>məs. O, hər gün nə edir?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>məs. O, hər gün məktəbə ___.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Cavablar</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Hər boşluq üçün bir cavab, vergüllə ayrılmış, ardıcıllıqla. Hərfi vergül üçün \, istifadə edin.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>məs. gedir</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Seçimlər</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Bir boşluq üçün seçimləri vergüllə ayırın; boşluqları qoşa iki nöqtə (::) ilə ayırın. Tək : olduğu kimi təhlükəsizdir; hərfi vergül üçün \,, hərfi :: üçün \::, və qəsdən boş seçim üçün ___ istifadə edin. İki boşluq üçün məsələn: gedir, get, gedən::hər, bəzi, əksər.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Vergüllə ayrılmış sürüklənə bilən lövhəciklər — düzgün cavabları, üstəlik tələbəni çaşdıra biləcək əlavə yanlış variantları daxil edin. Hərfi vergül üçün \,, boş lövhəcik üçün isə ___ istifadə edin (boş qalmalı olan boşluq üçün). Bunlar müəyyən edildikdən sonra aşağıdakı boşluqları doldurun.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>məs. gedir, get, gedən::hər, bəzi, əksər</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>məs. gedir, get, gedən, getmiş</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Hər boşluq üçün düzgün cavab</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Aşağıdakı hər qutuda düzgün seçimə toxunun.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Hər boşluq üçün düzgün cavab seçin.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Boşluq %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Boşluqları doldurun</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Aşağıdakı boşluğa bir lövhəcik sürükləyin, yaxud lövhəciyə, sonra boşluğa toxunaraq yerləşdirin.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Hər boşluğu bir lövhəciklə doldurun.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Vergüllə ayrılmış seçimlər — aşağıda düzgün cavaba toxunun. Hərfi vergül üçün \, istifadə edin.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Vergüllə ayrılmış seçimlər — aşağıda bütün düzgün cavablara toxunun. Hərfi vergül üçün \, istifadə edin.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>məs. gedir, get, gedən, getmiş</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Yalnız bir düzgün cavab</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Düzgün cavab</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Düzgün cavab(lar)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Düzgün cavabı seçin.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Ən azı bir düzgün cavab seçin.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Sual əlavə et</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Sil</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Yadda saxla</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Başlıq tələb olunur</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Qrammatikanı izah et</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>%1 sualı yüklənə bilmədi: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Yalnız %2 sorğudan %1-i yaradıldı — daha geniş mövzu sınayın və ya yuxarıdakı sayları azaldın.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>İzah dili</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>İzah dili</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Mövzu dili</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Mövzu dili</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Bu mövzu yaradıla bilməz. Süni intellekt yalnız bütün yaşlar üçün uyğun məzmun yaradır — cinsi, söyüşlü və ya təhqiredici mövzular dəstəklənmir. Zəhmət olmasa, başqa mövzu sınayın.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Bu ay üçün bütün süni intellekt generasiyalarınızı istifadə etmisiniz. Gələn ay yenidən cəhd edin.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Bu gün çox şikayət göndərilib — zəhmət olmasa, sabah yenidən cəhd edin.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Süni intellekt xidməti hazırda məşğuldur — bir az sonra yenidən cəhd edin.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Əvvəlcə mövzu daxil edin.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Mövzu çox uzundur (maks. %1 simvol).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Ən azı bir sual növünü sıfırdan yuxarı təyin edin.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Sessiyanızın vaxtı bitib — zəhmət olmasa, yenidən daxil olun.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Serverə qoşulmaq mümkün olmadı. İnternet bağlantınızı yoxlayın və yenidən cəhd edin.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Xəta baş verdi. Zəhmət olmasa, yenidən cəhd edin.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Daxil olunmayıb.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Çevirmək üçün toxunun</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Geri çevirmək üçün toxunun</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>BİLİRƏM</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>KEÇ</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Bilmirəm</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Bilirəm</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Seçilməyib</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Lisenziya mətni yüklənə bilmədi.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Davam etmək üçün daxil olun</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Brauzer açılır…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Google ilə daxil olun</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Bu adda kitabxana və ya dəst artıq buradadır.</translation>
    </message>
    <message>
        <location line="+309"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Bu adda söz dəsti artıq buradadır.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Bu adda qayda dəsti artıq buradadır.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+37"/>
        <source>Results</source>
        <translation>Nəticələr</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Well</source>
        <translation>Əla</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>done</source>
        <translation>iş</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>%1-dən</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Əla iş! Belə davam et!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Yaxşı cəhd! Məşq etməyə davam et.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Təslim olma – məşq mükəmməllik yaradır!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Bu sessiya</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Bilmirəm</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Bilirəm</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Practice Again</source>
        <translation>Yenidən məşq et</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Test irəliləyişi sıfırlansın?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Bu, bu qayda dəstindəki irəliləyişinizi təmizləyəcək və yeni sessiya başlayacaq.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 sual</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Tamamlandı: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Davam edir: %1 / %2</translation>
    </message>
    <message>
        <location line="+67"/>
        <source>← Reset</source>
        <translation>← Sıfırla</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Qayda İzahı</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Bu dəst üçün izah əlavə edilməyib.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Audio klip</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Yazılış sərtliyi</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Sərt</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Yumşaq</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Testə Başla</translation>
    </message>
    <message>
        <location line="-198"/>
        <source>Test is completed</source>
        <translation>Test tamamlandı</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Növbəti sual: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Düzgün: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Qayda</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Qayda İzahı</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Audio klip</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Ləğv et</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Qaydaya bax</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Hər boşluğun sözünü seçmək üçün çarxı fırladın.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Boşluq %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>boş</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Bir lövhəciyi boşluğa sürükləyin, yaxud lövhəciyə, sonra boşluğa toxunaraq yerləşdirin.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Düzgün cavabı seçin.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Uyğun olan hər şeyi seçin.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Düzgün: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Göndər</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Düzgün: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Nəticələrə Bax</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Növbəti →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Sual nömrəsi %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Söz dəsti üzərinə yazılsın?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Kitabxanalar birləşdirilsin?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>«%1» adlı söz dəsti artıq buradadır. Köçürülmüş dəstlə üzərinə yazılsın?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>«%1» adlı kitabxana artıq buradadır. Onun məzmunu bununla birləşdirilsin?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>«%1» adlı söz dəsti artıq %2-də mövcuddur. Birləşdirilmiş versiya ilə üzərinə yazılsın?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>təyinat kitabxanası</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>.ppset kimi ixrac et</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Yeni kitabxana</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Library name:</source>
        <translation>Kitabxananın adı:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>məs. Səyahət, İş, Məktəb…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Bu adda kitabxana və ya dəst artıq buradadır.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+74"/>
        <source>A library with this name already exists here.</source>
        <translation>Bu adda kitabxana artıq buradadır.</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Create</source>
        <translation>Yarat</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Rename Library</source>
        <translation>Kitabxananı yenidən adlandır</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Yeni ad:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Yenidən adlandır</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Söz dəstləriniz</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Kitabxana</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Bayıra köçür</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>İçəri köçürmək üçün buraxın</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>söz</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>sual</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Kitabxananı sil</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Redaktə et</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Sil</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>.ppset faylını paylaş</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>.ppset ixrac et (diskə yadda saxla)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Burada hələ heç nə yoxdur.
Söz dəsti və ya kitabxana əlavə etmək üçün + Yarat düyməsinə toxunun.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Söz dəsti</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Qayda Dəsti</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Yarat</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>İnterfeys dili</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Cancel</source>
        <translation>Ləğv et</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Test növünü seçin</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Bilgi kartları</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Açmaq üçün çevirin — bilirsinizsə sağa sürüşdürün</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Sözü yazın</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>İpucuna baxın — ifadəni yazın</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>İpucunu yazın</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Sözə baxın — tərcüməsini yazın</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Sözü seçin</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>İpucuna baxın — 4 variantdan seçin</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>İpucunu seçin</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Sözə baxın — 4 variantdan seçin</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Mütərəqqi öyrənmə</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Öyrənmək üçün əvvəlcə çoxvariantlı, sonra bütün sözlərdə ustalaşmaq üçün yazı</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Tərsinə mütərəqqi öyrənmə</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Öyrənmək üçün əvvəlcə çoxvariantlı, sonra bütün ipuclarında ustalaşmaq üçün yazı</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>✓ Done</source>
        <translation>✓ Tamamlandı</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>← Reset</source>
        <translation>← Sıfırla</translation>
    </message>
    <message>
        <location line="+96"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Yazılış sərtliyi</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Sərt</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Yumşaq</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Ləğv et</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>İfadələrə yenidən baxın</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Dayandır</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Dinlə</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Testə başla</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Hələ söz yoxdur</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>İpucunu / tərcüməni yazın…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>İfadəni yazın…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Düzgün: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Düzgün kimi işarələ (səhv yazdım)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Göndər</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Düzgün kimi işarələ (səhv kliklədim)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Düzgün: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Nəticələrə bax</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Növbəti →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Sual nömrəsi %1</translation>
    </message>
</context>
</TS>
