<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ur">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>بارے میں</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">الفاظ کے سیٹ یاد رکھنے کے لیے ذخیرہ الفاظ ٹرینر۔</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>ذخیرہ الفاظ اور گرامر کے لیے ٹرینر۔</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>اوپن سورس لائسنس</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>یہ ایپلیکیشن GNU Lesser General Public License ورژن 3 کے تحت Qt استعمال کرتی ہے۔</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Qt نوٹس</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Qt نوٹس</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Qt سورس کوڈ</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Qt پراجیکٹ ویب سائٹ</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ اے آئی کا بنایا ہوا — اس میں غلطیاں ہو سکتی ہیں</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 رپورٹ کریں</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>شکریہ — آپ کی رپورٹ بھیج دی گئی ہے اور اس کا جائزہ لیا جائے گا۔</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 اے آئی مواد کی رپورٹ کریں</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>اس بنائے گئے مواد میں کیا خرابی ہے؟</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>جنسی یا فحش اشاروں والا مواد</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>گالی گلوچ یا توہین آمیز زبان</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>نفرت انگیز یا ہراسانی پر مبنی مواد</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>پرتشدد یا خطرناک مواد</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>غلط یا گمراہ کن معلومات</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>کچھ اور</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>تفصیلات (اختیاری)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>بھیجا جا رہا ہے…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>بند کریں</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>منسوخ کریں</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>رپورٹ بھیجیں</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>تصویر لیں</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>منسوخ کریں</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>جلد آ رہا ہے</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1 دن %2 گھنٹے میں</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1 گھنٹے %2 منٹ میں</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1 منٹ میں</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>تصویر منتخب کریں</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>آڈیو منتخب کریں</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>لفظی سیٹ درآمد کریں</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>لفظ کی زبان</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>اشارے کی زبان</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+339"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>منسوخ کریں</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ اے آئی لفظی سیٹ جنریٹر</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Gemini سے چلتا ہے</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 موضوع</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>وہ سیٹ بیان کریں جو آپ چاہتے ہیں — مثلاً «باورچی خانے کی اشیاء جو فرانسیسی گھر میں ملیں گی» یا «کانفرنس کے کاروباری سفر کے فقرے»…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>اس ماہ %2 میں سے %1 تخلیقات باقی ہیں — %3 کو ری سیٹ ہوگا</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>اے آئی غلطی کر سکتا ہے۔ صرف ہر عمر کے لیے موزوں مواد بنایا جاتا ہے — کسی بھی نامناسب چیز کی نشاندہی کے لیے 🚩 رپورٹ کریں استعمال کریں۔</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>لفظ کی زبان</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>اشارے کی زبان</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 الفاظ کی تعداد</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Gemini سے پوچھا جا رہا ہے…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>درخواست منسوخ کریں</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ تخلیق کریں</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ اے آئی</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>نیا لفظی سیٹ</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>لفظی سیٹ میں ترمیم کریں</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>درآمد کریں</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>سیٹ کا عنوان…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>تصاویر خودکار طور پر حاصل کریں</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>لفظ</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>منتخب</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>لفظ / اصطلاح</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>منتخب نہیں</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>لفظ درج کریں...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>اشارہ / معنی</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>اشارہ، تعریف...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>استعمال کی مثال</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>لفظ استعمال کرتے ہوئے مثالی جملہ...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>تصویر تبدیل کریں</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>تصویر شامل کریں</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>حاصل کریں</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>کیمرہ</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>آڈیو شامل کریں</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ روکیں</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ چلائیں</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ بولیں</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ روکیں</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● ریکارڈ</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ لفظ شامل کریں</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>ہٹا دیں</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>محفوظ کریں</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>عنوان درکار ہے</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>جلد ہی</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1د %2گھ میں</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1گھ %2م میں</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1م میں</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>تصویر منتخب کریں</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>آڈیو منتخب کریں</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ اے آئی</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>نیا قوانین کا سیٹ</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>قوانین کا سیٹ ترمیم کریں</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>درآمد کریں</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>قوانین کا سیٹ درآمد کریں</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ اے آئی قوانین سیٹ جنریٹر</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Gemini سے تقویت یافتہ</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>اس مہینے %2 میں سے %1 جنریشنز باقی ہیں — %3 کو ری سیٹ ہوگا</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 وضاحت کے لیے قانون/موضوع</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>وہ قانون بیان کریں جو آپ چاہتے ہیں — مثلاً &quot;present simple بمقابلہ present continuous&quot; یا &quot;تیسری قسم کے مشروط جملے&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 فی قسم سوالات</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 خالی جگہ پُر کریں</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 کثیر انتخابی</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 ڈراپ ڈاؤن انتخاب</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 گھسیٹیں اور چھوڑیں</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Gemini سے پوچھا جا رہا ہے…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>درخواست منسوخ کریں</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>منسوخ کریں</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>اے آئی غلطی کر سکتا ہے۔ صرف ہر عمر کے لیے موزوں مواد بنایا جاتا ہے — کسی بھی نامناسب چیز کی نشاندہی کے لیے 🚩 رپورٹ کریں استعمال کریں۔</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ تخلیق کریں</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>عنوان درج کریں…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>نظریاتی وضاحت</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>ٹیسٹ کے دوران چھپا رہتا ہے جب تک طالب علم غلطی نہ کرے — پیش منظر میں ہمیشہ پڑھنے کے قابل۔</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>بلاک کو دوبارہ ترتیب دینے کے لیے ▲▼ استعمال کریں۔ تصویر کا سائز تبدیل کرنے کے لیے اس کا // کونا گھسیٹیں۔</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>اس سیٹ کے مشق کردہ قانون کی وضاحت کریں…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>آڈیو کلپ</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ متن</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ تصویر</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ آڈیو</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>سوال</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>منتخب کردہ</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>خالی جگہ پُر کریں</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>کثیر انتخابی</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>ڈراپ ڈاؤن انتخاب</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>گھسیٹیں اور چھوڑیں</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>طالب علم کی بھری جانے والی ہر خالی جگہ کے لیے ___ (تین انڈر اسکور) استعمال کریں۔</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>مثلاً وہ ہر روز کیا کرتی ہے؟</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>مثلاً وہ ہر روز اسکول ___ جاتی ہے۔</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>جوابات</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>ہر خالی جگہ کے لیے ایک جواب، کاما سے الگ، ترتیب میں۔ لفظی کاما کے لیے \, استعمال کریں۔</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>مثلاً جاتی ہے</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>اختیارات</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>ایک خالی جگہ کے اختیارات کو کاما سے الگ کریں؛ خالی جگہوں کو دوہرے کولن (::) سے الگ کریں۔ ایک اکیلا : جیسا ہے ویسا ہی محفوظ ہے؛ لفظی کاما کے لیے \,، لفظی :: کے لیے \::، اور جان بوجھ کر خالی اختیار کے لیے ___ استعمال کریں۔ مثلاً دو خالی جگہوں کے لیے: جاتی ہے، جانا، جاتے ہوئے::ہر، کچھ، زیادہ تر۔</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>کاما سے الگ کردہ گھسیٹنے کے قابل ٹائلز — درست جوابات شامل کریں، نیز اختیاری دھوکہ جن سے طالب علم کو الجھایا جا سکتا ہے۔ لفظی کاما کے لیے \, اور خالی ٹائل کے لیے ___ استعمال کریں (اس خالی جگہ کے لیے جو درست طور پر خالی رہنی چاہیے)۔ ان کے سیٹ ہونے کے بعد ذیل کی خالی جگہیں پُر کریں۔</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>مثلاً جاتی ہے، جانا، جاتے ہوئے::ہر، کچھ، زیادہ تر</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>مثلاً جاتی ہے، جانا، جاتے ہوئے، گئی</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>ہر خالی جگہ کے لیے درست جواب</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>ذیل کے ہر باکس میں درست اختیار پر تھپتھپائیں۔</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>ہر خالی جگہ کے لیے ایک درست جواب منتخب کریں۔</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>خالی جگہ %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>خالی جگہیں پُر کریں</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>ایک ٹائل کو ذیل کی خالی جگہ پر گھسیٹیں، یا اسے رکھنے کے لیے ٹائل پر اور پھر خالی جگہ پر تھپتھپائیں۔</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>ہر خالی جگہ کو ٹائل سے پُر کریں۔</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>کاما سے الگ کردہ اختیارات — ذیل کے درست جواب پر تھپتھپائیں۔ لفظی کاما کے لیے \, استعمال کریں۔</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>کاما سے الگ کردہ اختیارات — ذیل کے تمام درست جوابات پر تھپتھپائیں۔ لفظی کاما کے لیے \, استعمال کریں۔</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>مثلاً جاتی ہے، جانا، جاتے ہوئے، گئی</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>صرف ایک درست جواب</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>درست جواب</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>درست جواب(ات)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>درست جواب منتخب کریں۔</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>کم از کم ایک درست جواب منتخب کریں۔</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ سوال شامل کریں</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>ہٹائیں</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>محفوظ کریں</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>عنوان درکار ہے</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 گرامر کی وضاحت کریں</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>%1 سوال لوڈ نہیں ہو سکا: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>درخواست کردہ %2 میں سے صرف %1 سوالات بنائے گئے — وسیع تر موضوع آزمائیں، یا اوپر دیے گئے اعداد کم کریں۔</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>وضاحت کی زبان</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>وضاحت کی زبان</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>موضوع کی زبان</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>موضوع کی زبان</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>یہ موضوع نہیں بنایا جا سکتا۔ اے آئی صرف ہر عمر کے لیے موزوں مواد بناتا ہے — جنسی، فحش یا توہین آمیز موضوعات تعاون یافتہ نہیں ہیں۔ براہ کرم کوئی دوسرا موضوع آزمائیں۔</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>آپ اس مہینے کی تمام اے آئی جنریشنز استعمال کر چکے ہیں۔ اگلے مہینے دوبارہ کوشش کریں۔</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>آج بہت زیادہ رپورٹیں — براہ کرم کل دوبارہ کوشش کریں۔</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>اے آئی سروس اس وقت مصروف ہے — براہ کرم تھوڑی دیر بعد دوبارہ کوشش کریں۔</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>پہلے ایک موضوع درج کریں۔</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>موضوع بہت لمبا ہے (زیادہ سے زیادہ %1 حروف)۔</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>کم از کم ایک سوال کی قسم کو صفر سے زیادہ پر سیٹ کریں۔</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>آپ کا سیشن ختم ہو گیا ہے — براہ کرم دوبارہ سائن ان کریں۔</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>سرور تک رسائی نہیں ہو سکی۔ اپنا انٹرنیٹ کنکشن چیک کریں اور دوبارہ کوشش کریں۔</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>کچھ غلط ہو گیا۔ براہ کرم دوبارہ کوشش کریں۔</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>سائن ان نہیں ہے۔</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>پلٹنے کے لیے تھپتھپائیں</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>واپس پلٹنے کے لیے تھپتھپائیں</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>معلوم ہے</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>نظرانداز کریں</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  معلوم نہیں</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  معلوم ہے</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>منتخب نہیں</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>لائسنس متن لوڈ نہیں ہو سکا۔</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>جاری رکھنے کے لیے سائن ان کریں</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>براؤزر کھل رہا ہے…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Google سے سائن ان کریں</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">اس نام کی لائبریری یا سیٹ یہاں پہلے سے موجود ہے۔</translation>
    </message>
    <message>
        <location line="+317"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>اس نام کا لفظی سیٹ یہاں پہلے سے موجود ہے۔</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>اس نام کا قوانین کا سیٹ یہاں پہلے سے موجود ہے۔</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+38"/>
        <source>Results</source>
        <translation>نتائج</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>Well</source>
        <translation>بہت</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>done</source>
        <translation>خوب</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>%1 میں سے</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>بہترین کام! اسی طرح جاری رکھیں!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>اچھی کوشش! مشق جاری رکھیں۔</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>ہمت نہ ہاریں – مشق کمال پیدا کرتی ہے!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>یہ سیشن</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>معلوم نہیں</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>معلوم ہے</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Practice again</source>
        <translation>دوبارہ مشق کریں</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Find another set</source>
        <translation>کوئی اور سیٹ تلاش کریں</translation>
    </message>
    <message>
        <source>Practice Again</source>
        <translation type="vanished">دوبارہ مشق کریں</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>ٹیسٹ کی پیش رفت ری سیٹ کریں؟</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>اس سے اس قوانین کے سیٹ پر آپ کی پیش رفت صاف ہو جائے گی اور ایک نیا سیشن شروع ہوگا۔</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 سوالات</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">مکمل: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">جاری: %1 / %2</translation>
    </message>
    <message>
        <source>← Reset</source>
        <translation type="vanished">← ری سیٹ</translation>
    </message>
    <message>
        <location line="+185"/>
        <source>Reset to practise again</source>
        <translation>دوبارہ مشق کے لیے ری سیٹ کریں</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Reset</source>
        <translation>ری سیٹ</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>قانون کی وضاحت</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>اس سیٹ کے لیے کوئی وضاحت شامل نہیں کی گئی۔</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>آڈیو کلپ</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ ہجے کی سختی</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>سخت</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>عام</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>نرم</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>ٹیسٹ شروع کریں</translation>
    </message>
    <message>
        <location line="-316"/>
        <source>Test is completed</source>
        <translation>ٹیسٹ مکمل ہو گیا ہے</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>اگلا سوال: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>درست: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>قانون</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 قانون کی وضاحت</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>آڈیو کلپ</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>منسوخ کریں</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 قانون دیکھیں</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>ہر خالی جگہ کا لفظ منتخب کرنے کے لیے پہیہ گھمائیں۔</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>خالی جگہ %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>ایک ٹائل کو خالی جگہ پر گھسیٹیں، یا اسے رکھنے کے لیے ٹائل پر اور پھر خالی جگہ پر تھپتھپائیں۔</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>درست جواب منتخب کریں۔</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>جو بھی لاگو ہو وہ سب منتخب کریں۔</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>درست: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>جمع کروائیں</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>درست: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>نتائج دیکھیں</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>اگلا →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>سوال نمبر %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>لفظی سیٹ کو اوور رائٹ کریں؟</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>لائبریریوں کو ضم کریں؟</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>“%1” نامی لفظی سیٹ یہاں پہلے سے موجود ہے۔ کیا اسے منتقل شدہ سیٹ سے اوور رائٹ کریں؟</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>“%1” نامی لائبریری یہاں پہلے سے موجود ہے۔ کیا اس کے مواد کو اس میں ضم کریں؟</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>“%1” نامی لفظی سیٹ %2 میں پہلے سے موجود ہے۔ کیا اسے ضم شدہ ورژن سے اوور رائٹ کریں؟</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>منزل لائبریری</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>‎.ppset‎ کے طور پر برآمد کریں</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>نئی لائبریری</translation>
    </message>
    <message>
        <location line="+31"/>
        <source>Library name:</source>
        <translation>لائبریری کا نام:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>مثلاً: سفر، کام، اسکول…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">اس نام کی لائبریری یا سیٹ یہاں پہلے سے موجود ہے۔</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+99"/>
        <source>A library with this name already exists here.</source>
        <translation>اس نام کی لائبریری یہاں پہلے سے موجود ہے۔</translation>
    </message>
    <message>
        <location line="-62"/>
        <source>Create</source>
        <translation>بنائیں</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Rename Library</source>
        <translation>لائبریری کا نام تبدیل کریں</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>نیا نام:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>نام تبدیل کریں</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>آپ کے لفظی سیٹس</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>لائبریری</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>سے باہر منتقل کریں</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>اندر منتقل کرنے کے لیے چھوڑیں</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>الفاظ</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>سوالات</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>لائبریری حذف کریں</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>ترمیم کریں</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>حذف کریں</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>‎.ppset‎ فائل شیئر کریں</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>‎.ppset‎ برآمد کریں (ڈسک پر محفوظ کریں)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>ابھی یہاں کچھ نہیں ہے۔
لفظی سیٹ یا لائبریری شامل کرنے کے لیے + بنائیں پر تھپتھپائیں۔</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>لفظی سیٹ</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>قوانین کا سیٹ</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ بنائیں</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>انٹرفیس کی زبان</translation>
    </message>
    <message>
        <location line="-710"/>
        <location line="+796"/>
        <source>Cancel</source>
        <translation>منسوخ کریں</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>ٹیسٹ کی قسم منتخب کریں</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>فلیش کارڈز</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>ظاہر کرنے کے لیے پلٹیں — اگر معلوم ہو تو دائیں طرف سوائپ کریں</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>لفظ لکھیں</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>اشارہ دیکھیں — فقرہ ٹائپ کریں</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>اشارہ لکھیں</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>لفظ دیکھیں — اس کا ترجمہ ٹائپ کریں</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>لفظ منتخب کریں</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>اشارہ دیکھیں — 4 اختیارات میں سے منتخب کریں</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>اشارہ منتخب کریں</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>لفظ دیکھیں — 4 اختیارات میں سے منتخب کریں</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>ترقی پذیر تعلیم</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>سیکھنے کے لیے پہلے کثیر انتخابی، پھر تمام الفاظ میں مہارت کے لیے لکھنا</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>الٹی ترقی پذیر تعلیم</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>سیکھنے کے لیے پہلے کثیر انتخابی، پھر تمام اشاروں میں مہارت کے لیے لکھنا</translation>
    </message>
    <message>
        <location line="+36"/>
        <location line="+82"/>
        <source>✓ Done</source>
        <translation>✓ مکمل</translation>
    </message>
    <message>
        <location line="-82"/>
        <source>← Reset</source>
        <translation>← ری سیٹ</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Completed — swipe left to reset</source>
        <translation>مکمل — ری سیٹ کرنے کے لیے بائیں سوائپ کریں</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>%1 left</source>
        <translation>%1 باقی</translation>
    </message>
    <message>
        <location line="+51"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ ہجے کی سختی</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>سخت</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>عام</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>نرم</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>منسوخ کریں</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>فقروں کا جائزہ</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  روکیں</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  سنیں</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>ٹیسٹ شروع کریں</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>ابھی تک کوئی لفظ نہیں</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>اشارہ / ترجمہ ٹائپ کریں…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>فقرہ ٹائپ کریں…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>درست: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ درست کے طور پر نشان زد کریں (میں نے غلط ٹائپ کیا)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>جمع کرائیں</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ درست کے طور پر نشان زد کریں (میں نے غلط کلک کیا)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>درست: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>نتائج دیکھیں</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>اگلا ←</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>سوال نمبر %1</translation>
    </message>
</context>
</TS>
