<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="el">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Σχετικά</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Εκπαιδευτής λεξιλογίου για την απομνημόνευση συνόλων λέξεων.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Εκπαιδευτής λεξιλογίου και γραμματικής.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Άδειες ανοιχτού κώδικα</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Αυτή η εφαρμογή χρησιμοποιεί το Qt υπό την άδεια GNU Lesser General Public License έκδοση 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Ειδοποίηση Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Ειδοποίηση Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Πηγαίος κώδικας Qt</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Ιστότοπος έργου Qt</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Δημιουργήθηκε από ΤΝ — μπορεί να περιέχει λάθη</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Αναφορά</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Ευχαριστούμε — η αναφορά σας στάλθηκε και θα εξεταστεί.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Αναφορά περιεχομένου ΤΝ</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Τι πρόβλημα έχει αυτό το περιεχόμενο που δημιουργήθηκε;</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Σεξουαλικό ή υπονοούμενο περιεχόμενο</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Βωμολοχίες ή προσβλητική γλώσσα</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Περιεχόμενο μίσους ή παρενόχλησης</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Βίαιο ή επικίνδυνο περιεχόμενο</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Λανθασμένες ή παραπλανητικές πληροφορίες</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Κάτι άλλο</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Λεπτομέρειες (προαιρετικά)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Αποστολή…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Κλείσιμο</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Άκυρο</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Αποστολή αναφοράς</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Λήψη φωτογραφίας</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Άκυρο</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>σύντομα</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>σε %1μ %2ω</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>σε %1ω %2λ</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>σε %1λ</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Επιλογή εικόνας</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Επιλογή ήχου</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Εισαγωγή συνόλου λέξεων</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Γλώσσα λέξης</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Γλώσσα υπόδειξης</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+339"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Άκυρο</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ Δημιουργός συνόλων λέξεων με ΤΝ</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Με την υποστήριξη του Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Θέμα</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Περιγράψτε το σύνολο που θέλετε — π.χ. «σκεύη κουζίνας που θα βρίσκατε σε ένα γαλλικό σπίτι» ή «φράσεις για επαγγελματικό ταξίδι σε συνέδριο»…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Απομένουν %1 από %2 δημιουργίες αυτόν τον μήνα — επαναφορά στις %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>Η ΤΝ μπορεί να κάνει λάθη. Δημιουργείται μόνο περιεχόμενο κατάλληλο για όλες τις ηλικίες — χρησιμοποιήστε το 🚩 Αναφορά για να επισημάνετε οτιδήποτε ακατάλληλο.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Γλώσσα λέξης</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Γλώσσα υπόδειξης</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Αριθμός λέξεων</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Ερώτηση στο Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Ακύρωση αιτήματος</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Δημιουργία</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ ΤΝ</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Νέο σύνολο λέξεων</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Επεξεργασία συνόλου λέξεων</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Εισαγωγή</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Τίτλος συνόλου…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Αυτόματη λήψη εικόνων</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Λέξη</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>επιλέχθηκε</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Λέξη / Όρος</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Δεν επιλέχθηκε</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Εισαγάγετε λέξη...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Υπόδειξη / σημασία</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Υπόδειξη, ορισμός...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Παράδειγμα χρήσης</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Παράδειγμα πρότασης που χρησιμοποιεί τη λέξη...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Αλλαγή εικόνας</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Προσθήκη εικόνας</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Λήψη</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Κάμερα</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Προσθήκη ήχου</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Διακοπή</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Αναπαραγωγή</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ Εκφώνηση</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Διακοπή</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Εγγραφή</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Προσθήκη λέξης</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Αφαίρεση</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Αποθήκευση</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Ο τίτλος είναι υποχρεωτικός</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>σύντομα</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>σε %1η %2ω</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>σε %1ω %2λ</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>σε %1λ</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Επιλογή εικόνας</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Επιλογή ήχου</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ Τεχνητή νοημοσύνη</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Νέο σύνολο κανόνων</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Επεξεργασία συνόλου κανόνων</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Εισαγωγή</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Εισαγωγή συνόλου κανόνων</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ Γεννήτρια συνόλων κανόνων με ΤΝ</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Με την υποστήριξη του Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Απομένουν %1 από %2 δημιουργίες αυτόν τον μήνα — επαναφορά %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Κανόνας/θέμα προς επεξήγηση</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Περιγράψτε τον κανόνα που θέλετε — π.χ. &quot;ενεστώτας διαρκείας έναντι απλού ενεστώτα&quot; ή &quot;προτάσεις τρίτου τύπου υποθετικού λόγου&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Ερωτήσεις ανά τύπο</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Συμπλήρωση κενού</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Πολλαπλής επιλογής</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Αναπτυσσόμενη επιλογή</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Σύρετε και αποθέστε</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Ερώτημα στο Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Ακύρωση αιτήματος</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Ακύρωση</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>Η ΤΝ μπορεί να κάνει λάθη. Δημιουργείται μόνο περιεχόμενο κατάλληλο για όλες τις ηλικίες — χρησιμοποιήστε το 🚩 Αναφορά για να επισημάνετε οτιδήποτε ακατάλληλο.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Δημιουργία</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Εισαγάγετε τίτλο…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Επεξήγηση θεωρίας</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Κρυφό κατά τη διάρκεια του τεστ μέχρι ο μαθητής να κάνει λάθος — πάντα ορατό στην προεπισκόπηση.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Χρησιμοποιήστε ▲▼ για αναδιάταξη ενός μπλοκ. Σύρετε τη γωνία // μιας φωτογραφίας για αλλαγή μεγέθους.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Εξηγήστε τον κανόνα που εξασκεί αυτό το σύνολο…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Ηχητικό απόσπασμα</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Κείμενο</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Φωτογραφία</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Ήχος</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Ερώτηση</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>επιλέχθηκε</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Συμπλήρωση κενού</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Πολλαπλής επιλογής</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Αναπτυσσόμενη επιλογή</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Σύρετε και αποθέστε</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Χρησιμοποιήστε ___ (τρεις κάτω παύλες) για κάθε κενό που συμπληρώνει ο μαθητής.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>π.χ. Τι κάνει κάθε μέρα;</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>π.χ. Αυτή ___ σχολείο κάθε μέρα.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Απαντήσεις</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Μία απάντηση ανά κενό, χωρισμένες με κόμμα, με σειρά. Χρησιμοποιήστε \, για κυριολεκτικό κόμμα.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>π.χ. πηγαίνει</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Επιλογές</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Διαχωρίστε τις επιλογές για ένα κενό με κόμματα· διαχωρίστε τα κενά με διπλή άνω-κάτω τελεία (::). Μία μεμονωμένη : είναι ασφαλής ως έχει· χρησιμοποιήστε \, για κυριολεκτικό κόμμα, \:: για κυριολεκτικό ::, και ___ για σκόπιμα κενή επιλογή. Π.χ. για δύο κενά: πηγαίνει, πάει, πηγαίνοντας::κάθε, μερικοί, οι περισσότεροι.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Πλακίδια που σύρονται, χωρισμένα με κόμμα — συμπεριλάβετε τις σωστές απαντήσεις, συν προαιρετικά δολώματα με τα οποία μπορεί να ξεγελαστεί ο μαθητής. Χρησιμοποιήστε \, για κυριολεκτικό κόμμα, και ___ για κενό πλακίδιο (για κενό που σωστά πρέπει να παραμείνει κενό). Συμπληρώστε τα παρακάτω κενά μόλις οριστούν αυτά.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>π.χ. πηγαίνει, πάει, πηγαίνοντας::κάθε, μερικοί, οι περισσότεροι</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>π.χ. πηγαίνει, πάει, πηγαίνοντας, πήγε</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Σωστή απάντηση για κάθε κενό</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Πατήστε τη σωστή επιλογή σε κάθε πλαίσιο παρακάτω.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Επιλέξτε μια σωστή απάντηση για κάθε κενό.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Κενό %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Συμπληρώστε τα κενά</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Σύρετε ένα πλακίδιο σε ένα κενό παρακάτω, ή πατήστε ένα πλακίδιο και έπειτα ένα κενό για να το τοποθετήσετε.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Συμπληρώστε κάθε κενό με ένα πλακίδιο.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Επιλογές χωρισμένες με κόμμα — πατήστε τη σωστή απάντηση παρακάτω. Χρησιμοποιήστε \, για κυριολεκτικό κόμμα.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Επιλογές χωρισμένες με κόμμα — πατήστε όλες τις σωστές απαντήσεις παρακάτω. Χρησιμοποιήστε \, για κυριολεκτικό κόμμα.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>π.χ. πηγαίνει, πάει, πηγαίνοντας, πήγε</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Μόνο μία σωστή απάντηση</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Σωστή απάντηση</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Σωστή(ές) απάντηση(εις)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Επιλέξτε τη σωστή απάντηση.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Επιλέξτε τουλάχιστον μία σωστή απάντηση.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Προσθήκη ερώτησης</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Αφαίρεση</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Αποθήκευση</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Ο τίτλος είναι υποχρεωτικός</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Εξήγηση γραμματικής</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Δεν ήταν δυνατή η φόρτωση της ερώτησης %1: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Δημιουργήθηκαν μόνο %1 από %2 ζητούμενες ερωτήσεις — δοκιμάστε ένα ευρύτερο θέμα ή μειώστε τους αριθμούς παραπάνω.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Γλώσσα επεξήγησης</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Γλώσσα επεξήγησης</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Γλώσσα θέματος</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Γλώσσα θέματος</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Αυτό το θέμα δεν μπορεί να δημιουργηθεί. Η ΤΝ δημιουργεί μόνο περιεχόμενο κατάλληλο για όλες τις ηλικίες — σεξουαλικά, χυδαία ή προσβλητικά θέματα δεν υποστηρίζονται. Δοκιμάστε ένα διαφορετικό θέμα.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Έχετε χρησιμοποιήσει όλες τις δημιουργίες ΤΝ αυτού του μήνα. Δοκιμάστε ξανά τον επόμενο μήνα.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Πάρα πολλές αναφορές σήμερα — δοκιμάστε ξανά αύριο.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Η υπηρεσία ΤΝ είναι απασχολημένη αυτή τη στιγμή — δοκιμάστε ξανά σε λίγο.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Εισαγάγετε πρώτα ένα θέμα.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Το θέμα είναι πολύ μεγάλο (έως %1 χαρακτήρες).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Ορίστε τουλάχιστον έναν τύπο ερωτήσεων πάνω από το μηδέν.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Η συνεδρία σας έληξε — συνδεθείτε ξανά.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Δεν ήταν δυνατή η σύνδεση με τον διακομιστή. Ελέγξτε τη σύνδεσή σας στο διαδίκτυο και δοκιμάστε ξανά.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Κάτι πήγε στραβά. Δοκιμάστε ξανά.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Δεν έχετε συνδεθεί.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Πατήστε για αναστροφή</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Πατήστε για αναστροφή πίσω</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>ΞΕΡΩ</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>ΠΑΡΑΛΕΙΨΗ</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Δεν ξέρω</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Ξέρω</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Δεν επιλέχθηκε</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Δεν ήταν δυνατή η φόρτωση του κειμένου άδειας.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Συνδεθείτε για να συνεχίσετε</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Άνοιγμα προγράμματος περιήγησης…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Σύνδεση με Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Υπάρχει ήδη εδώ μια βιβλιοθήκη ή σύνολο με αυτό το όνομα.</translation>
    </message>
    <message>
        <location line="+317"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Υπάρχει ήδη εδώ ένα σύνολο λέξεων με αυτό το όνομα.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Υπάρχει ήδη εδώ ένα σύνολο κανόνων με αυτό το όνομα.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+38"/>
        <source>Results</source>
        <translation>Αποτελέσματα</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>Well</source>
        <translation>Μπράβο</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>done</source>
        <translation>σωστά</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>από %1</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Εξαιρετική δουλειά! Συνέχισε έτσι!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Καλή προσπάθεια! Συνέχισε να εξασκείσαι.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Μην τα παρατάς – η εξάσκηση φέρνει τελειότητα!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Αυτή η συνεδρία</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Δεν ξέρω</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Ξέρω</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Practice again</source>
        <translation>Εξάσκηση ξανά</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Find another set</source>
        <translation>Βρείτε άλλο σετ</translation>
    </message>
    <message>
        <source>Practice Again</source>
        <translation type="vanished">Εξάσκηση ξανά</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Επαναφορά προόδου τεστ;</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Αυτό θα διαγράψει την πρόοδό σας σε αυτό το σύνολο κανόνων και θα ξεκινήσει μια νέα συνεδρία.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 ερωτήσεις</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Ολοκληρώθηκε: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Σε εξέλιξη: %1 / %2</translation>
    </message>
    <message>
        <source>← Reset</source>
        <translation type="vanished">← Επαναφορά</translation>
    </message>
    <message>
        <location line="+185"/>
        <source>Reset to practise again</source>
        <translation>Επαναφορά για νέα εξάσκηση</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Reset</source>
        <translation>Επαναφορά</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Επεξήγηση κανόνα</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Δεν προστέθηκε επεξήγηση για αυτό το σύνολο.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Ηχητικό απόσπασμα</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Αυστηρότητα ορθογραφίας</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Αυστηρή</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Κανονική</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Ελαστική</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Έναρξη τεστ</translation>
    </message>
    <message>
        <location line="-316"/>
        <source>Test is completed</source>
        <translation>Το τεστ ολοκληρώθηκε</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Επόμενη ερώτηση: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Σωστό: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Κανόνας</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Επεξήγηση κανόνα</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Ηχητικό απόσπασμα</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Ακύρωση</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Προβολή κανόνα</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Γυρίστε τον τροχό για να επιλέξετε τη λέξη κάθε κενού.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Κενό %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Σύρετε ένα πλακίδιο σε ένα κενό, ή πατήστε ένα πλακίδιο και έπειτα ένα κενό για να το τοποθετήσετε.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Επιλέξτε τη σωστή απάντηση.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Επιλέξτε όσα ισχύουν.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Σωστό: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Υποβολή</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Σωστό: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Προβολή αποτελεσμάτων</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Επόμενο →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Αριθμός ερώτησης %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Αντικατάσταση συνόλου λέξεων;</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Συγχώνευση βιβλιοθηκών;</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Ένα σύνολο λέξεων με το όνομα «%1» υπάρχει ήδη εδώ. Να αντικατασταθεί με το μετακινημένο σύνολο;</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Μια βιβλιοθήκη με το όνομα «%1» υπάρχει ήδη εδώ. Να συγχωνευθεί το περιεχόμενό της σε αυτήν;</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Ένα σύνολο λέξεων με το όνομα «%1» υπάρχει ήδη στο %2. Να αντικατασταθεί με τη συγχωνευμένη έκδοση;</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>η βιβλιοθήκη προορισμού</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Εξαγωγή ως .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Νέα βιβλιοθήκη</translation>
    </message>
    <message>
        <location line="+31"/>
        <source>Library name:</source>
        <translation>Όνομα βιβλιοθήκης:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>π.χ. Ταξίδια, Δουλειά, Σχολείο…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Υπάρχει ήδη εδώ μια βιβλιοθήκη ή σύνολο με αυτό το όνομα.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+99"/>
        <source>A library with this name already exists here.</source>
        <translation>Υπάρχει ήδη εδώ μια βιβλιοθήκη με αυτό το όνομα.</translation>
    </message>
    <message>
        <location line="-62"/>
        <source>Create</source>
        <translation>Δημιουργία</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Rename Library</source>
        <translation>Μετονομασία βιβλιοθήκης</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Νέο όνομα:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Μετονομασία</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Τα σύνολα λέξεών σου</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Βιβλιοθήκη</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Μετακίνηση έξω από</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Άφησέ το εδώ για μετακίνηση μέσα</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>λέξεις</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>ερωτήσεις</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Διαγραφή βιβλιοθήκης</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Επεξεργασία</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Διαγραφή</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Κοινή χρήση αρχείου .ppset</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Εξαγωγή .ppset (αποθήκευση στον δίσκο)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Δεν υπάρχει τίποτα εδώ ακόμη.
Πατήστε + Δημιουργία για να προσθέσετε ένα σύνολο λέξεων ή βιβλιοθήκη.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Σύνολο λέξεων</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Σύνολο κανόνων</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Δημιουργία</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Γλώσσα διεπαφής</translation>
    </message>
    <message>
        <location line="-710"/>
        <location line="+796"/>
        <source>Cancel</source>
        <translation>Άκυρο</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Επιλέξτε τύπο τεστ</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Κάρτες μνήμης</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Γύρισε για αποκάλυψη — σύρε δεξιά αν το ξέρεις</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Γράψε τη λέξη</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Δες την υπόδειξη — πληκτρολόγησε την έκφραση</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Γράψε την υπόδειξη</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Δες τη λέξη — πληκτρολόγησε τη μετάφρασή της</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Διάλεξε τη λέξη</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Δες την υπόδειξη — διάλεξε από 4 επιλογές</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Διάλεξε την υπόδειξη</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Δες τη λέξη — διάλεξε από 4 επιλογές</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Προοδευτική εκμάθηση</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Πολλαπλή επιλογή για εκμάθηση, μετά γραφή για εμπέδωση όλων των λέξεων</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Αντίστροφη προοδευτική εκμάθηση</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Πολλαπλή επιλογή για εκμάθηση, μετά γραφή για εμπέδωση όλων των υποδείξεων</translation>
    </message>
    <message>
        <location line="+36"/>
        <location line="+82"/>
        <source>✓ Done</source>
        <translation>✓ Ολοκληρώθηκε</translation>
    </message>
    <message>
        <location line="-82"/>
        <source>← Reset</source>
        <translation>← Επαναφορά</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Completed — swipe left to reset</source>
        <translation>Ολοκληρώθηκε — σύρετε αριστερά για επαναφορά</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>%1 left</source>
        <translation>Απομένουν %1</translation>
    </message>
    <message>
        <location line="+51"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Αυστηρότητα ορθογραφίας</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Αυστηρή</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Κανονική</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Ελαστική</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Άκυρο</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Επανάληψη εκφράσεων</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Διακοπή</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Ακρόαση</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Έναρξη τεστ</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Δεν υπάρχουν ακόμη λέξεις</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Πληκτρολόγησε την υπόδειξη / μετάφραση…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Πληκτρολόγησε την έκφραση…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Σωστό: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Σήμανση ως σωστού (έκανα τυπογραφικό λάθος)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Υποβολή</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Σήμανση ως σωστού (πάτησα λάθος)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Σωστό: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Δείτε αποτελέσματα</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Επόμενο →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Αριθμός ερώτησης %1</translation>
    </message>
</context>
</TS>
