<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="uk">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Про застосунок</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Тренажер словникового запасу для запам&apos;ятовування наборів слів.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Тренажер лексики та граматики.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Ліцензії з відкритим кодом</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Цей застосунок використовує Qt за ліцензією GNU Lesser General Public License версії 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Повідомлення Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Повідомлення Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Вихідний код Qt</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Сайт проєкту Qt</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Створено ШІ — можливі помилки</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Поскаржитися</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Дякуємо — вашу скаргу надіслано, її буде розглянуто.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Поскаржитися на контент ШІ</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Що не так із цим згенерованим контентом?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Сексуальний або непристойний контент</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Лайка або образлива мова</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Контент, що розпалює ненависть, або цькування</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Жорстокий або небезпечний контент</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Хибна або оманлива інформація</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Інше</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Подробиці (необов&apos;язково)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Надсилання…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Закрити</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Скасувати</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Надіслати скаргу</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Зробити фото</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Скасувати</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>незабаром</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>через %1д %2год</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>через %1год %2хв</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>через %1хв</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Вибрати зображення</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Вибрати аудіо</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Імпортувати набір слів</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Мова слова</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Мова підказки</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+326"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Скасувати</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ Генератор наборів слів зі ШІ</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>На основі Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Тема</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Опишіть потрібний набір — напр. «кухонне начиння, яке можна знайти у французькому домі» або «фрази для ділової поїздки на конференцію»…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Залишилося %1 з %2 генерацій цього місяця — скидання %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>ШІ може помилятися. Створюється лише контент, придатний для всіх вікових груп — використовуйте 🚩 Поскаржитися, щоб позначити будь-що недоречне.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Мова слова</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Мова підказки</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Кількість слів</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Запит до Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Скасувати запит</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Створити</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ ШІ</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Новий набір слів</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Редагувати набір слів</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Імпортувати</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Назва набору…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Автозавантаження зображень</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Слово</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>вибрано</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Слово / термін</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Не вибрано</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Введіть слово...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Підказка / значення</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Підказка, визначення...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Приклад використання</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Приклад речення зі словом...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Змінити зображення</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Додати зображення</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Завантажити</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Камера</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Додати аудіо</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Стоп</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Відтворити</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ Озвучити</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Стоп</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Зап.</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Додати слово</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Видалити</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Зберегти</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Потрібна назва</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>незабаром</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>через %1д %2г</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>через %1г %2хв</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>через %1хв</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Вибрати зображення</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Вибрати аудіо</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ ШІ</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Новий набір правил</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Редагувати набір правил</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Імпорт</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Імпортувати набір правил</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ Генератор наборів правил на основі ШІ</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Працює на Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Залишилося %1 з %2 генерацій цього місяця — скидання %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Правило/тема для пояснення</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Опишіть потрібне правило — напр. &quot;теперішній простий проти теперішнього тривалого&quot; або &quot;умовні речення третього типу&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Питань на тип</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Заповнити пропуск</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Множинний вибір</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Спадне меню</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Перетягніть і відпустіть</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Запит до Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Скасувати запит</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Скасувати</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>ШІ може помилятися. Створюється лише контент, придатний для всіх вікових груп — використовуйте 🚩 Поскаржитися, щоб позначити будь-що недоречне.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Згенерувати</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Введіть назву…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Пояснення теорії</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Приховано під час тестування, доки учень не припуститься помилки — завжди читабельне в попередньому перегляді.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Використовуйте ▲▼ для зміни порядку блоку. Перетягніть кут // фото, щоб змінити розмір.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Поясніть правило, яке відпрацьовує цей набір…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Аудіофрагмент</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Текст</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Фото</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Аудіо</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Питання</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>вибрано</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Заповнити пропуск</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Множинний вибір</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Спадне меню</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Перетягніть і відпустіть</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Використовуйте ___ (три підкреслення) для кожного пропуску, який заповнює учень.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>напр. Що вона робить щодня?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>напр. Вона ___ до школи щодня.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Відповіді</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Одна відповідь на пропуск, розділені комами, за порядком. Використовуйте \, для буквальної коми.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>напр. іде</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Варіанти</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Розділяйте варіанти для одного пропуску комами; розділяйте пропуски подвійною двокрапкою (::). Одна : безпечна як є; використовуйте \, для буквальної коми, \:: для буквального ::, і ___ для навмисно порожнього варіанту. Напр. для двох пропусків: іде, йти, ідучи::кожен, деякі, більшість.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Плитки для перетягування, розділені комами — додайте правильні відповіді, а також необов&apos;язкові пастки, якими учня можна заплутати. Використовуйте \, для буквальної коми, і ___ для порожньої плитки (для пропуску, який правильно має залишатися порожнім). Заповніть пропуски нижче, щойно вони будуть задані.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>напр. іде, йти, ідучи::кожен, деякі, більшість</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>напр. іде, йти, ідучи, пішов</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Правильна відповідь для кожного пропуску</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Торкніться правильного варіанту в кожному полі нижче.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Виберіть правильну відповідь для кожного пропуску.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Пропуск %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Заповніть пропуски</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Перетягніть плитку на пропуск нижче, або торкніться плитки, а потім пропуску, щоб розмістити її.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Заповніть кожен пропуск плиткою.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Варіанти, розділені комами — торкніться правильної відповіді нижче. Використовуйте \, для буквальної коми.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Варіанти, розділені комами — торкніться всіх правильних відповідей нижче. Використовуйте \, для буквальної коми.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>напр. іде, йти, ідучи, пішов</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Лише одна правильна відповідь</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Правильна відповідь</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Правильна(і) відповідь(і)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Виберіть правильну відповідь.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Виберіть принаймні одну правильну відповідь.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Додати питання</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Видалити</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Зберегти</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Назва обов&apos;язкова</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Пояснити граматику</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Не вдалося завантажити питання %1: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Створено лише %1 із %2 запитаних питань — спробуйте ширшу тему або зменште числа вище.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Мова пояснення</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Мова пояснення</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Мова теми</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Мова теми</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Цю тему неможливо згенерувати. ШІ створює лише контент, придатний для всіх вікових груп — сексуальні, лайливі чи образливі теми не підтримуються. Спробуйте іншу тему.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Ви використали всі генерації ШІ цього місяця. Спробуйте ще раз наступного місяця.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Забагато скарг сьогодні — спробуйте ще раз завтра.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Сервіс ШІ зараз перевантажений — спробуйте трохи пізніше.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Спочатку введіть тему.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Тема задовга (макс. %1 символів).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Задайте хоча б для одного типу запитань значення більше нуля.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Термін дії вашого сеансу минув — увійдіть знову.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Не вдалося з&apos;єднатися із сервером. Перевірте підключення до інтернету й спробуйте ще раз.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Щось пішло не так. Спробуйте ще раз.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Вхід не виконано.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Торкніться, щоб перевернути</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Торкніться, щоб перевернути назад</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>ЗНАЮ</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>ПРОПУСТИТИ</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Не знаю</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Знаю</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Не вибрано</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Не вдалося завантажити текст ліцензії.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Увійдіть, щоб продовжити</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Відкриття браузера…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Увійти через Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Бібліотека або набір із такою назвою вже існує тут.</translation>
    </message>
    <message>
        <location line="+309"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Набір слів із такою назвою вже існує тут.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Набір правил із такою назвою вже існує тут.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+37"/>
        <source>Results</source>
        <translation>Результати</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Well</source>
        <translation>Чудово</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>done</source>
        <translation>зроблено</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>з %1</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Відмінна робота! Так тримати!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Гарна спроба! Продовжуйте практикуватися.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Не здавайтеся – повторення — мати навчання!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Ця сесія</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Не знаю</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Знаю</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Practice Again</source>
        <translation>Практикуватися знову</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Скинути прогрес тесту?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Це очистить ваш прогрес у цьому наборі правил і почне нову сесію.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 питань</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Завершено: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">У процесі: %1 / %2</translation>
    </message>
    <message>
        <location line="+67"/>
        <source>← Reset</source>
        <translation>← Скинути</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Пояснення правила</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Для цього набору не додано пояснення.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Аудіофрагмент</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Строгість орфографії</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Строга</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Звичайна</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>М&apos;яка</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Почати тест</translation>
    </message>
    <message>
        <location line="-198"/>
        <source>Test is completed</source>
        <translation>Тест завершено</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Наступне питання: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Правильно: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Правило</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Пояснення правила</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Аудіофрагмент</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Скасувати</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Переглянути правило</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Покрутіть колесо, щоб вибрати слово для кожного пропуску.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Пропуск %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Перетягніть плитку на пропуск, або торкніться плитки, а потім пропуску, щоб розмістити її.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Виберіть правильну відповідь.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Виберіть усе, що застосовується.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Правильно: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Надіслати</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Правильно: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Переглянути результати</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Далі →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Номер питання %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Перезаписати набір слів?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Об&apos;єднати бібліотеки?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Набір слів з назвою «%1» вже існує тут. Перезаписати його переміщеним набором?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Бібліотека з назвою «%1» вже існує тут. Об&apos;єднати її вміст із цим набором?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Набір слів з назвою «%1» вже існує в %2. Перезаписати його об&apos;єднаною версією?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>цільова бібліотека</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Експортувати як .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Нова бібліотека</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Library name:</source>
        <translation>Назва бібліотеки:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>напр. Подорожі, Робота, Школа…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Бібліотека або набір із такою назвою вже існує тут.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+74"/>
        <source>A library with this name already exists here.</source>
        <translation>Бібліотека із такою назвою вже існує тут.</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Create</source>
        <translation>Створити</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Rename Library</source>
        <translation>Перейменувати бібліотеку</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Нова назва:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Перейменувати</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Ваші набори слів</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Бібліотека</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Перемістити з</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Відпустіть, щоб перемістити всередину</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>слів</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>питання</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Видалити бібліотеку</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Редагувати</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Видалити</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Поділитися файлом .ppset</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Експортувати .ppset (зберегти на диск)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Тут поки нічого немає.
Торкніться + Створити, щоб додати набір слів або бібліотеку.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Набір слів</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Набір правил</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Створити</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Мова інтерфейсу</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Cancel</source>
        <translation>Скасувати</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Вибрати тип тесту</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Картки</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Переверніть, щоб відкрити — проведіть праворуч, якщо знаєте</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Напишіть слово</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Перегляньте підказку — введіть вираз</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Напишіть підказку</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Перегляньте слово — введіть переклад</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Виберіть слово</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Перегляньте підказку — виберіть із 4 варіантів</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Виберіть підказку</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Перегляньте слово — виберіть із 4 варіантів</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Прогресивне навчання</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Спочатку вибір із варіантів, потім письмо для опанування всіх слів</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Зворотне прогресивне навчання</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Спочатку вибір із варіантів, потім письмо для опанування всіх підказок</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>✓ Done</source>
        <translation>✓ Готово</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>← Reset</source>
        <translation>← Скинути</translation>
    </message>
    <message>
        <location line="+96"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Строгість орфографії</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Строга</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Звичайна</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>М&apos;яка</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Скасувати</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Повторити вирази</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Стоп</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Слухати</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Почати тест</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Поки немає слів</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Введіть підказку / переклад…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Введіть вираз…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Правильно: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Позначити як правильне (я помилився під час набору)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Надіслати</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Позначити як правильне (я помилково натиснув)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Правильно: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Переглянути результати</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Далі →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Номер питання %1</translation>
    </message>
</context>
</TS>
