<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="sq">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Rreth</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Trajner fjalori për të mësuar përmendësh grupe fjalësh.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Trajner fjalori dhe gramatike.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Licencat me burim të hapur</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Ky aplikacion përdor Qt sipas licencës GNU Lesser General Public License versioni 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Njoftimi i Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Njoftimi i Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Kodi burimor i Qt</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Faqja e internetit e projektit Qt</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Krijuar nga AI — mund të përmbajë gabime</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Raporto</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Faleminderit — raporti yt u dërgua dhe do të shqyrtohet.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Raporto përmbajtje AI</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Çfarë nuk shkon me këtë përmbajtje të krijuar?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Përmbajtje seksuale ose sugjestive</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Fjalë të pista ose gjuhë fyese</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Përmbajtje urrejtjeje ose ngacmimi</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Përmbajtje e dhunshme ose e rrezikshme</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Informacion i gabuar ose mashtrues</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Diçka tjetër</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Hollësi (opsionale)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Po dërgohet…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Mbyll</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Anulo</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Dërgo raportin</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Bëj foto</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Anulo</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>së shpejti</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>pas %1d %2o</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>pas %1o %2min</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>pas %1min</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Zgjidh imazhin</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Zgjidh audion</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Importo grupin e fjalëve</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Gjuha e fjalës</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Gjuha e ndihmës</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+339"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Anulo</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ Gjeneruesi i grupeve të fjalëve me AI</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Mundësuar nga Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Tema</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Përshkruaje grupin që dëshiron — p.sh. «sende kuzhine që do t&apos;i gjeje në një shtëpi franceze» ose «fraza për udhëtim pune drejt një konference»…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Kanë mbetur %1 nga %2 gjenerime këtë muaj — rivendoset më %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI mund të gabojë. Krijohet vetëm përmbajtje e përshtatshme për të gjitha moshat — përdor 🚩 Raporto për të sinjalizuar çdo gjë të papërshtatshme.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Gjuha e fjalës</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Gjuha e ndihmës</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Numri i fjalëve</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Duke pyetur Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Anulo kërkesën</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Gjenero</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Grup i ri fjalësh</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Modifiko grupin e fjalëve</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importo</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Titulli i grupit…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Merr imazhet automatikisht</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Fjalë</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>zgjedhur</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Fjalë / Term</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Nuk është zgjedhur</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Shkruaj fjalën...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Ndihmë / kuptim</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Ndihmë, përkufizim...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Shembull përdorimi</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Fjali shembull që përdor fjalën...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Ndrysho imazhin</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Shto imazh</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Merr</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Kamera</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Shto audio</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Ndalo</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Luaj</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ Lexo me zë</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Ndalo</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Regjistro</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Shto fjalë</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Hiq</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Ruaj</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Titulli kërkohet</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>së shpejti</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>brenda %1d %2o</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>brenda %1o %2m</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>brenda %1m</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Zgjidh imazhin</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Zgjidh audion</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ IA</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Grup i ri rregullash</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Redakto grupin e rregullave</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importo</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Importo grupin e rregullave</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ Gjenerues i grupeve të rregullave me IA</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Mundësuar nga Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Kanë mbetur %1 nga %2 gjenerime këtë muaj — rivendoset %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Rregulli/tema për të shpjeguar</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Përshkruani rregullin që dëshironi — p.sh. &quot;e tashme e thjeshtë kundrejt së tashmes së vazhduar&quot; ose &quot;fjali kushtore të llojit të tretë&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Pyetje për lloj</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Plotëso hapësirën bosh</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Zgjedhje e shumëfishtë</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Zgjedhje rënëse</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Zvarrit dhe lësho</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Duke pyetur Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Anulo kërkesën</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Anulo</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI mund të gabojë. Krijohet vetëm përmbajtje e përshtatshme për të gjitha moshat — përdor 🚩 Raporto për të sinjalizuar çdo gjë të papërshtatshme.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Gjenero</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Vendos titullin…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Shpjegimi i teorisë</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>I fshehur gjatë testit derisa nxënësi të bëjë një gabim — gjithmonë i lexueshëm në parashikim.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Përdorni ▲▼ për të riorganizuar një bllok. Zvarritni cepin // të një fotoje për ta ripërmasuar.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Shpjegoni rregullin që praktikon ky grup…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Klip audio</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Tekst</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Foto</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Audio</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Pyetje</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>zgjedhur</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Plotëso hapësirën bosh</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Zgjedhje e shumëfishtë</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Zgjedhje rënëse</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Zvarrit dhe lësho</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Përdorni ___ (tre nënvija) për çdo hapësirë bosh që plotëson nxënësi.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>p.sh. Çfarë bën ajo çdo ditë?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>p.sh. Ajo shkon ___ në shkollë çdo ditë.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Përgjigjet</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Një përgjigje për çdo hapësirë bosh, të ndara me presje, sipas radhës. Përdorni \, për një presje literale.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>p.sh. shkon</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Opsionet</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Ndani opsionet për një hapësirë bosh me presje; ndani hapësirat bosh me dy pika të dyfishta (::). Një : i vetëm është i sigurt siç është; përdorni \, për një presje literale, \:: për një :: literal, dhe ___ për një opsion qëllimisht bosh. P.sh. për dy hapësira bosh: shkon, të shkosh, duke shkuar::çdo, disa, shumica.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Pllakëza të zvarritshme të ndara me presje — përfshini përgjigjet e sakta, plus grackat opsionale me të cilat nxënësi mund të mashtrohet. Përdorni \, për një presje literale, dhe ___ për një pllakëz bosh (për një hapësirë bosh që duhet të mbetet bosh saktë). Plotësoni hapësirat bosh më poshtë sapo këto të vendosen.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>p.sh. shkon, të shkosh, duke shkuar::çdo, disa, shumica</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>p.sh. shkon, të shkosh, duke shkuar, ka shkuar</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Përgjigja e saktë për çdo hapësirë bosh</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Prekni opsionin e saktë në secilën kuti më poshtë.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Zgjidhni një përgjigje të saktë për çdo hapësirë bosh.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Hapësirë bosh %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Plotësoni hapësirat bosh</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Zvarritni një pllakëz te një hapësirë bosh më poshtë, ose prekni një pllakëz e më pas një hapësirë bosh për ta vendosur.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Plotësoni çdo hapësirë bosh me një pllakëz.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Opsione të ndara me presje — prekni përgjigjen e saktë më poshtë. Përdorni \, për një presje literale.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Opsione të ndara me presje — prekni të gjitha përgjigjet e sakta më poshtë. Përdorni \, për një presje literale.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>p.sh. shkon, të shkosh, duke shkuar, ka shkuar</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Vetëm një përgjigje e saktë</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Përgjigja e saktë</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Përgjigja(t) e saktë</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Zgjidhni përgjigjen e saktë.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Zgjidhni të paktën një përgjigje të saktë.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Shto pyetje</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Hiq</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Ruaj</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Titulli kërkohet</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Shpjego gramatikën</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Nuk u ngarkua dot pyetja %1: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>U gjeneruan vetëm %1 nga %2 pyetjet e kërkuara — provoni një temë më të gjerë, ose ulni numrat më sipër.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Gjuha e shpjegimit</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Gjuha e shpjegimit</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Gjuha e temës</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Gjuha e temës</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Kjo temë nuk mund të krijohet. AI krijon vetëm përmbajtje të përshtatshme për të gjitha moshat — temat seksuale, vulgare ose fyese nuk mbështeten. Provo një temë tjetër.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>I ke përdorur të gjitha krijimet me AI për këtë muaj. Provo përsëri muajin tjetër.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Shumë raporte sot — provo përsëri nesër.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Shërbimi i AI është i zënë tani — provo përsëri pas pak.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Fillimisht shkruaj një temë.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Tema është shumë e gjatë (maks. %1 karaktere).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Vendos të paktën një lloj pyetjeje mbi zero.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Sesioni yt skadoi — identifikohu përsëri.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Nuk u arrit lidhja me serverin. Kontrollo lidhjen me internetin dhe provo përsëri.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Diçka shkoi keq. Provo përsëri.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Nuk je i identifikuar.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Trokit për ta kthyer</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Trokit për ta kthyer prapa</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>E DI</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>KALO</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Nuk e di</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  E di</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Nuk është zgjedhur</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Teksti i licencës nuk mund të ngarkohej.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Identifikohu për të vazhduar</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Duke hapur shfletuesin…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Identifikohu me Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Këtu ekziston tashmë një bibliotekë ose grup me këtë emër.</translation>
    </message>
    <message>
        <location line="+317"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Këtu ekziston tashmë një grup fjalësh me këtë emër.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Këtu ekziston tashmë një grup rregullash me këtë emër.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+38"/>
        <source>Results</source>
        <translation>Rezultatet</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>Well</source>
        <translation>Punë</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>done</source>
        <translation>e shkëlqyer</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>nga %1</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Punë e shkëlqyer! Vazhdo kështu!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Përpjekje e mirë! Vazhdo të praktikosh.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Mos hiq dorë – praktika sjell përsosmërinë!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Kjo sesion</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Nuk e di</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>E di</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Practice again</source>
        <translation>Praktiko përsëri</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Find another set</source>
        <translation>Gjej një grup tjetër</translation>
    </message>
    <message>
        <source>Practice Again</source>
        <translation type="vanished">Praktiko përsëri</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Të rivendoset përparimi i testit?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Kjo do të pastrojë përparimin tuaj në këtë grup rregullash dhe do të fillojë një sesion të ri.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 pyetje</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Përfunduar: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Në vazhdim: %1 / %2</translation>
    </message>
    <message>
        <source>← Reset</source>
        <translation type="vanished">← Rivendos</translation>
    </message>
    <message>
        <location line="+185"/>
        <source>Reset to practise again</source>
        <translation>Rivendos për të praktikuar përsëri</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Reset</source>
        <translation>Rivendos</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Shpjegimi i rregullit</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Nuk është shtuar asnjë shpjegim për këtë grup.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Klip audio</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Ashpërsia e drejtshkrimit</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Rreptë</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normale</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Tolerante</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Fillo testin</translation>
    </message>
    <message>
        <location line="-316"/>
        <source>Test is completed</source>
        <translation>Testi ka përfunduar</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Pyetja tjetër: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Saktë: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Rregulli</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Shpjegimi i rregullit</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Klip audio</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Anulo</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Shiko rregullin</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Rrotulloni rrotën për të zgjedhur fjalën e çdo hapësire bosh.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Hapësirë bosh %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Zvarritni një pllakëz te një hapësirë bosh, ose prekni një pllakëz e më pas një hapësirë bosh për ta vendosur.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Zgjidhni përgjigjen e saktë.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Zgjidhni gjithçka që zbatohet.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Saktë: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Dërgo</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Saktë: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Shiko rezultatet</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Tjetra →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Numri i pyetjes %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Të mbishkruhet grupi i fjalëve?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Të bashkohen bibliotekat?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Një grup fjalësh me emrin «%1» ekziston tashmë këtu. Ta mbishkruaj me grupin e zhvendosur?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Një bibliotekë me emrin «%1» ekziston tashmë këtu. Të bashkohet përmbajtja e saj me të?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Një grup fjalësh me emrin «%1» ekziston tashmë në %2. Ta mbishkruaj me versionin e bashkuar?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>biblioteka e destinacionit</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Eksporto si .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Bibliotekë e re</translation>
    </message>
    <message>
        <location line="+31"/>
        <source>Library name:</source>
        <translation>Emri i bibliotekës:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>p.sh. Udhëtim, Punë, Shkollë…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Këtu ekziston tashmë një bibliotekë ose grup me këtë emër.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+99"/>
        <source>A library with this name already exists here.</source>
        <translation>Këtu ekziston tashmë një bibliotekë me këtë emër.</translation>
    </message>
    <message>
        <location line="-62"/>
        <source>Create</source>
        <translation>Krijo</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Rename Library</source>
        <translation>Riemërto bibliotekën</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Emri i ri:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Riemërto</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Grupet e tua të fjalëve</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Bibliotekë</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Zhvendos jashtë nga</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Lësho për ta zhvendosur brenda</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>fjalë</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>pyetje</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Fshi bibliotekën</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Modifiko</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Fshi</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Ndaj skedarin .ppset</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Eksporto .ppset (ruaj në disk)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Nuk ka ende asgjë këtu.
Trokit + Krijo për të shtuar një grup fjalësh ose bibliotekë.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Grup fjalësh</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Grup rregullash</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Krijo</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Gjuha e ndërfaqes</translation>
    </message>
    <message>
        <location line="-710"/>
        <location line="+796"/>
        <source>Cancel</source>
        <translation>Anulo</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Zgjidh llojin e testit</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Karta mësimore</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Ktheje për ta zbuluar — rrëshqit djathtas nëse e di</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Shkruaj fjalën</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Shiko ndihmën — shkruaj shprehjen</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Shkruaj ndihmën</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Shiko fjalën — shkruaj përkthimin e saj</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Zgjidh fjalën</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Shiko ndihmën — zgjidh nga 4 opsione</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Zgjidh ndihmën</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Shiko fjalën — zgjidh nga 4 opsione</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Mësim progresiv</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Zgjedhje e shumëfishtë për të mësuar, pastaj shkrim për të zotëruar të gjitha fjalët</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Mësim progresiv i përmbysur</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Zgjedhje e shumëfishtë për të mësuar, pastaj shkrim për të zotëruar të gjitha ndihmat</translation>
    </message>
    <message>
        <location line="+36"/>
        <location line="+82"/>
        <source>✓ Done</source>
        <translation>✓ U krye</translation>
    </message>
    <message>
        <location line="-82"/>
        <source>← Reset</source>
        <translation>← Rivendos</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Completed — swipe left to reset</source>
        <translation>Përfunduar — rrëshqit majtas për ta rivendosur</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>%1 left</source>
        <translation>Kanë mbetur %1</translation>
    </message>
    <message>
        <location line="+51"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Ashpërsia e drejtshkrimit</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Rreptë</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normale</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Tolerante</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Anulo</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Rishiko shprehjet</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Ndalo</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Dëgjo</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Fillo testin</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Ende pa fjalë</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Shkruaj ndihmën / përkthimin…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Shkruaj shprehjen…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Saktë: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Shëno si të saktë (gabova duke shkruar)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Dërgo</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Shëno si të saktë (klikova gabimisht)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Saktë: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Shiko rezultatet</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Tjetra →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Numri i pyetjes %1</translation>
    </message>
</context>
</TS>
