<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="fi">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Tietoja</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Sanastoharjoittelija sanastojen ulkoa oppimiseen.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Sanaston ja kieliopin harjoittelija.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Avoimen lähdekoodin lisenssit</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Tämä sovellus käyttää Qt:ta GNU Lesser General Public License -lisenssin version 3 alaisena.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Qt-ilmoitus</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Qt-ilmoitus</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Qt:n lähdekoodi</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Qt-projektin verkkosivusto</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Tekoälyn luoma — voi sisältää virheitä</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Ilmoita</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Kiitos — ilmoituksesi lähetettiin ja se tarkistetaan.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Ilmoita tekoälyn sisällöstä</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Mikä tässä luodussa sisällössä on vialla?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Seksuaalinen tai vihjaileva sisältö</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Kiroilu tai loukkaava kieli</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Vihamielinen tai häiritsevä sisältö</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Väkivaltainen tai vaarallinen sisältö</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Väärää tai harhaanjohtavaa tietoa</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Jokin muu</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Lisätiedot (valinnainen)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Lähetetään…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Sulje</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Peruuta</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Lähetä ilmoitus</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Ota kuva</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Peruuta</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>tulossa pian</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1 pv %2 t kuluttua</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1 t %2 min kuluttua</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1 min kuluttua</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Valitse kuva</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Valitse ääni</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Tuo sanasto</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Sanan kieli</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Vihjeen kieli</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+339"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Peruuta</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ Tekoälyn sanastogeneraattori</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Gemini-pohjainen</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Aihe</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Kuvaile haluamasi sanasto — esim. ”keittiötarvikkeita, joita löytyisi ranskalaisesta kodista” tai ”liikematkafraaseja konferenssia varten”…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Tässä kuussa jäljellä %1/%2 luontikertaa — palautuu %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>Tekoäly voi tehdä virheitä. Vain kaikenikäisille sopivaa sisältöä luodaan — ilmoita sopimattomasta sisällöstä painikkeella 🚩 Ilmoita.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Sanan kieli</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Vihjeen kieli</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Sanojen määrä</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Kysytään Geministä…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Peruuta pyyntö</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Luo</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ Tekoäly</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Uusi sanasto</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Muokkaa sanastoa</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Tuo</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Sanaston nimi…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Nouda kuvat automaattisesti</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Sana</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>valittu</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Sana / Termi</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Ei valittu</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Kirjoita sana...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Vihje / merkitys</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Vihje, määritelmä...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Käyttöesimerkki</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Esimerkkilause, jossa sana esiintyy...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Vaihda kuva</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Lisää kuva</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Nouda</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Kamera</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Lisää ääni</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Pysäytä</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Toista</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ Puhu</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Pysäytä</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Nauhoita</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Lisää sana</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Poista</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Tallenna</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Nimi vaaditaan</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>pian</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1pv %2t kuluttua</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1t %2min kuluttua</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1min kuluttua</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Valitse kuva</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Valitse ääni</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ Tekoäly</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Uusi sääntökokoelma</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Muokkaa sääntökokoelmaa</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Tuo</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Tuo sääntökokoelma</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ Tekoälyn sääntökokoelmageneraattori</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Tekniikan tarjoaa Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>%1/%2 luontikertaa jäljellä tässä kuussa — nollautuu %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Selitettävä sääntö/aihe</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Kuvaile haluamasi sääntö — esim. &quot;preesens vs. kestopreesens&quot; tai &quot;kolmannen tyypin ehtolauseet&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Kysymyksiä tyyppiä kohden</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Täytä aukko</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Monivalinta</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Pudotusvalikko</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Vedä ja pudota</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Kysytään Geminiltä…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Peruuta pyyntö</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Peruuta</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>Tekoäly voi tehdä virheitä. Vain kaikenikäisille sopivaa sisältöä luodaan — ilmoita sopimattomasta sisällöstä painikkeella 🚩 Ilmoita.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Luo</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Anna otsikko…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Teoriaselitys</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Piilotettu testin aikana, kunnes oppija tekee virheen — aina luettavissa esikatselussa.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Järjestä lohko uudelleen ▲▼-painikkeilla. Muuta kuvan kokoa vetämällä sen //-kulmasta.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Selitä sääntö, jota tämä kokoelma harjoittaa…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Ääniklippi</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Teksti</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Kuva</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Ääni</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Kysymys</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>valittu</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Täytä aukko</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Monivalinta</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Pudotusvalikko</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Vedä ja pudota</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Käytä ___ (kolme alaviivaa) jokaisessa aukossa, jonka oppija täyttää.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>esim. Mitä hän tekee joka päivä?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>esim. Hän menee ___ kouluun joka päivä.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Vastaukset</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Yksi vastaus aukkoa kohden, pilkuin eroteltuna, järjestyksessä. Käytä \, kirjaimellista pilkkua varten.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>esim. menee</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Vaihtoehdot</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Erota yhden aukon vaihtoehdot pilkuilla; erota aukot kaksoiskaksoispisteellä (::). Yksittäinen : on turvallinen sellaisenaan; käytä \, kirjaimellista pilkkua varten, \:: kirjaimellista ::-merkkiä varten ja ___ tarkoituksella tyhjää vaihtoehtoa varten. Esim. kahdelle aukolle: menee, mennä, menossa::jokainen, jotkut, useimmat.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Pilkuin eroteltuja vedettäviä laattoja — sisällytä oikeat vastaukset sekä valinnaisia harhautuksia, joilla oppijaa voi hämätä. Käytä \, kirjaimellista pilkkua varten ja ___ tyhjää laattaa varten (aukolle, jonka pitää oikein olla tyhjä). Täytä alla olevat aukot, kun nämä on asetettu.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>esim. menee, mennä, menossa::jokainen, jotkut, useimmat</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>esim. menee, mennä, menossa, mennyt</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Oikea vastaus jokaiselle aukolle</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Napauta oikeaa vaihtoehtoa kussakin alla olevassa ruudussa.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Valitse oikea vastaus jokaiselle aukolle.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Aukko %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Täytä aukot</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Vedä laatta alla olevaan aukkoon, tai napauta laattaa ja sitten aukkoa asettaaksesi sen.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Täytä jokainen aukko laatalla.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Pilkuin eroteltuja vaihtoehtoja — napauta oikeaa vastausta alla. Käytä \, kirjaimellista pilkkua varten.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Pilkuin eroteltuja vaihtoehtoja — napauta kaikkia oikeita vastauksia alla. Käytä \, kirjaimellista pilkkua varten.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>esim. menee, mennä, menossa, mennyt</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Vain yksi oikea vastaus</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Oikea vastaus</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Oikea(t) vastaus(et)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Valitse oikea vastaus.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Valitse vähintään yksi oikea vastaus.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Lisää kysymys</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Poista</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Tallenna</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Otsikko vaaditaan</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Selitä kielioppi</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Kysymystä %1 ei voitu ladata: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Vain %1 pyydetystä %2 kysymyksestä luotiin — kokeile laajempaa aihetta tai pienennä yllä olevia lukuja.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Selityksen kieli</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Selityksen kieli</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Aiheen kieli</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Aiheen kieli</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Tästä aiheesta ei voi luoda sisältöä. Tekoäly luo vain kaikenikäisille sopivaa sisältöä — seksuaalisia, rivoja tai loukkaavia aiheita ei tueta. Kokeile toista aihetta.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Olet käyttänyt kaikki tämän kuun tekoälyluonnit. Yritä uudelleen ensi kuussa.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Liian monta ilmoitusta tänään — yritä huomenna uudelleen.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Tekoälypalvelu on juuri nyt ruuhkautunut — yritä hetken kuluttua uudelleen.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Kirjoita ensin aihe.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Aihe on liian pitkä (enintään %1 merkkiä).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Aseta vähintään yhden kysymystyypin määräksi enemmän kuin nolla.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Istuntosi on vanhentunut — kirjaudu uudelleen sisään.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Palvelimeen ei saatu yhteyttä. Tarkista internetyhteys ja yritä uudelleen.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Jokin meni vikaan. Yritä uudelleen.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Et ole kirjautunut sisään.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Napauta kääntääksesi</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Napauta kääntääksesi takaisin</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>OSAAN</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>OHITA</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  En osaa</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Osaan</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Ei valittu</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Lisenssitekstiä ei voitu ladata.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Kirjaudu sisään jatkaaksesi</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Avataan selainta…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Kirjaudu sisään Googlella</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Tämän niminen kirjasto tai sanasto on jo täällä.</translation>
    </message>
    <message>
        <location line="+317"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Tämän niminen sanasto on jo täällä.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Tämän niminen sääntökokoelma on jo täällä.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+38"/>
        <source>Results</source>
        <translation>Tulokset</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>Well</source>
        <translation>Hienoa</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>done</source>
        <translation>työtä</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>/ %1</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Loistavaa työtä! Jatka samaan malliin!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Hyvä yritys! Jatka harjoittelua.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Älä luovuta – harjoitus tekee mestarin!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Tämä istunto</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>En osaa</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Osaan</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Practice again</source>
        <translation>Harjoittele uudelleen</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Find another set</source>
        <translation>Etsi toinen sarja</translation>
    </message>
    <message>
        <source>Practice Again</source>
        <translation type="vanished">Harjoittele uudelleen</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Nollataanko testin edistyminen?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Tämä tyhjentää edistymisesi tässä sääntökokoelmassa ja aloittaa uuden istunnon.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 kysymystä</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Valmis: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Kesken: %1 / %2</translation>
    </message>
    <message>
        <source>← Reset</source>
        <translation type="vanished">← Nollaa</translation>
    </message>
    <message>
        <location line="+185"/>
        <source>Reset to practise again</source>
        <translation>Nollaa ja harjoittele uudelleen</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Reset</source>
        <translation>Nollaa</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Säännön selitys</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Tälle kokoelmalle ei ole lisätty selitystä.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Ääniklippi</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Oikeinkirjoituksen tiukkuus</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Tiukka</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normaali</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Salliva</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Aloita testi</translation>
    </message>
    <message>
        <location line="-316"/>
        <source>Test is completed</source>
        <translation>Testi on suoritettu</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Seuraava kysymys: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Oikein: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Sääntö</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Säännön selitys</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Ääniklippi</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Peruuta</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Näytä sääntö</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Pyöritä pyörää valitaksesi jokaisen aukon sanan.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Aukko %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Vedä laatta aukkoon, tai napauta laattaa ja sitten aukkoa asettaaksesi sen.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Valitse oikea vastaus.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Valitse kaikki sopivat.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Oikein: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Lähetä</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Oikein: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Näytä tulokset</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Seuraava →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Kysymyksen numero %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Kirjoitetaanko sanasto päälle?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Yhdistetäänkö kirjastot?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Sanasto nimeltä ”%1” on jo täällä. Kirjoitetaanko se päälle siirretyllä sanastolla?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Kirjasto nimeltä ”%1” on jo täällä. Yhdistetäänkö sen sisältö tähän?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Sanasto nimeltä ”%1” on jo kohteessa %2. Kirjoitetaanko se päälle yhdistetyllä versiolla?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>kohdekirjasto</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Vie muodossa .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Uusi kirjasto</translation>
    </message>
    <message>
        <location line="+31"/>
        <source>Library name:</source>
        <translation>Kirjaston nimi:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>esim. Matkailu, Työ, Koulu…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Tämän niminen kirjasto tai sanasto on jo täällä.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+99"/>
        <source>A library with this name already exists here.</source>
        <translation>Tämän niminen kirjasto on jo täällä.</translation>
    </message>
    <message>
        <location line="-62"/>
        <source>Create</source>
        <translation>Luo</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Rename Library</source>
        <translation>Nimeä kirjasto uudelleen</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Uusi nimi:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Nimeä uudelleen</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Sanastosi</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Kirjasto</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Siirrä pois kohteesta</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Pudota siirtääksesi sisään</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>sanaa</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>kysymystä</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Poista kirjasto</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Muokkaa</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Poista</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Jaa .ppset-tiedosto</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Vie .ppset (tallenna levylle)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Täällä ei ole vielä mitään.
Napauta + Luo lisätäksesi sanaston tai kirjaston.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Sanasto</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Sääntökokoelma</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Luo</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Käyttöliittymän kieli</translation>
    </message>
    <message>
        <location line="-710"/>
        <location line="+796"/>
        <source>Cancel</source>
        <translation>Peruuta</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Valitse testin tyyppi</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Muistikortit</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Käännä paljastaaksesi — pyyhkäise oikealle, jos osaat sen</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Kirjoita sana</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Katso vihje — kirjoita ilmaus</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Kirjoita vihje</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Katso sana — kirjoita sen käännös</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Valitse sana</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Katso vihje — valitse 4 vaihtoehdosta</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Valitse vihje</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Katso sana — valitse 4 vaihtoehdosta</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Etenevä oppiminen</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Ensin monivalinta oppimiseen, sitten kirjoittaminen kaikkien sanojen hallitsemiseksi</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Käänteinen etenevä oppiminen</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Ensin monivalinta oppimiseen, sitten kirjoittaminen kaikkien vihjeiden hallitsemiseksi</translation>
    </message>
    <message>
        <location line="+36"/>
        <location line="+82"/>
        <source>✓ Done</source>
        <translation>✓ Valmis</translation>
    </message>
    <message>
        <location line="-82"/>
        <source>← Reset</source>
        <translation>← Nollaa</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Completed — swipe left to reset</source>
        <translation>Valmis — nollaa pyyhkäisemällä vasemmalle</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>%1 left</source>
        <translation>%1 jäljellä</translation>
    </message>
    <message>
        <location line="+51"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Oikeinkirjoituksen tiukkuus</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Tiukka</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normaali</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Salliva</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Peruuta</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Kertaa ilmaukset</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Pysäytä</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Kuuntele</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Aloita testi</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Ei vielä sanoja</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Kirjoita vihje / käännös…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Kirjoita ilmaus…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Oikein: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Merkitse oikeaksi (kirjoitin väärin)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Lähetä</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Merkitse oikeaksi (klikkasin väärin)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Oikein: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Näytä tulokset</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Seuraava →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Kysymyksen numero %1</translation>
    </message>
</context>
</TS>
