<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="eu">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Honi buruz</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Hiztegi-entrenatzailea hitz-sortak memorizatzeko.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Hiztegi eta gramatika entrenatzailea.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Iturburu irekiko lizentziak</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Aplikazio honek Qt erabiltzen du GNU Lesser General Public License 3 bertsioaren lizentziapean.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Qt jakinarazpena</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Qt jakinarazpena</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Qt iturburu-kodea</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Qt proiektuaren webgunea</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ AIak sortua — akatsak izan ditzake</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Salatu</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Eskerrik asko — zure salaketa bidali da eta berrikusi egingo da.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Salatu AI edukia</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Zer du gaizki sortutako eduki honek?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Eduki sexuala edo iradokitzailea</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Hitz itsusiak edo hizkera iraingarria</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Gorroto- edo jazarpen-edukia</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Eduki bortitza edo arriskutsua</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Informazio okerra edo engainagarria</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Beste zerbait</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Xehetasunak (aukerakoa)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Bidaltzen…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Itxi</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Utzi</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Bidali salaketa</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Argazkia atera</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Utzi</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>laster</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1e %2o barru</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1o %2min barru</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1min barru</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Irudia hautatu</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Audioa hautatu</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Hitz-sorta inportatu</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Hitzaren hizkuntza</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Pistaren hizkuntza</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+339"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Utzi</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ AI hitz-sorta sortzailea</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Gemini-k eragindakoa</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Gaia</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Deskribatu nahi duzun sorta — adib. «etxe frantses batean aurkituko zenituzkeen sukaldeko tresnak» edo «konferentzia batera negozio-bidaiarako esaldiak»…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>%1/%2 sorkuntza geratzen dira hilabete honetan — %3(e)an berrezarriko da</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AIak akatsak egin ditzake. Adin guztietarako egokia den edukia soilik sortzen da — erabili 🚩 Salatu desegokia den edozer adierazteko.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Hitzaren hizkuntza</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Pistaren hizkuntza</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Hitz kopurua</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Gemini-ri galdetzen…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Eskaera bertan behera utzi</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Sortu</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Hitz-sorta berria</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Hitz-sorta editatu</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Inportatu</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Sortaren izenburua…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Irudiak automatikoki eskuratu</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Hitza</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>hautatuta</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Hitza / Terminoa</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Hautatu gabe</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Sartu hitza...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Pista / esanahia</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Pista, definizioa...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Erabilera-adibidea</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Adibide-esaldia hitza erabiliz...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Irudia aldatu</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Irudia gehitu</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Eskuratu</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Kamera</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Audioa gehitu</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Gelditu</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Erreproduzitu</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ Ahots-irakurketa</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Gelditu</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Grabatu</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Hitza gehitu</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Kendu</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Gorde</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Izenburua beharrezkoa da</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>laster</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1e %2o barru</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1o %2m barru</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1m barru</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Hautatu irudia</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Hautatu audioa</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Arau-multzo berria</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Editatu arau-multzoa</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Inportatu</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Inportatu arau-multzoa</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ AI arau-multzo sortzailea</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Gemini bidez hornitua</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>%1/%2 sorkuntza geratzen dira hilabete honetan — %3 berrezartzen da</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Azaldu beharreko araua/gaia</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Deskribatu nahi duzun araua — adib. &quot;present simple vs present continuous&quot; edo &quot;hirugarren motako baldintzazko esaldiak&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Galderak motaka</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Bete hutsunea</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Aukera anitzeko</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Goitibeherako aukera</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Arrastatu eta jaregin</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Gemini galdetzen…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Utzi eskaera</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Utzi</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AIak akatsak egin ditzake. Adin guztietarako egokia den edukia soilik sortzen da — erabili 🚩 Salatu desegokia den edozer adierazteko.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Sortu</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Sartu izenburua…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Teoriaren azalpena</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Ezkutatuta probaldian ikasleak akats bat egin arte — beti irakurgarri aurrebistan.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Erabili ▲▼ bloke bat berrantolatzeko. Arrastatu argazki baten // izkina tamaina aldatzeko.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Azaldu multzo honek lantzen duen araua…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Audio-klipa</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Testua</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Argazkia</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Audioa</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Galdera</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>hautatuta</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Bete hutsunea</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Aukera anitzeko</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Goitibeherako aukera</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Arrastatu eta jaregin</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Erabili ___ (hiru azpimarra) ikasleak betetzen duen hutsune bakoitzarentzat.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>adib. Zer egiten du egunero?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>adib. Eskolara ___ doa egunero.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Erantzunak</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Erantzun bat hutsune bakoitzeko, komaz bereizita, ordenan. Erabili \, koma literal baterako.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>adib. doa</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Aukerak</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Bereizi hutsune bateko aukerak komaz; bereizi hutsuneak bi puntu bikoitzez (::). : bakarra segurua da dagoen bezala; erabili \, koma literal baterako, \:: :: literal baterako, eta ___ nahita hutsik dagoen aukera baterako. Adib. bi hutsunerentzat: doa, joan, joaten::bakoitza, batzuk, gehienak.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Komaz bereizitako arrastatzeko fitxak — sartu erantzun zuzenak, gehi aukerako amuak, horiekin ikaslea nahas daitekeela. Erabili \, koma literal baterako, eta ___ fitxa huts baterako (zuzen hutsik geratu behar duen hutsune baterako). Bete beheko hutsuneak hauek ezarri bezain laster.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>adib. doa, joan, joaten::bakoitza, batzuk, gehienak</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>adib. doa, joan, joaten, joan da</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Erantzun zuzena hutsune bakoitzeko</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Ukitu erantzun zuzena beheko kutxa bakoitzean.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Hautatu erantzun zuzen bat hutsune bakoitzerako.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Hutsunea %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Bete hutsuneak</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Arrastatu fitxa bat beheko hutsune batera, edo ukitu fitxa bat eta gero hutsune bat kokatzeko.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Bete hutsune bakoitza fitxa batekin.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Komaz bereizitako aukerak — ukitu beheko erantzun zuzena. Erabili \, koma literal baterako.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Komaz bereizitako aukerak — ukitu beheko erantzun zuzen guztiak. Erabili \, koma literal baterako.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>adib. doa, joan, joaten, joan da</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Erantzun zuzen bakarra</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Erantzun zuzena</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Erantzun zuzena(k)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Hautatu erantzun zuzena.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Hautatu gutxienez erantzun zuzen bat.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Gehitu galdera</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Kendu</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Gorde</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Izenburua beharrezkoa da</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Azaldu gramatika</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Ezin izan da %1 galdera kargatu: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Eskatutako %2 galderatik %1 bakarrik sortu dira — probatu gai zabalago bat, edo murriztu goiko kopuruak.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Azalpenaren hizkuntza</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Azalpenaren hizkuntza</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Gaiaren hizkuntza</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Gaiaren hizkuntza</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Gai hau ezin da sortu. AIak adin guztietarako egokia den edukia soilik sortzen du — gai sexualak, zakarrak edo iraingarriak ez dira onartzen. Saiatu beste gai batekin.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Hilabete honetako AI sorkuntza guztiak erabili dituzu. Saiatu berriro hurrengo hilabetean.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Salaketa gehiegi gaur — saiatu berriro bihar.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>AI zerbitzua lanpetuta dago une honetan — saiatu berriro une batean.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Idatzi gai bat lehenik.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Gaia luzeegia da (gehienez %1 karaktere).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Ezarri gutxienez galdera mota bat zero baino gehiagotan.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Saioa iraungi da — hasi saioa berriro.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Ezin izan da zerbitzariarekin konektatu. Egiaztatu interneteko konexioa eta saiatu berriro.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Zerbait gaizki joan da. Saiatu berriro.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Ez da saioa hasi.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Ukitu iraultzeko</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Ukitu atzera itzultzeko</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>BADAKIT</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>SALTATU</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Ez dakit</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Badakit</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Hautatu gabe</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Ezin izan da lizentziaren testua kargatu.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Hasi saioa jarraitzeko</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Nabigatzailea irekitzen…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Hasi saioa Google-rekin</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Izen hori duen liburutegi edo sorta bat badago hemen jada.</translation>
    </message>
    <message>
        <location line="+317"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Izen hori duen hitz-sorta bat badago hemen jada.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Izen hori duen arau-multzo bat badago hemen jada.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+38"/>
        <source>Results</source>
        <translation>Emaitzak</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>Well</source>
        <translation>Oso</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>done</source>
        <translation>ondo</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>%1etik</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Lan bikaina! Jarraitu horrela!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Ahalegin ona! Jarraitu praktikatzen.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Ez etsi – praktikak bikaintasuna dakar!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Saio hau</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Ez dakit</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Badakit</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Practice again</source>
        <translation>Praktikatu berriro</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Find another set</source>
        <translation>Bilatu beste multzo bat</translation>
    </message>
    <message>
        <source>Practice Again</source>
        <translation type="vanished">Praktikatu berriro</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Probaren aurrerapena berrezarri?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Honek arau-multzo honetako zure aurrerapena garbituko du eta saio berri bat hasiko du.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 galdera</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Amaituta: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Martxan: %1 / %2</translation>
    </message>
    <message>
        <source>← Reset</source>
        <translation type="vanished">← Berrezarri</translation>
    </message>
    <message>
        <location line="+185"/>
        <source>Reset to practise again</source>
        <translation>Berrezarri berriro praktikatzeko</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Reset</source>
        <translation>Berrezarri</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Arauaren azalpena</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Ez da azalpenik gehitu multzo honetarako.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Audio-klipa</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Ortografiaren zorroztasuna</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Zorrotza</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Arrunta</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Malgua</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Hasi proba</translation>
    </message>
    <message>
        <location line="-316"/>
        <source>Test is completed</source>
        <translation>Proba osatuta dago</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Hurrengo galdera: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Zuzena: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Araua</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Arauaren azalpena</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Audio-klipa</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Utzi</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Ikusi araua</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Biratu gurpila hutsune bakoitzeko hitza aukeratzeko.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Hutsunea %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Arrastatu fitxa bat hutsune batera, edo ukitu fitxa bat eta gero hutsune bat kokatzeko.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Hautatu erantzun zuzena.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Hautatu bat datozen guztiak.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Zuzena: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Bidali</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Zuzena: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Ikusi emaitzak</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Hurrengoa →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>%1 galdera zenbakia</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Hitz-sorta gainidatzi?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Liburutegiak batu?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>«%1» izeneko hitz-sorta bat badago hemen jada. Lekuz aldatutako sortarekin gainidatzi?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>«%1» izeneko liburutegi bat badago hemen jada. Bere edukia honekin batu?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>«%1» izeneko hitz-sorta bat badago jada %2(e)n. Batutako bertsioarekin gainidatzi?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>helmugako liburutegia</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Esportatu .ppset gisa</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Liburutegi berria</translation>
    </message>
    <message>
        <location line="+31"/>
        <source>Library name:</source>
        <translation>Liburutegiaren izena:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>adib. Bidaiak, Lana, Eskola…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Izen hori duen liburutegi edo sorta bat badago hemen jada.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+99"/>
        <source>A library with this name already exists here.</source>
        <translation>Izen hori duen liburutegi bat badago hemen jada.</translation>
    </message>
    <message>
        <location line="-62"/>
        <source>Create</source>
        <translation>Sortu</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Rename Library</source>
        <translation>Liburutegia berrizendatu</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Izen berria:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Berrizendatu</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Zure hitz-sortak</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Liburutegia</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Atera hemendik</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Askatu barrura mugitzeko</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>hitz</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>galdera</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Liburutegia ezabatu</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Editatu</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Ezabatu</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>.ppset fitxategia partekatu</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>.ppset esportatu (diskoan gorde)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Ez dago ezer hemen oraindik.
Ukitu + Sortu hitz-sorta edo liburutegi bat gehitzeko.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Hitz-sorta</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Arau-multzoa</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Sortu</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Interfazearen hizkuntza</translation>
    </message>
    <message>
        <location line="-710"/>
        <location line="+796"/>
        <source>Cancel</source>
        <translation>Utzi</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Aukeratu proba mota</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Fitxa mnemoteknikoak</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Iraul agerian jartzeko — pasatu hatza eskuinera badakizu</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Idatzi hitza</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Ikusi pista — idatzi esapidea</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Idatzi pista</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Ikusi hitza — idatzi haren itzulpena</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Aukeratu hitza</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Ikusi pista — aukeratu 4 aukeren artean</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Aukeratu pista</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Ikusi hitza — aukeratu 4 aukeren artean</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Ikaskuntza progresiboa</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Aukera anitzeko galderak lehenengo ikasteko, gero idatzi hitz guztiak menderatzeko</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Alderantzizko ikaskuntza progresiboa</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Aukera anitzeko galderak lehenengo ikasteko, gero idatzi pista guztiak menderatzeko</translation>
    </message>
    <message>
        <location line="+36"/>
        <location line="+82"/>
        <source>✓ Done</source>
        <translation>✓ Eginda</translation>
    </message>
    <message>
        <location line="-82"/>
        <source>← Reset</source>
        <translation>← Berrezarri</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Completed — swipe left to reset</source>
        <translation>Osatuta — irristatu ezkerrera berrezartzeko</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>%1 left</source>
        <translation>%1 falta dira</translation>
    </message>
    <message>
        <location line="+51"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Ortografiaren zorroztasuna</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Zorrotza</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Arrunta</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Malgua</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Utzi</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Berrikusi esapideak</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Gelditu</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Entzun</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Hasi proba</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Oraindik ez dago hitzik</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Idatzi pista / itzulpena…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Idatzi esapidea…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Zuzena: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Zuzentzat markatu (gaizki idatzi dut)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Bidali</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Zuzentzat markatu (gaizki klikatu dut)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Zuzena: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Ikusi emaitzak</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Hurrengoa →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>%1 galdera zenbakia</translation>
    </message>
</context>
</TS>
