<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="sw">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Kuhusu</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Mkufunzi wa msamiati kwa kukumbuka seti za maneno.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Mkufunzi wa msamiati na sarufi.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Leseni za Chanzo Huria</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Programu hii inatumia Qt chini ya leseni ya GNU Lesser General Public License toleo la 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Ilani ya Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Ilani ya Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Msimbo chanzi wa Qt</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Tovuti ya mradi wa Qt</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Imeundwa na AI — huenda ikawa na makosa</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Ripoti</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Asante — ripoti yako imetumwa na itakaguliwa.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Ripoti maudhui ya AI</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Kuna tatizo gani na maudhui haya yaliyoundwa?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Maudhui ya ngono au ya kuashiria ngono</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Matusi au lugha ya kuudhi</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Maudhui ya chuki au unyanyasaji</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Maudhui ya vurugu au hatari</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Taarifa zisizo sahihi au za kupotosha</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Kitu kingine</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Maelezo (si lazima)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Inatuma…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Funga</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Ghairi</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Tuma ripoti</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Piga Picha</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Ghairi</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>hivi karibuni</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>baada ya siku %1 saa %2</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>baada ya saa %1 dakika %2</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>baada ya dakika %1</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Chagua Picha</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Chagua Sauti</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Leta Seti ya Maneno</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Lugha ya Neno</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Lugha ya Dokezo</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+339"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Ghairi</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ Kitengenezaji cha Seti za Maneno cha AI</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Inaendeshwa na Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Mada</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Eleza seti unayotaka — mfano “vifaa vya jikoni ambavyo unaweza kuvipata katika nyumba ya Kifaransa” au “misemo ya safari za kikazi kwa mkutano”…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Zimebaki %1 kati ya %2 za kuunda mwezi huu — itaanza upya %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI inaweza kukosea. Maudhui yanayofaa rika zote pekee ndiyo huundwa — tumia 🚩 Ripoti kuashiria chochote kisichofaa.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Lugha ya neno</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Lugha ya dokezo</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Idadi ya maneno</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Kuuliza Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Ghairi Ombi</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Tengeneza</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Seti Mpya ya Maneno</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Hariri Seti ya Maneno</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Leta</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Kichwa cha seti…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Pakua picha kiotomatiki</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Neno</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>limechaguliwa</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Neno / Neno la Kiufundi</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Halijachaguliwa</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Weka neno...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Dokezo / maana</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Dokezo, ufafanuzi...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Mfano wa matumizi</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Sentensi ya mfano inayotumia neno...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Badilisha picha</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Ongeza picha</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Pakua</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Kamera</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Ongeza sauti</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Simamisha</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Cheza</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ Sema</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Simamisha</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Rekodi</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Ongeza neno</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Ondoa</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Hifadhi</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Kichwa kinahitajika</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>hivi karibuni</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>baada ya %1s %2m</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>baada ya %1m %2d</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>baada ya %1d</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Chagua Picha</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Chagua Sauti</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Seti Mpya ya Sheria</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Hariri Seti ya Sheria</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Ingiza</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Ingiza Seti ya Sheria</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ Kizalishi cha Seti za Sheria za AI</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Inaendeshwa na Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Zimebaki %1 kati ya %2 uzalishaji mwezi huu — itawekwa upya %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Sheria/mada ya kueleza</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Eleza sheria unayotaka — mf. &quot;present simple dhidi ya present continuous&quot; au &quot;sentensi za masharti aina ya tatu&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Maswali kwa kila aina</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Jaza Nafasi Wazi</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Chaguo Nyingi</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Chaguo la Kushusha</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Buruta na Uachie</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Inauliza Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Ghairi ombi</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Ghairi</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI inaweza kukosea. Maudhui yanayofaa rika zote pekee ndiyo huundwa — tumia 🚩 Ripoti kuashiria chochote kisichofaa.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Zalisha</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Weka kichwa…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Maelezo ya Nadharia</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Imefichwa wakati wa mtihani hadi mwanafunzi afanye kosa — daima inasomeka kwenye hakikisho.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Tumia ▲▼ kupanga upya kizuizi. Buruta kona ya // ya picha ili kubadilisha ukubwa wake.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Eleza sheria ambayo seti hii inafanyiza mazoezi…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Kipande cha sauti</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Maandishi</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Picha</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Sauti</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Swali</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>limechaguliwa</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Jaza Nafasi Wazi</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Chaguo Nyingi</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Chaguo la Kushusha</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Buruta na Uachie</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Tumia ___ (mistari mitatu ya chini) kwa kila nafasi wazi ambayo mwanafunzi anajaza.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>mf. Anafanya nini kila siku?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>mf. Yeye huenda shuleni ___ kila siku.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Majibu</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Jibu moja kwa kila nafasi wazi, likitenganishwa na koma, kwa mpangilio. Tumia \, kwa koma halisi.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>mf. anaenda</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Chaguo</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Tenganisha chaguo za nafasi wazi moja kwa koma; tenganisha nafasi wazi kwa nukta mbili mara mbili (::). : moja ni salama kama ilivyo; tumia \, kwa koma halisi, \:: kwa :: halisi, na ___ kwa chaguo tupu kimakusudi. Mf. kwa nafasi wazi mbili: anaenda, kwenda, akienda::kila, baadhi, wengi.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Vigae vinavyoweza kuburutwa vikitenganishwa na koma — jumuisha majibu sahihi, pamoja na vishawishi vya hiari ambavyo mwanafunzi anaweza kudanganywa navyo. Tumia \, kwa koma halisi, na ___ kwa kigae tupu (kwa nafasi wazi ambayo inapaswa kubaki tupu kwa usahihi). Jaza nafasi wazi hapa chini mara hizi zikiwekwa.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>mf. anaenda, kwenda, akienda::kila, baadhi, wengi</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>mf. anaenda, kwenda, akienda, alienda</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Jibu sahihi kwa kila nafasi wazi</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Gusa chaguo sahihi katika kila kisanduku hapa chini.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Chagua jibu sahihi kwa kila nafasi wazi.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Nafasi Wazi %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Jaza nafasi wazi</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Buruta kigae kwenye nafasi wazi hapa chini, au gusa kigae kisha nafasi wazi ili kukiweka.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Jaza kila nafasi wazi na kigae.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Chaguo zikitenganishwa na koma — gusa jibu sahihi hapa chini. Tumia \, kwa koma halisi.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Chaguo zikitenganishwa na koma — gusa majibu yote sahihi hapa chini. Tumia \, kwa koma halisi.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>mf. anaenda, kwenda, akienda, alienda</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Jibu sahihi moja tu</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Jibu sahihi</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Jibu/majibu sahihi</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Chagua jibu sahihi.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Chagua angalau jibu moja sahihi.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Ongeza swali</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Ondoa</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Hifadhi</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Kichwa kinahitajika</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Eleza sarufi</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Imeshindwa kupakia swali la %1: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Maswali %1 tu kati ya %2 yaliyoombwa yalitengenezwa — jaribu mada pana zaidi, au punguza idadi hapo juu.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Lugha ya maelezo</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Lugha ya maelezo</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Lugha ya mada</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Lugha ya mada</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Mada hii haiwezi kuundwa. AI huunda maudhui yanayofaa rika zote pekee — mada za ngono, matusi au za kuudhi hazitumiki. Tafadhali jaribu mada nyingine.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Umetumia uundaji wote wa AI wa mwezi huu. Jaribu tena mwezi ujao.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Ripoti nyingi mno leo — tafadhali jaribu tena kesho.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Huduma ya AI ina shughuli nyingi sasa hivi — tafadhali jaribu tena baada ya muda mfupi.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Weka mada kwanza.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Mada ni ndefu mno (kiwango cha juu ni herufi %1).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Weka angalau aina moja ya swali juu ya sifuri.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Muda wa kipindi chako umeisha — tafadhali ingia tena.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Imeshindwa kufikia seva. Angalia muunganisho wako wa intaneti kisha ujaribu tena.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Hitilafu imetokea. Tafadhali jaribu tena.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Hujaingia.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Gusa ili kugeuza</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Gusa ili kurudisha nyuma</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>NINAJUA</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>RUKA</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Sijui</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Ninajua</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Halijachaguliwa</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Imeshindikana kupakia maandishi ya leseni.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Ingia ili kuendelea</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Inafungua kivinjari…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Ingia kwa Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Maktaba au seti yenye jina hili tayari ipo hapa.</translation>
    </message>
    <message>
        <location line="+317"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Seti ya maneno yenye jina hili tayari ipo hapa.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Seti ya sheria yenye jina hili tayari ipo hapa.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+38"/>
        <source>Results</source>
        <translation>Matokeo</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>Well</source>
        <translation>Kazi</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>done</source>
        <translation>nzuri</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>kati ya %1</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Kazi nzuri sana! Endelea hivyo!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Jitihada nzuri! Endelea kufanya mazoezi.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Usikate tamaa – mazoezi hukamilisha!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Kipindi hiki</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Sijui</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Ninajua</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Practice again</source>
        <translation>Fanya mazoezi tena</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Find another set</source>
        <translation>Tafuta seti nyingine</translation>
    </message>
    <message>
        <source>Practice Again</source>
        <translation type="vanished">Fanya Mazoezi Tena</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Weka upya maendeleo ya mtihani?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Hii itafuta maendeleo yako kwenye seti hii ya sheria na kuanza kipindi kipya.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">Maswali %1</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Imekamilika: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Inaendelea: %1 / %2</translation>
    </message>
    <message>
        <source>← Reset</source>
        <translation type="vanished">← Weka upya</translation>
    </message>
    <message>
        <location line="+185"/>
        <source>Reset to practise again</source>
        <translation>Weka upya ili kufanya mazoezi tena</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Reset</source>
        <translation>Weka Upya</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Maelezo ya Sheria</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Hakuna maelezo yaliyoongezwa kwa seti hii.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Kipande cha sauti</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Ukali wa tahajia</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Kali</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Kawaida</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Rahisi</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Anza Mtihani</translation>
    </message>
    <message>
        <location line="-316"/>
        <source>Test is completed</source>
        <translation>Mtihani umekamilika</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Swali linalofuata: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Sahihi: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Sheria</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Maelezo ya Sheria</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Kipande cha sauti</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Ghairi</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Angalia sheria</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Zungusha gurudumu kuchagua neno la kila nafasi wazi.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Nafasi Wazi %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Buruta kigae kwenye nafasi wazi, au gusa kigae kisha nafasi wazi ili kukiweka.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Chagua jibu sahihi.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Chagua yote yanayotumika.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Sahihi: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Wasilisha</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Sahihi: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Angalia Matokeo</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Ifuatayo →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Nambari ya swali %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Andika upya seti ya maneno?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Unganisha maktaba?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Seti ya maneno yenye jina “%1” tayari ipo hapa. Iandike upya kwa seti iliyohamishwa?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Maktaba yenye jina “%1” tayari ipo hapa. Unganisha maudhui yake ndani yake?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Seti ya maneno yenye jina “%1” tayari ipo katika %2. Iandike upya kwa toleo lililounganishwa?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>maktaba lengwa</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Hamisha kama .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Maktaba Mpya</translation>
    </message>
    <message>
        <location line="+31"/>
        <source>Library name:</source>
        <translation>Jina la maktaba:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>mfano Safari, Kazi, Shule…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Maktaba au seti yenye jina hili tayari ipo hapa.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+99"/>
        <source>A library with this name already exists here.</source>
        <translation>Maktaba yenye jina hili tayari ipo hapa.</translation>
    </message>
    <message>
        <location line="-62"/>
        <source>Create</source>
        <translation>Unda</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Rename Library</source>
        <translation>Badilisha Jina la Maktaba</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Jina jipya:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Badilisha Jina</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Seti zako za maneno</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Maktaba</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Hamisha nje ya</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Dondosha ili kuhamisha ndani</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>maneno</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>maswali</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Futa Maktaba</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Hariri</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Futa</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Shiriki faili la .ppset</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Hamisha .ppset (hifadhi kwenye diski)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Hakuna kitu hapa bado.
Gusa + Unda ili kuongeza seti ya maneno au maktaba.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Seti ya Maneno</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Seti ya Sheria</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Unda</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Lugha ya Kiolesura</translation>
    </message>
    <message>
        <location line="-710"/>
        <location line="+796"/>
        <source>Cancel</source>
        <translation>Ghairi</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Chagua Aina ya Jaribio</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Kadi za Kumbukumbu</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Geuza ili kufichua — telezesha kulia ikiwa unajua</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Andika Neno</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Angalia dokezo — andika usemi</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Andika Dokezo</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Angalia neno — andika tafsiri yake</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Chagua Neno</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Angalia dokezo — chagua kati ya chaguo 4</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Chagua Dokezo</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Angalia neno — chagua kati ya chaguo 4</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Ujifunzaji Endelevu</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Chaguo nyingi kwanza kujifunza, kisha kuandika kubobea maneno yote</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Ujifunzaji Endelevu wa Kinyume</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Chaguo nyingi kwanza kujifunza, kisha kuandika kubobea dokezo zote</translation>
    </message>
    <message>
        <location line="+36"/>
        <location line="+82"/>
        <source>✓ Done</source>
        <translation>✓ Imekamilika</translation>
    </message>
    <message>
        <location line="-82"/>
        <source>← Reset</source>
        <translation>← Weka Upya</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Completed — swipe left to reset</source>
        <translation>Imekamilika — telezesha kushoto ili kuweka upya</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>%1 left</source>
        <translation>Zimebaki %1</translation>
    </message>
    <message>
        <location line="+51"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Ukali wa tahajia</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Kali</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Kawaida</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Rahisi</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Ghairi</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Pitia Misemo Tena</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Simamisha</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Sikiliza</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Anza Jaribio</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Hakuna maneno bado</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Andika dokezo / tafsiri…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Andika usemi…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Sahihi: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Weka alama kuwa sahihi (nimekosea kuandika)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Wasilisha</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Weka alama kuwa sahihi (nimebonyeza vibaya)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Sahihi: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Angalia Matokeo</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Ifuatayo →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Nambari ya swali %1</translation>
    </message>
</context>
</TS>
