<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="tr">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Hakkında</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Kelime setlerini ezberlemek için kelime dağarcığı eğitmeni.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Kelime dağarcığı ve dil bilgisi eğitmeni.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Açık Kaynak Lisansları</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Bu uygulama, Qt&apos;yi GNU Lesser General Public License sürüm 3 altında kullanmaktadır.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Qt bildirimi</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Qt bildirimi</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Qt kaynak kodu</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Qt proje web sitesi</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Yapay zeka tarafından oluşturuldu — hata içerebilir</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Bildir</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Teşekkürler — bildiriminiz gönderildi ve incelenecek.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Yapay zeka içeriğini bildir</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Oluşturulan bu içerikte sorun ne?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Cinsel veya müstehcen içerik</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Küfür veya saldırgan dil</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Nefret söylemi veya taciz içeren içerik</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Şiddet içeren veya tehlikeli içerik</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Yanlış veya yanıltıcı bilgi</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Başka bir şey</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Ayrıntılar (isteğe bağlı)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Gönderiliyor…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Kapat</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>İptal</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Bildirimi gönder</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Fotoğraf Çek</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>İptal</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>yakında</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1g %2s içinde</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1s %2dk içinde</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1dk içinde</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Görsel Seç</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Ses Seç</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Kelime Setini İçe Aktar</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Kelime Dili</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>İpucu Dili</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+326"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>İptal</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ Yapay Zeka Kelime Seti Oluşturucu</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Gemini destekli</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Konu</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>İstediğiniz seti tanımlayın — örn. «bir Fransız evinde bulabileceğiniz mutfak eşyaları» veya «bir konferans için iş seyahati ifadeleri»…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Bu ay %2 üretimden %1 kaldı — %3 tarihinde sıfırlanır</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>Yapay zeka hata yapabilir. Yalnızca her yaşa uygun içerik oluşturulur — uygunsuz bir şeyi bildirmek için 🚩 Bildir&apos;i kullanın.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Kelime dili</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>İpucu dili</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Kelime sayısı</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Gemini&apos;ye soruluyor…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>İsteği İptal Et</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Oluştur</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ Yapay Zeka</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Yeni Kelime Seti</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Kelime Setini Düzenle</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>İçe Aktar</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Set başlığı…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Görselleri otomatik getir</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Kelime</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>seçildi</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Kelime / Terim</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Seçilmedi</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Kelime girin...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>İpucu / anlam</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>İpucu, tanım...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Kullanım örneği</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Kelimeyi kullanan örnek cümle...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Görseli değiştir</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Görsel ekle</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Getir</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Kamera</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Ses ekle</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Durdur</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Oynat</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ Seslendir</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Durdur</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Kaydet</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Kelime ekle</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Kaldır</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Kaydet</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Başlık gereklidir</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>yakında</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1g %2s içinde</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1s %2dk içinde</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1dk içinde</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Görsel Seç</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Ses Seç</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ Yapay Zeka</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Yeni Kural Seti</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Kural Setini Düzenle</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>İçe Aktar</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Kural Seti İçe Aktar</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ Yapay Zeka Kural Seti Oluşturucu</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Gemini destekli</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Bu ay %2 üretimden %1 kaldı — %3 tarihinde sıfırlanır</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Açıklanacak kural/konu</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>İstediğiniz kuralı tanımlayın — örn. &quot;geniş zaman ile şimdiki zaman&quot; veya &quot;üçüncü tip koşul cümleleri&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Türe göre soru sayısı</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Boşluğu Doldur</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Çoktan Seçmeli</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Açılır Seçim</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Sürükle ve Bırak</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Gemini&apos;ye soruluyor…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>İsteği iptal et</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>İptal</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>Yapay zeka hata yapabilir. Yalnızca her yaşa uygun içerik oluşturulur — uygunsuz bir şeyi bildirmek için 🚩 Bildir&apos;i kullanın.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Oluştur</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Başlık girin…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Teori Açıklaması</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Öğrenci hata yapana kadar test sırasında gizlidir — önizlemede her zaman okunabilir.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Bir bloğu yeniden sıralamak için ▲▼ kullanın. Bir fotoğrafı yeniden boyutlandırmak için // köşesini sürükleyin.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Bu setin pratik yaptığı kuralı açıklayın…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Ses klibi</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Metin</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Fotoğraf</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Ses</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Soru</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>seçildi</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Boşluğu Doldur</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Çoktan Seçmeli</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Açılır Seçim</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Sürükle ve Bırak</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Öğrencinin dolduracağı her boşluk için ___ (üç alt çizgi) kullanın.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>örn. Her gün ne yapar?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>örn. Her gün okula ___ gider.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Cevaplar</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Her boşluk için bir cevap, virgülle ayrılmış, sırayla. Gerçek virgül için \, kullanın.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>örn. gider</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Seçenekler</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Bir boşluğun seçeneklerini virgülle ayırın; boşlukları çift iki nokta üst üste (::) ile ayırın. Tek bir : olduğu gibi güvenlidir; gerçek virgül için \,, gerçek :: için \::, ve kasıtlı olarak boş bir seçenek için ___ kullanın. Örn. iki boşluk için: gider, gitmek, giderken::her, bazı, çoğu.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Virgülle ayrılmış sürüklenebilir karolar — doğru cevapları, artı öğrencinin kandırılabileceği isteğe bağlı yem seçenekleri ekleyin. Gerçek virgül için \, ve boş karo için ___ kullanın (doğru şekilde boş kalması gereken bir boşluk için). Bunlar ayarlandıktan sonra aşağıdaki boşlukları doldurun.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>örn. gider, gitmek, giderken::her, bazı, çoğu</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>örn. gider, gitmek, giderken, gitti</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Her boşluk için doğru cevap</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Aşağıdaki her kutuda doğru seçeneğe dokunun.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Her boşluk için doğru bir cevap seçin.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Boşluk %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Boşlukları doldurun</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Bir karoyu aşağıdaki bir boşluğa sürükleyin veya yerleştirmek için bir karoya, ardından bir boşluğa dokunun.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Her boşluğu bir karoyla doldurun.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Virgülle ayrılmış seçenekler — aşağıdaki doğru cevaba dokunun. Gerçek virgül için \, kullanın.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Virgülle ayrılmış seçenekler — aşağıdaki tüm doğru cevaplara dokunun. Gerçek virgül için \, kullanın.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>örn. gider, gitmek, giderken, gitti</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Yalnızca bir doğru cevap</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Doğru cevap</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Doğru cevap(lar)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Doğru cevabı seçin.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>En az bir doğru cevap seçin.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Soru ekle</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Kaldır</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Kaydet</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Başlık gerekli</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Grameri açıkla</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>%1 sorusu yüklenemedi: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>İstenen %2 sorudan yalnızca %1 tanesi oluşturuldu — daha geniş bir konu deneyin veya yukarıdaki sayıları azaltın.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Açıklama dili</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Açıklama dili</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Konu dili</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Konu dili</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Bu konu oluşturulamaz. Yapay zeka yalnızca her yaşa uygun içerik oluşturur — cinsel, kaba veya saldırgan konular desteklenmez. Lütfen farklı bir konu deneyin.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Bu ayki tüm yapay zeka oluşturma hakkınızı kullandınız. Gelecek ay tekrar deneyin.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Bugün çok fazla bildirim yapıldı — lütfen yarın tekrar deneyin.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Yapay zeka hizmeti şu anda yoğun — lütfen biraz sonra tekrar deneyin.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Önce bir konu girin.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Konu çok uzun (en fazla %1 karakter).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>En az bir soru türünü sıfırın üzerine ayarlayın.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Oturumunuzun süresi doldu — lütfen tekrar oturum açın.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Sunucuya ulaşılamadı. İnternet bağlantınızı kontrol edip tekrar deneyin.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Bir sorun oluştu. Lütfen tekrar deneyin.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Oturum açılmadı.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Çevirmek için dokunun</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Geri çevirmek için dokunun</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>BİLİYORUM</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>GEÇ</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Bilmiyorum</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Biliyorum</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Seçilmedi</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Lisans metni yüklenemedi.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Devam etmek için oturum açın</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Tarayıcı açılıyor…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Google ile oturum açın</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Bu ada sahip bir kütüphane veya set burada zaten mevcut.</translation>
    </message>
    <message>
        <location line="+309"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Bu ada sahip bir kelime seti burada zaten mevcut.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Bu ada sahip bir kural seti burada zaten mevcut.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+37"/>
        <source>Results</source>
        <translation>Sonuçlar</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Well</source>
        <translation>Aferin</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>done</source>
        <translation>tamamlandı</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>%1 üzerinden</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Harika iş! Böyle devam et!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>İyi bir çaba! Pratik yapmaya devam et.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Vazgeçme – pratik mükemmelleştirir!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Bu oturum</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Bilmiyorum</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Biliyorum</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Practice Again</source>
        <translation>Tekrar pratik yap</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Test ilerlemesi sıfırlansın mı?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Bu, bu kural setindeki ilerlemenizi temizleyecek ve yeni bir oturum başlatacaktır.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 soru</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Tamamlandı: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Devam ediyor: %1 / %2</translation>
    </message>
    <message>
        <location line="+67"/>
        <source>← Reset</source>
        <translation>← Sıfırla</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Kural Açıklaması</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Bu set için açıklama eklenmedi.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Ses klibi</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Yazım katılığı</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Katı</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Esnek</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Testi Başlat</translation>
    </message>
    <message>
        <location line="-198"/>
        <source>Test is completed</source>
        <translation>Test tamamlandı</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Sonraki soru: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Doğru: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Kural</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Kural Açıklaması</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Ses klibi</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>İptal</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Kuralı görüntüle</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Her boşluğun kelimesini seçmek için çarkı çevirin.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Boşluk %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Bir karoyu bir boşluğa sürükleyin veya yerleştirmek için bir karoya, ardından bir boşluğa dokunun.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Doğru cevabı seçin.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Geçerli olan her şeyi seçin.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Doğru: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Gönder</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Doğru: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Sonuçları Görüntüle</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>İleri →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Soru numarası %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Kelime seti üzerine yazılsın mı?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Kütüphaneler birleştirilsin mi?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>“%1” adlı bir kelime seti burada zaten mevcut. Taşınan setle üzerine yazılsın mı?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>“%1” adlı bir kütüphane burada zaten mevcut. İçeriği bununla birleştirilsin mi?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>“%1” adlı bir kelime seti %2 içinde zaten mevcut. Birleştirilen sürümle üzerine yazılsın mı?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>hedef kütüphane</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>.ppset olarak dışa aktar</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Yeni Kütüphane</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Library name:</source>
        <translation>Kütüphane adı:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>örn. Seyahat, İş, Okul…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Bu ada sahip bir kütüphane veya set burada zaten mevcut.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+74"/>
        <source>A library with this name already exists here.</source>
        <translation>Bu ada sahip bir kütüphane burada zaten mevcut.</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Create</source>
        <translation>Oluştur</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Rename Library</source>
        <translation>Kütüphaneyi Yeniden Adlandır</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Yeni ad:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Yeniden Adlandır</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Kelime Setleriniz</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Kütüphane</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Dışarı taşı</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>İçeri taşımak için bırakın</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>kelime</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>soru</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Kütüphaneyi Sil</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Düzenle</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Sil</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>.ppset dosyasını paylaş</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>.ppset dışa aktar (diske kaydet)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Burada henüz bir şey yok.
Kelime seti veya kütüphane eklemek için + Oluştur&apos;a dokunun.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Kelime Seti</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Kural Seti</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Oluştur</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Arayüz Dili</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Cancel</source>
        <translation>İptal</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Test Türünü Seçin</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Bilgi Kartları</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Görmek için çevirin — biliyorsanız sağa kaydırın</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Kelimeyi Yaz</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>İpucuna bak — ifadeyi yazın</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>İpucunu Yaz</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Kelimeye bak — çevirisini yazın</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Kelimeyi Seç</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>İpucuna bak — 4 seçenekten seçin</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>İpucunu Seç</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Kelimeye bak — 4 seçenekten seçin</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Aşamalı Öğrenme</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Öğrenmek için önce çoktan seçmeli, sonra tüm kelimelerde ustalaşmak için yazma</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Ters Aşamalı Öğrenme</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Öğrenmek için önce çoktan seçmeli, sonra tüm ipuçlarında ustalaşmak için yazma</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>✓ Done</source>
        <translation>✓ Bitti</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>← Reset</source>
        <translation>← Sıfırla</translation>
    </message>
    <message>
        <location line="+96"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Yazım katılığı</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Katı</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Esnek</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>İptal</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>İfadeleri Gözden Geçir</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Durdur</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Dinle</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Testi Başlat</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Henüz kelime yok</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>İpucunu / çeviriyi yazın…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>İfadeyi yazın…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Doğru: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Doğru olarak işaretle (yanlış yazdım)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Gönder</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Doğru olarak işaretle (yanlış tıkladım)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Doğru: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Sonuçları Gör</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Sonraki →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Soru numarası %1</translation>
    </message>
</context>
</TS>
