<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="de">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Über</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Vokabeltrainer zum Einprägen von Wortsets.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Trainer für Wortschatz und Grammatik.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Open-Source-Lizenzen</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Diese Anwendung verwendet Qt unter der GNU Lesser General Public License Version 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Qt-Hinweis</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Qt-Hinweis</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Qt-Quellcode</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Qt-Projekt-Website</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Von KI erzeugt — kann Fehler enthalten</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Melden</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Danke — deine Meldung wurde gesendet und wird geprüft.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 KI-Inhalt melden</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Was stimmt mit diesem erzeugten Inhalt nicht?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Sexuelle oder anzügliche Inhalte</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Schimpfwörter oder beleidigende Sprache</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Hasserfüllte oder belästigende Inhalte</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Gewalttätige oder gefährliche Inhalte</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Falsche oder irreführende Informationen</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Etwas anderes</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Details (optional)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Wird gesendet…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Schließen</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Abbrechen</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Meldung senden</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Foto aufnehmen</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Abbrechen</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>bald</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>in %1 T %2 Std</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>in %1 Std %2 Min</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>in %1 Min</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Bild auswählen</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Audio auswählen</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Wortset importieren</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Wortsprache</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Hinweissprache</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+326"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Abbrechen</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ KI-Wortset-Generator</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Unterstützt durch Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Thema</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Beschreibe das gewünschte Set — z. B. „Küchengegenstände, die man in einem französischen Haushalt findet“ oder „Geschäftsreise-Redewendungen für eine Konferenz“…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>%1 von %2 Generierungen diesen Monat übrig — Zurücksetzung %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>KI kann Fehler machen. Es werden nur Inhalte erzeugt, die für alle Altersgruppen geeignet sind — melde Unangemessenes über 🚩 Melden.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Wortsprache</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Hinweissprache</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Anzahl der Wörter</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Frage Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Anfrage abbrechen</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Generieren</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ KI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Neues Wortset</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Wortset bearbeiten</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importieren</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Set-Titel…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Bilder automatisch abrufen</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Wort</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>ausgewählt</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Wort / Begriff</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Nicht ausgewählt</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Wort eingeben...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Hinweis / Bedeutung</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Hinweis, Definition...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Beispielverwendung</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Beispielsatz mit dem Wort...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Bild ändern</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Bild hinzufügen</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Abrufen</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Kamera</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Audio hinzufügen</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Stopp</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Abspielen</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ TTS</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Stopp</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Aufn.</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Wort hinzufügen</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Entfernen</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Speichern</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Titel ist erforderlich</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>bald</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>in %1d %2Std.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>in %1Std. %2Min.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>in %1Min.</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Bild auswählen</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Audio auswählen</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ KI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Neues Regelset</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Regelset bearbeiten</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importieren</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Regelset importieren</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ KI-Regelset-Generator</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Unterstützt von Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Noch %1 von %2 Generierungen diesen Monat — Zurücksetzung %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Zu erklärende Regel/Thema</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Beschreibe die gewünschte Regel — z. B. „Present Simple vs. Present Continuous“ oder „Bedingungssätze Typ 3“…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Fragen pro Typ</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Lücke füllen</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Multiple Choice</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Dropdown-Auswahl</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Ziehen &amp; Ablegen</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Gemini wird gefragt…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Anfrage abbrechen</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Abbrechen</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>KI kann Fehler machen. Es werden nur Inhalte erzeugt, die für alle Altersgruppen geeignet sind — melde Unangemessenes über 🚩 Melden.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Generieren</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Titel eingeben…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Theorie-Erklärung</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Während des Tests verborgen, bis der Lernende einen Fehler macht — in der Vorschau immer lesbar.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Verwende ▲▼, um einen Block neu anzuordnen. Ziehe die //-Ecke eines Fotos, um es zu skalieren.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Erkläre die Regel, die dieses Set übt…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Audioclip</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Text</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Foto</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Audio</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Frage</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>ausgewählt</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Lücke füllen</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Multiple Choice</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Dropdown-Auswahl</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Ziehen &amp; Ablegen</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Verwende ___ (drei Unterstriche) für jede Lücke, die der Lernende ausfüllt.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>z. B. Was macht sie jeden Tag?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>z. B. Sie geht jeden Tag ___ zur Schule.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Antworten</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Eine Antwort pro Lücke, durch Kommas getrennt, in Reihenfolge. Verwende \, für ein literales Komma.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>z. B. geht</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Optionen</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Trenne Optionen für eine Lücke mit Kommas; trenne Lücken mit doppeltem Doppelpunkt (::). Ein einzelnes : ist unbedenklich; verwende \, für ein literales Komma, \:: für ein literales ::, und ___ für eine absichtlich leere Option. Z. B. für zwei Lücken: geht, gehen, gehend::jeder, einige, die meisten.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Durch Kommas getrennte, ziehbare Kacheln — füge die richtigen Antworten hinzu, plus optionale Ablenker, mit denen der Lernende getäuscht werden kann. Verwende \, für ein literales Komma, und ___ für eine leere Kachel (für eine Lücke, die korrekterweise leer bleiben soll). Fülle die untenstehenden Lücken, sobald diese festgelegt sind.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>z. B. geht, gehen, gehend::jeder, einige, die meisten</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>z. B. geht, gehen, gehend, gegangen</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Richtige Antwort für jede Lücke</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Tippe auf die richtige Auswahl in jedem Feld unten.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Wähle eine richtige Antwort für jede Lücke.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Lücke %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Lücken füllen</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Ziehe eine Kachel auf eine Lücke unten, oder tippe eine Kachel und dann eine Lücke, um sie zu platzieren.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Fülle jede Lücke mit einer Kachel.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Durch Kommas getrennte Auswahl — tippe unten auf die richtige Antwort. Verwende \, für ein literales Komma.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Durch Kommas getrennte Auswahl — tippe unten auf alle richtigen Antworten. Verwende \, für ein literales Komma.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>z. B. geht, gehen, gehend, gegangen</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Nur eine richtige Antwort</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Richtige Antwort</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Richtige Antwort(en)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Wähle die richtige Antwort.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Wähle mindestens eine richtige Antwort.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Frage hinzufügen</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Entfernen</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Speichern</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Titel ist erforderlich</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Grammatik erklären</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>%1-Frage konnte nicht geladen werden: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Nur %1 von %2 angeforderten Fragen wurden generiert — versuche ein breiteres Thema oder verringere die Zahlen oben.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Erklärungssprache</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Erklärungssprache</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Themensprache</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Themensprache</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Zu diesem Thema kann nichts erzeugt werden. Die KI erstellt nur Inhalte, die für alle Altersgruppen geeignet sind — sexuelle, vulgäre oder beleidigende Themen werden nicht unterstützt. Bitte versuche ein anderes Thema.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Du hast alle KI-Generierungen für diesen Monat aufgebraucht. Versuche es nächsten Monat erneut.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Zu viele Meldungen heute — bitte versuche es morgen erneut.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Der KI-Dienst ist gerade ausgelastet — bitte versuche es gleich noch einmal.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Gib zuerst ein Thema ein.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Das Thema ist zu lang (max. %1 Zeichen).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Setze mindestens einen Fragetyp auf mehr als null.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Deine Sitzung ist abgelaufen — bitte melde dich erneut an.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Server nicht erreichbar. Prüfe deine Internetverbindung und versuche es erneut.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Etwas ist schiefgelaufen. Bitte versuche es erneut.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Nicht angemeldet.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Tippen zum Umdrehen</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Tippen zum Zurückdrehen</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>WEISS ICH</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>ÜBERSPRINGEN</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Weiß ich nicht</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Weiß ich</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Nicht ausgewählt</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Lizenztext konnte nicht geladen werden.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Zum Fortfahren anmelden</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Browser wird geöffnet…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Mit Google anmelden</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Eine Bibliothek oder ein Set mit diesem Namen existiert hier bereits.</translation>
    </message>
    <message>
        <location line="+309"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Ein Wortset mit diesem Namen existiert hier bereits.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Ein Regelset mit diesem Namen existiert hier bereits.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+37"/>
        <source>Results</source>
        <translation>Ergebnisse</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Well</source>
        <translation>Gut</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>done</source>
        <translation>gemacht</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>von %1</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Ausgezeichnete Arbeit! Weiter so!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Guter Einsatz! Übe weiter.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Nicht aufgeben – Übung macht den Meister!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Diese Sitzung</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Weiß ich nicht</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Weiß ich</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Practice Again</source>
        <translation>Erneut üben</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Testfortschritt zurücksetzen?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Dadurch wird dein Fortschritt bei diesem Regelset gelöscht und eine neue Sitzung gestartet.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 Fragen</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Abgeschlossen: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">In Bearbeitung: %1 / %2</translation>
    </message>
    <message>
        <location line="+67"/>
        <source>← Reset</source>
        <translation>← Zurücksetzen</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Regel-Erklärung</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Für dieses Set wurde keine Erklärung hinzugefügt.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Audioclip</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Rechtschreibstrenge</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Streng</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Nachsichtig</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Test starten</translation>
    </message>
    <message>
        <location line="-198"/>
        <source>Test is completed</source>
        <translation>Test ist abgeschlossen</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Nächste Frage: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Richtig: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Regel</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Regel-Erklärung</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Audioclip</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Abbrechen</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Regel ansehen</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Drehe das Rad, um das Wort für jede Lücke zu wählen.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Lücke %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Ziehe eine Kachel auf eine Lücke, oder tippe eine Kachel und dann eine Lücke, um sie zu platzieren.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Wähle die richtige Antwort.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Wähle alle zutreffenden aus.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Richtig: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Absenden</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Richtig: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Ergebnisse ansehen</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Weiter →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Frage Nummer %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Wortset überschreiben?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Bibliotheken zusammenführen?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Ein Wortset namens „%1“ existiert hier bereits. Mit dem verschobenen Set überschreiben?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Eine Bibliothek namens „%1“ existiert hier bereits. Ihren Inhalt damit zusammenführen?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Ein Wortset namens „%1“ existiert bereits in %2. Mit der zusammengeführten Version überschreiben?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>die Zielbibliothek</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Als .ppset exportieren</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Neue Bibliothek</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Library name:</source>
        <translation>Bibliotheksname:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>z. B. Reisen, Arbeit, Schule…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Eine Bibliothek oder ein Set mit diesem Namen existiert hier bereits.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+74"/>
        <source>A library with this name already exists here.</source>
        <translation>Eine Bibliothek mit diesem Namen existiert hier bereits.</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Create</source>
        <translation>Erstellen</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Rename Library</source>
        <translation>Bibliothek umbenennen</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Neuer Name:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Umbenennen</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Deine Wortsets</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Bibliothek</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Herausbewegen aus</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Loslassen, um hineinzuverschieben</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>Wörter</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>Fragen</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Bibliothek löschen</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Bearbeiten</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Löschen</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>.ppset-Datei teilen</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>.ppset exportieren (auf Datenträger speichern)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Hier ist noch nichts.
Tippe auf + Erstellen, um ein Wortset oder eine Bibliothek hinzuzufügen.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Wortset</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Regelset</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Erstellen</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Sprache der Oberfläche</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Cancel</source>
        <translation>Abbrechen</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Testart wählen</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Karteikarten</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Umdrehen zum Aufdecken — nach rechts wischen, wenn du es weißt</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Schreibe das Wort</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Hinweis ansehen — den Ausdruck eintippen</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Schreibe den Hinweis</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Wort ansehen — die Übersetzung eintippen</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Wähle das Wort</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Hinweis ansehen — aus 4 Optionen wählen</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Wähle den Hinweis</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Wort ansehen — aus 4 Optionen wählen</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Progressives Lernen</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Erst Multiple-Choice zum Lernen, dann Schreiben, um alle Wörter zu meistern</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Umgekehrtes progressives Lernen</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Erst Multiple-Choice zum Lernen, dann Schreiben, um alle Hinweise zu meistern</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>✓ Done</source>
        <translation>✓ Fertig</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>← Reset</source>
        <translation>← Zurücksetzen</translation>
    </message>
    <message>
        <location line="+96"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Rechtschreibstrenge</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Streng</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Nachsichtig</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Abbrechen</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Ausdrücke wiederholen</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Stopp</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Anhören</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Test starten</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Noch keine Wörter</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Hinweis / Übersetzung eingeben…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Ausdruck eingeben…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Richtig: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Als richtig markieren (Tippfehler)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Absenden</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Als richtig markieren (Fehlklick)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Richtig: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Ergebnisse ansehen</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Weiter →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Frage Nummer %1</translation>
    </message>
</context>
</TS>
