<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="da">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Om</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Ordforrådstræner til at memorere ordsæt.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Træner til ordforråd og grammatik.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Open source-licenser</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Denne applikation bruger Qt under GNU Lesser General Public License version 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Qt-meddelelse</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Qt-meddelelse</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Qt-kildekode</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Qt-projektets websted</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Genereret af AI — kan indeholde fejl</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Anmeld</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Tak — din anmeldelse er sendt og vil blive gennemgået.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Anmeld AI-indhold</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Hvad er der galt med dette genererede indhold?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Seksuelt eller udfordrende indhold</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Bandeord eller stødende sprog</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Hadefuldt eller chikanerende indhold</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Voldeligt eller farligt indhold</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Forkerte eller vildledende oplysninger</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Noget andet</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Detaljer (valgfrit)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Sender…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Luk</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Annuller</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Send anmeldelse</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Tag foto</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Annuller</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>snart</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>om %1d %2t</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>om %1t %2m</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>om %1m</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Vælg billede</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Vælg lyd</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Importer ordsæt</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Ordsprog</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Sprog for hint</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+326"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Annuller</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ AI-ordsætgenerator</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Drevet af Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Emne</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Beskriv det sæt, du ønsker — f.eks. &quot;køkkenting, man ville finde i en fransk husholdning&quot; eller &quot;forretningsrejsesætninger til en konference&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>%1 af %2 genereringer tilbage denne måned — nulstilles %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI kan tage fejl. Der genereres kun indhold, der passer til alle aldre — brug 🚩 Anmeld til at markere noget upassende.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Ordsprog</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Sprog for hint</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Antal ord</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Spørger Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Annuller anmodning</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Generer</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Nyt ordsæt</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Rediger ordsæt</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importer</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Sættitel…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Hent billeder automatisk</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Ord</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>valgt</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Ord / Term</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Ikke valgt</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Indtast ord...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Hint / betydning</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Hint, definition...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Eksempel på brug</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Eksempelsætning med ordet...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Skift billede</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Tilføj billede</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Hent</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Kamera</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Tilføj lyd</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Stop</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Afspil</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ TTS</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Stop</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Optag</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Tilføj ord</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Fjern</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Gem</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Titel er påkrævet</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>snart</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>om %1d %2t</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>om %1t %2m</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>om %1m</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Vælg billede</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Vælg lyd</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Nyt regelsæt</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Rediger regelsæt</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importér</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Importér regelsæt</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ AI-regelsætgenerator</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Drevet af Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>%1 ud af %2 genereringer tilbage denne måned — nulstilles %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Regel/emne der skal forklares</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Beskriv reglen, du vil have — f.eks. &quot;nutid vs. udvidet nutid&quot; eller &quot;tredje betingelsessætninger&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Spørgsmål pr. type</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Udfyld hullet</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Multiple choice</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Rullemenu</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Træk og slip</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Spørger Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Annullér anmodning</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Annullér</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI kan tage fejl. Der genereres kun indhold, der passer til alle aldre — brug 🚩 Anmeld til at markere noget upassende.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Generér</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Angiv titel…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Teoriforklaring</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Skjult under testen, indtil eleven laver en fejl — altid læsbar i forhåndsvisning.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Brug ▲▼ til at omarrangere en blok. Træk et fotos //-hjørne for at ændre størrelsen.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Forklar reglen, som dette sæt øver…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Lydklip</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Tekst</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Foto</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Lyd</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Spørgsmål</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>valgt</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Udfyld hullet</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Multiple choice</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Rullemenu</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Træk og slip</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Brug ___ (tre understregninger) for hvert hul, eleven udfylder.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>f.eks. Hvad laver hun hver dag?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>f.eks. Hun ___ i skole hver dag.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Svar</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Ét svar pr. hul, adskilt med kommaer, i rækkefølge. Brug \, for et bogstaveligt komma.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>f.eks. går</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Valgmuligheder</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Adskil valgmuligheder for ét hul med kommaer; adskil huller med dobbelt kolon (::). Et enkelt : er sikkert som det er; brug \, for et bogstaveligt komma, \:: for et bogstaveligt ::, og ___ for en bevidst tom valgmulighed. F.eks. for to huller: går, gå, gående::hver, nogle, de fleste.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Trækbare brikker adskilt med kommaer — inkludér de korrekte svar plus valgfrie lokkemidler, som eleven kan blive narret af. Brug \, for et bogstaveligt komma, og ___ for en tom brik (til et hul, der korrekt skal forblive tomt). Udfyld hullerne nedenfor, når disse er angivet.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>f.eks. går, gå, gående::hver, nogle, de fleste</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>f.eks. går, gå, gående, gået</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Korrekt svar for hvert hul</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Tryk på det korrekte valg i hver boks nedenfor.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Vælg et korrekt svar for hvert hul.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Hul %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Udfyld hullerne</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Træk en brik til et hul nedenfor, eller tryk på en brik og derefter et hul for at placere den.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Udfyld hvert hul med en brik.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Valgmuligheder adskilt med kommaer — tryk på det korrekte svar nedenfor. Brug \, for et bogstaveligt komma.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Valgmuligheder adskilt med kommaer — tryk på alle korrekte svar nedenfor. Brug \, for et bogstaveligt komma.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>f.eks. går, gå, gående, gået</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Kun ét korrekt svar</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Korrekt svar</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Korrekt(e) svar</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Vælg det korrekte svar.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Vælg mindst ét korrekt svar.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Tilføj spørgsmål</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Fjern</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Gem</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Titel er påkrævet</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Forklar grammatik</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Kunne ikke indlæse %1-spørgsmål: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Kun %1 ud af %2 anmodede spørgsmål blev genereret — prøv et bredere emne, eller sænk antallene ovenfor.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Forklaringssprog</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Forklaringssprog</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Emnesprog</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Emnesprog</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Dette emne kan ikke genereres. AI&apos;en laver kun indhold, der passer til alle aldre — seksuelle, vulgære eller stødende emner understøttes ikke. Prøv et andet emne.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Du har brugt alle dine AI-genereringer for denne måned. Prøv igen næste måned.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>For mange anmeldelser i dag — prøv igen i morgen.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>AI-tjenesten er optaget lige nu — prøv igen om et øjeblik.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Angiv et emne først.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Emnet er for langt (maks. %1 tegn).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Sæt mindst én spørgsmålstype over nul.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Din session er udløbet — log ind igen.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Kunne ikke få forbindelse til serveren. Tjek din internetforbindelse, og prøv igen.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Noget gik galt. Prøv igen.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Ikke logget ind.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Tryk for at vende</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Tryk for at vende tilbage</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>KAN</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>SPRING OVER</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Kan ikke</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Kan</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Ikke valgt</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Kunne ikke indlæse licenstekst.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Log ind for at fortsætte</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Åbner browser…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Log ind med Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Der findes allerede et bibliotek eller sæt med dette navn her.</translation>
    </message>
    <message>
        <location line="+309"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Der findes allerede et ordsæt med dette navn her.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Der findes allerede et regelsæt med dette navn her.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+37"/>
        <source>Results</source>
        <translation>Resultater</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Well</source>
        <translation>Godt</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>done</source>
        <translation>klaret</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>ud af %1</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Fremragende arbejde! Bliv ved!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Godt forsøg! Bliv ved med at øve.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Giv ikke op – øvelse gør mester!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Denne session</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Kan ikke</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Kan</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Practice Again</source>
        <translation>Øv igen</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Nulstil testfremgang?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Dette rydder din fremgang på dette regelsæt og starter en ny session.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 spørgsmål</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Fuldført: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">I gang: %1 / %2</translation>
    </message>
    <message>
        <location line="+67"/>
        <source>← Reset</source>
        <translation>← Nulstil</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Regelforklaring</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Der er ikke tilføjet nogen forklaring til dette sæt.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Lydklip</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Stavestrenghed</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Streng</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Mild</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Start test</translation>
    </message>
    <message>
        <location line="-198"/>
        <source>Test is completed</source>
        <translation>Testen er gennemført</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Næste spørgsmål: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Korrekt: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Regel</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Regelforklaring</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Lydklip</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Annullér</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Vis regel</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Drej hjulet for at vælge hvert huls ord.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Hul %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Træk en brik til et hul, eller tryk på en brik og derefter et hul for at placere den.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Vælg det korrekte svar.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Vælg alt, der gælder.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Korrekt: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Indsend</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Korrekt: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Se resultater</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Næste →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Spørgsmål nummer %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Overskrive ordsæt?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Flet biblioteker?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Et ordsæt ved navn &quot;%1&quot; findes allerede her. Overskriv det med det flyttede sæt?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Et bibliotek ved navn &quot;%1&quot; findes allerede her. Flet dets indhold ind i det?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Et ordsæt ved navn &quot;%1&quot; findes allerede i %2. Overskriv det med den sammenlagte version?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>destinationsbiblioteket</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Eksporter som .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Nyt bibliotek</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Library name:</source>
        <translation>Biblioteksnavn:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>f.eks. Rejser, Arbejde, Skole…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Der findes allerede et bibliotek eller sæt med dette navn her.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+74"/>
        <source>A library with this name already exists here.</source>
        <translation>Der findes allerede et bibliotek med dette navn her.</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Create</source>
        <translation>Opret</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Rename Library</source>
        <translation>Omdøb bibliotek</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Nyt navn:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Omdøb</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Dine ordsæt</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Bibliotek</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Flyt ud af</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Slip for at flytte ind</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>ord</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>spørgsmål</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Slet bibliotek</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Rediger</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Slet</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Del .ppset-fil</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Eksporter .ppset (gem på disk)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Intet her endnu.
Tryk på + Opret for at tilføje et ordsæt eller bibliotek.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Ordsæt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Regelsæt</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Opret</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Grænsefladesprog</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Cancel</source>
        <translation>Annuller</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Vælg testtype</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Flashcards</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Vend for at afsløre — stryg til højre, hvis du kender det</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Skriv ordet</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Se hintet — indtast udtrykket</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Skriv hintet</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Se ordet — indtast oversættelsen</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Vælg ordet</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Se hintet — vælg blandt 4 muligheder</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Vælg hintet</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Se ordet — vælg blandt 4 muligheder</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Progressiv læring</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Multiple choice for at lære, derefter skrivning for at mestre alle ord</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Omvendt progressiv læring</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Multiple choice for at lære, derefter skrivning for at mestre alle hints</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>✓ Done</source>
        <translation>✓ Færdig</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>← Reset</source>
        <translation>← Nulstil</translation>
    </message>
    <message>
        <location line="+96"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Stavestrenghed</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Streng</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Mild</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Annuller</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Gennemgå udtryk</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Stop</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Lyt</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Start test</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Ingen ord endnu</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Indtast hint / oversættelse…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Indtast udtrykket…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Korrekt: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Marker som korrekt (jeg tastede forkert)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Send</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Marker som korrekt (jeg klikkede forkert)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Korrekt: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Se resultater</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Næste →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Spørgsmål nummer %1</translation>
    </message>
</context>
</TS>
