<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="kk">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Қолданба туралы</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Сөз жиынтықтарын жаттауға арналған сөздік жаттықтырушысы.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Сөздік қор мен грамматика жаттықтырушысы.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Ашық бастапқы код лицензиялары</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Бұл қолданба GNU Lesser General Public License 3-нұсқасы бойынша Qt-ты пайдаланады.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Qt хабарламасы</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Qt хабарламасы</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Qt бастапқы коды</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Qt жобасының веб-сайты</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Жасанды интеллект жасаған — қателер болуы мүмкін</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Шағым жасау</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Рақмет — шағымыңыз жіберілді және қаралады.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Жасанды интеллект контентіне шағым жасау</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Бұл жасалған контенттің қандай ақауы бар?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Жыныстық не әдепсіз меңзеу бар контент</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Балағат не қорлайтын сөздер</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Өшпенділік не қудалау бар контент</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Зорлық-зомбылық не қауіпті контент</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Қате не жаңылыстыратын ақпарат</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Басқа нәрсе</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Толығырақ (міндетті емес)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Жіберілуде…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Жабу</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Бас тарту</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Шағым жіберу</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Фото түсіру</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Бас тарту</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>жақында</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1к %2с ішінде</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1с %2мин ішінде</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1мин ішінде</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Суретті таңдау</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Аудионы таңдау</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Сөз жиынтығын импорттау</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Сөз тілі</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Кеңес тілі</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+339"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Бас тарту</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ Жасанды интеллект сөз жиынтығы генераторы</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Gemini арқылы жұмыс істейді</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Тақырып</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Қалаған жиынтығыңызды сипаттаңыз — мыс. «француз үйінде кездесетін ас үй заттары» немесе «конференцияға іссапар үшін тіркестер»…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Бұл айда %2-ден %1 генерация қалды — %3 күні қалпына келеді</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>Жасанды интеллект қателесуі мүмкін. Тек барлық жасқа сай контент жасалады — орынсыз нәрсені белгілеу үшін 🚩 Шағым жасау батырмасын пайдаланыңыз.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Сөз тілі</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Кеңес тілі</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Сөздер саны</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Gemini-ден сұрау…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Сұрауды болдырмау</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Жасау</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ ЖИ</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Жаңа сөз жиынтығы</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Сөз жиынтығын өңдеу</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Импорттау</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Жиынтық атауы…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Суреттерді автоматты түрде алу</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Сөз</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>таңдалды</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Сөз / Термин</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Таңдалмаған</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Сөзді енгізіңіз...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Кеңес / мағына</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Кеңес, анықтама...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Қолдану мысалы</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Сөзді пайдаланатын мысал сөйлем...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Суретті өзгерту</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Сурет қосу</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Алу</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Камера</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Аудио қосу</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Тоқтату</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Ойнату</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ Дауыстап оқу</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Тоқтату</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Жазу</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Сөз қосу</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Жою</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Сақтау</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Атау қажет</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>жақында</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1к %2с ішінде</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1с %2мин ішінде</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1мин ішінде</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Суретті таңдау</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Аудионы таңдау</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ Жасанды интеллект</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Жаңа ережелер жиынтығы</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Ережелер жиынтығын өңдеу</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Импорттау</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Ережелер жиынтығын импорттау</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ ЖИ ережелер жиынтығының генераторы</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Gemini негізінде жұмыс істейді</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Бұл ай ішінде %2-ден %1 генерация қалды — қайта орнатылады %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Түсіндірілетін ереже/тақырып</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Қалаған ережеңізді сипаттаңыз — мыс. &quot;present simple мен present continuous&quot; немесе &quot;үшінші түрдегі шартты сөйлемдер&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Түр бойынша сұрақтар</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Бос орынды толтыру</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Көп таңдау</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Ашылмалы таңдау</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Сүйреп апару</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Gemini-ден сұрау…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Сұранысты болдырмау</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Бас тарту</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>Жасанды интеллект қателесуі мүмкін. Тек барлық жасқа сай контент жасалады — орынсыз нәрсені белгілеу үшін 🚩 Шағым жасау батырмасын пайдаланыңыз.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Жасау</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Тақырыпты енгізіңіз…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Теория түсіндірмесі</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Үйренуші қате жібергенше тестілеу кезінде жасырын — алдын ала қарауда әрқашан оқылады.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Блокты қайта реттеу үшін ▲▼ пайдаланыңыз. Суреттің өлшемін өзгерту үшін оның // бұрышын сүйреңіз.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Бұл жиынтық жаттықтыратын ережені түсіндіріңіз…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Аудио үзінді</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Мәтін</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Сурет</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Аудио</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Сұрақ</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>таңдалды</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Бос орынды толтыру</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Көп таңдау</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Ашылмалы таңдау</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Сүйреп апару</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Үйренуші толтыратын әрбір бос орын үшін ___ (үш төменгі сызық) пайдаланыңыз.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>мыс. Ол күн сайын не істейді?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>мыс. Ол күн сайын мектепке ___.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Жауаптар</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Әрбір бос орынға бір жауап, үтірмен бөлінген, ретімен. Нақты үтір үшін \, пайдаланыңыз.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>мыс. барады</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Опциялар</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Бір бос орынның опцияларын үтірмен бөліңіз; бос орындарды қос қос нүктемен (::) бөліңіз. Жалғыз : өзгеріссіз қауіпсіз; нақты үтір үшін \,, нақты :: үшін \::, және әдейі бос опция үшін ___ пайдаланыңыз. Мыс. екі бос орын үшін: барады, бару, барып жатыр::әрбір, кейбір, көпшілігі.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Үтірмен бөлінген сүйрелетін тақталар — дұрыс жауаптарды, сонымен қатар үйренуші адасуы мүмкін қосымша алдамшы нұсқаларды қосыңыз. Нақты үтір үшін \, және бос тақта үшін ___ пайдаланыңыз (дұрыс бос қалуы керек бос орын үшін). Бұлар орнатылғаннан кейін төмендегі бос орындарды толтырыңыз.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>мыс. барады, бару, барып жатыр::әрбір, кейбір, көпшілігі</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>мыс. барады, бару, барып жатыр, барды</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Әрбір бос орын үшін дұрыс жауап</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Төмендегі әрбір өрісте дұрыс нұсқаны түртіңіз.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Әрбір бос орын үшін дұрыс жауапты таңдаңыз.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Бос орын %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Бос орындарды толтырыңыз</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Тақтаны төмендегі бос орынға сүйреңіз немесе тақтаны түртіп, содан кейін оны орналастыру үшін бос орынды түртіңіз.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Әрбір бос орынды тақтамен толтырыңыз.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Үтірмен бөлінген опциялар — төмендегі дұрыс жауапты түртіңіз. Нақты үтір үшін \, пайдаланыңыз.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Үтірмен бөлінген опциялар — төмендегі барлық дұрыс жауаптарды түртіңіз. Нақты үтір үшін \, пайдаланыңыз.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>мыс. барады, бару, барып жатыр, барды</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Тек бір дұрыс жауап</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Дұрыс жауап</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Дұрыс жауап(тар)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Дұрыс жауапты таңдаңыз.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Кемінде бір дұрыс жауапты таңдаңыз.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Сұрақ қосу</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Жою</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Сақтау</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Тақырып қажет</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Грамматиканы түсіндіру</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>%1 сұрағын жүктеу мүмкін болмады: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Сұралған %2 сұрақтың тек %1 жасалды — кеңірек тақырыпты байқап көріңіз немесе жоғарыдағы сандарды азайтыңыз.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Түсіндірме тілі</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Түсіндірме тілі</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Тақырып тілі</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Тақырып тілі</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Бұл тақырыпқа контент жасау мүмкін емес. Жасанды интеллект тек барлық жасқа сай контент жасайды — жыныстық, балағат не қорлайтын тақырыптарға қолдау көрсетілмейді. Басқа тақырыпты көріңіз.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Осы айдағы барлық жасанды интеллект генерацияларын пайдаландыңыз. Келесі айда қайталап көріңіз.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Бүгін шағымдар тым көп — ертең қайталап көріңіз.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Жасанды интеллект қызметі қазір бос емес — сәлден кейін қайталап көріңіз.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Алдымен тақырыпты енгізіңіз.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Тақырып тым ұзын (ең көбі %1 таңба).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Кемінде бір сұрақ түрін нөлден жоғары қойыңыз.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Сеанс мерзімі аяқталды — қайта кіріңіз.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Серверге қосылу мүмкін болмады. Интернет байланысын тексеріп, қайталап көріңіз.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Бірдеңе дұрыс болмады. Қайталап көріңіз.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Жүйеге кірмегенсіз.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Аудару үшін түртіңіз</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Кері аудару үшін түртіңіз</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>БІЛЕМІН</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>ӨТКІЗІП ЖІБЕРУ</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Білмеймін</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Білемін</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Таңдалмаған</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Лицензия мәтінін жүктеу мүмкін болмады.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Жалғастыру үшін кіріңіз</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Браузер ашылуда…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Google арқылы кіру</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Мұндай атаумен кітапхана немесе жиынтық бұрыннан бар.</translation>
    </message>
    <message>
        <location line="+317"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Мұндай атаумен сөз жиынтығы бұрыннан бар.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Мұндай атаумен ережелер жиынтығы бұрыннан бар.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+38"/>
        <source>Results</source>
        <translation>Нәтижелер</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>Well</source>
        <translation>Жарайсың</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>done</source>
        <translation>орындалды</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>%1-ден</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Тамаша жұмыс! Осылай жалғастыр!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Жақсы әрекет! Жаттығуды жалғастыр.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Бас тартпа – жаттығу жетілдіреді!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Осы сессия</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Білмеймін</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Білемін</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Practice again</source>
        <translation>Қайта жаттығу</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Find another set</source>
        <translation>Басқа жинақ табу</translation>
    </message>
    <message>
        <source>Practice Again</source>
        <translation type="vanished">Қайта жаттығу</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Тест барысын қайта орнату керек пе?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Бұл осы ережелер жиынтығындағы прогресіңізді тазартады және жаңа сеанс бастайды.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 сұрақ</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Аяқталды: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Орындалуда: %1 / %2</translation>
    </message>
    <message>
        <source>← Reset</source>
        <translation type="vanished">← Қайта орнату</translation>
    </message>
    <message>
        <location line="+185"/>
        <source>Reset to practise again</source>
        <translation>Қайта жаттығу үшін қалпына келтіру</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Reset</source>
        <translation>Қалпына келтіру</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Ереже түсіндірмесі</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Бұл жиынтық үшін түсіндірме қосылмаған.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Аудио үзінді</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Емле қатаңдығы</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Қатаң</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Қалыпты</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Жеңіл</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Тестті бастау</translation>
    </message>
    <message>
        <location line="-316"/>
        <source>Test is completed</source>
        <translation>Тест аяқталды</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Келесі сұрақ: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Дұрыс: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Ереже</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Ереже түсіндірмесі</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Аудио үзінді</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Бас тарту</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Ережені қарау</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Әрбір бос орынның сөзін таңдау үшін дөңгелекті айналдырыңыз.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Бос орын %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Тақтаны бос орынға сүйреңіз немесе тақтаны түртіп, содан кейін оны орналастыру үшін бос орынды түртіңіз.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Дұрыс жауапты таңдаңыз.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Қолданылатынның барлығын таңдаңыз.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Дұрыс: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Жіберу</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Дұрыс: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Нәтижелерді қарау</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Келесі →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Сұрақ нөмірі %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Сөз жиынтығын үстінен жазу керек пе?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Кітапханаларды біріктіру керек пе?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>«%1» атты сөз жиынтығы бұрыннан осында бар. Оны жылжытылған жиынтықпен үстінен жазу керек пе?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>«%1» атты кітапхана бұрыннан осында бар. Оның мазмұнын осымен біріктіру керек пе?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>«%1» атты сөз жиынтығы бұрыннан %2 ішінде бар. Оны біріктірілген нұсқамен үстінен жазу керек пе?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>мақсатты кітапхана</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>.ppset форматында экспорттау</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Жаңа кітапхана</translation>
    </message>
    <message>
        <location line="+31"/>
        <source>Library name:</source>
        <translation>Кітапхана атауы:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>мыс. Саяхат, Жұмыс, Мектеп…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Мұндай атаумен кітапхана немесе жиынтық бұрыннан бар.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+99"/>
        <source>A library with this name already exists here.</source>
        <translation>Мұндай атаумен кітапхана бұрыннан бар.</translation>
    </message>
    <message>
        <location line="-62"/>
        <source>Create</source>
        <translation>Жасау</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Rename Library</source>
        <translation>Кітапхана атауын өзгерту</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Жаңа атау:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Атауын өзгерту</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Сіздің сөз жиынтықтарыңыз</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Кітапхана</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Сыртқа жылжыту</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Ішке жылжыту үшін тастаңыз</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>сөз</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>сұрақ</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Кітапханны жою</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Өңдеу</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Жою</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>.ppset файлымен бөлісу</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>.ppset экспорттау (дискіге сақтау)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Мұнда әлі ештеңе жоқ.
Сөз жиынтығын немесе кітапхананы қосу үшін + Жасау түймесін түртіңіз.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Сөз жиынтығы</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Ережелер жиынтығы</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Жасау</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Интерфейс тілі</translation>
    </message>
    <message>
        <location line="-710"/>
        <location line="+796"/>
        <source>Cancel</source>
        <translation>Бас тарту</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Тест түрін таңдаңыз</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Есте сақтау карталары</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Ашу үшін аударыңыз — білсеңіз оңға сырғытыңыз</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Сөзді жазыңыз</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Кеңесті қараңыз — тіркесті теріңіз</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Кеңесті жазыңыз</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Сөзді қараңыз — оның аудармасын теріңіз</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Сөзді таңдаңыз</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Кеңесті қараңыз — 4 нұсқадан таңдаңыз</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Кеңесті таңдаңыз</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Сөзді қараңыз — 4 нұсқадан таңдаңыз</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Прогрессивті оқыту</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Оқу үшін алдымен көп таңдаулы, содан кейін барлық сөздерді меңгеру үшін жазу</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Кері прогрессивті оқыту</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Оқу үшін алдымен көп таңдаулы, содан кейін барлық кеңестерді меңгеру үшін жазу</translation>
    </message>
    <message>
        <location line="+36"/>
        <location line="+82"/>
        <source>✓ Done</source>
        <translation>✓ Дайын</translation>
    </message>
    <message>
        <location line="-82"/>
        <source>← Reset</source>
        <translation>← Қалпына келтіру</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Completed — swipe left to reset</source>
        <translation>Аяқталды — қалпына келтіру үшін солға сырғытыңыз</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>%1 left</source>
        <translation>%1 қалды</translation>
    </message>
    <message>
        <location line="+51"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Емле қатаңдығы</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Қатаң</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Қалыпты</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Жеңіл</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Бас тарту</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Тіркестерді қайталау</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Тоқтату</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Тыңдау</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Тестті бастау</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Әзірге сөздер жоқ</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Кеңесті / аударманы теріңіз…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Тіркесті теріңіз…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Дұрыс: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Дұрыс деп белгілеу (мен қате тердім)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Жіберу</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Дұрыс деп белгілеу (мен қате бастым)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Дұрыс: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Нәтижелерді көру</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Келесі →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Сұрақ нөмірі %1</translation>
    </message>
</context>
</TS>
