<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="nl">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Over</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Vocabulairetrainer om woordsets te onthouden.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Trainer voor woordenschat en grammatica.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Opensourcelicenties</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Deze toepassing gebruikt Qt onder de GNU Lesser General Public License versie 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Qt-kennisgeving</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Qt-kennisgeving</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Qt-broncode</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Qt-projectwebsite</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Gegenereerd door AI — kan fouten bevatten</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Melden</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Bedankt — je melding is verstuurd en wordt beoordeeld.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 AI-inhoud melden</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Wat is er mis met deze gegenereerde inhoud?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Seksuele of suggestieve inhoud</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Scheldwoorden of beledigende taal</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Haatdragende of intimiderende inhoud</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Gewelddadige of gevaarlijke inhoud</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Onjuiste of misleidende informatie</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Iets anders</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Details (optioneel)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Versturen…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Sluiten</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Annuleren</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Melding versturen</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Foto maken</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Annuleren</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>binnenkort</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>over %1d %2u</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>over %1u %2m</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>over %1m</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Afbeelding selecteren</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Audio selecteren</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Woordset importeren</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Woordtaal</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Hinttaal</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+339"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Annuleren</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ AI-woordsetgenerator</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Mogelijk gemaakt door Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Onderwerp</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Beschrijf de set die je wilt — bijv. &quot;keukenspullen die je in een Frans huishouden zou vinden&quot; of &quot;zakenreiszinnen voor een conferentie&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Nog %1 van %2 generaties deze maand — reset %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI kan fouten maken. Er wordt alleen inhoud gemaakt die geschikt is voor alle leeftijden — gebruik 🚩 Melden om iets ongepasts te markeren.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Woordtaal</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Hinttaal</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Aantal woorden</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Gemini wordt gevraagd…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Verzoek annuleren</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Genereren</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Nieuwe woordset</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Woordset bewerken</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importeren</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Settitel…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Afbeeldingen automatisch ophalen</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Woord</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>geselecteerd</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Woord / Term</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Niet geselecteerd</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Woord invoeren...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Hint / betekenis</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Hint, definitie...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Voorbeeldgebruik</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Voorbeeldzin met het woord...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Afbeelding wijzigen</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Afbeelding toevoegen</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Ophalen</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Camera</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Audio toevoegen</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Stoppen</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Afspelen</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ TTS</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Stoppen</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Opn.</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Woord toevoegen</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Verwijderen</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Opslaan</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Titel is verplicht</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>binnenkort</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>over %1d %2u</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>over %1u %2m</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>over %1m</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Afbeelding selecteren</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Audio selecteren</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Nieuwe regelset</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Regelset bewerken</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importeren</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Regelset importeren</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ AI-regelsetgenerator</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Aangedreven door Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Nog %1 van %2 generaties deze maand — reset %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Uit te leggen regel/onderwerp</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Beschrijf de regel die je wilt — bijv. &quot;present simple versus present continuous&quot; of &quot;derde-type voorwaardelijke zinnen&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Vragen per type</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Vul de leemte in</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Meerkeuze</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Vervolgkeuzelijst</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Slepen en neerzetten</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Gemini wordt geraadpleegd…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Verzoek annuleren</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Annuleren</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI kan fouten maken. Er wordt alleen inhoud gemaakt die geschikt is voor alle leeftijden — gebruik 🚩 Melden om iets ongepasts te markeren.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Genereren</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Voer titel in…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Theorie-uitleg</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Verborgen tijdens de test totdat de leerling een fout maakt — altijd leesbaar in voorbeeld.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Gebruik ▲▼ om een blok opnieuw te ordenen. Sleep de //-hoek van een foto om deze te vergroten of verkleinen.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Leg de regel uit die deze set oefent…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Audiofragment</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Tekst</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Foto</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Audio</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Vraag</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>geselecteerd</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Vul de leemte in</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Meerkeuze</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Vervolgkeuzelijst</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Slepen en neerzetten</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Gebruik ___ (drie liggende streepjes) voor elke leemte die de leerling invult.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>bijv. Wat doet ze elke dag?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>bijv. Ze gaat elke dag ___ naar school.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Antwoorden</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Eén antwoord per leemte, gescheiden door komma&apos;s, in volgorde. Gebruik \, voor een letterlijke komma.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>bijv. gaat</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Opties</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Scheid opties voor één leemte met komma&apos;s; scheid leemtes met dubbele dubbele punt (::). Eén enkele : is veilig zoals die is; gebruik \, voor een letterlijke komma, \:: voor een letterlijke ::, en ___ voor een bewust lege optie. Bijv. voor twee leemtes: gaat, gaan, gaand::elk, sommige, de meeste.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Door komma&apos;s gescheiden sleepbare tegels — voeg de juiste antwoorden toe, plus optionele afleiders waarmee de leerling misleid kan worden. Gebruik \, voor een letterlijke komma, en ___ voor een lege tegel (voor een leemte die terecht leeg moet blijven). Vul de onderstaande leemtes in zodra deze zijn ingesteld.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>bijv. gaat, gaan, gaand::elk, sommige, de meeste</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>bijv. gaat, gaan, gaand, gegaan</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Juist antwoord voor elke leemte</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Tik op de juiste keuze in elk vak hieronder.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Selecteer een juist antwoord voor elke leemte.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Leemte %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Vul de leemtes in</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Sleep een tegel naar een leemte hieronder, of tik op een tegel en vervolgens op een leemte om deze te plaatsen.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Vul elke leemte met een tegel.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Door komma&apos;s gescheiden opties — tik op het juiste antwoord hieronder. Gebruik \, voor een letterlijke komma.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Door komma&apos;s gescheiden opties — tik op alle juiste antwoorden hieronder. Gebruik \, voor een letterlijke komma.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>bijv. gaat, gaan, gaand, gegaan</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Slechts één juist antwoord</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Juist antwoord</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Juist(e) antwoord(en)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Selecteer het juiste antwoord.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Selecteer ten minste één juist antwoord.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Vraag toevoegen</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Verwijderen</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Opslaan</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Titel is verplicht</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Grammatica uitleggen</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Kan %1-vraag niet laden: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Slechts %1 van %2 gevraagde vragen zijn gegenereerd — probeer een breder onderwerp, of verlaag de aantallen hierboven.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Uitlegtaal</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Uitlegtaal</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Onderwerptaal</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Onderwerptaal</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Over dit onderwerp kan niets worden gemaakt. De AI maakt alleen inhoud die geschikt is voor alle leeftijden — seksuele, grove of beledigende onderwerpen worden niet ondersteund. Probeer een ander onderwerp.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Je hebt al je AI-generaties voor deze maand gebruikt. Probeer het volgende maand opnieuw.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Te veel meldingen vandaag — probeer het morgen opnieuw.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>De AI-dienst is op dit moment druk — probeer het zo opnieuw.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Voer eerst een onderwerp in.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Het onderwerp is te lang (max. %1 tekens).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Zet ten minste één vraagtype boven nul.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Je sessie is verlopen — log opnieuw in.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Kan de server niet bereiken. Controleer je internetverbinding en probeer het opnieuw.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Er is iets misgegaan. Probeer het opnieuw.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Niet ingelogd.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Tik om om te draaien</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Tik om terug te draaien</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>WEET IK</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>OVERSLAAN</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Weet ik niet</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Weet ik</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Niet geselecteerd</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Kon licentietekst niet laden.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Log in om door te gaan</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Browser wordt geopend…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Inloggen met Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Er bestaat hier al een bibliotheek of set met deze naam.</translation>
    </message>
    <message>
        <location line="+317"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Er bestaat hier al een woordset met deze naam.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Er bestaat hier al een regelset met deze naam.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+38"/>
        <source>Results</source>
        <translation>Resultaten</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>Well</source>
        <translation>Goed</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>done</source>
        <translation>gedaan</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>van %1</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Uitstekend werk! Ga zo door!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Goede inzet! Blijf oefenen.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Geef niet op – oefening baart kunst!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Deze sessie</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Weet ik niet</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Weet ik</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Practice again</source>
        <translation>Opnieuw oefenen</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Find another set</source>
        <translation>Andere set zoeken</translation>
    </message>
    <message>
        <source>Practice Again</source>
        <translation type="vanished">Opnieuw oefenen</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Testvoortgang resetten?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Dit wist je voortgang in deze regelset en start een nieuwe sessie.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 vragen</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Voltooid: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Bezig: %1 / %2</translation>
    </message>
    <message>
        <source>← Reset</source>
        <translation type="vanished">← Resetten</translation>
    </message>
    <message>
        <location line="+185"/>
        <source>Reset to practise again</source>
        <translation>Resetten om opnieuw te oefenen</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Reset</source>
        <translation>Resetten</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Regeluitleg</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Er is geen uitleg toegevoegd voor deze set.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Audiofragment</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Spellingsstrengheid</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Streng</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normaal</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Soepel</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Test starten</translation>
    </message>
    <message>
        <location line="-316"/>
        <source>Test is completed</source>
        <translation>Test is voltooid</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Volgende vraag: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Juist: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Regel</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Regeluitleg</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Audiofragment</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Annuleren</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Regel bekijken</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Draai aan het wiel om het woord voor elke leemte te kiezen.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Leemte %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Sleep een tegel naar een leemte, of tik op een tegel en vervolgens op een leemte om deze te plaatsen.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Selecteer het juiste antwoord.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Selecteer alles wat van toepassing is.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Juist: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Indienen</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Juist: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Resultaten bekijken</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Volgende →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Vraagnummer %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Woordset overschrijven?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Bibliotheken samenvoegen?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Er bestaat hier al een woordset met de naam &quot;%1&quot;. Overschrijven met de verplaatste set?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Er bestaat hier al een bibliotheek met de naam &quot;%1&quot;. De inhoud ermee samenvoegen?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Er bestaat al een woordset met de naam &quot;%1&quot; in %2. Overschrijven met de samengevoegde versie?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>de doelbibliotheek</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Exporteren als .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Nieuwe bibliotheek</translation>
    </message>
    <message>
        <location line="+31"/>
        <source>Library name:</source>
        <translation>Bibliotheeknaam:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>bijv. Reizen, Werk, School…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Er bestaat hier al een bibliotheek of set met deze naam.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+99"/>
        <source>A library with this name already exists here.</source>
        <translation>Er bestaat hier al een bibliotheek met deze naam.</translation>
    </message>
    <message>
        <location line="-62"/>
        <source>Create</source>
        <translation>Aanmaken</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Rename Library</source>
        <translation>Bibliotheek hernoemen</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Nieuwe naam:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Hernoemen</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Jouw woordsets</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Bibliotheek</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Verplaatsen uit</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Neerzetten om naar binnen te verplaatsen</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>woorden</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>vragen</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Bibliotheek verwijderen</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Bewerken</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Verwijderen</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>.ppset-bestand delen</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>.ppset exporteren (opslaan op schijf)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Hier is nog niets.
Tik op + Aanmaken om een woordset of bibliotheek toe te voegen.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Woordset</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Regelset</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Aanmaken</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Interfacetaal</translation>
    </message>
    <message>
        <location line="-710"/>
        <location line="+796"/>
        <source>Cancel</source>
        <translation>Annuleren</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Kies testtype</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Flashcards</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Draai om om te onthullen — veeg naar rechts als je het weet</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Schrijf het woord</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Bekijk de hint — typ de uitdrukking</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Schrijf de hint</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Bekijk het woord — typ de vertaling</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Kies het woord</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Bekijk de hint — kies uit 4 opties</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Kies de hint</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Bekijk het woord — kies uit 4 opties</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Progressief leren</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Meerkeuze om te leren, daarna schrijven om alle woorden te beheersen</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Omgekeerd progressief leren</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Meerkeuze om te leren, daarna schrijven om alle hints te beheersen</translation>
    </message>
    <message>
        <location line="+36"/>
        <location line="+82"/>
        <source>✓ Done</source>
        <translation>✓ Klaar</translation>
    </message>
    <message>
        <location line="-82"/>
        <source>← Reset</source>
        <translation>← Resetten</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Completed — swipe left to reset</source>
        <translation>Voltooid — veeg naar links om te resetten</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>%1 left</source>
        <translation>Nog %1</translation>
    </message>
    <message>
        <location line="+51"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Spellingsstrengheid</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Streng</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normaal</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Soepel</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Annuleren</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Uitdrukkingen herhalen</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Stoppen</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Luisteren</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Test starten</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Nog geen woorden</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Typ de hint / vertaling…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Typ de uitdrukking…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Correct: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Markeren als correct (typefout)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Verzenden</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Markeren als correct (verkeerd geklikt)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Correct: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Resultaten bekijken</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Volgende →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Vraagnummer %1</translation>
    </message>
</context>
</TS>
