<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ms">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Perihal</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Jurulatih kosa kata untuk menghafal set perkataan.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Jurulatih kosa kata dan tatabahasa.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Lesen Sumber Terbuka</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Aplikasi ini menggunakan Qt di bawah lesen GNU Lesser General Public License versi 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Notis Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Notis Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Kod sumber Qt</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Laman web projek Qt</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Dijana oleh AI — mungkin mengandungi kesilapan</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Laporkan</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Terima kasih — laporan anda telah dihantar dan akan disemak.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Laporkan kandungan AI</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Apakah masalah dengan kandungan yang dijana ini?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Kandungan seksual atau sugestif</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Kata-kata kesat atau bahasa yang menyinggung</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Kandungan kebencian atau gangguan</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Kandungan ganas atau berbahaya</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Maklumat yang salah atau mengelirukan</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Perkara lain</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Butiran (pilihan)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Menghantar…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Tutup</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Batal</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Hantar laporan</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Ambil Gambar</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Batal</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>tidak lama lagi</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>dalam %1h %2j</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>dalam %1j %2m</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>dalam %1m</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Pilih Imej</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Pilih Audio</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Import Set Perkataan</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Bahasa Perkataan</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Bahasa Petunjuk</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+326"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Batal</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ Penjana Set Perkataan AI</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Dikuasakan oleh Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Tema</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Terangkan set yang anda mahu — cth. “barangan dapur yang boleh dijumpai di rumah Perancis” atau “frasa perjalanan perniagaan untuk persidangan”…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Baki %1 daripada %2 penjanaan bulan ini — set semula pada %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI boleh membuat kesilapan. Hanya kandungan yang sesuai untuk semua peringkat umur dijana — gunakan 🚩 Laporkan untuk menanda apa-apa yang tidak sesuai.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Bahasa perkataan</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Bahasa petunjuk</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Bilangan perkataan</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Bertanya kepada Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Batalkan Permintaan</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Jana</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Set Perkataan Baharu</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Edit Set Perkataan</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Import</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Tajuk set…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Ambil imej secara automatik</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Perkataan</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>dipilih</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Perkataan / Istilah</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Tidak dipilih</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Masukkan perkataan...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Petunjuk / makna</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Petunjuk, takrifan...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Contoh penggunaan</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Ayat contoh menggunakan perkataan itu...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Tukar imej</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Tambah imej</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Ambil</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Kamera</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Tambah audio</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Henti</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Main</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ Sebutan</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Henti</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Rakam</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Tambah perkataan</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Alih keluar</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Simpan</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Tajuk diperlukan</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>tidak lama lagi</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>dalam %1h %2j</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>dalam %1j %2m</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>dalam %1m</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Pilih Imej</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Pilih Audio</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Set Peraturan Baharu</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Edit Set Peraturan</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Import</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Import Set Peraturan</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ Penjana Set Peraturan AI</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Dikuasakan oleh Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>%1 daripada %2 penjanaan tinggal bulan ini — ditetapkan semula %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Peraturan/topik untuk dijelaskan</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Terangkan peraturan yang anda mahukan — cth. &quot;present simple lwn present continuous&quot; atau &quot;ayat bersyarat jenis ketiga&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Soalan mengikut jenis</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Isi Tempat Kosong</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Pelbagai Pilihan</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Pilihan Lungsur</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Seret &amp; Lepas</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Bertanya kepada Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Batalkan permintaan</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Batal</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI boleh membuat kesilapan. Hanya kandungan yang sesuai untuk semua peringkat umur dijana — gunakan 🚩 Laporkan untuk menanda apa-apa yang tidak sesuai.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Jana</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Masukkan tajuk…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Penjelasan Teori</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Disembunyikan semasa ujian sehingga pelajar membuat kesilapan — sentiasa boleh dibaca dalam pratonton.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Gunakan ▲▼ untuk menyusun semula blok. Seret bucu // foto untuk mengubah saiznya.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Terangkan peraturan yang diamalkan oleh set ini…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Klip audio</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Teks</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Foto</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Audio</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Soalan</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>dipilih</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Isi Tempat Kosong</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Pelbagai Pilihan</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Pilihan Lungsur</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Seret &amp; Lepas</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Gunakan ___ (tiga garis bawah) untuk setiap tempat kosong yang diisi pelajar.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>cth. Apakah yang dilakukannya setiap hari?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>cth. Dia pergi ___ ke sekolah setiap hari.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Jawapan</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Satu jawapan setiap tempat kosong, dipisahkan dengan koma, mengikut susunan. Gunakan \, untuk koma literal.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>cth. pergi</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Pilihan</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Pisahkan pilihan untuk satu tempat kosong dengan koma; pisahkan tempat kosong dengan titik bertindih berganda (::). Satu : selamat seperti sedia ada; gunakan \, untuk koma literal, \:: untuk :: literal, dan ___ untuk pilihan sengaja kosong. Cth. untuk dua tempat kosong: pergi, pergi, pergi::setiap, sesetengah, kebanyakan.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Jubin boleh diseret dipisahkan koma — sertakan jawapan yang betul, ditambah umpan pilihan yang boleh mengelirukan pelajar. Gunakan \, untuk koma literal, dan ___ untuk jubin kosong (untuk tempat kosong yang sepatutnya kekal kosong). Isi tempat kosong di bawah setelah ini ditetapkan.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>cth. pergi, pergi, pergi::setiap, sesetengah, kebanyakan</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>cth. pergi, pergi, pergi, telah pergi</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Jawapan betul untuk setiap tempat kosong</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Ketik pilihan yang betul dalam setiap kotak di bawah.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Pilih jawapan yang betul untuk setiap tempat kosong.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Tempat Kosong %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Isi tempat kosong</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Seret jubin ke tempat kosong di bawah, atau ketik jubin dan kemudian tempat kosong untuk meletakkannya.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Isi setiap tempat kosong dengan jubin.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Pilihan dipisahkan koma — ketik jawapan yang betul di bawah. Gunakan \, untuk koma literal.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Pilihan dipisahkan koma — ketik semua jawapan yang betul di bawah. Gunakan \, untuk koma literal.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>cth. pergi, pergi, pergi, telah pergi</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Hanya satu jawapan betul</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Jawapan betul</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Jawapan betul</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Pilih jawapan yang betul.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Pilih sekurang-kurangnya satu jawapan yang betul.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Tambah soalan</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Alih keluar</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Simpan</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Tajuk diperlukan</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Terangkan tatabahasa</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Tidak dapat memuatkan soalan %1: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Hanya %1 daripada %2 soalan yang diminta dijana — cuba topik yang lebih luas, atau kurangkan bilangan di atas.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Bahasa penerangan</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Bahasa penerangan</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Bahasa topik</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Bahasa topik</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Topik ini tidak boleh dijana. AI hanya mencipta kandungan yang sesuai untuk semua peringkat umur — topik seksual, lucah atau menyinggung tidak disokong. Sila cuba topik lain.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Anda telah menggunakan semua penjanaan AI untuk bulan ini. Cuba lagi bulan depan.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Terlalu banyak laporan hari ini — sila cuba lagi esok.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Perkhidmatan AI sedang sibuk — sila cuba lagi sebentar lagi.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Masukkan tema terlebih dahulu.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Tema terlalu panjang (maks. %1 aksara).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Tetapkan sekurang-kurangnya satu jenis soalan melebihi sifar.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Sesi anda telah tamat — sila log masuk semula.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Tidak dapat menghubungi pelayan. Semak sambungan internet anda dan cuba lagi.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Berlaku ralat. Sila cuba lagi.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Belum log masuk.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Ketik untuk terbalikkan</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Ketik untuk terbalikkan semula</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>TAHU</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>LANGKAU</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Tidak tahu</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Tahu</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Tidak dipilih</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Teks lesen tidak dapat dimuatkan.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Log masuk untuk teruskan</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Membuka pelayar…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Log masuk dengan Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Pustaka atau set dengan nama ini sudah wujud di sini.</translation>
    </message>
    <message>
        <location line="+309"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Set perkataan dengan nama ini sudah wujud di sini.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Set peraturan dengan nama ini sudah wujud di sini.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+37"/>
        <source>Results</source>
        <translation>Keputusan</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Well</source>
        <translation>Kerja</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>done</source>
        <translation>hebat</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>daripada %1</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Kerja yang hebat! Teruskan!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Usaha yang baik! Teruskan berlatih.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Jangan mengalah – latihan menjadikan sempurna!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Sesi ini</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Tidak tahu</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Tahu</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Practice Again</source>
        <translation>Berlatih Semula</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Tetapkan semula kemajuan ujian?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Ini akan mengosongkan kemajuan anda pada set peraturan ini dan memulakan sesi baharu.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 soalan</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Selesai: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Sedang berjalan: %1 / %2</translation>
    </message>
    <message>
        <location line="+67"/>
        <source>← Reset</source>
        <translation>← Tetapkan semula</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Penjelasan Peraturan</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Tiada penjelasan ditambah untuk set ini.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Klip audio</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Ketegasan ejaan</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Ketat</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Biasa</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Longgar</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Mula Ujian</translation>
    </message>
    <message>
        <location line="-198"/>
        <source>Test is completed</source>
        <translation>Ujian telah selesai</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Soalan seterusnya: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Betul: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Peraturan</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Penjelasan Peraturan</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Klip audio</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Batal</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Lihat peraturan</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Putar roda untuk memilih perkataan setiap tempat kosong.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Tempat Kosong %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Seret jubin ke tempat kosong, atau ketik jubin dan kemudian tempat kosong untuk meletakkannya.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Pilih jawapan yang betul.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Pilih semua yang berkenaan.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Betul: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Hantar</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Betul: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Lihat Keputusan</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Seterusnya →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Nombor soalan %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Timpa set perkataan?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Gabungkan pustaka?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Set perkataan bernama “%1” sudah wujud di sini. Timpa dengan set yang dipindahkan?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Pustaka bernama “%1” sudah wujud di sini. Gabungkan kandungannya ke dalamnya?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Set perkataan bernama “%1” sudah wujud di %2. Timpa dengan versi yang digabungkan?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>pustaka destinasi</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Eksport sebagai .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Pustaka Baharu</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Library name:</source>
        <translation>Nama pustaka:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>cth. Perjalanan, Kerja, Sekolah…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Pustaka atau set dengan nama ini sudah wujud di sini.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+74"/>
        <source>A library with this name already exists here.</source>
        <translation>Pustaka dengan nama ini sudah wujud di sini.</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Create</source>
        <translation>Cipta</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Rename Library</source>
        <translation>Namakan Semula Pustaka</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Nama baharu:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Namakan Semula</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Set perkataan anda</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Pustaka</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Alih keluar dari</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Lepaskan untuk pindah ke dalam</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>perkataan</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>soalan</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Padam Pustaka</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Edit</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Padam</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Kongsi fail .ppset</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Eksport .ppset (simpan ke cakera)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Belum ada apa-apa di sini.
Ketik + Cipta untuk menambah set perkataan atau pustaka.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Set Perkataan</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Set Peraturan</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Cipta</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Bahasa Antara Muka</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Cancel</source>
        <translation>Batal</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Pilih Jenis Ujian</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Kad Kilas</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Terbalikkan untuk dedah — leret kanan jika anda tahu</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Tulis Perkataan</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Lihat petunjuk — taip ungkapan</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Tulis Petunjuk</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Lihat perkataan — taip terjemahannya</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Pilih Perkataan</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Lihat petunjuk — pilih daripada 4 pilihan</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Pilih Petunjuk</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Lihat perkataan — pilih daripada 4 pilihan</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Pembelajaran Progresif</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Pilihan berganda untuk belajar, kemudian menulis untuk menguasai semua perkataan</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Pembelajaran Progresif Terbalik</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Pilihan berganda untuk belajar, kemudian menulis untuk menguasai semua petunjuk</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>✓ Done</source>
        <translation>✓ Selesai</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>← Reset</source>
        <translation>← Tetapkan Semula</translation>
    </message>
    <message>
        <location line="+96"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Ketegasan ejaan</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Ketat</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Biasa</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Longgar</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Batal</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Semak Semula Ungkapan</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Henti</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Dengar</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Mula Ujian</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Belum ada perkataan</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Taip petunjuk / terjemahan…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Taip ungkapan…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Betul: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Tandakan sebagai betul (saya tersilap taip)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Hantar</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Tandakan sebagai betul (saya tersilap klik)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Betul: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Lihat Keputusan</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Seterusnya →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Nombor soalan %1</translation>
    </message>
</context>
</TS>
