<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="mr">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>विषयी</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">शब्द संच लक्षात ठेवण्यासाठी शब्दसंग्रह प्रशिक्षक.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>शब्दसंग्रह आणि व्याकरणासाठी प्रशिक्षक.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>ओपन सोर्स परवाने</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>हे अॅप्लिकेशन GNU Lesser General Public License आवृत्ती 3 अंतर्गत Qt वापरते.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Qt सूचना</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Qt सूचना</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Qt स्रोत कोड</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Qt प्रकल्प संकेतस्थळ</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ एआयने तयार केले — यात चुका असू शकतात</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 तक्रार करा</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>धन्यवाद — तुमची तक्रार पाठवली गेली आहे आणि तिचे पुनरावलोकन केले जाईल.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 एआय सामग्रीची तक्रार करा</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>या तयार केलेल्या सामग्रीत काय चूक आहे?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>लैंगिक किंवा सूचक सामग्री</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>शिवीगाळ किंवा आक्षेपार्ह भाषा</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>द्वेषपूर्ण किंवा छळ करणारी सामग्री</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>हिंसक किंवा धोकादायक सामग्री</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>चुकीची किंवा दिशाभूल करणारी माहिती</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>दुसरे काहीतरी</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>तपशील (ऐच्छिक)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>पाठवत आहे…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>बंद करा</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>रद्द करा</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>तक्रार पाठवा</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>फोटो काढा</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>रद्द करा</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>लवकरच येत आहे</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1दि %2ता मध्ये</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1ता %2मि मध्ये</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1मि मध्ये</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>प्रतिमा निवडा</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>ऑडिओ निवडा</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>शब्द संच आयात करा</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>शब्दाची भाषा</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>इशाऱ्याची भाषा</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+339"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>रद्द करा</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ एआय शब्द संच जनरेटर</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Gemini द्वारा समर्थित</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 विषय</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>तुम्हाला हवा असलेला संच वर्णन करा — उदा. “फ्रेंच घरात सापडतील अशा स्वयंपाकघरातील वस्तू” किंवा “परिषदेसाठी व्यावसायिक प्रवासाचे वाक्प्रचार”…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>या महिन्यात %2 पैकी %1 जनरेशन्स शिल्लक — %3 रोजी रीसेट होईल</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>एआय चुका करू शकतो. फक्त सर्व वयोगटांसाठी योग्य सामग्री तयार केली जाते — अयोग्य काहीही आढळल्यास 🚩 तक्रार करा वापरा.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>शब्दाची भाषा</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>इशाऱ्याची भाषा</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 शब्दांची संख्या</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Gemini ला विचारत आहे…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>विनंती रद्द करा</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ तयार करा</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ एआय</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>नवीन शब्द संच</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>शब्द संच संपादित करा</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>आयात करा</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>संचाचे शीर्षक…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>प्रतिमा आपोआप आणा</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>शब्द</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>निवडलेले</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>शब्द / संज्ञा</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>निवडलेले नाही</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>शब्द प्रविष्ट करा...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>इशारा / अर्थ</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>इशारा, व्याख्या...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>वापराचे उदाहरण</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>शब्द वापरून उदाहरण वाक्य...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>प्रतिमा बदला</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>प्रतिमा जोडा</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>आणा</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>कॅमेरा</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>ऑडिओ जोडा</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ थांबवा</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ प्ले करा</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ उच्चार</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ थांबवा</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● रेकॉर्ड</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ शब्द जोडा</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>काढा</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>जतन करा</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>शीर्षक आवश्यक आहे</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>लवकरच</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1दि %2ता मध्ये</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1ता %2मि मध्ये</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1मि मध्ये</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>प्रतिमा निवडा</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>ऑडिओ निवडा</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ एआय</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>नवीन नियम संच</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>नियम संच संपादित करा</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>आयात करा</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>नियम संच आयात करा</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ एआय नियम संच जनरेटर</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Gemini द्वारा समर्थित</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>या महिन्यात %2 पैकी %1 जनरेशन शिल्लक — %3 रोजी रीसेट होईल</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 स्पष्ट करावयाचा नियम/विषय</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>तुम्हाला हवा असलेला नियम वर्णन करा — उदा. &quot;प्रेझेंट सिंपल वि. प्रेझेंट कंटिन्युअस&quot; किंवा &quot;तिसऱ्या प्रकारची अट वाक्ये&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 प्रति प्रकार प्रश्न</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 रिकामी जागा भरा</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 बहुपर्यायी</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 ड्रॉपडाउन निवड</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 ड्रॅग आणि ड्रॉप</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Gemini ला विचारत आहे…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>विनंती रद्द करा</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>रद्द करा</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>एआय चुका करू शकतो. फक्त सर्व वयोगटांसाठी योग्य सामग्री तयार केली जाते — अयोग्य काहीही आढळल्यास 🚩 तक्रार करा वापरा.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ तयार करा</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>शीर्षक प्रविष्ट करा…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>सिद्धांत स्पष्टीकरण</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>विद्यार्थी चूक करेपर्यंत चाचणी दरम्यान लपलेले — पूर्वावलोकनात नेहमी वाचनीय.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>ब्लॉक पुन्हा व्यवस्थित करण्यासाठी ▲▼ वापरा. फोटोचा आकार बदलण्यासाठी त्याचा // कोपरा ड्रॅग करा.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>हा संच सराव करत असलेला नियम स्पष्ट करा…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>ऑडिओ क्लिप</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ मजकूर</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ फोटो</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ ऑडिओ</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>प्रश्न</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>निवडले</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>रिकामी जागा भरा</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>बहुपर्यायी</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>ड्रॉपडाउन निवड</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>ड्रॅग आणि ड्रॉप</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>विद्यार्थी भरत असलेल्या प्रत्येक रिकाम्या जागेसाठी ___ (तीन अधोरेखा) वापरा.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>उदा. ती दररोज काय करते?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>उदा. ती दररोज शाळेत ___.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>उत्तरे</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>प्रत्येक रिकाम्या जागेसाठी एक उत्तर, स्वल्पविरामाने विभक्त, क्रमाने. शाब्दिक स्वल्पविरामासाठी \, वापरा.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>उदा. जाते</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>पर्याय</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>एका रिकाम्या जागेचे पर्याय स्वल्पविरामाने विभक्त करा; रिकाम्या जागा दुहेरी कोलनने (::) विभक्त करा. एकच : जसा आहे तसा सुरक्षित आहे; शाब्दिक स्वल्पविरामासाठी \,, शाब्दिक ::साठी \::, आणि जाणूनबुजून रिकाम्या पर्यायासाठी ___ वापरा. उदा. दोन रिकाम्या जागांसाठी: जाते, जाणे, जात आहे::प्रत्येक, काही, बहुतेक.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>स्वल्पविरामाने विभक्त केलेल्या ड्रॅग करण्यायोग्य टाइल्स — योग्य उत्तरे, तसेच विद्यार्थ्याला फसवू शकणारे पर्यायी सापळे समाविष्ट करा. शाब्दिक स्वल्पविरामासाठी \, आणि रिकाम्या टाइलसाठी ___ वापरा (जी रिकामी जागा योग्यरित्या रिकामी राहावी त्यासाठी). हे सेट झाल्यावर खालील रिकाम्या जागा भरा.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>उदा. जाते, जाणे, जात आहे::प्रत्येक, काही, बहुतेक</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>उदा. जाते, जाणे, जात आहे, गेली</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>प्रत्येक रिकाम्या जागेसाठी योग्य उत्तर</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>खालील प्रत्येक बॉक्समध्ये योग्य पर्यायावर टॅप करा.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>प्रत्येक रिकाम्या जागेसाठी योग्य उत्तर निवडा.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>रिकामी जागा %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>रिकाम्या जागा भरा</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>खालील रिकाम्या जागेवर टाइल ड्रॅग करा, किंवा टाइलवर टॅप करा आणि नंतर ती ठेवण्यासाठी रिकाम्या जागेवर टॅप करा.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>प्रत्येक रिकामी जागा टाइलने भरा.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>स्वल्पविरामाने विभक्त पर्याय — खालील योग्य उत्तरावर टॅप करा. शाब्दिक स्वल्पविरामासाठी \, वापरा.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>स्वल्पविरामाने विभक्त पर्याय — खालील सर्व योग्य उत्तरांवर टॅप करा. शाब्दिक स्वल्पविरामासाठी \, वापरा.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>उदा. जाते, जाणे, जात आहे, गेली</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>फक्त एक योग्य उत्तर</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>योग्य उत्तर</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>योग्य उत्तर(े)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>योग्य उत्तर निवडा.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>किमान एक योग्य उत्तर निवडा.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ प्रश्न जोडा</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>काढा</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>जतन करा</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>शीर्षक आवश्यक आहे</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 व्याकरण स्पष्ट करा</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>%1 प्रश्न लोड करता आला नाही: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>विनंती केलेल्या %2 पैकी फक्त %1 प्रश्न तयार झाले — विस्तृत विषय वापरून पहा, किंवा वरील संख्या कमी करा.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>स्पष्टीकरणाची भाषा</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>स्पष्टीकरणाची भाषा</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>विषयाची भाषा</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>विषयाची भाषा</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>हा विषय तयार करता येणार नाही. एआय फक्त सर्व वयोगटांसाठी योग्य सामग्री तयार करतो — लैंगिक, अश्लील किंवा आक्षेपार्ह विषयांना समर्थन नाही. कृपया दुसरा विषय वापरून पहा.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>तुम्ही या महिन्यातील सर्व एआय निर्मिती वापरल्या आहेत. पुढच्या महिन्यात पुन्हा प्रयत्न करा.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>आज खूप जास्त तक्रारी — कृपया उद्या पुन्हा प्रयत्न करा.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>एआय सेवा सध्या व्यस्त आहे — कृपया थोड्या वेळाने पुन्हा प्रयत्न करा.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>आधी एक विषय प्रविष्ट करा.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>विषय खूप मोठा आहे (कमाल %1 वर्ण).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>किमान एक प्रश्न प्रकार शून्यापेक्षा जास्त सेट करा.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>तुमचे सत्र संपले आहे — कृपया पुन्हा साइन इन करा.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>सर्व्हरशी संपर्क होऊ शकला नाही. तुमचे इंटरनेट कनेक्शन तपासा आणि पुन्हा प्रयत्न करा.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>काहीतरी चुकले. कृपया पुन्हा प्रयत्न करा.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>साइन इन केलेले नाही.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>पलटण्यासाठी टॅप करा</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>परत पलटण्यासाठी टॅप करा</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>माहीत आहे</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>वगळा</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  माहीत नाही</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  माहीत आहे</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>निवडलेले नाही</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>परवाना मजकूर लोड करता आला नाही.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>सुरू ठेवण्यासाठी साइन इन करा</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>ब्राउझर उघडत आहे…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Google सह साइन इन करा</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">या नावाची लायब्ररी किंवा संच येथे आधीच अस्तित्वात आहे.</translation>
    </message>
    <message>
        <location line="+317"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>या नावाचा शब्द संच येथे आधीच अस्तित्वात आहे.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>या नावाचा नियम संच येथे आधीच अस्तित्वात आहे.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+38"/>
        <source>Results</source>
        <translation>निकाल</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>Well</source>
        <translation>उत्तम</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>done</source>
        <translation>काम</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>%1 पैकी</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>उत्कृष्ट काम! असेच सुरू ठेवा!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>चांगला प्रयत्न! सराव सुरू ठेवा.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>हार मानू नका – सरावाने परिपूर्णता येते!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>हे सत्र</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>माहीत नाही</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>माहीत आहे</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Practice again</source>
        <translation>पुन्हा सराव करा</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Find another set</source>
        <translation>दुसरा संच शोधा</translation>
    </message>
    <message>
        <source>Practice Again</source>
        <translation type="vanished">पुन्हा सराव करा</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>चाचणी प्रगती रीसेट करायची?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>हे या नियम संचावरील तुमची प्रगती साफ करेल आणि नवीन सत्र सुरू करेल.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 प्रश्न</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">पूर्ण: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">प्रगतीत: %1 / %2</translation>
    </message>
    <message>
        <source>← Reset</source>
        <translation type="vanished">← रीसेट</translation>
    </message>
    <message>
        <location line="+185"/>
        <source>Reset to practise again</source>
        <translation>पुन्हा सरावासाठी रीसेट करा</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Reset</source>
        <translation>रीसेट करा</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>नियम स्पष्टीकरण</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>या संचासाठी कोणतेही स्पष्टीकरण जोडलेले नाही.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>ऑडिओ क्लिप</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ स्पेलिंग कठोरता</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>कठोर</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>सामान्य</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>सौम्य</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>चाचणी सुरू करा</translation>
    </message>
    <message>
        <location line="-316"/>
        <source>Test is completed</source>
        <translation>चाचणी पूर्ण झाली आहे</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>पुढील प्रश्न: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>बरोबर: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>नियम</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 नियम स्पष्टीकरण</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>ऑडिओ क्लिप</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>रद्द करा</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 नियम पहा</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>प्रत्येक रिकाम्या जागेचा शब्द निवडण्यासाठी चाक फिरवा.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>रिकामी जागा %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>रिकाम्या जागेवर टाइल ड्रॅग करा, किंवा टाइलवर टॅप करा आणि नंतर ती ठेवण्यासाठी रिकाम्या जागेवर टॅप करा.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>योग्य उत्तर निवडा.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>लागू असलेले सर्व निवडा.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>बरोबर: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>सबमिट करा</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>बरोबर: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>निकाल पहा</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>पुढे →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>प्रश्न क्रमांक %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>शब्द संच अधिलिखित करायचा?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>लायब्ररी विलीन करायच्या?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>“%1” नावाचा शब्द संच येथे आधीच अस्तित्वात आहे. हलवलेल्या संचाने तो अधिलिखित करायचा?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>“%1” नावाची लायब्ररी येथे आधीच अस्तित्वात आहे. तिची सामग्री यात विलीन करायची?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>“%1” नावाचा शब्द संच %2 मध्ये आधीच अस्तित्वात आहे. विलीन केलेल्या आवृत्तीने तो अधिलिखित करायचा?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>गंतव्य लायब्ररी</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>.ppset म्हणून निर्यात करा</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>नवीन लायब्ररी</translation>
    </message>
    <message>
        <location line="+31"/>
        <source>Library name:</source>
        <translation>लायब्ररीचे नाव:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>उदा. प्रवास, काम, शाळा…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">या नावाची लायब्ररी किंवा संच येथे आधीच अस्तित्वात आहे.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+99"/>
        <source>A library with this name already exists here.</source>
        <translation>या नावाची लायब्ररी येथे आधीच अस्तित्वात आहे.</translation>
    </message>
    <message>
        <location line="-62"/>
        <source>Create</source>
        <translation>तयार करा</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Rename Library</source>
        <translation>लायब्ररीचे नाव बदला</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>नवीन नाव:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>नाव बदला</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>तुमचे शब्द संच</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>लायब्ररी</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>बाहेर हलवा</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>आत हलवण्यासाठी सोडा</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>शब्द</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>प्रश्न</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>लायब्ररी हटवा</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>संपादित करा</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>हटवा</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>.ppset फाइल शेअर करा</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>.ppset निर्यात करा (डिस्कवर जतन करा)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>इथे अजून काही नाही.
शब्द संच किंवा लायब्ररी जोडण्यासाठी + तयार करा वर टॅप करा.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>शब्द संच</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>नियम संच</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ तयार करा</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>इंटरफेस भाषा</translation>
    </message>
    <message>
        <location line="-710"/>
        <location line="+796"/>
        <source>Cancel</source>
        <translation>रद्द करा</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>चाचणी प्रकार निवडा</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>फ्लॅश कार्ड्स</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>उघड करण्यासाठी पलटवा — माहीत असल्यास उजवीकडे स्वाइप करा</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>शब्द लिहा</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>इशारा पहा — अभिव्यक्ती टाइप करा</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>इशारा लिहा</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>शब्द पहा — त्याचे भाषांतर टाइप करा</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>शब्द निवडा</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>इशारा पहा — 4 पर्यायांपैकी निवडा</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>इशारा निवडा</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>शब्द पहा — 4 पर्यायांपैकी निवडा</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>प्रगतिशील शिक्षण</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>शिकण्यासाठी आधी बहुपर्यायी, नंतर सर्व शब्दांवर प्रभुत्व मिळवण्यासाठी लेखन</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>उलट प्रगतिशील शिक्षण</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>शिकण्यासाठी आधी बहुपर्यायी, नंतर सर्व इशाऱ्यांवर प्रभुत्व मिळवण्यासाठी लेखन</translation>
    </message>
    <message>
        <location line="+36"/>
        <location line="+82"/>
        <source>✓ Done</source>
        <translation>✓ पूर्ण</translation>
    </message>
    <message>
        <location line="-82"/>
        <source>← Reset</source>
        <translation>← रीसेट करा</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Completed — swipe left to reset</source>
        <translation>पूर्ण — रीसेट करण्यासाठी डावीकडे स्वाइप करा</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>%1 left</source>
        <translation>%1 बाकी</translation>
    </message>
    <message>
        <location line="+51"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ स्पेलिंग कठोरता</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>कठोर</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>सामान्य</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>सौम्य</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>रद्द करा</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>अभिव्यक्तींचे पुनरावलोकन करा</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  थांबवा</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  ऐका</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>चाचणी सुरू करा</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>अजून शब्द नाहीत</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>इशारा / भाषांतर टाइप करा…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>अभिव्यक्ती टाइप करा…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>बरोबर: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ बरोबर म्हणून चिन्हांकित करा (माझ्याकडून टायपो झाला)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>सबमिट करा</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ बरोबर म्हणून चिन्हांकित करा (माझ्याकडून चुकीचे क्लिक झाले)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>बरोबर: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>निकाल पहा</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>पुढे →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>प्रश्न क्रमांक %1</translation>
    </message>
</context>
</TS>
