<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="lt">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Apie</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Žodyno treniruoklis žodžių rinkiniams įsiminti.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Žodyno ir gramatikos treniruoklis.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Atvirojo kodo licencijos</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Ši programa naudoja Qt pagal GNU Lesser General Public License 3 versijos licenciją.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Qt pranešimas</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Qt pranešimas</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Qt šaltinio kodas</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Qt projekto svetainė</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Sukurta AI — gali būti klaidų</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Pranešti</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Ačiū — jūsų pranešimas išsiųstas ir bus peržiūrėtas.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Pranešti apie AI turinį</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Kas negerai su šiuo sukurtu turiniu?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Seksualinis ar dviprasmiškas turinys</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Keiksmažodžiai ar įžeidžianti kalba</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Neapykantą kurstantis ar priekabiaujantis turinys</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Smurtinis ar pavojingas turinys</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Klaidinga ar klaidinanti informacija</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Kita</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Išsami informacija (neprivaloma)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Siunčiama…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Uždaryti</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Atšaukti</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Siųsti pranešimą</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Fotografuoti</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Atšaukti</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>greitai</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>po %1d %2val</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>po %1val %2min</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>po %1min</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Pasirinkti vaizdą</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Pasirinkti garsą</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Importuoti žodžių rinkinį</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Žodžio kalba</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Užuominos kalba</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+326"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Atšaukti</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ AI žodžių rinkinių generatorius</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Veikia su Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Tema</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Aprašykite norimą rinkinį — pvz., „virtuvės reikmenys, kuriuos rastum prancūziškuose namuose“ arba „verslo kelionės į konferenciją frazės“…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Liko %1 iš %2 generavimų šį mėnesį — atsinaujins %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI gali klysti. Kuriamas tik visoms amžiaus grupėms tinkamas turinys — pažymėkite bet ką netinkamo mygtuku 🚩 Pranešti.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Žodžio kalba</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Užuominos kalba</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Žodžių skaičius</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Klausiama Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Atšaukti užklausą</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Generuoti</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Naujas žodžių rinkinys</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Redaguoti žodžių rinkinį</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importuoti</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Rinkinio pavadinimas…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Automatiškai gauti vaizdus</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Žodis</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>pasirinkta</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Žodis / Terminas</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Nepasirinkta</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Įveskite žodį...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Užuomina / reikšmė</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Užuomina, apibrėžimas...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Vartojimo pavyzdys</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Pavyzdinis sakinys su žodžiu...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Keisti vaizdą</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Pridėti vaizdą</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Gauti</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Kamera</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Pridėti garsą</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Stabdyti</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Groti</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ Balsu</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Stabdyti</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Įrašyti</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Pridėti žodį</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Šalinti</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Išsaugoti</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Pavadinimas privalomas</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>netrukus</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>po %1d %2val.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>po %1val. %2min.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>po %1min.</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Pasirinkti vaizdą</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Pasirinkti garsą</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ DI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Naujas taisyklių rinkinys</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Redaguoti taisyklių rinkinį</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importuoti</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Importuoti taisyklių rinkinį</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ DI taisyklių rinkinio generatorius</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Veikia su „Gemini“</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Šį mėnesį liko %1 iš %2 generavimų — atsinaujins %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Aiškintina taisyklė / tema</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Aprašykite norimą taisyklę — pvz., „esamasis paprastasis prieš esamąjį tęstinį laiką“ arba „trečiojo tipo sąlygos sakiniai“…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Klausimai pagal tipą</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Užpildykite tarpą</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Kelių pasirinkimų</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Išskleidžiamasis pasirinkimas</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Vilkite ir paleiskite</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Klausiama „Gemini“…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Atšaukti užklausą</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Atšaukti</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI gali klysti. Kuriamas tik visoms amžiaus grupėms tinkamas turinys — pažymėkite bet ką netinkamo mygtuku 🚩 Pranešti.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Generuoti</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Įveskite pavadinimą…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Teorijos paaiškinimas</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Paslėpta testavimo metu, kol besimokantysis padarys klaidą — peržiūroje visada skaitoma.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Naudokite ▲▼ blokui pertvarkyti. Vilkite nuotraukos // kampą, kad pakeistumėte dydį.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Paaiškinkite taisyklę, kurią lavina šis rinkinys…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Garso įrašas</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Tekstas</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Nuotrauka</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Garsas</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Klausimas</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>pasirinkta</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Užpildykite tarpą</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Kelių pasirinkimų</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Išskleidžiamasis pasirinkimas</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Vilkite ir paleiskite</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Naudokite ___ (tris pabraukimus) kiekvienam tarpui, kurį užpildo besimokantysis.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>pvz. Ką ji veikia kasdien?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>pvz. Ji ___ į mokyklą kasdien.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Atsakymai</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Vienas atsakymas kiekvienam tarpui, atskirtas kableliais, eilės tvarka. Naudokite \, tikrajam kableliui.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>pvz. eina</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Parinktys</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Atskirkite vieno tarpo parinktis kableliais; atskirkite tarpus dvigubu dvitaškiu (::). Vienas : yra saugus toks, koks yra; naudokite \, tikrajam kableliui, \:: tikrajam ::, ir ___ tyčia tuščiai parinkčiai. Pvz. dviem tarpams: eina, eiti, einant::kiekvienas, kai kurie, dauguma.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Kableliais atskirtos velkamos plytelės — įtraukite teisingus atsakymus, plius pasirenkamus masalus, kuriais besimokantysis gali būti suklaidintas. Naudokite \, tikrajam kableliui, ir ___ tuščiai plytelei (tarpui, kuris teisingai turi likti tuščias). Užpildykite žemiau esančius tarpus, kai šie nustatyti.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>pvz. eina, eiti, einant::kiekvienas, kai kurie, dauguma</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>pvz. eina, eiti, einant, ėjo</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Teisingas atsakymas kiekvienam tarpui</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Bakstelėkite teisingą pasirinkimą kiekviename langelyje žemiau.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Pasirinkite teisingą atsakymą kiekvienam tarpui.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Tarpas %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Užpildykite tarpus</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Vilkite plytelę į tarpą žemiau arba bakstelėkite plytelę, o tada tarpą, kad ją įdėtumėte.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Užpildykite kiekvieną tarpą plytele.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Kableliais atskirtos parinktys — bakstelėkite teisingą atsakymą žemiau. Naudokite \, tikrajam kableliui.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Kableliais atskirtos parinktys — bakstelėkite visus teisingus atsakymus žemiau. Naudokite \, tikrajam kableliui.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>pvz. eina, eiti, einant, ėjo</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Tik vienas teisingas atsakymas</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Teisingas atsakymas</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Teisingas(-i) atsakymas(-ai)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Pasirinkite teisingą atsakymą.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Pasirinkite bent vieną teisingą atsakymą.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Pridėti klausimą</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Pašalinti</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Išsaugoti</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Būtinas pavadinimas</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Paaiškinti gramatiką</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Nepavyko įkelti %1 klausimo: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Sugeneruota tik %1 iš %2 užklaustų klausimų — pabandykite platesnę temą arba sumažinkite aukščiau esančius skaičius.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Paaiškinimo kalba</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Paaiškinimo kalba</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Temos kalba</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Temos kalba</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Šia tema turinio sukurti negalima. AI kuria tik visoms amžiaus grupėms tinkamą turinį — seksualinės, vulgarios ar įžeidžiančios temos nepalaikomos. Pabandykite kitą temą.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Išnaudojote visus šio mėnesio AI generavimus. Bandykite dar kartą kitą mėnesį.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Šiandien per daug pranešimų — bandykite dar kartą rytoj.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>AI paslauga šiuo metu užimta — bandykite dar kartą po akimirkos.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Pirmiausia įveskite temą.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Tema per ilga (daugiausia %1 simbolių).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Nustatykite bent vieno klausimų tipo skaičių didesnį nei nulis.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Jūsų seansas baigėsi — prisijunkite dar kartą.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Nepavyko pasiekti serverio. Patikrinkite interneto ryšį ir bandykite dar kartą.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Kažkas nepavyko. Bandykite dar kartą.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Neprisijungta.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Bakstelėkite, kad apverstumėte</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Bakstelėkite, kad apverstumėte atgal</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>ŽINAU</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>PRALEISTI</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Nežinau</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Žinau</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Nepasirinkta</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Nepavyko įkelti licencijos teksto.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Prisijunkite, kad tęstumėte</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Atveriama naršyklė…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Prisijungti su Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Biblioteka ar rinkinys tokiu pavadinimu jau yra čia.</translation>
    </message>
    <message>
        <location line="+309"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Žodžių rinkinys tokiu pavadinimu jau yra čia.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Taisyklių rinkinys tokiu pavadinimu jau yra čia.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+37"/>
        <source>Results</source>
        <translation>Rezultatai</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Well</source>
        <translation>Puikiai</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>done</source>
        <translation>atlikta</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>iš %1</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Puikus darbas! Taip toliau!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Geros pastangos! Toliau treniruokitės.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Nepasiduokite – treniruotės daro tobulą!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Ši sesija</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Nežinau</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Žinau</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Practice Again</source>
        <translation>Treniruotis dar kartą</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Atkurti testo eigą?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Tai išvalys jūsų pažangą šiame taisyklių rinkinyje ir pradės naują seansą.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 klausimai</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Baigta: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Vykdoma: %1 / %2</translation>
    </message>
    <message>
        <location line="+67"/>
        <source>← Reset</source>
        <translation>← Atkurti</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Taisyklės paaiškinimas</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Šiam rinkiniui paaiškinimas nepridėtas.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Garso įrašas</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Rašybos griežtumas</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Griežtas</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Įprastas</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Švelnus</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Pradėti testą</translation>
    </message>
    <message>
        <location line="-198"/>
        <source>Test is completed</source>
        <translation>Testas baigtas</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Kitas klausimas: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Teisingai: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Taisyklė</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Taisyklės paaiškinimas</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Garso įrašas</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Atšaukti</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Peržiūrėti taisyklę</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Pasukite ratą, kad pasirinktumėte kiekvieno tarpo žodį.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Tarpas %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Vilkite plytelę į tarpą arba bakstelėkite plytelę, o tada tarpą, kad ją įdėtumėte.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Pasirinkite teisingą atsakymą.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Pasirinkite visus tinkamus.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Teisingai: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Pateikti</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Teisingai: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Žiūrėti rezultatus</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Toliau →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Klausimo numeris %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Perrašyti žodžių rinkinį?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Sujungti bibliotekas?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Žodžių rinkinys pavadinimu „%1“ jau yra čia. Perrašyti jį perkeltu rinkiniu?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Biblioteka pavadinimu „%1“ jau yra čia. Sujungti jos turinį su ja?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Žodžių rinkinys pavadinimu „%1“ jau yra %2. Perrašyti jį sujungta versija?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>paskirties biblioteka</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Eksportuoti kaip .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Nauja biblioteka</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Library name:</source>
        <translation>Bibliotekos pavadinimas:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>pvz., Kelionės, Darbas, Mokykla…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Biblioteka ar rinkinys tokiu pavadinimu jau yra čia.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+74"/>
        <source>A library with this name already exists here.</source>
        <translation>Biblioteka tokiu pavadinimu jau yra čia.</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Create</source>
        <translation>Kurti</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Rename Library</source>
        <translation>Pervadinti biblioteką</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Naujas pavadinimas:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Pervadinti</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Jūsų žodžių rinkiniai</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Biblioteka</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Iškelti iš</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Nuleiskite, kad perkeltumėte į vidų</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>žodžių</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>klausimai</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Ištrinti biblioteką</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Redaguoti</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Ištrinti</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Bendrinti .ppset failą</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Eksportuoti .ppset (išsaugoti diske)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Čia dar nieko nėra.
Bakstelėkite + Kurti, kad pridėtumėte žodžių rinkinį ar biblioteką.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Žodžių rinkinys</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Taisyklių rinkinys</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Kurti</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Sąsajos kalba</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Cancel</source>
        <translation>Atšaukti</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Pasirinkite testo tipą</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Atmintinės kortelės</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Apverskite, kad atskleistumėte — perbraukite dešinėn, jei žinote</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Parašykite žodį</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Pažiūrėkite užuominą — įveskite posakį</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Parašykite užuominą</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Pažiūrėkite žodį — įveskite jo vertimą</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Pasirinkite žodį</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Pažiūrėkite užuominą — pasirinkite iš 4 variantų</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Pasirinkite užuominą</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Pažiūrėkite žodį — pasirinkite iš 4 variantų</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Progresyvus mokymasis</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Iš pradžių renkatės iš variantų, tada rašote, kad įsisavintumėte visus žodžius</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Atvirkštinis progresyvus mokymasis</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Iš pradžių renkatės iš variantų, tada rašote, kad įsisavintumėte visas užuominas</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>✓ Done</source>
        <translation>✓ Atlikta</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>← Reset</source>
        <translation>← Atstatyti</translation>
    </message>
    <message>
        <location line="+96"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Rašybos griežtumas</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Griežtas</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Įprastas</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Švelnus</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Atšaukti</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Peržiūrėti posakius</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Stabdyti</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Klausytis</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Pradėti testą</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Kol kas žodžių nėra</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Įveskite užuominą / vertimą…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Įveskite posakį…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Teisingai: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Pažymėti kaip teisingą (suklydau rašydamas)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Pateikti</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Pažymėti kaip teisingą (paspaudžiau netyčia)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Teisingai: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Žiūrėti rezultatus</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Toliau →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Klausimo numeris %1</translation>
    </message>
</context>
</TS>
