<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="fr">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>À propos</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Entraîneur de vocabulaire pour mémoriser des ensembles de mots.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Entraîneur de vocabulaire et de grammaire.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Licences open source</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Cette application utilise Qt sous la licence GNU Lesser General Public License version 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Avis Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Avis Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Code source de Qt</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Site du projet Qt</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Généré par IA — peut contenir des erreurs</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Signaler</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Merci — votre signalement a été envoyé et sera examiné.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Signaler un contenu d&apos;IA</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Quel est le problème avec ce contenu généré ?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Contenu sexuel ou suggestif</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Grossièretés ou propos offensants</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Contenu haineux ou harcelant</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Contenu violent ou dangereux</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Informations erronées ou trompeuses</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Autre chose</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Détails (facultatif)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Envoi…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Fermer</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Annuler</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Envoyer le signalement</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Prendre une photo</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Annuler</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>bientôt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>dans %1j %2h</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>dans %1h %2min</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>dans %1min</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Sélectionner une image</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Sélectionner un audio</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Importer un ensemble de mots</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Langue du mot</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Langue de l&apos;indice</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+326"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Annuler</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ Générateur d&apos;ensembles de mots par IA</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Propulsé par Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Thème</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Décrivez l&apos;ensemble souhaité — p. ex. « ustensiles de cuisine que l&apos;on trouverait dans un foyer français » ou « phrases de voyage d&apos;affaires pour une conférence »…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>%1 génération(s) sur %2 restantes ce mois-ci — réinitialisation %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>L&apos;IA peut se tromper. Seul du contenu adapté à tous les âges est généré — utilisez 🚩 Signaler pour signaler tout contenu inapproprié.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Langue du mot</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Langue de l&apos;indice</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Nombre de mots</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Interrogation de Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Annuler la demande</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Générer</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ IA</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Nouvel ensemble de mots</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Modifier l&apos;ensemble de mots</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importer</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Titre de l&apos;ensemble…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Récupérer les images automatiquement</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Mot</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>sélectionné</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Mot / Terme</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Non sélectionné</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Saisir le mot...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Indice / signification</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Indice, définition...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Exemple d&apos;utilisation</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Phrase d&apos;exemple utilisant le mot...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Changer l&apos;image</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Ajouter une image</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Récupérer</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Appareil photo</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Ajouter un audio</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Arrêter</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Lire</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ Synthèse vocale</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Arrêter</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Enr.</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Ajouter un mot</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Supprimer</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Enregistrer</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Le titre est obligatoire</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>bientôt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>dans %1j %2h</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>dans %1h %2min</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>dans %1min</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Sélectionner une image</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Sélectionner un audio</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ IA</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Nouvel ensemble de règles</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Modifier l&apos;ensemble de règles</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importer</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Importer un ensemble de règles</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ Générateur d&apos;ensembles de règles par IA</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Propulsé par Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Il reste %1 générations sur %2 ce mois-ci — réinitialisation %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Règle/sujet à expliquer</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Décrivez la règle que vous voulez — p. ex. &quot;présent simple vs présent continu&quot; ou &quot;phrases conditionnelles de troisième type&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Questions par type</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Compléter le trou</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Choix multiple</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Choix déroulant</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Glisser-déposer</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Interrogation de Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Annuler la demande</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Annuler</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>L&apos;IA peut se tromper. Seul du contenu adapté à tous les âges est généré — utilisez 🚩 Signaler pour signaler tout contenu inapproprié.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Générer</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Saisir le titre…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Explication de la théorie</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Masqué pendant le test jusqu&apos;à ce que l&apos;apprenant fasse une erreur — toujours lisible en aperçu.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Utilisez ▲▼ pour réorganiser un bloc. Faites glisser le coin // d&apos;une photo pour la redimensionner.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Expliquez la règle que pratique cet ensemble…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Extrait audio</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Texte</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Photo</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Audio</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Question</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>sélectionné</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Compléter le trou</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Choix multiple</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Choix déroulant</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Glisser-déposer</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Utilisez ___ (trois traits de soulignement) pour chaque trou que l&apos;apprenant complète.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>p. ex. Que fait-elle chaque jour ?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>p. ex. Elle va ___ à l&apos;école chaque jour.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Réponses</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Une réponse par trou, séparées par des virgules, dans l&apos;ordre. Utilisez \, pour une virgule littérale.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>p. ex. va</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Options</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Séparez les options d&apos;un trou par des virgules ; séparez les trous par un double deux-points (::). Un seul : est sûr tel quel ; utilisez \, pour une virgule littérale, \:: pour un :: littéral, et ___ pour une option volontairement vide. P. ex. pour deux trous : va, aller, allant::chaque, certains, la plupart.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Tuiles à glisser séparées par des virgules — incluez les bonnes réponses, plus des leurres facultatifs qui peuvent tromper l&apos;apprenant. Utilisez \, pour une virgule littérale, et ___ pour une tuile vide (pour un trou qui doit rester vide à juste titre). Complétez les trous ci-dessous une fois ceux-ci définis.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>p. ex. va, aller, allant::chaque, certains, la plupart</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>p. ex. va, aller, allant, allé</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Bonne réponse pour chaque trou</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Touchez le bon choix dans chaque case ci-dessous.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Sélectionnez une bonne réponse pour chaque trou.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Trou %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Complétez les trous</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Faites glisser une tuile vers un trou ci-dessous, ou touchez une tuile puis un trou pour la placer.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Complétez chaque trou avec une tuile.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Options séparées par des virgules — touchez la bonne réponse ci-dessous. Utilisez \, pour une virgule littérale.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Options séparées par des virgules — touchez toutes les bonnes réponses ci-dessous. Utilisez \, pour une virgule littérale.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>p. ex. va, aller, allant, allé</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Une seule bonne réponse</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Bonne réponse</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Bonne(s) réponse(s)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Sélectionnez la bonne réponse.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Sélectionnez au moins une bonne réponse.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Ajouter une question</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Supprimer</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Enregistrer</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Le titre est obligatoire</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Expliquer la grammaire</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Impossible de charger la question %1 : %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Seulement %1 question(s) sur %2 demandées ont été générées — essayez un sujet plus large ou réduisez les nombres ci-dessus.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Langue de l&apos;explication</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Langue de l&apos;explication</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Langue du sujet</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Langue du sujet</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Ce sujet ne peut pas être généré. L&apos;IA ne crée que du contenu adapté à tous les âges — les sujets sexuels, vulgaires ou offensants ne sont pas pris en charge. Veuillez essayer un autre sujet.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Vous avez utilisé toutes vos générations par IA pour ce mois-ci. Réessayez le mois prochain.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Trop de signalements aujourd&apos;hui — veuillez réessayer demain.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Le service d&apos;IA est actuellement occupé — veuillez réessayer dans un instant.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Saisissez d&apos;abord un thème.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Le thème est trop long (%1 caractères max.).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Réglez au moins un type de question au-dessus de zéro.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Votre session a expiré — veuillez vous reconnecter.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Impossible de joindre le serveur. Vérifiez votre connexion Internet et réessayez.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Une erreur s&apos;est produite. Veuillez réessayer.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Non connecté.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Touchez pour retourner</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Touchez pour retourner à nouveau</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>JE SAIS</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>PASSER</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Je ne sais pas</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Je sais</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Non sélectionné</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Impossible de charger le texte de la licence.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Connectez-vous pour continuer</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Ouverture du navigateur…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Se connecter avec Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Une bibliothèque ou un ensemble portant ce nom existe déjà ici.</translation>
    </message>
    <message>
        <location line="+309"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Un ensemble de mots portant ce nom existe déjà ici.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Un ensemble de règles portant ce nom existe déjà ici.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+37"/>
        <source>Results</source>
        <translation>Résultats</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Well</source>
        <translation>Bien</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>done</source>
        <translation>joué</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>sur %1</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Excellent travail ! Continuez ainsi !</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Bel effort ! Continuez à vous entraîner.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>N&apos;abandonnez pas – c&apos;est en forgeant qu&apos;on devient forgeron !</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Cette session</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Je ne sais pas</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Je sais</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Practice Again</source>
        <translation>S&apos;entraîner à nouveau</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Réinitialiser la progression du test ?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Cela effacera votre progression sur cet ensemble de règles et démarrera une nouvelle session.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 questions</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Terminé : %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">En cours : %1 / %2</translation>
    </message>
    <message>
        <location line="+67"/>
        <source>← Reset</source>
        <translation>← Réinitialiser</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Explication de la règle</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Aucune explication n&apos;a été ajoutée pour cet ensemble.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Extrait audio</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Rigueur orthographique</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Stricte</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normale</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Souple</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Démarrer le test</translation>
    </message>
    <message>
        <location line="-198"/>
        <source>Test is completed</source>
        <translation>Le test est terminé</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Question suivante : #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Correct : %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Règle</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Explication de la règle</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Extrait audio</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Annuler</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Voir la règle</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Tournez la roue pour choisir le mot de chaque trou.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Trou %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Faites glisser une tuile vers un trou, ou touchez une tuile puis un trou pour la placer.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Sélectionnez la bonne réponse.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Sélectionnez toutes celles qui s&apos;appliquent.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Correct : </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Envoyer</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Correct : %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Voir les résultats</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Suivant →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Question numéro %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Écraser l&apos;ensemble de mots ?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Fusionner les bibliothèques ?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Un ensemble de mots nommé « %1 » existe déjà ici. L&apos;écraser avec l&apos;ensemble déplacé ?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Une bibliothèque nommée « %1 » existe déjà ici. Fusionner son contenu avec elle ?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Un ensemble de mots nommé « %1 » existe déjà dans %2. L&apos;écraser avec la version en cours de fusion ?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>la bibliothèque de destination</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Exporter en .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Nouvelle bibliothèque</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Library name:</source>
        <translation>Nom de la bibliothèque :</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>p. ex. Voyage, Travail, École…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Une bibliothèque ou un ensemble portant ce nom existe déjà ici.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+74"/>
        <source>A library with this name already exists here.</source>
        <translation>Une bibliothèque portant ce nom existe déjà ici.</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Create</source>
        <translation>Créer</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Rename Library</source>
        <translation>Renommer la bibliothèque</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Nouveau nom :</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Renommer</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Vos ensembles de mots</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Bibliothèque</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Sortir de</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Déposer pour déplacer à l&apos;intérieur</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>mots</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>questions</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Supprimer la bibliothèque</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Modifier</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Supprimer</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Partager le fichier .ppset</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Exporter .ppset (enregistrer sur le disque)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Rien ici pour l&apos;instant.
Touchez + Créer pour ajouter un ensemble de mots ou une bibliothèque.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Ensemble de mots</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Ensemble de règles</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Créer</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Langue de l&apos;interface</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Cancel</source>
        <translation>Annuler</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Choisir le type de test</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Cartes mémoire</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Retournez pour révéler — glissez à droite si vous le savez</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Écrire le mot</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Voir l&apos;indice — saisir l&apos;expression</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Écrire l&apos;indice</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Voir le mot — saisir sa traduction</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Choisir le mot</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Voir l&apos;indice — choisir parmi 4 options</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Choisir l&apos;indice</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Voir le mot — choisir parmi 4 options</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Apprentissage progressif</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>QCM pour apprendre, puis écriture pour maîtriser tous les mots</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Apprentissage progressif inversé</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>QCM pour apprendre, puis écriture pour maîtriser tous les indices</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>✓ Done</source>
        <translation>✓ Terminé</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>← Reset</source>
        <translation>← Réinitialiser</translation>
    </message>
    <message>
        <location line="+96"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Rigueur orthographique</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Stricte</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normale</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Souple</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Annuler</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Réviser les expressions</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Arrêter</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Écouter</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Démarrer le test</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Aucun mot pour l&apos;instant</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Saisissez l&apos;indice / la traduction…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Saisissez l&apos;expression…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Correct : </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Marquer comme correct (faute de frappe)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Valider</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Marquer comme correct (mauvais clic)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Correct : %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Voir les résultats</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Suivant →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Question numéro %1</translation>
    </message>
</context>
</TS>
