<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ja">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>アプリについて</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">単語セットを記憶するための語彙トレーナー。</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>語彙と文法のトレーナー。</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>オープンソースライセンス</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>本アプリケーションは GNU Lesser General Public License バージョン3のもとで Qt を使用しています。</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Qt に関する通知</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Qt に関する通知</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Qt ソースコード</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Qt プロジェクトのウェブサイト</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ AI が生成 — 誤りを含む場合があります</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 報告</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>ありがとうございます。報告は送信され、確認されます。</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 AI コンテンツを報告</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>この生成されたコンテンツの問題点は何ですか？</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>性的または示唆的なコンテンツ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>卑語や不快な言葉</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>憎悪や嫌がらせを含むコンテンツ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>暴力的または危険なコンテンツ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>誤った情報や誤解を招く情報</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>その他</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>詳細（任意）</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>送信中…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>閉じる</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>キャンセル</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>報告を送信</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>写真を撮る</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>キャンセル</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>近日公開</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1日%2時間後</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1時間%2分後</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1分後</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>画像を選択</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>音声を選択</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>単語セットをインポート</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>単語の言語</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>ヒントの言語</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+339"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>キャンセル</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ AI 単語セットジェネレーター</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Gemini 搭載</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 テーマ</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>作成したいセットを説明してください — 例:「フランスの家庭にありそうな台所用品」や「出張で会議に行くときのフレーズ」など…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>今月の残り生成回数 %1/%2 — %3 にリセット</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI は間違えることがあります。すべての年齢に適したコンテンツのみが生成されます。不適切なものがあれば 🚩 報告 から報告してください。</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>単語の言語</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>ヒントの言語</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 単語数</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Gemini に問い合わせ中…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>リクエストをキャンセル</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ 生成</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>新しい単語セット</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>単語セットを編集</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>インポート</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>セットのタイトル…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>画像を自動取得</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>単語</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>選択済み</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>単語 / 用語</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>未選択</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>単語を入力...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>ヒント / 意味</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>ヒント、定義...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>使用例</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>この単語を使った例文...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>画像を変更</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>画像を追加</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>取得</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>カメラ</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>音声を追加</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ 停止</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ 再生</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ 読み上げ</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ 停止</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● 録音</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ 単語を追加</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>削除</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>タイトルは必須です</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>まもなく</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>%1日%2時間後</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>%1時間%2分後</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>%1分後</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>画像を選択</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>音声を選択</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>新しいルールセット</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>ルールセットを編集</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>インポート</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>ルールセットをインポート</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ AIルールセットジェネレーター</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Gemini搭載</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>今月の生成回数は残り%1/%2 — %3にリセット</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 説明するルール／トピック</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>希望するルールを説明してください — 例:「現在形と現在進行形の違い」や「第3条件文」…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 種類ごとの問題数</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 空所補充</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 多肢選択</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 ドロップダウン選択</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 ドラッグ＆ドロップ</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Geminiに問い合わせ中…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>リクエストをキャンセル</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>キャンセル</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>AI は間違えることがあります。すべての年齢に適したコンテンツのみが生成されます。不適切なものがあれば 🚩 報告 から報告してください。</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ 生成</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>タイトルを入力…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>理論の説明</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>学習者が間違えるまでテスト中は非表示 — プレビューでは常に閲覧可能。</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>▲▼を使ってブロックの順序を変更します。写真の//の角をドラッグしてサイズを変更します。</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>このセットが練習するルールを説明してください…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>音声クリップ</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ テキスト</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ 写真</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ 音声</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>問題</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>選択済み</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>空所補充</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>多肢選択</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>ドロップダウン選択</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>ドラッグ＆ドロップ</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>学習者が埋める各空所には___（アンダースコア3つ）を使用してください。</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>例: 彼女は毎日何をしますか？</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>例: 彼女は毎日学校に___。</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>答え</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>空所ごとに1つの答えを、カンマで区切って順番に入力します。文字通りのカンマには\,を使用してください。</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>例: 行く</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>選択肢</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>1つの空所の選択肢はカンマで区切り、空所同士は二重コロン（::）で区切ります。単一の : はそのまま安全です。文字通りのカンマには\,、文字通りの::には\::、意図的に空の選択肢には___を使用してください。例：2つの空所の場合: 行く、行く、行っている::毎、いくつか、ほとんど。</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>カンマ区切りのドラッグ可能なタイル — 正しい答えに加え、学習者を惑わせる可能性のある任意のおとりを含めます。文字通りのカンマには\,、空のタイルには___を使用してください（正しく空のままにすべき空所用）。これらが設定されたら、以下の空所を埋めてください。</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>例: 行く、行く、行っている::毎、いくつか、ほとんど</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>例: 行く、行く、行っている、行った</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>各空所の正解</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>以下の各ボックスで正しい選択肢をタップしてください。</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>各空所に正しい答えを選択してください。</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>空所 %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>空所を埋める</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>以下の空所にタイルをドラッグするか、タイルをタップしてから空所をタップして配置します。</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>各空所をタイルで埋めてください。</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>カンマ区切りの選択肢 — 以下の正しい答えをタップしてください。文字通りのカンマには\,を使用してください。</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>カンマ区切りの選択肢 — 以下のすべての正しい答えをタップしてください。文字通りのカンマには\,を使用してください。</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>例: 行く、行く、行っている、行った</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>正解は1つのみ</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>正解</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>正解</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>正しい答えを選択してください。</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>少なくとも1つの正しい答えを選択してください。</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ 問題を追加</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>削除</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>タイトルは必須です</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 文法を説明</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>%1 の質問を読み込めませんでした: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>要求された%2問中%1問しか生成されませんでした — より広いトピックを試すか、上の数を減らしてください。</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>説明の言語</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>説明の言語</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>トピックの言語</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>トピックの言語</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>このトピックは生成できません。AI はすべての年齢に適したコンテンツのみを作成します。性的、卑猥、または不快なトピックには対応していません。別のトピックをお試しください。</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>今月の AI 生成回数をすべて使い切りました。来月もう一度お試しください。</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>今日は報告が多すぎます。明日もう一度お試しください。</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>AI サービスは現在混み合っています。しばらくしてからもう一度お試しください。</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>先にテーマを入力してください。</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>テーマが長すぎます（最大 %1 文字）。</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>少なくとも 1 つの問題タイプを 0 より大きくしてください。</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>セッションの有効期限が切れました。もう一度サインインしてください。</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>サーバーに接続できませんでした。インターネット接続を確認して、もう一度お試しください。</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>問題が発生しました。もう一度お試しください。</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>サインインしていません。</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>タップして裏返す</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>タップして戻す</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>知っている</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>スキップ</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  知らない</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  知っている</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>未選択</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>ライセンス文を読み込めませんでした。</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>続けるにはサインインしてください</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>ブラウザを開いています…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Google でサインイン</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">この名前のライブラリまたはセットはすでに存在します。</translation>
    </message>
    <message>
        <location line="+317"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>この名前の単語セットはすでに存在します。</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>この名前のルールセットはすでに存在します。</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+38"/>
        <source>Results</source>
        <translation>結果</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>Well</source>
        <translation>よくできました</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>done</source>
        <translation>完了</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>%1 問中</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>素晴らしい成果です！その調子！</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>よく頑張りました！練習を続けましょう。</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>諦めないで――練習は完璧への道！</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>今回のセッション</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>知らない</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>知っている</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Practice again</source>
        <translation>もう一度練習</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Find another set</source>
        <translation>別のセットを探す</translation>
    </message>
    <message>
        <source>Practice Again</source>
        <translation type="vanished">もう一度練習</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>テストの進行状況をリセットしますか？</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>これにより、このルールセットの進行状況が消去され、新しいセッションが開始されます。</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1問</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">完了: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">進行中: %1 / %2</translation>
    </message>
    <message>
        <source>← Reset</source>
        <translation type="vanished">← リセット</translation>
    </message>
    <message>
        <location line="+185"/>
        <source>Reset to practise again</source>
        <translation>リセットしてもう一度練習</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Reset</source>
        <translation>リセット</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>ルールの説明</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>このセットには説明が追加されていません。</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>音声クリップ</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ スペルの厳しさ</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>厳格</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>標準</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>寛容</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>テスト開始</translation>
    </message>
    <message>
        <location line="-316"/>
        <source>Test is completed</source>
        <translation>テストは完了しました</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>次の質問: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>正解: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>ルール</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 ルールの説明</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>音声クリップ</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>キャンセル</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 ルールを見る</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>ホイールを回して各空所の単語を選んでください。</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>空所 %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>空所にタイルをドラッグするか、タイルをタップしてから空所をタップして配置します。</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>正しい答えを選択してください。</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>該当するものをすべて選択してください。</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>正解: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>送信</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>正解: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>結果を見る</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>次へ →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>質問番号 %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>単語セットを上書きしますか？</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>ライブラリを統合しますか？</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>「%1」という名前の単語セットはすでに存在します。移動したセットで上書きしますか？</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>「%1」という名前のライブラリはすでに存在します。その内容をこのライブラリに統合しますか？</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>「%1」という名前の単語セットは %2 にすでに存在します。統合されたバージョンで上書きしますか？</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>移動先のライブラリ</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>.ppset としてエクスポート</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>新しいライブラリ</translation>
    </message>
    <message>
        <location line="+31"/>
        <source>Library name:</source>
        <translation>ライブラリ名:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>例: 旅行、仕事、学校…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">この名前のライブラリまたはセットはすでに存在します。</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+99"/>
        <source>A library with this name already exists here.</source>
        <translation>この名前のライブラリはすでに存在します。</translation>
    </message>
    <message>
        <location line="-62"/>
        <source>Create</source>
        <translation>作成</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Rename Library</source>
        <translation>ライブラリ名を変更</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>新しい名前:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>名前を変更</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>あなたの単語セット</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>ライブラリ</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>外に移動</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>ドロップして中に移動</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>単語</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>問題</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>ライブラリを削除</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>編集</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>削除</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>.ppset ファイルを共有</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>.ppset をエクスポート（ディスクに保存）</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>まだ何もありません。
「+ 作成」をタップして単語セットまたはライブラリを追加してください。</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>単語セット</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>ルールセット</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ 作成</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>インターフェース言語</translation>
    </message>
    <message>
        <location line="-710"/>
        <location line="+796"/>
        <source>Cancel</source>
        <translation>キャンセル</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>テストの種類を選択</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>フラッシュカード</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>タップして確認 — 知っていれば右にスワイプ</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>単語を書く</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>ヒントを見て表現を入力</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>ヒントを書く</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>単語を見てその翻訳を入力</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>単語を選ぶ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>ヒントを見て4つの選択肢から選ぶ</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>ヒントを選ぶ</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>単語を見て4つの選択肢から選ぶ</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>段階的学習</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>まず選択式で学び、その後記述式ですべての単語を習得</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>逆順段階的学習</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>まず選択式で学び、その後記述式ですべてのヒントを習得</translation>
    </message>
    <message>
        <location line="+36"/>
        <location line="+82"/>
        <source>✓ Done</source>
        <translation>✓ 完了</translation>
    </message>
    <message>
        <location line="-82"/>
        <source>← Reset</source>
        <translation>← リセット</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Completed — swipe left to reset</source>
        <translation>完了 — 左にスワイプしてリセット</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>%1 left</source>
        <translation>残り%1</translation>
    </message>
    <message>
        <location line="+51"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ スペルの厳しさ</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>厳格</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>標準</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>寛容</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>キャンセル</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>表現を復習</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  停止</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  聞く</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>テストを開始</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>まだ単語がありません</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>ヒント / 翻訳を入力…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>表現を入力…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>正解: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ 正解としてマーク（タイプミスでした）</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>送信</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ 正解としてマーク（誤クリックでした）</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>正解: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>結果を見る</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>次へ →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>質問番号 %1</translation>
    </message>
</context>
</TS>
