<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="cy">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Ynghylch</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Hyfforddwr geirfa ar gyfer cofio setiau geiriau.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Hyfforddwr geirfa a gramadeg.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Trwyddedau Ffynhonnell Agored</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Mae&apos;r cymhwysiad hwn yn defnyddio Qt o dan drwydded GNU Lesser General Public License fersiwn 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Hysbysiad Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Hysbysiad Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Cod ffynhonnell Qt</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Gwefan prosiect Qt</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Wedi&apos;i gynhyrchu gan AI — gall gynnwys camgymeriadau</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Adrodd</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Diolch — mae eich adroddiad wedi&apos;i anfon a bydd yn cael ei adolygu.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Adrodd cynnwys AI</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Beth sydd o&apos;i le ar y cynnwys hwn a gynhyrchwyd?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Cynnwys rhywiol neu awgrymog</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Rhegi neu iaith sarhaus</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Cynnwys casineb neu aflonyddu</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Cynnwys treisgar neu beryglus</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Gwybodaeth anghywir neu gamarweiniol</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Rhywbeth arall</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Manylion (dewisol)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Wrthi&apos;n anfon…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Cau</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Canslo</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Anfon adroddiad</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Tynnu Llun</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Canslo</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>yn fuan</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>mewn %1d %2a</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>mewn %1a %2m</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>mewn %1m</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Dewis Delwedd</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Dewis Sain</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Mewnforio Set Eiriau</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Iaith y Gair</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Iaith yr Awgrym</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+326"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Canslo</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ Cynhyrchydd Setiau Geiriau AI</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Wedi&apos;i bweru gan Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Thema</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Disgrifiwch y set rydych ei heisiau — e.e. «eitemau cegin y byddech yn dod o hyd iddynt mewn cartref Ffrengig» neu «ymadroddion teithio busnes ar gyfer cynhadledd»…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>%1 o %2 cynhyrchiad ar ôl y mis hwn — yn ailosod ar %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>Gall AI wneud camgymeriadau. Dim ond cynnwys sy&apos;n addas i bob oed sy&apos;n cael ei gynhyrchu — defnyddiwch 🚩 Adrodd i dynnu sylw at unrhyw beth amhriodol.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Iaith y gair</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Iaith yr awgrym</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Nifer y geiriau</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Yn gofyn i Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Canslo&apos;r Cais</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Cynhyrchu</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Set Eiriau Newydd</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Golygu Set Eiriau</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Mewnforio</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Teitl y set…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Nôl delweddau&apos;n awtomatig</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Gair</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>dewiswyd</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Gair / Term</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Heb ddewis</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Rhowch y gair...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Awgrym / ystyr</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Awgrym, diffiniad...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Enghraifft o ddefnydd</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Brawddeg enghreifftiol yn defnyddio&apos;r gair...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Newid delwedd</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Ychwanegu delwedd</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Nôl</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Camera</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Ychwanegu sain</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Stopio</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Chwarae</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ Llefaru</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Stopio</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Recordio</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Ychwanegu gair</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Tynnu</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Cadw</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Mae angen teitl</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>yn fuan</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>mewn %1d %2a</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>mewn %1a %2m</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>mewn %1m</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Dewis Llun</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Dewis Sain</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ AI</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Set Reolau Newydd</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Golygu Set Reolau</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Mewnforio</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Mewnforio Set Reolau</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ Cynhyrchydd Set Reolau AI</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Wedi&apos;i bweru gan Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>%1 o %2 cynhyrchiad ar ôl y mis hwn — ailosod %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Rheol/pwnc i&apos;w esbonio</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Disgrifiwch y rheol rydych ei heisiau — e.e. &quot;present simple vs present continuous&quot; neu &quot;brawddegau amodol trydydd math&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Cwestiynau fesul math</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Llenwi&apos;r Bwlch</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Amlddewis</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Dewis Gostwng i Lawr</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Llusgo a Gollwng</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Gofyn i Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Diddymu&apos;r cais</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Diddymu</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>Gall AI wneud camgymeriadau. Dim ond cynnwys sy&apos;n addas i bob oed sy&apos;n cael ei gynhyrchu — defnyddiwch 🚩 Adrodd i dynnu sylw at unrhyw beth amhriodol.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Cynhyrchu</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Rhowch deitl…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Esboniad Damcaniaeth</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Wedi&apos;i guddio yn ystod y prawf nes bod y dysgwr yn gwneud camgymeriad — bob amser yn ddarllenadwy yn yr olwg ymlaen llaw.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Defnyddiwch ▲▼ i ad-drefnu bloc. Llusgwch gornel // llun i&apos;w ailfeintio.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Esboniwch y rheol y mae&apos;r set hon yn ei hymarfer…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Clip Sain</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Testun</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Llun</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Sain</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Cwestiwn</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>dewiswyd</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Llenwi&apos;r Bwlch</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Amlddewis</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Dewis Gostwng i Lawr</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Llusgo a Gollwng</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Defnyddiwch ___ (tri thanlinelliad) ar gyfer pob bwlch y mae&apos;r dysgwr yn ei lenwi.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>e.e. Beth mae hi&apos;n ei wneud bob dydd?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>e.e. Mae hi&apos;n ___ i&apos;r ysgol bob dydd.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Atebion</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Un ateb fesul bwlch, wedi&apos;u gwahanu â choma, mewn trefn. Defnyddiwch \, ar gyfer coma llythrennol.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>e.e. yn mynd</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Opsiynau</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Gwahanwch ddewisiadau ar gyfer un bwlch â choma; gwahanwch fylchau â cholon dwbl (::). Mae : sengl yn ddiogel fel ag y mae; defnyddiwch \, ar gyfer coma llythrennol, \:: ar gyfer :: llythrennol, ac ___ ar gyfer dewis bwriadol wag. E.e. ar gyfer dau fwlch: yn mynd, mynd, yn mynd::pob, rhai, y rhan fwyaf.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Teilsen y gellir eu llusgo wedi&apos;u gwahanu â choma — cynhwyswch yr atebion cywir, ynghyd â dewisiadau twyllodrus dewisol y gall y dysgwr gael ei dwyllo ganddynt. Defnyddiwch \, ar gyfer coma llythrennol, ac ___ ar gyfer teilsen wag (ar gyfer bwlch y dylai aros yn wag yn gywir). Llenwch y bylchau isod cyn gynted ag y bydd y rhain wedi&apos;u gosod.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>e.e. yn mynd, mynd, yn mynd::pob, rhai, y rhan fwyaf</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>e.e. yn mynd, mynd, yn mynd, wedi mynd</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Ateb cywir ar gyfer pob bwlch</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Cyffyrddwch â&apos;r dewis cywir ym mhob blwch isod.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Dewiswch ateb cywir ar gyfer pob bwlch.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Bwlch %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Llenwch y bylchau</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Llusgwch deilsen i fwlch isod, neu cyffyrddwch â theilsen ac yna bwlch i&apos;w gosod.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Llenwch bob bwlch â theilsen.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Dewisiadau wedi&apos;u gwahanu â choma — cyffyrddwch â&apos;r ateb cywir isod. Defnyddiwch \, ar gyfer coma llythrennol.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Dewisiadau wedi&apos;u gwahanu â choma — cyffyrddwch â&apos;r holl atebion cywir isod. Defnyddiwch \, ar gyfer coma llythrennol.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>e.e. yn mynd, mynd, yn mynd, wedi mynd</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Un ateb cywir yn unig</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Ateb cywir</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Ateb(ion) cywir</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Dewiswch yr ateb cywir.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Dewiswch o leiaf un ateb cywir.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Ychwanegu cwestiwn</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Tynnu</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Cadw</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>Mae angen teitl</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Esbonio gramadeg</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Methu llwytho cwestiwn %1: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Dim ond %1 o %2 cwestiwn a ofynnwyd a gynhyrchwyd — ceisiwch bwnc ehangach, neu leihau&apos;r niferoedd uchod.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Iaith yr esboniad</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Iaith yr esboniad</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Iaith y pwnc</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Iaith y pwnc</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Nid oes modd cynhyrchu&apos;r pwnc hwn. Dim ond cynnwys sy&apos;n addas i bob oed y mae&apos;r AI yn ei greu — nid yw pynciau rhywiol, anweddus na sarhaus yn cael eu cefnogi. Rhowch gynnig ar bwnc gwahanol.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Rydych wedi defnyddio eich holl gynhyrchiadau AI ar gyfer y mis hwn. Rhowch gynnig arall arni fis nesaf.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Gormod o adroddiadau heddiw — rhowch gynnig arall arni yfory.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>Mae&apos;r gwasanaeth AI yn brysur ar hyn o bryd — rhowch gynnig arall arni mewn munud.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Rhowch thema yn gyntaf.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>Mae&apos;r thema&apos;n rhy hir (uchafswm %1 nod).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Gosodwch o leiaf un math o gwestiwn uwchlaw sero.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>Mae eich sesiwn wedi dod i ben — mewngofnodwch eto.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Methu cyrraedd y gweinydd. Gwiriwch eich cysylltiad rhyngrwyd a rhowch gynnig arall arni.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Aeth rhywbeth o&apos;i le. Rhowch gynnig arall arni.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Heb fewngofnodi.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Tapiwch i droi drosodd</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Tapiwch i droi&apos;n ôl</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>GWN</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>SGIPIO</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Ni wn</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Gwn</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Heb ddewis</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Methwyd llwytho testun y drwydded.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Mewngofnodwch i barhau</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Yn agor y porwr…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Mewngofnodi gyda Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Mae llyfrgell neu set gyda&apos;r enw hwn eisoes yn bodoli yma.</translation>
    </message>
    <message>
        <location line="+309"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Mae set eiriau gyda&apos;r enw hwn eisoes yn bodoli yma.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Mae set reolau gyda&apos;r enw hwn eisoes yn bodoli yma.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+37"/>
        <source>Results</source>
        <translation>Canlyniadau</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Well</source>
        <translation>Gwaith</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>done</source>
        <translation>ardderchog</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>allan o %1</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Gwaith gwych! Daliwch ati!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Ymdrech dda! Parhewch i ymarfer.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Peidiwch â rhoi&apos;r gorau iddi – mae ymarfer yn gwneud yn berffaith!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Y sesiwn hon</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Ni wn</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Gwn</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Practice Again</source>
        <translation>Ymarfer Eto</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Ailosod cynnydd y prawf?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Bydd hyn yn clirio&apos;ch cynnydd ar y set reolau hon ac yn dechrau sesiwn newydd.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 cwestiwn</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Wedi&apos;i gwblhau: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">Ar y gweill: %1 / %2</translation>
    </message>
    <message>
        <location line="+67"/>
        <source>← Reset</source>
        <translation>← Ailosod</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Esboniad Rheol</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Ni ychwanegwyd unrhyw esboniad ar gyfer y set hon.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Clip Sain</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Trylwyredd sillafu</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Llym</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Arferol</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Hyblyg</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Dechrau&apos;r Prawf</translation>
    </message>
    <message>
        <location line="-198"/>
        <source>Test is completed</source>
        <translation>Mae&apos;r prawf wedi&apos;i gwblhau</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Cwestiwn nesaf: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Cywir: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Rheol</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Esboniad Rheol</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Clip Sain</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Diddymu</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Gweld y rheol</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Trowch yr olwyn i ddewis gair pob bwlch.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Bwlch %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Llusgwch deilsen i fwlch, neu cyffyrddwch â theilsen ac yna bwlch i&apos;w gosod.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Dewiswch yr ateb cywir.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Dewiswch bopeth sy&apos;n gymwys.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Cywir: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Cyflwyno</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Cywir: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Gweld Canlyniadau</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Nesaf →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Rhif cwestiwn %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Trosysgrifo&apos;r set eiriau?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Cyfuno llyfrgelloedd?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Mae set eiriau o&apos;r enw «%1» eisoes yn bodoli yma. Ei throsysgrifo â&apos;r set a symudwyd?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Mae llyfrgell o&apos;r enw «%1» eisoes yn bodoli yma. Cyfuno ei chynnwys â hon?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Mae set eiriau o&apos;r enw «%1» eisoes yn bodoli yn %2. Ei throsysgrifo â&apos;r fersiwn wedi&apos;i chyfuno?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>y llyfrgell gyrchfan</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Allforio fel .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Llyfrgell Newydd</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Library name:</source>
        <translation>Enw&apos;r llyfrgell:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>e.e. Teithio, Gwaith, Ysgol…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Mae llyfrgell neu set gyda&apos;r enw hwn eisoes yn bodoli yma.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+74"/>
        <source>A library with this name already exists here.</source>
        <translation>Mae llyfrgell gyda&apos;r enw hwn eisoes yn bodoli yma.</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Create</source>
        <translation>Creu</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Rename Library</source>
        <translation>Ailenwi&apos;r Llyfrgell</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Enw newydd:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Ailenwi</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Eich setiau geiriau</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Llyfrgell</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Symud allan o</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Gollwng i symud i mewn</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>gair</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>cwestiwn</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Dileu&apos;r Llyfrgell</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Golygu</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Dileu</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Rhannu ffeil .ppset</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Allforio .ppset (cadw i ddisg)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Does dim byd yma eto.
Tapiwch + Creu i ychwanegu set eiriau neu lyfrgell.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Set Eiriau</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Set Reolau</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Creu</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Iaith y Rhyngwyneb</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Cancel</source>
        <translation>Canslo</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Dewiswch Fath y Prawf</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Cardiau Fflach</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Trowch drosodd i ddatgelu — llusgwch i&apos;r dde os ydych yn ei wybod</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Ysgrifennwch y Gair</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Gweler yr awgrym — teipiwch yr ymadrodd</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Ysgrifennwch yr Awgrym</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Gweler y gair — teipiwch ei gyfieithiad</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Dewiswch y Gair</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Gweler yr awgrym — dewiswch o 4 opsiwn</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Dewiswch yr Awgrym</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Gweler y gair — dewiswch o 4 opsiwn</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Dysgu Cynyddol</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Aml-ddewis i ddysgu, yna ysgrifennu i feistroli&apos;r holl eiriau</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Dysgu Cynyddol Gwrthdro</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Aml-ddewis i ddysgu, yna ysgrifennu i feistroli&apos;r holl awgrymiadau</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>✓ Done</source>
        <translation>✓ Wedi Gorffen</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>← Reset</source>
        <translation>← Ailosod</translation>
    </message>
    <message>
        <location line="+96"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Trylwyredd sillafu</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Llym</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Arferol</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Hyblyg</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Canslo</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Adolygu Ymadroddion</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Stopio</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Gwrando</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Dechrau&apos;r Prawf</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Dim geiriau eto</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Teipiwch yr awgrym / cyfieithiad…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Teipiwch yr ymadrodd…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Cywir: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Marcio fel cywir (fe wnes i deipio o&apos;i le)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Cyflwyno</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Marcio fel cywir (fe wnes i glicio o&apos;i le)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Cywir: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Gweld Canlyniadau</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Nesaf →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Rhif cwestiwn %1</translation>
    </message>
</context>
</TS>
