<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="gl">
<context>
    <name>AboutOpenSourcePage</name>
    <message>
        <location filename="../AboutOpenSourcePage.qml" line="+7"/>
        <location line="+17"/>
        <source>About</source>
        <translation>Sobre</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</source>
        <translation>&lt;b&gt;Passepartout&lt;/b&gt;&lt;font color=&apos;#1e88e5&apos;&gt; v%1&lt;/font&gt;</translation>
    </message>
    <message>
        <source>Vocabulary trainer for memorizing word sets.</source>
        <translation type="vanished">Adestrador de vocabulario para memorizar conxuntos de palabras.</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Trainer for vocabulary and grammar.</source>
        <translation>Adestrador de vocabulario e gramática.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Open Source Licenses</source>
        <translation>Licenzas de código aberto</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>This application uses Qt under the GNU Lesser General Public License version 3.</source>
        <translation>Esta aplicación usa Qt baixo a GNU Lesser General Public License versión 3.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt notice</source>
        <translation>Aviso de Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt Notice</source>
        <translation>Aviso de Qt</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU LGPL v3</source>
        <translation>GNU LGPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <location line="+4"/>
        <source>GNU GPL v3</source>
        <translation>GNU GPL v3</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Qt source code</source>
        <translation>Código fonte de Qt</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Qt project website</source>
        <translation>Sitio web do proxecto Qt</translation>
    </message>
</context>
<context>
    <name>AiContentNotice</name>
    <message>
        <location filename="../AiContentNotice.qml" line="+33"/>
        <source>✨ Generated by AI — may contain mistakes</source>
        <translation>✨ Xerado por IA — pode conter erros</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>🚩 Report</source>
        <translation>🚩 Denunciar</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Thank you — your report was sent and will be reviewed.</source>
        <translation>Grazas — a túa denuncia enviouse e será revisada.</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>🚩 Report AI content</source>
        <translation>🚩 Denunciar contido de IA</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>What&apos;s wrong with this generated content?</source>
        <translation>Que problema ten este contido xerado?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Sexual or suggestive content</source>
        <translation>Contido sexual ou insinuante</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Profanity or offensive language</source>
        <translation>Palabrotas ou linguaxe ofensiva</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Hateful or harassing content</source>
        <translation>Contido de odio ou acoso</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Violent or dangerous content</source>
        <translation>Contido violento ou perigoso</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Wrong or misleading information</source>
        <translation>Información incorrecta ou enganosa</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Something else</source>
        <translation>Outra cousa</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Details (optional)</source>
        <translation>Detalles (opcional)</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Sending…</source>
        <translation>Enviando…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Close</source>
        <translation>Pechar</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Cancel</source>
        <translation>Cancelar</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Send report</source>
        <translation>Enviar denuncia</translation>
    </message>
</context>
<context>
    <name>CameraCapture</name>
    <message>
        <location filename="../CameraCapture.qml" line="+55"/>
        <source>Take Photo</source>
        <translation>Facer foto</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Cancel</source>
        <translation>Cancelar</translation>
    </message>
</context>
<context>
    <name>CreatingRecSet</name>
    <message>
        <location filename="../CreatingRecSet.qml" line="+58"/>
        <source>soon</source>
        <translation>en breve</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>en %1d %2h</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>en %1h %2min</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>en %1min</translation>
    </message>
    <message>
        <location line="+130"/>
        <source>Select Image</source>
        <translation>Seleccionar imaxe</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select Audio</source>
        <translation>Seleccionar audio</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import Word Set</source>
        <translation>Importar conxunto de palabras</translation>
    </message>
    <message>
        <location line="+69"/>
        <source>Word Language</source>
        <translation>Idioma da palabra</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Hint Language</source>
        <translation>Idioma da pista</translation>
    </message>
    <message>
        <location line="+124"/>
        <location line="+326"/>
        <location line="+835"/>
        <source>Cancel</source>
        <translation>Cancelar</translation>
    </message>
    <message>
        <location line="-1081"/>
        <source>✨ AI Word Set Generator</source>
        <translation>✨ Xerador de conxuntos de palabras con IA</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Con tecnoloxía de Gemini</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>🎯 Theme</source>
        <translation>🎯 Tema</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the set you want — e.g. &quot;kitchen items you&apos;d find in a French household&quot; or &quot;business travel phrases for a conference&quot;…</source>
        <translation>Describe o conxunto que queres — p. ex. «utensilios de cociña que atoparías nun fogar francés» ou «frases de viaxe de negocios para unha conferencia»…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="-54"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Quedan %1 de %2 xeracións este mes — reiníciase %3</translation>
    </message>
    <message>
        <location line="+11"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>A IA pode equivocarse. Só se xera contido axeitado para todas as idades — usa 🚩 Denunciar para sinalar calquera cousa inapropiada.</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Word language</source>
        <translation>Idioma da palabra</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>Hint language</source>
        <translation>Idioma da pista</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>🔢 Number of words</source>
        <translation>🔢 Número de palabras</translation>
    </message>
    <message>
        <location line="+74"/>
        <source>Asking Gemini…</source>
        <translation>Preguntando a Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Cancelar solicitude</translation>
    </message>
    <message>
        <location line="+33"/>
        <source>✨ Generate</source>
        <translation>✨ Xerar</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>✨ AI</source>
        <translation>✨ IA</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Word Set</source>
        <translation>Novo conxunto de palabras</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Word Set</source>
        <translation>Editar conxunto de palabras</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importar</translation>
    </message>
    <message>
        <location line="+29"/>
        <source>Set title…</source>
        <translation>Título do conxunto…</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Auto-fetch images</source>
        <translation>Obter imaxes automaticamente</translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Word</source>
        <translation>Palabra</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>selected</source>
        <translation>seleccionado</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Word / Term</source>
        <translation>Palabra / Termo</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+60"/>
        <source>Not selected</source>
        <translation>Non seleccionado</translation>
    </message>
    <message>
        <location line="-38"/>
        <source>Enter word...</source>
        <translation>Introduce a palabra...</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Hint / meaning</source>
        <translation>Pista / significado</translation>
    </message>
    <message>
        <location line="+39"/>
        <source>Hint, definition...</source>
        <translation>Pista, definición...</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Example usage</source>
        <translation>Exemplo de uso</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Example sentence using the word...</source>
        <translation>Frase de exemplo coa palabra...</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Change image</source>
        <translation>Cambiar imaxe</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Add image</source>
        <translation>Engadir imaxe</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Fetch</source>
        <translation>Obter</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Camera</source>
        <translation>Cámara</translation>
    </message>
    <message>
        <location line="+73"/>
        <source>Add audio</source>
        <translation>Engadir audio</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>■ Stop</source>
        <translation>■ Deter</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ Play</source>
        <translation>▶ Reproducir</translation>
    </message>
    <message>
        <location line="+47"/>
        <source>■</source>
        <translation>■</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶ TTS</source>
        <translation>▶ TTS</translation>
    </message>
    <message>
        <location line="+41"/>
        <source>⬛ Stop</source>
        <translation>⬛ Deter</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>● Rec</source>
        <translation>● Grav.</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>+ Add word</source>
        <translation>+ Engadir palabra</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Remove</source>
        <translation>Eliminar</translation>
    </message>
    <message>
        <location line="+46"/>
        <source>Save</source>
        <translation>Gardar</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>O título é obrigatorio</translation>
    </message>
</context>
<context>
    <name>CreatingRuleSet</name>
    <message>
        <location filename="../CreatingRuleSet.qml" line="+418"/>
        <source>soon</source>
        <translation>en breve</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>in %1d %2h</source>
        <translation>en %1d %2h</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>in %1h %2m</source>
        <translation>en %1h %2m</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>in %1m</source>
        <translation>en %1m</translation>
    </message>
    <message>
        <location line="+43"/>
        <source>Select Image</source>
        <translation>Seleccionar imaxe</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Select Audio</source>
        <translation>Seleccionar audio</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>✨ AI</source>
        <translation>✨ IA</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>New Rule Set</source>
        <translation>Novo conxunto de regras</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Edit Rule Set</source>
        <translation>Editar conxunto de regras</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Import</source>
        <translation>Importar</translation>
    </message>
    <message>
        <location line="+20"/>
        <source>Import Rule Set</source>
        <translation>Importar conxunto de regras</translation>
    </message>
    <message>
        <location line="+365"/>
        <source>✨ AI Rule Set Generator</source>
        <translation>✨ Xerador de conxuntos de regras con IA</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>Powered by Gemini</source>
        <translation>Impulsado por Gemini</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>%1 of %2 generations left this month — resets %3</source>
        <translation>Quedan %1 de %2 xeracións este mes — reiníciase %3</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>🎯 Rule/topic to explain</source>
        <translation>🎯 Regra/tema a explicar</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>Describe the rule you want — e.g. &quot;present simple vs present continuous&quot; or &quot;third conditional sentences&quot;…</source>
        <translation>Describe a regra que queres — p. ex. &quot;presente simple vs presente continuo&quot; ou &quot;oracións condicionais de terceiro tipo&quot;…</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>%1/%2</source>
        <translation>%1/%2</translation>
    </message>
    <message>
        <location line="+89"/>
        <source>🔢 Questions per type</source>
        <translation>🔢 Preguntas por tipo</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>📝 Fill in the Gap</source>
        <translation>📝 Encher o oco</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔘 Multiple Choice</source>
        <translation>🔘 Opción múltiple</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🔽 Dropdown Choice</source>
        <translation>🔽 Selección despregábel</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>🫳 Drag &amp; Drop</source>
        <translation>🫳 Arrastrar e soltar</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Asking Gemini…</source>
        <translation>Preguntando a Gemini…</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Cancel request</source>
        <translation>Cancelar solicitude</translation>
    </message>
    <message>
        <location line="-358"/>
        <location line="+358"/>
        <location line="+1115"/>
        <source>Cancel</source>
        <translation>Cancelar</translation>
    </message>
    <message>
        <location line="-1307"/>
        <source>AI can make mistakes. Only content suitable for all ages is generated — use 🚩 Report to flag anything inappropriate.</source>
        <translation>A IA pode equivocarse. Só se xera contido axeitado para todas as idades — usa 🚩 Denunciar para sinalar calquera cousa inapropiada.</translation>
    </message>
    <message>
        <location line="+227"/>
        <source>✨ Generate</source>
        <translation>✨ Xerar</translation>
    </message>
    <message>
        <location line="+56"/>
        <source>Set title…</source>
        <translation>Introduce o título…</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Theory Explanation</source>
        <translation>Explicación da teoría</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Hidden during testing until the learner makes a mistake — always readable in preview.</source>
        <translation>Agochado durante a proba ata que o alumno cometa un erro — sempre lexible na vista previa.</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Use ▲▼ to reorder a block. Drag a photo&apos;s // corner to resize it.</source>
        <translation>Usa ▲▼ para reordenar un bloque. Arrastra a esquina // dunha foto para redimensionala.</translation>
    </message>
    <message>
        <location line="+66"/>
        <source>Explain the rule this set practices…</source>
        <translation>Explica a regra que practica este conxunto…</translation>
    </message>
    <message>
        <location line="+93"/>
        <source>Audio clip</source>
        <translation>Fragmento de audio</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>+ Text</source>
        <translation>+ Texto</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Photo</source>
        <translation>+ Foto</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>+ Audio</source>
        <translation>+ Audio</translation>
    </message>
    <message>
        <location line="+56"/>
        <location line="+59"/>
        <source>Question</source>
        <translation>Pregunta</translation>
    </message>
    <message>
        <location line="-52"/>
        <source>selected</source>
        <translation>seleccionado</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Fill in the Gap</source>
        <translation>Encher o oco</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Multiple Choice</source>
        <translation>Opción múltiple</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Dropdown Choice</source>
        <translation>Selección despregábel</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Drag &amp; Drop</source>
        <translation>Arrastrar e soltar</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Use ___ (three underscores) for each blank the learner fills in.</source>
        <translation>Usa ___ (tres guións baixos) para cada oco que o alumno complete.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. What does she do every day?</source>
        <translation>p. ex. Que fai cada día?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. She ___ to school every day.</source>
        <translation>p. ex. Ela vai ___ á escola cada día.</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Answers</source>
        <translation>Respostas</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>One answer per blank, separated by commas, in order. Use , for a literal comma.</source>
        <translation>Unha resposta por oco, separadas por comas, en orde. Usa \, para unha coma literal.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. goes</source>
        <translation>p. ex. vai</translation>
    </message>
    <message>
        <location line="+8"/>
        <location line="+370"/>
        <source>Options</source>
        <translation>Opcións</translation>
    </message>
    <message>
        <location line="-364"/>
        <source>Separate choices for one blank with commas; separate blanks with double colons (::). A single : is safe as-is; use , for a literal comma, :: for a literal ::, and ___ for a deliberately blank choice. E.g. for two blanks: goes, go, going::every, some, most.</source>
        <translation>Separa as opcións dun oco con comas; separa os ocos con dous puntos dobres (::). Un só : é seguro tal cal; usa \, para unha coma literal, \:: para un :: literal, e ___ para unha opción deliberadamente baleira. P. ex. para dous ocos: vai, ir, indo::cada, algúns, a maioría.</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Comma-separated draggable tiles — include the correct answers, plus optional decoys the learner can be tricked by. Use , for a literal comma, and ___ for a blank tile (for a blank that should correctly stay empty). Fill in the blanks below once these are set.</source>
        <translation>Pezas arrastrábeis separadas por comas — inclúe as respostas correctas, ademais de sinais falsos opcionais cos que se pode confundir o alumno. Usa \, para unha coma literal, e ___ para unha peza baleira (para un oco que correctamente debe quedar baleiro). Enche os ocos de abaixo unha vez establecidos estes.</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>e.g. goes, go, going::every, some, most</source>
        <translation>p. ex. vai, ir, indo::cada, algúns, a maioría</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>e.g. goes, go, going, went</source>
        <translation>p. ex. vai, ir, indo, ido</translation>
    </message>
    <message>
        <location line="+14"/>
        <source>Correct answer for each blank</source>
        <translation>Resposta correcta para cada oco</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Tap the correct choice in each box below.</source>
        <translation>Toca a opción correcta en cada caixa de abaixo.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select a correct answer for every blank.</source>
        <translation>Selecciona unha resposta correcta para cada oco.</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Blank %1</source>
        <translation>Oco %1</translation>
    </message>
    <message>
        <location line="+53"/>
        <source>Fill in the blanks</source>
        <translation>Enche os ocos</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Drag a tile onto a blank below, or tap a tile then tap a blank to place it.</source>
        <translation>Arrastra unha peza a un oco de abaixo, ou toca unha peza e despois un oco para colocala.</translation>
    </message>
    <message>
        <location line="+37"/>
        <source>Fill every blank with a tile.</source>
        <translation>Enche cada oco cunha peza.</translation>
    </message>
    <message>
        <location line="+190"/>
        <source>Comma-separated choices — tap the correct answer below. Use , for a literal comma.</source>
        <translation>Opcións separadas por comas — toca a resposta correcta de abaixo. Usa \, para unha coma literal.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Comma-separated choices — tap all correct answers below. Use , for a literal comma.</source>
        <translation>Opcións separadas por comas — toca todas as respostas correctas de abaixo. Usa \, para unha coma literal.</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>e.g. go, goes, going, went</source>
        <translation>p. ex. vai, ir, indo, ido</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Only one correct answer</source>
        <translation>Só unha resposta correcta</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Correct answer</source>
        <translation>Resposta correcta</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Correct answer(s)</source>
        <translation>Resposta(s) correcta(s)</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Select the correct answer.</source>
        <translation>Selecciona a resposta correcta.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select at least one correct answer.</source>
        <translation>Selecciona polo menos unha resposta correcta.</translation>
    </message>
    <message>
        <location line="+77"/>
        <source>+ Add question</source>
        <translation>+ Engadir pregunta</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Remove</source>
        <translation>Eliminar</translation>
    </message>
    <message>
        <location line="+25"/>
        <source>Save</source>
        <translation>Gardar</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Title is required</source>
        <translation>O título é obrigatorio</translation>
    </message>
    <message>
        <location line="-1167"/>
        <source>💡 Explain grammar</source>
        <translation>💡 Explicar a gramática</translation>
    </message>
    <message>
        <location line="-962"/>
        <source>Could not load a %1 question: %2</source>
        <translation>Non se puido cargar a pregunta %1: %2</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Generated only %1 of %2 requested questions — try a broader topic, or lower the counts above.</source>
        <translation>Só se xeraron %1 de %2 preguntas solicitadas — proba un tema máis amplo ou reduce os números de arriba.</translation>
    </message>
    <message>
        <location line="+557"/>
        <source>Explanation Language</source>
        <translation>Idioma da explicación</translation>
    </message>
    <message>
        <location line="+355"/>
        <source>Explanation language</source>
        <translation>Idioma da explicación</translation>
    </message>
    <message>
        <location line="-355"/>
        <source>Topic Language</source>
        <translation>Idioma do tema</translation>
    </message>
    <message>
        <location line="+321"/>
        <source>Topic language</source>
        <translation>Idioma do tema</translation>
    </message>
</context>
<context>
    <name>FirebaseAiHelper</name>
    <message>
        <location filename="../src/firebaseAiHelper.cpp" line="+153"/>
        <source>This topic can&apos;t be generated. The AI only creates content suitable for all ages — sexual, profane or offensive topics aren&apos;t supported. Please try a different topic.</source>
        <translation>Este tema non se pode xerar. A IA só crea contido axeitado para todas as idades — non se admiten temas sexuais, groseiros ou ofensivos. Proba cun tema diferente.</translation>
    </message>
    <message>
        <location line="+3"/>
        <location line="+14"/>
        <source>You&apos;ve used all your AI generations for this month. Try again next month.</source>
        <translation>Usaches todas as xeracións con IA deste mes. Téntao de novo o mes que vén.</translation>
    </message>
    <message>
        <location line="-12"/>
        <source>Too many reports today — please try again tomorrow.</source>
        <translation>Demasiadas denuncias hoxe — téntao de novo mañá.</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>The AI service is busy right now — please try again in a moment.</source>
        <translation>O servizo de IA está ocupado neste momento — téntao de novo nun intre.</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+87"/>
        <location line="+128"/>
        <source>Enter a theme first.</source>
        <translation>Primeiro introduce un tema.</translation>
    </message>
    <message>
        <location line="-213"/>
        <source>The theme is too long (max %1 characters).</source>
        <translation>O tema é demasiado longo (máx. %1 caracteres).</translation>
    </message>
    <message>
        <location line="+2"/>
        <location line="+215"/>
        <source>Set at least one question type above zero.</source>
        <translation>Pon polo menos un tipo de pregunta por riba de cero.</translation>
    </message>
    <message>
        <location line="-213"/>
        <location line="+45"/>
        <source>Your session expired — please sign in again.</source>
        <translation>A túa sesión caducou — volve iniciar sesión.</translation>
    </message>
    <message>
        <location line="-39"/>
        <source>Couldn&apos;t reach the server. Check your internet connection and try again.</source>
        <translation>Non se puido conectar co servidor. Comproba a túa conexión a internet e téntao de novo.</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+44"/>
        <location line="+94"/>
        <location line="+142"/>
        <source>Something went wrong. Please try again.</source>
        <translation>Algo saíu mal. Téntao de novo.</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Not signed in.</source>
        <translation>Non iniciaches sesión.</translation>
    </message>
</context>
<context>
    <name>FlashCard</name>
    <message>
        <location filename="../FlashCard.qml" line="+222"/>
        <source>Tap to flip</source>
        <translation>Toca para virar</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Tap to flip back</source>
        <translation>Toca para virar de novo</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>KNOW</source>
        <translation>SÁIO</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>SKIP</source>
        <translation>SALTAR</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>x  Don&apos;t know</source>
        <translation>x  Non o sei</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>✓  Know</source>
        <translation>✓  Sáio</translation>
    </message>
</context>
<context>
    <name>LanguageHelper</name>
    <message>
        <location filename="../src/languageHelper.cpp" line="+34"/>
        <source>Not selected</source>
        <translation>Non seleccionado</translation>
    </message>
</context>
<context>
    <name>LicenseTextPage</name>
    <message>
        <location filename="../LicenseTextPage.qml" line="+37"/>
        <source>Could not load license text.</source>
        <translation>Non se puido cargar o texto da licenza.</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="../Main.qml" line="+306"/>
        <source>Passepartout</source>
        <translation>Passepartout</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Sign in to continue</source>
        <translation>Inicia sesión para continuar</translation>
    </message>
    <message>
        <location line="+35"/>
        <source>Opening browser…</source>
        <translation>Abrindo o navegador…</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Sign in with Google</source>
        <translation>Iniciar sesión con Google</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Xa existe aquí unha biblioteca ou conxunto con este nome.</translation>
    </message>
    <message>
        <location line="+309"/>
        <location line="+7"/>
        <source>A word set with this name already exists here.</source>
        <translation>Xa existe aquí un conxunto de palabras con este nome.</translation>
    </message>
    <message>
        <location line="+64"/>
        <location line="+7"/>
        <source>A rule set with this name already exists here.</source>
        <translation>Xa existe aquí un conxunto de regras con este nome.</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../Results.qml" line="+37"/>
        <source>Results</source>
        <translation>Resultados</translation>
    </message>
    <message>
        <location line="+30"/>
        <source>Well</source>
        <translation>Ben</translation>
    </message>
    <message>
        <location line="+7"/>
        <source>done</source>
        <translation>feito</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>out of %1</source>
        <translation>de %1</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+2"/>
        <source>Excellent work! Keep it up!</source>
        <translation>Excelente traballo! Continúa así!</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Good effort! Keep practising.</source>
        <translation>Bo esforzo! Segue practicando.</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Don&apos;t give up – practice makes perfect!</source>
        <translation>Non desistas – a práctica fai o mestre!</translation>
    </message>
    <message>
        <location line="+22"/>
        <source>This session</source>
        <translation>Esta sesión</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Don&apos;t know</source>
        <translation>Non o sei</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Know</source>
        <translation>Sáio</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Practice Again</source>
        <translation>Practicar de novo</translation>
    </message>
</context>
<context>
    <name>RuleSetPreview</name>
    <message>
        <location filename="../RuleSetPreview.qml" line="+65"/>
        <source>Reset Test Progress?</source>
        <translation>Restablecer o progreso da proba?</translation>
    </message>
    <message>
        <location line="+5"/>
        <source>This clears your progress on this rule set and starts a fresh session.</source>
        <translation>Isto borrará o teu progreso neste conxunto de regras e comezará unha nova sesión.</translation>
    </message>
    <message>
        <source>%1 questions</source>
        <translation type="vanished">%1 preguntas</translation>
    </message>
    <message>
        <source>Completed: %1 / %2</source>
        <translation type="vanished">Completado: %1 / %2</translation>
    </message>
    <message>
        <source>In progress: %1 / %2</source>
        <translation type="vanished">En curso: %1 / %2</translation>
    </message>
    <message>
        <location line="+67"/>
        <source>← Reset</source>
        <translation>← Restablecer</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>Rule Explanation</source>
        <translation>Explicación da regra</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>No explanation was added for this set.</source>
        <translation>Non se engadiu ningunha explicación para este conxunto.</translation>
    </message>
    <message>
        <location line="+65"/>
        <source>Audio clip</source>
        <translation>Fragmento de audio</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Rigor ortográfico</translation>
    </message>
    <message>
        <location line="+9"/>
        <source>Strict</source>
        <translation>Estrito</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Flexíbel</translation>
    </message>
    <message>
        <location line="+38"/>
        <source>Start Test</source>
        <translation>Iniciar proba</translation>
    </message>
    <message>
        <location line="-198"/>
        <source>Test is completed</source>
        <translation>A proba está completada</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next question: #%1</source>
        <translation>Seguinte pregunta: #%1</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Correct: %1 / %2</source>
        <translation>Correcto: %1 / %2</translation>
    </message>
</context>
<context>
    <name>RuleTest</name>
    <message>
        <location filename="../RuleTest.qml" line="+292"/>
        <source>Rule</source>
        <translation>Regra</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>💡 Rule Explanation</source>
        <translation>💡 Explicación da regra</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Audio clip</source>
        <translation>Fragmento de audio</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Cancel</source>
        <translation>Cancelar</translation>
    </message>
    <message>
        <location line="+36"/>
        <source>💡 View rule</source>
        <translation>💡 Ver a regra</translation>
    </message>
    <message>
        <location line="+171"/>
        <source>Spin the wheel to choose each blank&apos;s word.</source>
        <translation>Xira a roda para escoller a palabra de cada oco.</translation>
    </message>
    <message>
        <location line="+59"/>
        <source>Blank %1</source>
        <translation>Oco %1</translation>
    </message>
    <message>
        <location line="-676"/>
        <location line="+693"/>
        <location line="+75"/>
        <source>null</source>
        <translation>null</translation>
    </message>
    <message>
        <location line="+216"/>
        <source>Drag a tile onto a blank, or tap a tile then tap a blank to place it.</source>
        <translation>Arrastra unha peza a un oco, ou toca unha peza e despois un oco para colocala.</translation>
    </message>
    <message>
        <location line="+114"/>
        <source>Select the correct answer.</source>
        <translation>Selecciona a resposta correcta.</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Select all that apply.</source>
        <translation>Selecciona todas as que correspondan.</translation>
    </message>
    <message>
        <location line="+91"/>
        <location line="+6"/>
        <source>Correct: </source>
        <translation>Correcto: </translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Submit</source>
        <translation>Enviar</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>Correct: %1 / %2</source>
        <translation>Correcto: %1 / %2</translation>
    </message>
    <message>
        <location line="+42"/>
        <source>See Results</source>
        <translation>Ver resultados</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Next →</source>
        <translation>Seguinte →</translation>
    </message>
    <message>
        <location line="-831"/>
        <source>Question number %1</source>
        <translation>Pregunta número %1</translation>
    </message>
</context>
<context>
    <name>SetDirMenu</name>
    <message>
        <location filename="../SetDirMenu.qml" line="+115"/>
        <location line="+67"/>
        <source>Overwrite word set?</source>
        <translation>Sobrescribir o conxunto de palabras?</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Merge libraries?</source>
        <translation>Combinar bibliotecas?</translation>
    </message>
    <message>
        <location line="+8"/>
        <source>A word set named &quot;%1&quot; already exists here. Overwrite it with the moved set?</source>
        <translation>Xa existe aquí un conxunto de palabras chamado «%1». Sobrescribilo co conxunto movido?</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>A library named &quot;%1&quot; already exists here. Merge its contents into it?</source>
        <translation>Xa existe aquí unha biblioteca chamada «%1». Combinar o seu contido con ela?</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>A word set named &quot;%1&quot; already exists in %2. Overwrite it with the version being merged in?</source>
        <translation>Xa existe un conxunto de palabras chamado «%1» en %2. Sobrescribilo coa versión combinada?</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>the destination library</source>
        <translation>a biblioteca de destino</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Export as .ppset</source>
        <translation>Exportar como .ppset</translation>
    </message>
    <message>
        <location line="+13"/>
        <source>New Library</source>
        <translation>Nova biblioteca</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Library name:</source>
        <translation>Nome da biblioteca:</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>e.g. Travel, Work, School…</source>
        <translation>p. ex. Viaxes, Traballo, Escola…</translation>
    </message>
    <message>
        <source>A library or set with this name already exists here.</source>
        <translation type="vanished">Xa existe aquí unha biblioteca ou conxunto con este nome.</translation>
    </message>
    <message>
        <location line="+12"/>
        <location line="+74"/>
        <source>A library with this name already exists here.</source>
        <translation>Xa existe aquí unha biblioteca con este nome.</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Create</source>
        <translation>Crear</translation>
    </message>
    <message>
        <location line="+28"/>
        <source>Rename Library</source>
        <translation>Renomear biblioteca</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>New name:</source>
        <translation>Novo nome:</translation>
    </message>
    <message>
        <location line="+22"/>
        <location line="+321"/>
        <source>Rename</source>
        <translation>Renomear</translation>
    </message>
    <message>
        <location line="-273"/>
        <source>Your word sets</source>
        <translation>Os teus conxuntos de palabras</translation>
    </message>
    <message>
        <location line="+0"/>
        <location line="+495"/>
        <source>Library</source>
        <translation>Biblioteca</translation>
    </message>
    <message>
        <location line="-406"/>
        <source>Move out of</source>
        <translation>Sacar de</translation>
    </message>
    <message>
        <location line="+132"/>
        <source>Drop to move inside</source>
        <translation>Soltar para mover dentro</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>words</source>
        <translation>palabras</translation>
    </message>
    <message>
        <location line="+6"/>
        <source>questions</source>
        <translation>preguntas</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Delete Library</source>
        <translation>Eliminar biblioteca</translation>
    </message>
    <message>
        <location line="+13"/>
        <location line="+41"/>
        <source>Edit</source>
        <translation>Editar</translation>
    </message>
    <message>
        <location line="-35"/>
        <location line="+41"/>
        <source>Delete</source>
        <translation>Eliminar</translation>
    </message>
    <message>
        <location line="-29"/>
        <location line="+41"/>
        <source>Share .ppset file</source>
        <translation>Compartir ficheiro .ppset</translation>
    </message>
    <message>
        <location line="-30"/>
        <location line="+41"/>
        <source>Export .ppset (save to disk)</source>
        <translation>Exportar .ppset (gardar no disco)</translation>
    </message>
    <message>
        <location line="+95"/>
        <source>Nothing here yet.
Tap + Create to add a word set or library.</source>
        <translation>Aínda nada aquí.
Toca + Crear para engadir un conxunto de palabras ou biblioteca.</translation>
    </message>
    <message>
        <location line="+26"/>
        <source>Word Set</source>
        <translation>Conxunto de palabras</translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Rule Set</source>
        <translation>Conxunto de regras</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>+ Create</source>
        <translation>+ Crear</translation>
    </message>
    <message>
        <location line="+60"/>
        <source>Interface Language</source>
        <translation>Idioma da interface</translation>
    </message>
    <message>
        <location line="+86"/>
        <source>Cancel</source>
        <translation>Cancelar</translation>
    </message>
</context>
<context>
    <name>SetPreviewMenu</name>
    <message>
        <location filename="../SetPreviewMenu.qml" line="+76"/>
        <source>Choose Test Type</source>
        <translation>Escoller tipo de proba</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>Flash Cards</source>
        <translation>Tarxetas didácticas</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Flip to reveal — swipe right if you know it</source>
        <translation>Voltea para revelar — desliza á dereita se a sabes</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Word</source>
        <translation>Escribe a palabra</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — type the expression</source>
        <translation>Ve a pista — escribe a expresión</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Write the Hint</source>
        <translation>Escribe a pista</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — type its translation</source>
        <translation>Ve a palabra — escribe a súa tradución</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Word</source>
        <translation>Escolle a palabra</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the hint — choose from 4 options</source>
        <translation>Ve a pista — escolle entre 4 opcións</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Pick the Hint</source>
        <translation>Escolle a pista</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>See the word — choose from 4 options</source>
        <translation>Ve a palabra — escolle entre 4 opcións</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Progressive Learning</source>
        <translation>Aprendizaxe progresiva</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all words</source>
        <translation>Opción múltiple para aprender, logo escritura para dominar todas as palabras</translation>
    </message>
    <message>
        <location line="+2"/>
        <source>Reversed Progressive Learning</source>
        <translation>Aprendizaxe progresiva inversa</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>MC to learn, then write to master all hints</source>
        <translation>Opción múltiple para aprender, logo escritura para dominar todas as pistas</translation>
    </message>
    <message>
        <location line="+23"/>
        <source>✓ Done</source>
        <translation>✓ Feito</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>← Reset</source>
        <translation>← Restablecer</translation>
    </message>
    <message>
        <location line="+96"/>
        <source>✍️ Spelling strictness</source>
        <translation>✍️ Rigor ortográfico</translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Strict</source>
        <translation>Estrito</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Normal</source>
        <translation>Normal</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Lenient</source>
        <translation>Flexíbel</translation>
    </message>
    <message>
        <location line="+32"/>
        <source>Cancel</source>
        <translation>Cancelar</translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Review Expressions</source>
        <translation>Repasar expresións</translation>
    </message>
    <message>
        <location line="+120"/>
        <source>■  Stop</source>
        <translation>■  Deter</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>▶  Listen</source>
        <translation>▶  Escoitar</translation>
    </message>
    <message>
        <location line="+54"/>
        <source>Start Test</source>
        <translation>Iniciar proba</translation>
    </message>
    <message>
        <location line="+0"/>
        <source>No words yet</source>
        <translation>Aínda sen palabras</translation>
    </message>
</context>
<context>
    <name>SpellingTest</name>
    <message>
        <location filename="../SpellingTest.qml" line="+171"/>
        <source>Type the hint / translation…</source>
        <translation>Escribe a pista / tradución…</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Type the expression…</source>
        <translation>Escribe a expresión…</translation>
    </message>
    <message>
        <location line="+27"/>
        <location line="+1"/>
        <source>Correct: </source>
        <translation>Correcto: </translation>
    </message>
    <message>
        <location line="+11"/>
        <source>✓ Mark as correct (I mistyped)</source>
        <translation>✓ Marcar como correcto (escribín mal)</translation>
    </message>
    <message>
        <location line="+21"/>
        <source>Submit</source>
        <translation>Enviar</translation>
    </message>
    <message>
        <location line="+83"/>
        <source>✓ Mark as correct (I misclicked)</source>
        <translation>✓ Marcar como correcto (fixen clic mal)</translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Correct: %1 / %2</source>
        <translation>Correcto: %1 / %2</translation>
    </message>
    <message>
        <location line="+45"/>
        <source>See Results</source>
        <translation>Ver resultados</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Next →</source>
        <translation>Seguinte →</translation>
    </message>
    <message>
        <location line="-267"/>
        <source>Question number %1</source>
        <translation>Pregunta número %1</translation>
    </message>
</context>
</TS>
